### ISSUE TITLE
RowList.exe toolbar texts and tool tips' texts are not available

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#100]
```python
>>> t = app.RowListSampleApplication.Toolbar.WrapperObject()
>>> t.ButtonCount()
10L
>>> t.Texts()
['', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'']
>>> t.TipTexts()
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\...\pywinauto\pywinauto\controls\common_controls.py", line 2289, in TipTexts
    if not (-1 <= btn_tooltip_index < self.GetToolTipsControl().ToolCount()):
  File "C:\...\pywinauto\pywinauto\controls\common_controls.py", line 2323, in GetToolTipsControl
    return ToolTipsWrapper(self.SendMessage(win32defines.TB_GETTOOLTIPS))
  File "C:\...\pywinauto\pywinauto\controls\HwndWrapper.py", line 177, in __new__
    obj.__init__(handle)
  File "C:\...\pywinauto\pywinauto\controls\common_controls.py", line 2673, in __init__
    super(ToolTipsWrapper, self).__init__(hwnd)
  File "C:\...\pywinauto\pywinauto\controls\HwndWrapper.py", line 205, in __init__
    raise InvalidWindowHandle(hwnd)
InvalidWindowHandle: Handle 0x0 is not a vaild window handle
>>> t.Class()
u'ToolbarWindow32'
```
It would be great to find a root cause of the problem. It looks like standard MFC toolbar. If it has some unusual style or it's another corner case, we need to handle it as well.

**Comment by vasily-v-ryabov** [comment]
It looks like pywinauto support only `CToolBarCtrl` class in MFC (CmnCtrl1.exe).
`CToolBar`/`CMFCToolBar` (RowList.exe/RebarTest.exe) requires more efforts to support.

**Comment by vasily-v-ryabov** [comment]
There is useful article about MFC Feature Pack (see about `MFC Feature Pack samples` at the end):
http://www.codeproject.com/Articles/217588/Porting-a-legacy-MFC-app-to-MFC-Feature-Pack

**Comment by vasily-v-ryabov** [comment]
It seems [TB_GETBUTTONTEXT](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787325(v=vs.85).aspx) is not in use now. But it's a recommended way to retrieve a button text.

**Comment by vasily-v-ryabov** [comment]
[TB_GETUNICODEFORMAT](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787356(v=vs.85).aspx) is also interesting message that should help to know which version (A or W) of TB_GETBUTTONTEXT to use.

**Comment by vasily-v-ryabov** [comment]
I have no success with TB_GETBUTTONTEXT yet. It works for CToolBarCtrl, but not for CToolBar that is inherited from CControlBar in MFC.

Inspect.exe can see button texts for any toolbar so the UIA support seems to be a silver bullet for the problem.

**Comment by airelil** [comment]
I think I can start with an initial implementation of ToolBar wrapper for ```uia``` backend. I tried to check the issue with the recent UIA branch.
```python
from pywinauto.application import Application
app = Application(backend='uia')
app.start(r"apps\MFC_samples\x64\RowList.exe")
tb = app.RowListSampleApplication.ToolBar.wrapper_object()
```
And now we already have the access to children objects and their texts:
```
In [4]: tb.children_texts()
Out[4]:
[u'Large Icons',
 u'Small Icons',
 u'List',
 u'Details',
 u'Full Row Details',
 u'',
 u'Toggle State Icons',
 u'Client Width Sel',
 u'',
 u'About']

In [5]: tb.children()
Out[5]:
[<pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce50b8>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce5208>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce5278>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce52e8>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce5358>,
 <pywinauto.controls.uiawrapper.UIAWrapper at 0x4ce53c8>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce5438>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce54a8>,
 <pywinauto.controls.uiawrapper.UIAWrapper at 0x4ce5518>,
 <pywinauto.controls.uia_controls.ButtonWrapper at 0x4ce5588>]
```

**Comment by vasily-v-ryabov** [comment]
Everything is available right way on Win10. So closing so far.
