### ISSUE TITLE
Accessing some properties on UI Automation backend

### ISSUE THREAD

**Issue by Rohan-Kumar** [pywinauto/pywinauto#1000]
How can we access properties such as IsInvokePatternAvailable, IsSelectionPatternAvailable, etc. from the library? I see these properties in the Inspect application, but not finding any interface/method to access these properties.

**Comment by airelil** [comment]
Might try UIA wrapper properties:
https://github.com/pywinauto/pywinauto/blob/de1b1a8603a5372ad1dbf4e2e4f06dd01250cbd9/pywinauto/controls/uiawrapper.py#L225
and 
https://github.com/pywinauto/pywinauto/blob/de1b1a8603a5372ad1dbf4e2e4f06dd01250cbd9/pywinauto/controls/uiawrapper.py#L211
Given you created `wrp` variable with UIA wrapper instance for your control, you call it as `wrp.iface_selection_item.Select()`

**Comment by Rohan-Kumar** [comment]
Thank you for your reply.
This is what I've been looking for!

Although this works, on inspect it is a boolean property.
![Inspect - pattern](https://user-images.githubusercontent.com/11213888/97792230-b54bd180-1ba9-11eb-80e0-bc91af34c799.PNG)

Would it be alright if I created a pull request to add these methods as a boolean response?

Appreciate your help!

**Comment by airelil** [comment]
Franky, not sure. That's can be relatively easy achieved in the user code. Similar to the `UIAWrapper.is_dialog` method:
https://github.com/pywinauto/pywinauto/blob/4eec32e81cc3e5666eee57419c32a59ac22db667/pywinauto/controls/uiawrapper.py#L695
We do like PRs, but the expectations are to have some quality, as the code will have to be maintained later by pywinauto team. So for example, all the methods you'd like to add would have to come with unit tests, at least.

**Comment by Rohan-Kumar** [comment]
Alright. Will handle in the user code for now. 
In future if I do create a PR, will make sure it has all the unit tests.

Thank you for your help!
