### ISSUE TITLE
Pywinauto Incompatible with comtypes 1.1.8

### ISSUE THREAD

**Issue by Avnsx** [pywinauto/pywinauto#1048]
## Expected Behavior
Pywinauto launches at expected, using comtypes 1.1.8

## Actual Behavior
Pywinauto launches and instantly errors because of an incompability with comtypes version 1.1.8 and forces users to downgrade to 1.1.7

## Steps to Reproduce the Problem

  1. Try to run pywinauto with comtypes 1.1.8

## Short Example of Code to Demonstrate the Problem
https://stackoverflow.com/questions/65459632/cannot-import-pywinauto-on-windows-10

## Specifications

  - Pywinauto version: newest version possible
  - Python version and bitness: 3.9.2 - 64bit
  - Platform and OS: windows 10 20H2 build 19042

Opened Issue on comtypes too, but it's a dead repo: https://github.com/enthought/comtypes/issues/225
Also replicate of https://github.com/pywinauto/pywinauto/issues/1034 I guess

**Comment by vasily-v-ryabov** [comment]
`comtypes` is not completely dead, but it's much lower priority for me. I've released `comtypes==1.1.9` with the fix. Please check. And sorry for long waiting with such serious problem. It was my fault in `comtypes=1.1.8` (merged one of PRs without enough testing).
