### ISSUE TITLE
After doing some operation, I am getting element not found error for previously accessed element. 

### ISSUE THREAD

**Issue by Balaji1310** [pywinauto/pywinauto#1052]
## Expected Behavior
It should found the element and continue the process.

## Actual Behavior
its failing and showing error as "element not found"

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Short Example of Code to Demonstrate the Problem
main_window=Application(backend="uia").connect(title_re="Editor*")
pane= main_window.window(class_name="WindowsForms10.MDICLIENT.app.0.2bf8098_r33_ad1",control_type="Pane",top_level_only=False)

Note :- getting errors as element not found for "WindowsForms10.MDICLIENT.app.0.2bf8098_r33_ad1" but the same element is displayed while running py_inspect.py

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: python 3.6.8 and 64 bit
  - Platform and OS: 64 bit and windows

**Comment by Balaji1310** [comment]
please help me to find a solution.

**Comment by DiegoQueiroz** [comment]
This does not appear to be a bug or anything with pywinauto.

My bet is that your first statement is connecting to some other application that also matches `Editor*` regex.
I suggest you to improve your expression, since "Editor" is a very commom name (use path= instead).

**Comment by Balaji1310** [comment]
No Actually, this is sample name, just to display the syntax I have given here. After connecting to application, I am able to do any operation. In my application, on each step same window will be updated with some new data. so when I am trying to use already accessed element properties , I am getting element not found error.

**Comment by DiegoQueiroz** [comment]
Without more info, it is hard to help.
We can only guess where is your problem, and I think this is not the correct place to do this (I am not a project maintainer, but this is not a community forum to ask for help). Try [StackOverflow ](https://stackoverflow.com/questions/tagged/pywinauto)or the [Mailing List](https://sourceforge.net/p/pywinauto/mailman/).

Anyway, run these commands direct in a python terminal. Once you connect, try to run `print_control_identifiers()` to list the available controls, and check if your controls are available. I question myself if the control you're searching for is really there.

Another thing that you may consider is that, in .NET Applications, the class name is somewhat random.

> WindowsForms10.MDICLIENT.app.0.2bf8098_r**33**_ad**1** <-- these bold numbers may change

Double check if it is not the case.

**Comment by Balaji1310** [comment]
Hi I checked that too, its okay thank you for your help, Actually the syntax and everything is correct. still getting a error. I don't know whether the problem is in pywinauto. I thought this might have any work around. thank you.

**Comment by vasily-v-ryabov** [comment]
Maybe `visible_only=False` inside `main_window.window(...)` can help. Also `app` object returned by `connect` method is not a main window but a process that has a pid. That's why we name this object `app` in all examples. Then you can list top level windows in this process by `app.windows()`. For particular top level window there is method `app.window(title_re="Editor.*").dump_tree()`.

Another way is using `desktop = Desktop(backend="uia")` to walk the whole windows hierarchy without binding to process. Hope it helps.
