### ISSUE TITLE
Support Request: Pywinauto Timings Functionality

### ISSUE THREAD

**Issue by Avnsx** [pywinauto/pywinauto#1061]
Hey I've just read the [pywinauto docs > timings function ](https://pywinauto.readthedocs.io/en/latest/code/pywinauto.timings.html?highlight=timings.timings#pywinauto.timings) and I'm wondering if there's a way to reset ``timings.timestamp()`` so the value gets set to 0 and when the next time timestamp is printed; it will not output the time passed from the start of the code execution, but  instead from the point that timings was last reset. 👍

**Comment by vasily-v-ryabov** [comment]
There is built-in Python module `timeit` for monotonous timings (it is cross-platform and guaranteed to be monotonous while `time.time()` may flap):
```python
import timeit
start = timeit.default_timer()
# do something
print(timeit.default_timer() - start)
```
No need to duplicate it in pywinauto.

**Comment by Avnsx** [comment]
> There is built-in Python module `timeit` for monotonous timings (it is cross-platform and guaranteed to be monotonous while `time.time()` may flap):
> 
> ```python
> import timeit
> start = timeit.default_timer()
> # do something
> print(timeit.default_timer() - start)
> ```
> 
> No need to duplicate it in pywinauto.

Hey @vasily-v-ryabov, thanks for your quick competent response! I really like the work you do and how helpfull you've been over all the years with your released projects and also the support you're providing to them. Keep up the good work 👍

**Comment by vasily-v-ryabov** [comment]
Thanks and welcome! :)
