### ISSUE TITLE
Unable to target TLabel objects in Delphi application

### ISSUE THREAD

**Issue by bbeens** [pywinauto/pywinauto#1065]
## Expected Behavior
I expect to be able to target TLabel objects in pywinauto.  

## Actual Behavior
All TLabel objects are missing from dump_tree output.  
[TLabelTesting.zip](https://github.com/pywinauto/pywinauto/files/6400431/TLabelTesting.zip)

## Steps to Reproduce the Problem

  1.Extract the simple TLabelTesting.exe from the attached .zip file.
  2. Start this application using Pywinauto.
  3.Note, the Label1, Label2, Label3 are not visible in dump_tree.

## Short Example of Code to Demonstrate the Problem
from pywinauto import Application
tLabel = Application().start('TLabelTesting.exe')
tLabel.top_window().dump_tree()

Note, I have tested this using both backends win32 and uia.  No change in the behavior.
## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.7 32bit
  - Platform and OS: Windows 10

**Comment by vasily-v-ryabov** [comment]
`Inspect.exe` is also not able to see these labels. I would only recommend to try this project: https://github.com/jhc-systems/DelphiUIAutomation

Both pywinauto ("uia" backend) and `Inspect.exe` use MS UI Automation API through `UIAutomationCore.dll`. If application elements are not visible to both of them, it's an app side issue. There is no silver bullet unfortunately. But you are free to choose right dev tools for making application accessible.

**Comment by bbeens** [comment]
Thank you for looking into this.  I meant to close the ticket last week.  I found an alternative object that I am using without issue.  Using a TStaticText object allowed me to target the elements.  From a blog post I found the following statement:

"The difference between TLabel and TStaticText is that TStaticText registers itself with its own window handle, whereas TLabel does not."
