### ISSUE TITLE
pywinauto import disables copying from QLabel (PyQt5)

### ISSUE THREAD

**Issue by szwajkosz-aptiv** [pywinauto/pywinauto#1067]
## Expected Behavior
When using pywinauto PyQt5 program should be working as expected.

## Actual Behavior
When using pywinauto PyQt5 program disables copying text from Qlabel().

## Steps to Reproduce the Problem

  1. Copy code below
  2. Run it - you can select and copy text
  3. Uncomment 'from pywinauto import application' and rerun
  4. Now you can select text, but it can't be copied

## Short Example of Code to Demonstrate the Problem
          import sys
          from PyQt5.QtWidgets import QGridLayout, QScrollArea, QVBoxLayout, QLabel, QWidget, QApplication
          from PyQt5 import QtGui
          from PyQt5.QtCore import Qt
          # from pywinauto import application
          
          class TmpApp(QScrollArea):
              def __init__(self, parent=None):
                  super(TmpApp, self).__init__(parent)
                  widget = QWidget()
                  layout = QVBoxLayout(widget)
                  self.text = QLabel()
                  self.text.setTextInteractionFlags(Qt.TextSelectableByMouse)
                  self.text.setCursor(QtGui.QCursor(Qt.IBeamCursor))
                  txt = 'ABCDEFGHIJKLMNOPRSTUWXYZ'
                  self.text.setText(txt)
                  self.txt_layout = QGridLayout()
                  self.txt_layout.addWidget(self.text, 1, 1)
                  self.txt_layout.setSpacing(0)
                  layout.addLayout(self.txt_layout)
                  self.setWidget(widget)
                  self.setWidgetResizable(True)
          
          if __name__ == '__main__':
              app = QApplication(sys.argv)
              window = TmpApp()
              window.show()
              app.exec_()

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.3 64bit
  - Platform and OS: Windows 10, PyCharm 2021.1.1

**Comment by vasily-v-ryabov** [comment]
The only difference that usually changes Qt5 behavior is single threaded (STA) or multi threaded (MTA) mode of COM subsystem. It can be regulated by `sys.coinit_flags` set to `0` (MTA) or `2` (STA) before other imports (preferably set `sys.coinit_flags` first, then import pywinauto, then import PyQt5). Anyway it looks like some bug in PyQt5 or in Qt5 code. We face with Qt5 bugs from time to time and have to add some workarounds.

**Comment by szwajkosz-aptiv** [comment]
Workaround with setting `sys.coinit_flags = 2` works. Thank you!
