### ISSUE TITLE
could pywinauto switch an input method? 

### ISSUE THREAD

**Issue by leafonsword** [pywinauto/pywinauto#1074]
It seems autohotkey could switch an input method based on certain logic:[Change input method from Chinese to English... is this AHK territory?
](https://www.reddit.com/r/AutoHotkey/comments/54tg3i/change_input_method_from_chinese_to_english_is/+&cd=1&hl=zh-CN&ct=clnk)

Couldpywinauto do this too?

**Comment by vasily-v-ryabov** [comment]
pywinauto's method `.type_keys()` or basic function `send_keys()` from module `pywinauto.keyboard` already works with Unicode. It means you can use Chinese characters right in the input string and they should be printed correctly (I didn't check personally for Chinese, but it works this way for Russian characters). So you don't need to switch keyboard layout at all.

The only problem could be with the script encoding. You have to set correct encoding in the shebang-like comment at the beginning of the script (standard Python feature): `# encoding: utf-16` or whatever.

**Comment by leafonsword** [comment]
@vasily-v-ryabov thx,I will have a try!
