### ISSUE TITLE
Is it possible to get stdout and stderr by using pywinauto directly?

### ISSUE THREAD

**Issue by timlyeee** [pywinauto/pywinauto#1075]
I tried to use 
```python
app = pywinauto.Application().start(cmd_line="test.exe> log.txt")
```
to get my app start and output its message to the log.txt. Well, the app started, but no log.txt generated.

Should say that this cmd works on cmd prompt. So I'm confused now....
```cmd
test.exe > log.txt
```

**Comment by vasily-v-ryabov** [comment]
Use standard Python module `subprocess` for this purpose. Also please check `sys.getcwd()` and try to find `log.txt` there (with current pywinauto code).

**Comment by timlyeee** [comment]
which means there's no native method for stdout. Get it.
