### ISSUE TITLE
about type_keys()

### ISSUE THREAD

**Issue by OkabeRintarou1** [pywinauto/pywinauto#1090]
Hello, my dear,I want to use C to implement type_keys() function,because python is too slow,So can you tell me where to learn about it,thank you so much

**Comment by vasily-v-ryabov** [comment]
Hi @OkabeRintarou1 pywinauto is positioned as pure Python solution. There are few other open-source implementations of `pywinauto.keyboard.send_keys(...)` function as C extension of Python package. But making it faster doesn't necessary need C extension. Try to set timings in module `pywinauto.timings` which is used in `examples/notepad_slow/fast.py` Also other performance tuning is possible with methods that can set properties of elements directly (without typing). Some tricks were discussed in issue #256. The tuning guide in the docs doesn't exist yet. We plan to update the docs with next major release.
