### ISSUE TITLE
Can't seem to be able control an non windows pre installed program

### ISSUE THREAD

**Issue by AlexanderStavrop** [pywinauto/pywinauto#1156]
## Expected Behavior
I want to press some buttons on a program, TeXstudio for example. The given example for the notepad works but i cant seem to be able to run any other application that is not preinstalled with windows.

## Actual Behavior
Open the program but when i try to search for some specific button (e.g. File) like in the example, it raises ElementNotFoundError with mesage "pywinauto.findwindows.ElementNotFoundError: {'title_re': 'TeXstudio', 'backend': 'uia', 'process': 3592}"

This also happens as im trying to print the control identirfiers.
## Steps to Reproduce the Problem

  1. Open program you installed your self
  2. Find the File option
  3. Click on it and show the drop down menu

## Short Example of Code to Demonstrate the Problem
from pywinauto.application import Application

# Running the program
app = Application(backend="uia").start("C:\\Program Files\\texstudio\\texstudio.exe")

# Linking the app name to skp varible.
skp = app.window(title_re='TeXstudio')

# Trying to print the control identifiers
search = skp["Texstudio"].print_control_identifiers()

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.10
  - Platform and OS: windows 10

**Comment by bananoviiblinchik** [comment]
afaik `print_control_identifiers()` doesn't return anything.
Also, have you tried `skp = app.top_window()` ?

**Comment by cross-hello** [comment]
@AlexanderStavrop  u can learn from here [manual](https://pywinauto.readthedocs.io/en/atspi/getting_started.html)
What you described I think could be summary to how to locate element in application.

**Comment by marcoccio** [comment]
Try this: 

from pywinauto import Application

app = Application(backend="uia").start(r"absolute_path")
dlg = app.top_window()

Change "backend" and "absolute_path" accordingly. 
Also read the documentation: https://pywinauto.readthedocs.io/en/latest/getting_started.html
