### ISSUE TITLE
UnboundLocalError: local variable 'move_event_end' referenced before assignment

### ISSUE THREAD

**Issue by batara666** [pywinauto/pywinauto#1194]
UnboundLocalError: local variable 'move_event_end' referenced before assignment

Windows 11
pywinauto recorder 0.5.1

**Comment by vasily-v-ryabov** [comment]
Which recorder do you mean? It seems not an official part of the project.

**Comment by beuaaa** [comment]
Hi @vasily-v-ryabov,

@batara666 made a mistake, he closed this issue and then reposted in the right place: https://github.com/beuaaa/pywinauto_recorder/issues/37.
