### ISSUE TITLE
Attribute resolution

### ISSUE THREAD

**Issue by juysu2** [pywinauto/pywinauto#120]
In reference to documentation: http://pywinauto.github.io/docs/dev_notes.html#attribute-resolution, it say: app.dlg.control

what is the best way to acces to button "Purge": w_customer.tabfolder_customer.tabpage_invoices.tabfolder_years.tabpage_2015.Purge.Click() ?

app.w_customer.Purge.Click() # Exists tabpage_2014, tabpage_2013, ...
or 
app.w_customer['tabfolder_customer'].['tabpage_invoices'].['tabfolder_years'].['tabpage_2015'].['Purge'].Click()

**Comment by airelil** [comment]
It's hard to give a concrete tips without knowing your GUI layout. Generally, I'd suggest you to stick to "Dialog.control" model and break it on several small basic steps. Something as following:
1. Get app object: ``` app = app.start("path_to_your_app.exe")```
2. Get the main dialog: ```dlg = app.top_window_()``` or ```dlg = app["window title"]```
3. Get a tab control on the dialog: ```tab_ctrl = dlg["tab control name"]```
4. Select the right tab page: ```tab_ctrl.Select("tab page name")```
5. Run an action on the control on that page: ```tab_ctrl.Purge.Click()```

Not sure if it applicable for your case but notice that .Net applications currently are only partially supported by Pywinauto.

**Comment by vasily-v-ryabov** [comment]
`app.dlg.control` means that `control` is found in the whole controls tree under the dialog. So further expansion is not supported. If you need to click a button on another tab, you may do something like that:
```python
app.dlg.TabControl.Select("tab name")
app.dlg.Purge.Click()
```
This is much shorter than following a lot of tabs.

Some debugging tricks can be useful:
* `app.dlg.PrintControlIdentifiers()` method prints all available controls with corresponding access name for each one.
* `app.dlg.control.WrapperObject()` with just typed `.` (dot) will give you the most useful list of available methods for the control. There are 2 equivalent constructions: `app.dlg.Purge.WrapperObject().Click()` (for debugging) and `app.dlg.Purge.Click()` (for better readable scripts). But `app.dlg.Purge` is not equivalent to `app.dlg.Purge.WrapperObject()`. The first one is a description only (the control may not actually exist at some moment), while the wrapper object is for already found control.

**Comment by vasily-v-ryabov** [comment]
These tips and tricks can be moved to the documentation. So marking the issue as enhancement.

**Comment by vasily-v-ryabov** [comment]
This is explained in new [Getting Started Guide](http://pywinauto.readthedocs.io/en/latest/getting_started.html).
