### ISSUE TITLE
Send keystrokes not work for notepad and other programs

### ISSUE THREAD

**Issue by gitE0Z9** [pywinauto/pywinauto#1202]
## Expected Behavior

send keys in background like on-screen keyboard.

## Actual Behavior

nothing happened

## Steps to Reproduce the Problem

  1. application connect to a notepad
  2. send_keystrokes

## Short Example of Code to Demonstrate the Problem

```
from pywinauto.application import Application

app = Application().connect(title_re="a.txt")
app.top_window().send_keystrokes("aaaaa")
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.7
  - Platform and OS: windows 10

**Comment by vasily-v-ryabov** [comment]
`app.UntitledNotepad.Edit.send_keystrokes("aaa")` works for me. Also there is `.send_chars(...)` method (without key combinations support).

I guess sending keys to the top level window is incorrect for this kind of methods. Only `.type_keys(...)` may work for the whole window but it requires focus.

**Comment by Wavilson** [comment]
I have the same problem. Sending keys does not work in some programs. In these situations, I use the following code.

[https://github.com/Wavilson/SendKeys/blob/415b81b8ac2fb191bf0302e152222aadd88e8c8b/Key.py](url)

Would it be possible to use it with pywinauto?

**Comment by vasily-v-ryabov** [comment]
@Wavilson method `.type_keys("...", with_spaces=True)` can do everything. But it requires active desktop like Win32 API function `SendInput` used in the code you've referenced. So nothing to add to pywinauto.
