### ISSUE TITLE
How to run script on RemoteApp session

### ISSUE THREAD

**Issue by LeeEirc** [pywinauto/pywinauto#1234]
I want to run pywinauto script on remote host while open remoteapp session. I publish python as RemoteApp Program on windows 2022and create rdp.file as below.
```
screen mode id:i:1
use multimon:i:0
desktopwidth:i:1440
desktopheight:i:900
session bpp:i:32
winposstr:s:0,1,0,0,1456,899
compression:i:1
keyboardhook:i:2
audiocapturemode:i:0
videoplaybackmode:i:1
connection type:i:7
networkautodetect:i:1
bandwidthautodetect:i:1
displayconnectionbar:i:1
enableworkspacereconnect:i:0
disable wallpaper:i:0
allow font smoothing:i:0
allow desktop composition:i:0
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:0
disable cursor setting:i:0
bitmapcachepersistenable:i:1
full address:s:192.168.200.1:3389
audiomode:i:0
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
redirectclipboard:i:1
redirectposdevices:i:0
autoreconnection enabled:i:1
authentication level:i:2
prompt for credentials:i:0
negotiate security layer:i:1
remoteapplicationmode:i:1
alternate shell:s:||python
remoteapplicationprogram:s:||python
remoteapplicationcmdline:s:c:\\plsql.py
shell working directory:s:
gatewayhostname:s:
gatewayusagemethod:i:4
gatewaycredentialssource:i:4
gatewayprofileusagemethod:i:0
promptcredentialonce:i:0
gatewaybrokeringtype:i:0
use redirection server name:i:0
rdgiskdcproxy:i:0
kdcproxyname:s:
drivestoredirect:s:
```
 the script  only could lanuch application (plsql), but cloud not find controls to input password and username.
I have already read docs[remote_execution](https://pywinauto.readthedocs.io/en/latest/remote_execution.html), but did not find a solution.

**Comment by vasily-v-ryabov** [comment]
Are you running pywinauto script inside RDP sesssion on the remote machine? Does it work on local installation of PLSQL?

**Comment by LeeEirc** [comment]
it works on local machine. I found some weird things, when changing remote windows from 2022 to 2019,  It also works.

**Comment by vasily-v-ryabov** [comment]
Does it mean the issue is WinServer 2022 specific? Maybe some OS components are not installed or hotfix update is required if it's a bug (sometimes it was the case).

**Comment by LeeEirc** [comment]
Thank you for your reply. I think it maybe winServer 2022 OS bug.  I will update you as soon as I have further information.
