### ISSUE TITLE
Warning preferences of users should not be overriden

### ISSUE THREAD

**Issue by 5j9** [pywinauto/pywinauto#125]
Using [`warnings.simplefilter`](https://github.com/pywinauto/pywinauto/commit/3ecd1f4fb5175a703fead3b16952b238b0ddf30e#L945) each time before issuing warnings, causes [user warning settings](http://stackoverflow.com/a/9031848/2705757) to be lost. This will effect warning handling of other libraries, too.

I think it makes sense to remove all `warnings.simplefilter('always', UserWarning)` lines. It will suffice to put just one at the top of the module.

**Comment by airelil** [comment]
@5j9 thanks for your comment. It definitely makes sense though I'd like to add a notice to that. If a pywinauto user starts getting the warnings in his scripts he'd better fix them. In our case user should stop using deprecated methods: ```connect_,  Connect_, start_, Start_``` or switch to the correct bitness.

**Comment by vasily-v-ryabov** [comment]
@5j9, good point. Currently we have no plans to release more 0.5.x versions (but who knows). Probably some methods will be removed in 0.6.0. But some of the warnings might remain. So let's keep it tracking.

**Comment by Dimchord** [comment]
I would like to see at least the warning override for incorrect bitness to be removed. The major part of my python program relies on 64-bit for memory issues. On the side it controls a 32-bit program, which works just fine for the simple things it has to do.

**Comment by vasily-v-ryabov** [comment]
@Dimchord , you may have problems with TreeView controls if the bitness is mismatched. We don't know about other problems because of bitness. But the TreeView issue was noticed several times. That's why we have to take this warning into account.

**Comment by vasily-v-ryabov** [comment]
If issue #93 was fixed, we would like to remove bitness warnings at all.

**Comment by Dimchord** [comment]
I'm not suggesting to remove the warning, just the warnings.simplefilter('always') calls. Once I have seen the warning I want to be able to hide it, which is impossible now.

**Comment by airelil** [comment]
Didn't PR #138 solved the issue ?

**Comment by vasily-v-ryabov** [comment]
It seems the issue can be closed. The warnings are not relevant for `backend="uia"`. Several fixes was done for `backend="win32"`. If someone could reproduce it again, please reopen.
