### ISSUE TITLE
`comtypes` is moving forward with plans to drop support for Python2

### ISSUE THREAD

**Issue by junkmd** [pywinauto/pywinauto#1265]
The `comtypes` is the one of most important dependency of the `pywinauto`.

On the issue of `comtypes`, the discussion which @vasily-v-ryabov had participated was [reached the conclusion to drop support for Python 2.7](https://github.com/enthought/comtypes/issues/216#issuecomment-1207158728).

Now, the plan are in progress to [drop Python2.7 and support only Python3.7+](https://github.com/enthought/comtypes/issues/392#issue-1474579756).
The release timing is [*mid-2023 or maybe even earlier*](https://github.com/enthought/comtypes/issues/392#issue-1474579756).

The `pywinauto` community also need to discuss which Python version to continue to support.

**Comment by vasily-v-ryabov** [comment]
In fact there is no any community for pywinauto development. I'm the only maintainer at the time. I hope to release 0.7.0 with Py2.7 support and then work on moving to 3.7+.

**Comment by junkmd** [comment]
Understood.

Please let me know if there is anything I can do to help you.

A large part of my currently work depends on this package that you are maintaining

If there is no "community", I would like to create it with you as the first step.

**Comment by junkmd** [comment]
Thank you for your efforts and I wish for further advancement of this package.
