### ISSUE TITLE
To control without a screen

### ISSUE THREAD

**Issue by nuyhc** [pywinauto/pywinauto#1294]
I'm trying to control the program with pywinauto in a virtual env. (like VMware) The virual env itself has all the necessary libraries, including Python.

The execution state is that the virtual env has been shut down. The server continues to operate the env, and the information from some experiments is that GUI control is not possible at that state.

```python
try:
    elem.click()
except:
    try:
        elem.click_input()
    except:
        try:
             elem.send_keys("{ENTER}")
        except:
             elem.send_keystrokes("{ENTER}")
```

I also used methods such as set_focus.

Using the above code, I have successfully performed code that performs click actions in that situation, but I don't know how to solve it if the "ENTER" key doesn't work on the element...

(For ex, if you put your cursor on a specific elem in Windows File Explore and entered ENTER, you can get the same effect that you clicked.)

**Comment by lukjak** [comment]
So is the problem theoretical (your code works in the described situation and you just want to know what to do if it had not) or practical (your code does not work in this situation, despite writing "I have successfully performed code that performs click actions in that situation")?

**Comment by nuyhc** [comment]
> So is the problem theoretical (your code works in the described situation and you just want to know what to do if it had not) or practical (your code does not work in this situation, despite writing "I have successfully performed code that performs click actions in that situation")?

It's the former.
It doesn't matter if the element and the enter interact, but I want to know what to do if they don't interact (like clicking).

**Comment by lukjak** [comment]
To provide some definitive answer, as far as I know:

There may be situations, where you cannot interact with some control:
- The control is not visible to any available backend
- The control requires keyboard/mouse inputs and they are not accepted because desktop is locked or software runs in Session 0 etc.
