### ISSUE TITLE
where to download the manual PDF?

### ISSUE THREAD

**Issue by ileon** [pywinauto/pywinauto#132]
sorry , i need one offline PDF for study

**Comment by airelil** [comment]
Hi @ileon you can download it form our documentation site: https://readthedocs.org/projects/pywinauto/downloads/

**Comment by ileon** [comment]
my working place can not access the internet, thanks very much

**Comment by drongh** [comment]
if you use firefox browser, you can use a plugin scrapBook. It's a very nice tool.

**Comment by drongh** [comment]
[There is a issuse][http://pywinauto.readthedocs.org/en/latest/HowTo.html]

**Comment by vasily-v-ryabov** [comment]
Hi @ileon thank you for raising the problem. Let's keep the issue open until we make some more useful pdf version of the docs.

@drongh, correct. We're going to review all the docs in February before 0.6.0. All problems and misunderstandings are welcome to report.

**Comment by vasily-v-ryabov** [comment]
One PDF file can be downloaded from ReadTheDocs now (for UIA branch): [pywinauto.pdf](https://media.readthedocs.org/pdf/pywinauto/uia/pywinauto.pdf). Though the content is not fully up-to-date yet. Will close the issue after merging UIA to master.

**Comment by vasily-v-ryabov** [comment]
The latest pdf is [here](https://media.readthedocs.org/pdf/pywinauto/latest/pywinauto.pdf). Closing the issue as finally resolved.
