### ISSUE TITLE
SendKeys/TypeKeys always sends text to active window, ignores target

### ISSUE THREAD

**Issue by tunabee** [pywinauto/pywinauto#133]
Using Windows 7, Anaconda Python 3.5 (32bit).

    pxplus[u'Edit4'].TypeKeys('9.26')

Simply sends the text `9.26` directly to my text editor instead of the control specified. I've tried this with other controls also without success.

Unfortunately, I can't use SetText() with this control because as soon as I do, it always clears out the value. I've had no issues setting text in this control with AHK by using Send.

**Comment by vasily-v-ryabov** [comment]
Please try `pxplus[u'Edit4'].TypeKeys('9.26', set_foreground=False)`. If it doesn't help, there is another option:
```python
pxplus[u'Edit4'].SetEditText('9.26', pos_start=-1)
```
It sets the selection to [-1, -1) (i.e. nothing, but cursor is at the end of text).

**Comment by tunabee** [comment]
I actually discovered what the problem was: I was running my program from Spyder (the IDE that comes with Anaconda). For some reason, when you run the program within Spyder's console (either an iPython or regular Python), TypeKeys does not work. However, by setting the Run Settings to "Execute in an external System terminal," the program behaves as expected.

Hope this is helpful for others who have had the same issue.
