### ISSUE TITLE
The code after the sub dialog is opened is not executed

### ISSUE THREAD

**Issue by lickafrog** [pywinauto/pywinauto#1349]
## Expected Behavior
Button in a sub dialog is clicked

## Actual Behavior
The code after the sub dialog is opened is not executed

After some time, it gives you this error 
```
Traceback (most recent call last):
  File "C:\Users\Dima\PycharmProjects\mstar\main.py", line 39, in <module>
    close_shift_btn.click()
  File "C:\Users\Dima\.virtualenvs\mstar-Tjcfx_Hq\Lib\site-packages\pywinauto\controls\uia_controls.py", line 121, in click
    self.invoke()
  File "C:\Users\Dima\.virtualenvs\mstar-Tjcfx_Hq\Lib\site-packages\pywinauto\controls\uiawrapper.py", line 513, in invoke
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```

## Short Example of Code to Demonstrate the Problem
```
app = Application(backend="uia").start(r"C:\Program Files (x86)\Alfa-Project\APTools\APtools.exe")

app.window(title='APTools').wait('ready', timeout=20, retry_interval=5)

main_dlg = app.window()

# open the sub dialog
close_shift_btn.click()

# this code wont work
print(test)
dlg2 = app.window(title='Закрытие смены для ФФД версий 1.05 1.1')
btn = dlg2.child_window(title="Закрыть смену", auto_id="buttonShiftClose", control_type="Button").wrapper_object()
btn.click()
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.12
  - Platform and OS: Windows 10

**Comment by junkmd** [comment]
Hi.

Where is the `close_shift_btn` definition?

I think it's likely a descendant of `main_dlg`, and you've retrieved it in some way.

**Comment by lickafrog** [comment]
> Hi.
> 
> Where is the `close_shift_btn` definition?
> 
> I think it's likely a descendant of `main_dlg`, and you've retrieved it in some way.

`close_shift_btn = main_dlg.child_window(title="Закрыть", auto_id="dayCloseButton", control_type="Button")`

**Comment by junkmd** [comment]
> The code above works in python console

I still think it is a timing issue.
Please consider inserting `time.sleep` at key points in the code.

**Comment by lickafrog** [comment]
Sorry, I was wrong, it doesn't work in the console as well.

Here is the video
https://github.com/pywinauto/pywinauto/assets/130896496/951ad0e0-3e80-4d31-ac5c-8f403c85b9ce

**Comment by lickafrog** [comment]
> This tends to happen in cases where the name of the top-level window you want to obtain and the name of a transient progress dialog that appears when the application is launched are the same. It's possible that `app.window(title='APTools')` is actually retrieving a dialog that disappears in an instant.

I don't know if that can apply to my case. How can I check it and fix it?

**Comment by junkmd** [comment]
Can you change your code as below?

```diff
...
>>> main_dlg = app.window()
- >>> close_shift_btn = main_dlg.child_window(title="Закрыть", auto_id="dayCloseButton", control_type="Button").click()
+ >>> close_shift_btn = main_dlg.child_window(title="Закрыть", auto_id="dayCloseButton", control_type="Button")
+ >>> close_shift_btn.click()
```

The subdialog is probably opened in modal.
In other words, the main dialog might be unresponsive.
Trying to get the main dialog button after it is in such a state may be the cause of the problem.

> I don't know if that can apply to my case. How can I check it and fix it?

From the video, there does not appear to be any "flickering" dialog.
I am more concerned that you are manually dragging and moving the screen and manipulating the tree view to make screen transition.
Depending on the GUI, it may be redrawing the ui elements with a click and they may look the same but no longer be the UIA elements you originally retrieved.
It is better to let `pywinauto` do the treeview operation as well, to remove the influence of the click.

**Comment by lickafrog** [comment]
Thank you, you pointed me in the right direction.

I changed the code to
`close_shift_btn.click_input()`
and now it works.

` I am more concerned that you are manually dragging and moving the screen and manipulating the tree view to make screen transition.`
I did it just for saving time on the video. Everything is automated in the code.
