### ISSUE TITLE
Application hangs at FindAll in uia_element_info.py

### ISSUE THREAD

**Issue by b1t-hunter** [pywinauto/pywinauto#1350]
## Expected Behavior

I have an application that is automating activities in Firefox. It connects to a running Firefox process.

## Actual Behavior

Basically from one day to the next my application stopped working, meaning it hangs as soon as I want to connect to the running Firefox process. After further testing, it hangs on any connect.

Debugging the problem leads me to [this line with FindAll](https://github.com/pywinauto/pywinauto/blob/ff95296e42c16beaf1f8b94252276cb664a4e47e/pywinauto/uia_element_info.py#L269). Apparently, there was such an issue already that was related to multi-threading (#394), but it was fixed in a previous version. However, I am not using multi-threading at the moment.

What suprises me, is, that this stopped working from one day to the other. Just yesterday it was running properly. I cannot really say what has changed.

## Short Example of Code to Demonstrate the Problem

```python
from pywinauto.application import Application

app_obj = Application(backend='uia').connect(title_re=".*Mozilla Firefox")
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.11.6 x64
  - Platform and OS: Win 11

**Comment by b1t-hunter** [comment]
After waiting for a very long time, the program continues at some point. Anyway, all the following commands, like getting the top window or retrieving child windows takes endless time.

**Comment by junkmd** [comment]
Hi.

The `connect` method is used to automate the launched app.

Have you launched more apps with window title that match ".*Mozilla Firefox" than yesterday?

**Comment by b1t-hunter** [comment]
Hi,

no, it is just a single one. I also have set found_index=0 in my original app, becaue I had problems when two tabs where opened in Firefox. Anyway, there are less apps running than I had yesterday, but it takes much longer to return for that function. I waited 2 minutes for the connect to return and getting the top window. UISpy shows there are 20 top-level windows open.

Restarting my system multiple times didnt help either.

**Comment by b1t-hunter** [comment]
While debugging, I can only see the get_param in comtypes return a value and then I am not able to follow anymore. So I guess this FindAll is already the Win UI Automation API that runs natively in a driver? Which would mean you can probably not change anything about this being so slow? UI Spy displays all info instantly.

**Comment by junkmd** [comment]
If Firefox in your environment is automatically updating, then the GUI implementation may have changed.

You may want to check your Firefox version and try an older version.

**Comment by junkmd** [comment]
> So I guess this FindAll is already the Win UI Automation API that runs natively in a driver?

`comtypes` handles COM objects in your environment.
`pywinauto` treats UIA through `comtypes`.
(I am also a maintainer of `comtypes`.)

**Comment by junkmd** [comment]
Can you share the results shown by `print_control_identifiers` with the community?

**Comment by b1t-hunter** [comment]
Do you mean of the created Application object?

**Comment by junkmd** [comment]
I thought that `app_obj.window(title_re=".*Mozilla Firefox").print_control_identifiers` might tell us something.
However, I reconsidered that it is not very appropriate because we want to know the state before `connect`.

Instead, try running the following in the console.

```py
>>> from pywinauto import Desktop
>>> dt = Desktop(backend="uia")
>>> dt.windows(title_re=".*Mozilla Firefox")
```

**Comment by b1t-hunter** [comment]
```python
start_time = current_millis()

dt = Desktop(backend="uia")
window = dt.windows(title_re=".*Mozilla Firefox")

print(window)
print("duration=" + str((current_millis() - start_time) / 1000) + "s")
```

```
[<uiawrapper.UIAWrapper - 'Google – Mozilla Firefox', Dialog, -3829186715094450244>]
duration=70.175s
```

**Comment by b1t-hunter** [comment]
It returns the window, but seems extremely slow with 70 seconds.

**Comment by junkmd** [comment]
I am not sure what is slowing down the UIA process.

Can you try to (re)create your Python virtual environments?

**Comment by b1t-hunter** [comment]
Also created a clean project with no env and had the same issue.

**Comment by junkmd** [comment]
How is the memory usage?

**Comment by b1t-hunter** [comment]
around 16GB/32GB, CPU is around 10-20% on 8 cores, the system runs smoothly, also other apps. Its not much different to what I had the days before, actually even less load.

**Comment by junkmd** [comment]
It is very surprising that only UIA can be so slow.

It seems the only thing we can do is to run the script another day and observe what happens then.

**Comment by b1t-hunter** [comment]
Ok, so I tried it today and it really works like a charm now. I dont know what was causing it. I would close the ticket then, hoping this was just a one-time glitch.

**Comment by vasily-v-ryabov** [comment]
Since `desktop` object is looking for all open windows during the search, another window(s) may influence on this situation. Also some Windows updates (hotfixes) may contain fixes specifically for UIA. I remember one such case in the past, but it is too long to find it. So keeping Windows up-to-date may help sometimes.
