### ISSUE TITLE
Problems installing pywinauto 0.6.8 (Linux)

### ISSUE THREAD

**Issue by sasananas1** [pywinauto/pywinauto#1358]
When installing pywinauto (0.6.8) in pycharm, it throws an error:

ERROR: Could not find a version that satisfies the requirement pywin32 (from pywinauto) (from versions: none)
ERROR: No matching distribution found for pywin32

The installation of pywinauto (0.6.6) goes without problems.
Installed on python 3.8 and 3.11
Please tell me how to solve this problem

**Comment by vasily-v-ryabov** [comment]
More complete Linux support is a little bit unfinished in branch `atspi`. Unfortunately its further development is stopped due to lack of time for this hobby project. Any help is appreciated.

**Comment by sasananas1** [comment]
I found the solution on this branch https://github.com/pywinauto/pywinauto/issues/951
