### ISSUE TITLE
pywinauto tree dump is different from Inspect despite same/similar settings

### ISSUE THREAD

**Issue by a-r-r-o-w** [pywinauto/pywinauto#1383]
## Expected Behavior

Firstly, awesome work building this amazing wrapper around the Windows API! It has helped save me a lot of time once I found out about it from a colleague. Thank you.

As part of something I'm working on, below is what the tree view looks like with Inspect:

![image](https://github.com/pywinauto/pywinauto/assets/72266394/7cba37cd-4290-43f2-af84-491550103a59)

## Actual Behavior

When viewing the tree via `dump_tree` method using the UIA backend, I don't see the same results as above.

![image](https://github.com/pywinauto/pywinauto/assets/72266394/272a2e9b-ffac-4fba-8adb-3f54fa03b0c5)

The above is one instance of a mismatch occurring between Inspect output and pywinauto output, but there are many more such instances. I'd appreciate guidance on how to get the same/similar element tree if it can be done in an easy way. I believe my setup with pywinauto isn't too different from that of Inspect to the best of my knowledge.

## Specifications

  - Pywinauto version: Source (installed from astpi branch)
  - Python version and bitness: 3.12.2 (64-bit)
  - Platform and OS: Windows 10/11 (Errors on both)

@vasily-v-ryabov @airelil

**Comment by WorkSync** [comment]
> ## Expected Behavior
> Firstly, awesome work building this amazing wrapper around the Windows API! It has helped save me a lot of time once I found out about it from a colleague. Thank you.
> 
> As part of something I'm working on, below is what the tree view looks like with Inspect:
> 
> ![image](https://private-user-images.githubusercontent.com/72266394/311989032-7cba37cd-4290-43f2-af84-491550103a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDE3ODUsIm5iZiI6MTcyOTc0MTQ4NSwicGF0aCI6Ii83MjI2NjM5NC8zMTE5ODkwMzItN2NiYTM3Y2QtNDI5MC00M2YyLWFmODQtNDkxNTUwMTAzYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAzNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWZkMzVkMjczNzMzZWE4NzQzNDFmZTcyNWNmYTczNDMwMzY2NTVkMWQxZmRjYTkwYTlkOTRkNWRiMDE5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qk6WBdn9wbXrW85fyv8d9PFtFulsDPHitCirEViWRhU)
> 
> ## Actual Behavior
> When viewing the tree via `dump_tree` method using the UIA backend, I don't see the same results as above.
> 
> ![image](https://private-user-images.githubusercontent.com/72266394/311989475-272a2e9b-ffac-4fba-8adb-3f54fa03b0c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDE3ODUsIm5iZiI6MTcyOTc0MTQ4NSwicGF0aCI6Ii83MjI2NjM5NC8zMTE5ODk0NzUtMjcyYTJlOWItZmZhYy00ZmJhLThhZGItM2Y1NGZhMDNiMGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAzNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzk2MTMzMGNhZTk1ZTQwMjE0YjM3Zjc1MmY0OTc1YWM4NjBkNTg0NTQzOTFhNWRhNjRmMTQ5Y2Q1Y2JkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z5oGqmIMsFzGo_X-UIxfjtfR_v0xCaplyYScP1s5NhQ)
> 
> The above is one instance of a mismatch occurring between Inspect output and pywinauto output, but there are many more such instances. I'd appreciate guidance on how to get the same/similar element tree if it can be done in an easy way. I believe my setup with pywinauto isn't too different from that of Inspect to the best of my knowledge.
> 
> ## Steps to Reproduce the Problem
> ## Short Example of Code to Demonstrate the Problem
> ## Specifications
> * Pywinauto version: Source (installed from astpi branch)
> * Python version and bitness: 3.12.2 (64-bit)
> * Platform and OS: Windows 10/11 (Errors on both)
> 
> @vasily-v-ryabov @airelil

About of this warehouse has actually been pointed out “Windows GUI Automation with Python (based on text properties)”.So it's normal for the tree generated by pywinauto to be different from the one shown in the Inspector.

**Comment by a-r-r-o-w** [comment]
Thanks for the reply! I no longer have this issue and found a workaround for what I needed, so marking this as closed
