### ISSUE TITLE
Accessing item in the system tray on Windows 11

### ISSUE THREAD

**Issue by markox92** [pywinauto/pywinauto#1400]
Hello,
Is there any way to access items in the system tray on Windows 11? I want to get a list of apps inside the system tray but can't find a solution for this.  I was read doc. but I'm not sure that is still working on Windows 11

**Comment by accountuse** [comment]
```
desktop_explorer = Desktop(backend="uia")
taskbar = desktop_explorer.window(class_name="Shell_TrayWnd", control_type="Pane")
taskbar.child_window(title="Show Hidden Icons", auto_id="SystemTrayIcon", control_type="Button").click()
```

**Comment by ameleumit** [comment]
Win+B focuses to system tray.
