### ISSUE TITLE
Implement has_keyboard_focus() and set_keyboard_focus() for NativeElementInfo/HwndWrapper

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#141]
`has_keyboard_focus()` can be implemented using [GetFocus](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646294%28v=vs.85%29.aspx) Win32 API function including AttachThreadInput and GetGUIThreadInfo calls.

`set_keyboard_focus()` can be implemented using [SetFocus](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646312%28v=vs.85%29.aspx) Win32 API function.

One useful thread on SO: [How can I tell if a Window has focus? (Win32 API)](http://stackoverflow.com/questions/466354/how-can-i-tell-if-a-window-has-focus-win32-api).

**Comment by airelil** [comment]
The implementation of ```HwndWrapper.has_keyboard_focus()``` and ```HwndWrapper.set_keyboard_focus()``` introduced in [#961b955](https://github.com/pywinauto/pywinauto/commit/961b9552f6e38edddcd3e59ff06566069381450e) may suffer from the same problem of passing invalid parameters to ```AttachThreadInput``` as  recently fixed ```HwndWrapper.set_focus``` in PR #241

**Comment by vasily-v-ryabov** [comment]
We may open another issue if someone reports something for these functions. Closing for now.
