### ISSUE TITLE
"NameError: name '_compointer_base' is not defined" when importing pywinauto

### ISSUE THREAD

**Issue by cjstarvaggi** [pywinauto/pywinauto#1413]
## Expected Behavior

Normal operation of pywinauto.

## Actual Behavior

Can't even import pywinauto without triggering the following error:

Exception has occurred: NameError
name '_compointer_base' is not defined
  File "C:\Users\******\Desktop\Repo Installer\test.py", line 1, in <module>
    import pywinauto
NameError: name '_compointer_base' is not defined

The full Traceback is shown below:

![image](https://github.com/user-attachments/assets/bd37a6b7-a55b-4b84-be08-411a81f0b352)

All known dependencies are installed; checked using pip freeze:

![image](https://github.com/user-attachments/assets/03ac7329-9d3a-4e60-9e0c-eb4e5fd54dab)

## Steps to Reproduce the Problem

  1. Open up a new python file in VS code
  2. On the first line, enter "import pywinauto"
  3. Run the code

## Short Example of Code to Demonstrate the Problem

![image](https://github.com/user-attachments/assets/5f101d91-f9f6-43c7-9816-08659ebcd1b8)

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.13.0, 64-bit
  - Platform and OS: VS Code on Windows 11

**Comment by junkmd** [comment]
As a collaborator on this project and also a maintainer of `comtypes`, I can tell you that the cause of this error is that "`comtypes` does not yet support Python 3.11".

Once enthought/comtypes#636 is merged and released, the package available on PyPI will support Python 3.13.

Please try installing the aforementioned branch (and see also enthought/comtypes#618) and verify that there are no issues with your use case.

**Comment by cjstarvaggi** [comment]
I installed the branch as requested; this does indeed seem to have fixed the issue. Thanks for the help!
