### ISSUE TITLE
ButtonWrapper for UIA backend

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#142]
I open a separate issue for that. This is a first wrapper for UIA so we are going to have some discussions here.
I started to look into it. It looks that all ```controltypes``` has to be moved from all HwndWrapper descendants to UIAWrapper.
For example we have the following in ButtonWrapper of the 'native' backend:
```
 controltypes = [
            _UIA_dll.UIA_ButtonControlTypeId,
            _UIA_dll.UIA_CheckBoxControlTypeId,
            _UIA_dll.UIA_RadioButtonControlTypeId]
``` 
Maybe the same for ```r"WindowsForms\d*\.BUTTON\..*",``` criteria in ```windowclasses```

**Comment by vasily-v-ryabov** [comment]
Agree. Probably `re_windowclasses` is not required because WinForms button should have `UIA_ButtonControlTypeId` and not only WinForms one.

**Comment by airelil** [comment]
I placed an initial implementation for UIA ButtonWrapper in my repo (https://github.com/airelil/pywinauto/commits/wpf_controls). However, the main job is done in UIAElementInfo and the wrapper looks so thin...

**Comment by vasily-v-ryabov** [comment]
Thank you! It's a good starting point for discussion. So let's start.

a) I think UiaElementInfo should not be overloaded by methods which are applicable for small groups of controls. I consider UiaElementInfo as a class for search functionality only. So all common actions like invoke() should be implemented in UiaWrapper, other type-specific actions are for <ControlId>Wrappers.

b) Maybe pattern ids list should also be moved to uia_wrapper.py because it's not a search functionality. Yeah, it's kinda direct dll usage in 2 modules. But it might be OK from another point of view.

c) It would be nice to re-write filling patterns list in without empty exception handler. Probably some conditional appending is better: something like if hasattr.

**Comment by airelil** [comment]
I agree with the most points. ```UiaWrapper``` could be a good place for the pattern actions. 

Regarding the patterns IDs list, if I move it to _uia_wrapper.py_ we get circular dependency because it's already used by ```UiaElelementInfo.richText``` and apparently other methods dependent on pattern ids will be added to ```UiaElementInfo``` later. Maybe we should create a separate module for this kind of constants, something like _uia_definitions.py_, similar to the current _win32_definitions.py_

**Comment by airelil** [comment]
I added "uia_definitions.py" and moved the pattern actions to wrappers. I still in doubt about the patterns IDs list. Rewriting it without a silent exception would look a bit complicated and less comprehensible. Compare these two examples
```python
# Annotation control pattern.
cls_name = "IUIAutomationAnnotationPattern"
if hasattr(comtypes.gen.UIAutomationClient, cls_name):
    klass = getattr(comtypes.gen.UIAutomationClient, cls_name)
    pattern_ids['Annotation'] = [_UIA_dll.UIA_AnnotationPatternId, klass]

# CustomNavigation control pattern.
cls_name = "IUIAutomationCustomNavigationPattern"
if hasattr(comtypes.gen.UIAutomationClient, cls_name):
    klass = getattr(comtypes.gen.UIAutomationClient, cls_name)
    pattern_ids['CustomNavigation'] = [_UIA_dll.UIA_CustomNavigationPatternId, klass]
```
vs.
```python
try:
    # Annotation control pattern.
    pattern_ids['Annotation'] = [
        _UIA_dll.UIA_AnnotationPatternId,
        comtypes.gen.UIAutomationClient.IUIAutomationAnnotationPattern
        ],

    # CustomNavigation control pattern.
    pattern_ids['CustomNavigation'] = [
        _UIA_dll.UIA_CustomNavigationPatternId,
        comtypes.gen.UIAutomationClient.IUIAutomationCustomNavigationPattern
        ],
except(AttributeError): 
    pass
```

**Comment by vasily-v-ryabov** [comment]
Maybe small private function would make it shorter and more readable.

**Comment by vasily-v-ryabov** [comment]
The task seems completed.
