### ISSUE TITLE
Implement GridWrapper to support native Delphi/C++Builder grids

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#160]
`GridWrapper` implementation might be based on [GVM_* messages](https://github.com/avplayer/avdbg/blob/master/Other/HexEdit/src/GridView/GridView.h).

Delphi demo applications can be downloaded as a binaries [from here](http://www.rosinsky.cz/delphi_download/).

**Comment by sglebs** [comment]
Have you tried https://github.com/yinkaisheng/Python-UIAutomation-for-Windows to see if its UIA support solves your problem? I noticed that it does recognize the Calculator buttons (Win10 metro). Not sure about owner-drawn widgets in Delphi. But I am interested in the subject.

**Comment by vasily-v-ryabov** [comment]
I'm afraid Delphi grids are not visible in `Inspect.exe` as grids. So UIA support will not help.

After small research few months ago we discovered that `DBGrid` and similar grids do not respond on standard `GVM_*` messages. It means native Win32 API support for this kind of grids looks impossible.
