### ISSUE TITLE
'UIAWrapper' object has no attribute 'is_active'

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#166]
I got the error while trying to run dlg.Wait.
```python
import os
from pywinauto.application import Application
from pywinauto.sysinfo import is_x64_Python

wpf_samples_folder =  r"apps\WPF_samples"
if is_x64_Python():
    wpf_samples_folder = os.path.join(wpf_samples_folder, 'x64')
wpf_app_1 = os.path.join(wpf_samples_folder, u"WpfApplication1.exe")
app = Application(backend = 'uia').Start(wpf_app_1)
dlg = app.WPFSampleApplication

dlg.Wait('active')
```

Edit: fix the code to reproduce the error

**Comment by airelil** [comment]
Should we add to UIAWrapper a simple implementation of ```is_active``` method like following?
```python
    #-----------------------------------------------------------
    def is_active(self):
        """Whether the window is active or not"""
        return (self.is_visible() and self.is_enabled())
```

**Comment by vasily-v-ryabov** [comment]
`active` is not the same as `visible+enabled`. We need to find UIA functionality similar to `GetActive` for native windows.

**Comment by Eucaly** [comment]
Quoted from above
>
We need to find UIA functionality similar to GetActive for native windows.
>

I am wondering if there is some mechanism in [pywinauto](https://github.com/pywinauto/pywinauto) that doing the same as [WinActivate](https://autohotkey.com/docs/commands/WinActivate.htm) (in AutoHotKey) to **Activates the specified window (makes it foremost)**

Is this feature not implemented from win32 **[SetActiveWindow](https://github.com/pywinauto/pywinauto/blob/5176a9eaf568781a0cb8700dd020ab8753592e61/pywinauto/win32functions.py#L136)**, or there are some technical issue for it?

By the way, as an 8-year fan of AutoHotKey and 3-week new comer on Python, I really love the implementation of **pywinauto**

**Comment by airelil** [comment]
Hi @Eucaly. With the UIA branch we introduced a new concept of 'back ends'. This is to allow the GUI automation by using different available mechanisms. The ```uia``` back end, for example, implies working with MS UI Automation technology, without involving direct calls to Win32 API while the automation based on pure Win32 API calls now is incorporated into the ```native``` back end.  Trying to stick to UI Automation is the main reason for opening this issue. We wanted to find a UI Automation equivalent to ```SetActiveWindow```. @Eucaly, you can see my implementation for ```UiaWrapper.is_active``` method in PR #213. Any thoughts about it are always welcome.

**Comment by Eucaly** [comment]
Hi @airelil , thanks for quick response. My project (that uses **pywinauto**) is target for a floating bar to help different programs to do some scripting. (Just implement the early 5% concept proto, not on Github yet). Maybe named **bZmenu**

I have another UIA project (in c# AutomationElement) [**bZmd** to preview markdown files, when editing with (virtually) any editors](https://github.com/beZong/bZmd/blob/master/bZmd/Watcher/WindowWatcher.cs#L106). But that is a passive role (monitoring windows), rather than operate them. 

Do have some thought to port bZmd to pyQt5, but it seems pyQt webbrowser has some incompatible migration recently (QtWebKit, QtWebKitWidgets, QtWebEngineWidgets).

I will keep watching UIA/AutomationElement both from c# and Python.

**Comment by vasily-v-ryabov** [comment]
> I am wondering if there is some mechanism in pywinauto that doing the same as WinActivate (in AutoHotKey) to Activates the specified window (makes it foremost)

Hi @Eucaly , for Win32 API backend (pywinauto 0.5.4) you can use method `SetFocus()` that will be renamed to `set_focus()` in 0.6.0 (though `native` backend will support old deprecated name). Say `app.TopLevelDialog.SetFocus()` will bring the window to top.

**Comment by Eucaly** [comment]
Hi @vasily-v-ryabov , thanks for the clear instruction. It works now by using `.SetFocus()`
