### ISSUE TITLE
MenuBar for Notepad.exe cannot be wrapped in "uia" backend

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#170]
I'm trying simple code:

```python
import pywinauto

app = pywinauto.Application(backend='uia').start('notepad.exe')
dlg = app.UntitledNotepad
ctrl = dlg.Edit.WrapperObject()

dlg.PrintControlIdentifiers()
dlg.MenuBar.WrapperObject()
```

The output of `PrintControlIdentifiers()` is
```
Control Identifiers:
Edit - ''   (L209, T471, R1491, B999)	
'' '0' '1' 'Edit' 

StatusBar - ''   (L209, T999, R1491, B1019)	
'2' 'StatusBar' 

TitleBar - 'None'   (L228, T431, R1491, B451)	
'3' 'TitleBar' 

MenuBar - 'Application'   (L209, T451, R1491, B470)	
'Application' 'ApplicationMenuBar' 'MenuBar' 
```

But line `dlg.MenuBar.WrapperObject()` fails.

**Comment by cetygamer** [comment]
That happens because of extra class_name check here:
https://github.com/pywinauto/pywinauto/blob/UIA/pywinauto/findwindows.py#L264
Since there is also exception handling for `controls.InvalidWindowHandle` and `controls.InvalidElement` exceptions `if class_name` check seems to be unnecessary.
