### ISSUE TITLE
ImportError: cannot import name application

### ISSUE THREAD

**Issue by jingjinjingjin** [pywinauto/pywinauto#172]
When i use python 2.7.10 Shell, it's ok
`>>>from pywinauto import application`
`>>>`
When i use sublime text 3( or pycharm), ImportError happen
`from pywinauto import application`
`ImportError: cannot import name application`
What's wrong?

**Comment by airelil** [comment]
Looks for me as a wrong python interpreter or a different python path have been used. What do you get when you run following from your Sublime (pycharm) ?
```python
import os; print(os.getcwd(), os.sys.version, os.sys.winver)
import sys; print(sys.path)
```

**Comment by jingjinjingjin** [comment]
`('E:\\py_code', '2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]', '2.7')
['E:\\py_code', 'C:\\Python27\\lib\\site-packages\\pyltp-0.1.8-py2.7-win-amd64.egg', 'C:\\Python27\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages', 'C:\\Python27\\lib\\site-packages\\win32', 'C:\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\Python27\\lib\\site-packages\\Pythonwin']`

**Comment by airelil** [comment]
And where the pywinauto package resides ? Can you run the same commands from your shell ?

**Comment by jingjinjingjin** [comment]
`import os; print(os.getcwd(), os.sys.version, os.sys.winver)`
`('C:\\Python27', '2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]', '2.7')`

`import sys; print(sys.path)`
`['', 'C:\\Python27\\Lib\\idlelib', 'C:\\Python27\\lib\\site-packages\\pyltp-0.1.8-py2.7-win-amd64.egg', 'C:\\Python27\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages', 'C:\\Python27\\lib\\site-packages\\win32', 'C:\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\Python27\\lib\\site-packages\\Pythonwin']`

**Comment by jingjinjingjin** [comment]
@airelil  pywinauto package path:    C:\Python27\Lib\site-packages\pywinauto

**Comment by airelil** [comment]
Do other kind of imports work for your ? Try ```import pywinauto```  or ```from pywinauto import application as appl```?

**Comment by jingjinjingjin** [comment]
@airelil  
[sublime text3]
```import pywinauto
dir(pywinauto)
```
export `['__builtins__', '__doc__', '__file__', '__name__', '__package__', 'pywinauto']`
no application attribute

**Comment by cetygamer** [comment]
@jingjinjingjin
Does your `C:\\Python27\\lib\\site-packages` folder contain another `pywinauto` folder? If not, then it seems PyChamr and sublime are trying to import module from another place. Maybe, you downloaded main repository and placed it somewhere near PyCharm's project folder.

Anyway, this should work for you:
```python
import pywinauto.pywinauto as pywinauto
dir(pywinauto)
```

**Comment by jingjinjingjin** [comment]
@cetygamer  You are right. Sublime import module from another place (my script file name is pywinauto.py).  I am so stupid ╮(╯_╰)╭, sorry
