### ISSUE TITLE
How to get visibility of control id

### ISSUE THREAD

**Issue by jsonpanganiban** [pywinauto/pywinauto#223]
Using AutoIt's control_command(e.g. autoit.control_command('win_title', 'control_id', 'IsVisible')), I can get the visibility of control id. How can I do the same with pywinauto?

**Comment by vasily-v-ryabov** [comment]
You're able to do something like this:
```python
app.ApproxWindowTitle.ApproxControlName.IsVisible()
# or
app.Window_(title="Exact window title").ChildWindow(title="OK", class_name="Button").IsVisible()
```
