### ISSUE TITLE
pywintypes.error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')

### ISSUE THREAD

**Issue by meng89** [pywinauto/pywinauto#226]
my codes like this:
```python
import pywinauto
file = r'\\gentoo\data\windows_soft\python\7z1602.exe'
app = pywinauto.application.Application().start(file)
```
I got this error message when the file in a network drive.

**Comment by vasily-v-ryabov** [comment]
Hi @meng89, did you try the same file for `subprocess.call(file, shell=True)`? Is that working?

**Comment by meng89** [comment]
@vasily-v-ryabov , I am sorry for answering so late.
Yes,` subprocess.call(file, shell=True)` worked.
After some tests, I found out this error only come out when the file is share via Samba.

Sorry to bother you.

**Comment by vasily-v-ryabov** [comment]
If you map this share as a network drive, it works.
It's a bounding of `win32file.GetBinaryType` function (it doesn't handle UNC paths).
