### ISSUE TITLE
Docs for UIA branch doesn't have UIA related modules

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#230]
Documentation builds should be triggered with comtypes support in order to allow imports of uia related modules and generating of their docs.

**Comment by airelil** [comment]
I made several fixes in my branch: https://github.com/airelil/pywinauto/commits/menu

See an [example](pywinauto.readthedocs.io/en/menu/code/pywinauto.controls.uia_controls.html#pywinauto.controls.uia_controls.MenuWrapper) for UIA documentation. Notice a nasty [definition of ```control_types```](http://airelil-pywinauto.readthedocs.io/en/menu/code/pywinauto.controls.uia_controls.html#pywinauto.controls.uia_controls.MenuWrapper.control_types) in the doc. This is because of mocking ```comtypes``` module. Maybe we'd better put a Sphynx directive do not generate doc for these class variables...

**Comment by vasily-v-ryabov** [comment]
Looks good. Just one more thing. We need to make wrapper parameter name consistent: `elem` (now it's `elem_or_handle` or `hwnd` for various classes).

**Comment by vasily-v-ryabov** [comment]
@airelil it seems we can close this. Please re-open if I missed something.
