### ISSUE TITLE
Unable to automate Xilinx Vivado application using Swapy

### ISSUE THREAD

**Issue by KhajaRahimuddin** [pywinauto/pywinauto#237]
I am using swapy(desktop automation tool which uses pywinauto python package) to automate desktop UI activities, but swapy does not recognize the properties of Xilinx Vivado application.Please give me a way/solution to access the properties of Vivado application

**Comment by vasily-v-ryabov** [comment]
AFAIK Vivado should have batch mode to program the device without UI. Is GUI automation really necessary here?

**Comment by vasily-v-ryabov** [comment]
Closing since no response for a long time. If it's still relevant, please re-open.
