### ISSUE TITLE
HwndWrapper.SetFocus crash

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#240]
I have a crash in HwndWrapper.SetFocus (master branch and UIA branch). It seems that it crashed because the second argument for `AttachThreadInput` equals zero (see the last line in the trace below)

```
---> 26         app_dialog.SetFocus()
     27     except(WindowNotFoundError):
     28         print '"%s" not found' % random_app

D:\dev\try\pywinauto\controls\HwndWrapper.py in SetFocus(self
   1593                 win32process.AttachThreadInput(control_thread,
   1594                                                cur_fore_thread,
-> 1595                                                1)
   1596
   1597                 win32gui.SetForegroundWindow(self.handle)

error: (87, 'AttachThreadInput', 'The parameter is incorrect.')

In [4]: debug
> d:\dev\try\pywinauto\controls\hwndwrapper.py(1595)SetFocus(
   1593                 win32process.AttachThreadInput(control_thread,
   1594                                                cur_fore_thread,
-> 1595                                                1)
   1596
   1597                 win32gui.SetForegroundWindow(self.handle)

ipdb> pp control_thread, cur_fore_thread
(7464, 0)
ipdb>
```

edit: typos, added note about UIA branch

**Comment by airelil** [comment]
I think I managed to pinpoint the problem. The implementation of ```SetFocus``` doesn't handle a scenario when the desktop doesn't have any active window. The fix should be quite simple: just call ```SetForegroundWindow``` with a handle of a top window of our controlled application without attaching to any other threads. I'm not sure where the fix should be applied though, on master branch or on UIA?

Here the script reproducing the bug:
```python
from pywinauto.application import Application
import time

delay=0.5
calc = Application()
calc.start("calc.exe")
np = Application()
np.start("notepad.exe")
time.sleep(delay)

# We can switch focus as much as we want, it just works
for _ in range(5):
    calc.Calculator.SetFocus()
    np.UntitledNotepad.SetFocus()
# However, when we minimize/restore Notepad
# we end up without any active window on our desktop
np.UntitledNotepad.Minimize()
np.UntitledNotepad.Restore()

# Now setting focus to Calculator will fail even if we try to wait
time.sleep(delay*4)
calc.Calculator.SetFocus()
```

**Comment by vasily-v-ryabov** [comment]
Great! Please fix it in UIA. I'm planning to merge UIA into master very soon (probably in a week). Until this moment it's better to send PRs to UIA only.

**Comment by vasily-v-ryabov** [comment]
@airelil are you still able to reproduce this crash?

**Comment by airelil** [comment]
@vasily-v-ryabov, no I can't reproduce it so far. Notice that we also have a test case ```NonActiveWindowFocusTests.test_issue_240``` that checks this scenario.

**Comment by vasily-v-ryabov** [comment]
Can we close the issue then?

**Comment by airelil** [comment]
Yes, we can close
