### ISSUE TITLE
Is there any way to run pywinauto in remote desktop session?

### ISSUE THREAD

**Issue by mineralres** [pywinauto/pywinauto#247]
I can run pywinauto in rdp sesion when my rdp terminal is open and show normal, buy if the terminal is closed, some of the win32api function lik win32api.SetCursorPos will run into exception, is there any solution?

**Comment by vasily-v-ryabov** [comment]
Hi @mineralres, it's a common problem for all GUI automation libraries. There are 3 workarounds.
 * Run RDP in window mode (not full screen), do not minimize it, run pywinauto script and quickly switch to a local machine window.
 * Use VNC server connection (say TightVNC) and do not use RDP (need to reboot remote machine if RDP used). This approach allows safe disconnect (active desktop is still alive on remote machine even if you shutdown your laptop). For automated GUI testing schedule it's usually convenient to set up auto-logon additionally (but not strictly necessary).
 * Do not use `TypeKeys`, `ClickInput` and derived functions which require active desktop. Other methods just send window messages that work without active desktop and often for a minimized window. See [this thread for example](http://stackoverflow.com/q/32846550/3648361).

Also note that running local CI service (like Jenkins) as a Windows service will not work, you have to use it as usual process, not a daemon.

**Comment by mineralres** [comment]
thanks a lot! i got it.

**Comment by vasily-v-ryabov** [comment]
Just in case: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html
