### ISSUE TITLE
hooks module refactoring

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#258]
I start working on refactoring hooks.py module so I'd like to list the planned changes:
- switch to non-blocking `PeekMessageW` in the `listen` loop
- fix landscape.io/codacy warnings about a return statement inside of `finally`
- rename hooks.py to win32_hooks.py
- add unit tests for the module (not sure yet, but may be `mock` could be handy here)

**Comment by airelil** [comment]
Can we use ```mock``` for unit testing? However it's part of standard python distribution only from 3.3 and it should be added as an additional requirement for 2.7  (Only for the development )

**Comment by vasily-v-ryabov** [comment]
We can start from simple tests using `mock` but we also need kind of real app test scenario.

**Comment by airelil** [comment]
I close the issue. For any further changes in ```hooks``` we should open a separate issue describing the required changes/additions.
