### ISSUE TITLE
Cannot Find pypiwin32 when trying to sntall pywinauto

### ISSUE THREAD

**Issue by RHeniz** [pywinauto/pywinauto#264]
running install
running bdist_egg
running egg_info
writing pywinauto.egg-info\PKG-INFO
writing requirements to pywinauto.egg-info\requires.txt
writing dependency_links to pywinauto.egg-info\dependency_links.txt
writing top-level names to pywinauto.egg-info\top_level.txt
reading manifest file 'pywinauto.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'examples\examples_watsup\*.py'
writing manifest file 'pywinauto.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\actionlogger.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\application.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\backend.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\base_wrapper.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\clipboard.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\controlproperties.py -> build\bdist.win32\egg\pywinauto
creating build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\common_controls.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\hwndwrapper.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\menuwrapper.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\uiawrapper.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\uia_controls.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\win32_controls.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\controls\__init__.py -> build\bdist.win32\egg\pywinauto\controls
copying build\lib\pywinauto\element_info.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\findbestmatch.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\findwindows.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\fuzzydict.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\handleprops.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\keyboard.py -> build\bdist.win32\egg\pywinauto
creating build\bdist.win32\egg\pywinauto\linux
copying build\lib\pywinauto\linux\clipboard.py -> build\bdist.win32\egg\pywinauto\linux
copying build\lib\pywinauto\linux\keyboard.py -> build\bdist.win32\egg\pywinauto\linux
copying build\lib\pywinauto\linux\__init__.py -> build\bdist.win32\egg\pywinauto\linux
copying build\lib\pywinauto\mouse.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\remote_memory_block.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\sysinfo.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\taskbar.py -> build\bdist.win32\egg\pywinauto
creating build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\allcontrols.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\asianhotkey.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\comboboxdroppedheight.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\comparetoreffont.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\leadtrailspaces.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\miscvalues.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\missalignment.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\missingextrastring.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\overlapping.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\repeatedhotkey.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\translation.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\truncation.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\_menux.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\tests\__init__.py -> build\bdist.win32\egg\pywinauto\tests
copying build\lib\pywinauto\timings.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\uia_defines.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\uia_element_info.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\win32defines.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\win32functions.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\win32structures.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\win32_element_info.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\win32_hooks.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\xml_helpers.py -> build\bdist.win32\egg\pywinauto
copying build\lib\pywinauto\__init__.py -> build\bdist.win32\egg\pywinauto
byte-compiling build\bdist.win32\egg\pywinauto\actionlogger.py to actionlogger.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\application.py to application.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\backend.py to backend.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\base_wrapper.py to base_wrapper.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\clipboard.py to clipboard.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controlproperties.py to controlproperties.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\common_controls.py to common_controls.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\hwndwrapper.py to hwndwrapper.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\menuwrapper.py to menuwrapper.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\uiawrapper.py to uiawrapper.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\uia_controls.py to uia_controls.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\win32_controls.py to win32_controls.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\controls\__init__.py to __init__.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\element_info.py to element_info.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\findbestmatch.py to findbestmatch.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\findwindows.py to findwindows.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\fuzzydict.py to fuzzydict.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\handleprops.py to handleprops.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\keyboard.py to keyboard.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\linux\clipboard.py to clipboard.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\linux\keyboard.py to keyboard.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\linux\__init__.py to __init__.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\mouse.py to mouse.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\remote_memory_block.py to remote_memory_block.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\sysinfo.py to sysinfo.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\taskbar.py to taskbar.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\allcontrols.py to allcontrols.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\asianhotkey.py to asianhotkey.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\comboboxdroppedheight.py to comboboxdroppedheight.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\comparetoreffont.py to comparetoreffont.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\leadtrailspaces.py to leadtrailspaces.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\miscvalues.py to miscvalues.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\missalignment.py to missalignment.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\missingextrastring.py to missingextrastring.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\overlapping.py to overlapping.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\repeatedhotkey.py to repeatedhotkey.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\translation.py to translation.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\truncation.py to truncation.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\_menux.py to _menux.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\tests\__init__.py to __init__.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\timings.py to timings.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\uia_defines.py to uia_defines.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\uia_element_info.py to uia_element_info.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\win32defines.py to win32defines.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\win32functions.py to win32functions.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\win32structures.py to win32structures.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\win32_element_info.py to win32_element_info.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\win32_hooks.py to win32_hooks.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\xml_helpers.py to xml_helpers.cpython-35.pyc
byte-compiling build\bdist.win32\egg\pywinauto\__init__.py to __init__.cpython-35.pyc
creating build\bdist.win32\egg\EGG-INFO
copying pywinauto.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pywinauto.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pywinauto.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying pywinauto.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying pywinauto.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\pywinauto-0.6.0-py3.5.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing pywinauto-0.6.0-py3.5.egg
Removing c:\program files (x86)\python35-32\lib\site-packages\pywinauto-0.6.0-py3.5.egg
Copying pywinauto-0.6.0-py3.5.egg to c:\program files (x86)\python35-32\lib\site-packages
pywinauto 0.6.0 is already the active version in easy-install.pth

Installed c:\program files (x86)\python35-32\lib\site-packages\pywinauto-0.6.0-py3.5.egg
Processing dependencies for pywinauto==0.6.0
Searching for pypiwin32
Reading https://pypi.python.org/simple/pypiwin32/
Download error on https://pypi.python.org/simple/pypiwin32/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
Couldn't find index page for 'pypiwin32' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
No local packages or working download links found for pypiwin32
error: Could not find suitable distribution for Requirement.parse('pypiwin32')

---------------------------------------------------------------------------------------------------------

I cannot use pip to install it due to the firewalls at work, when I try to install manually I run into this problem. any help would be appreciated.

**Comment by vasily-v-ryabov** [comment]
`setup.py` is trying to install dependencies automatically (from PyPI which is not available for you).
Please follow [Manual Installation](http://pywinauto.readthedocs.io/en/latest/#manual-installation) list and download each dependency manually.

Or try this command for PyWin32: `easy_install https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20220/pywin32-220.win32-py3.5.exe`

**Comment by vasily-v-ryabov** [comment]
@RHeniz are you able to install pywinauto after all?

**Comment by vasily-v-ryabov** [comment]
Closing since no answer long time. If it's still relevant, please re-open.
