### ISSUE TITLE
Bug:  in application / master , possible crash when ctrl.window_text() becomes None at the right moment...

### ISSUE THREAD

**Issue by mborus** [pywinauto/pywinauto#266]
Hi,

this code is not safe and crashes, when ctrl.window_text() becomes None after
line 593. This happened to me when monitoring an application that opens and closes
a lot of windows. 

from line 593 in application.py / master:

    ctrl_text = ctrl.window_text()
    if ctrl_text:
         # transform multi-line text to one liner
         ctrl_text = ctrl.window_text().replace('\n', r'\n').replace('\r', r'\r')
`
I suggest using this last line instead.

    ctrl_text = ctrl_text.replace('\n', r'\n').replace('\r', r'\r')

**Comment by airelil** [comment]
Hi @mborus , I think it makes sense. Just for the record, can you provide a bit details: the Python version, architecture? As I understand you use the latest version Pywinauto form the main branch (ver 0.6). Is it right ?

**Comment by vasily-v-ryabov** [comment]
Hi @mborus, thanks for finding this! 👍  `window_text()` may return `None` in case the control is disappeared during text retrieval for example (or another rare case when something goes wrong). I can fix it a bit later (currently very busy at the main job). By the way, pull requests are welcome. ;-)

**Comment by mborus** [comment]
Brilliant, I'll attempt a pull request on the weekend!

To answer airelil's question: Windows Server 2012 64 bit, python 35-32 (and 32bit plugins due to some internal firewall problems that prevent me from downloading plugins, so I take them from my other 32bit setup). One core only, it's a VM, that's why monitoring a running resource hog is challenging.
