### ISSUE TITLE
 TypeError: adding NoneType + String in findbestmatch.py

### ISSUE THREAD

**Issue by halfnibble** [pywinauto/pywinauto#269]
I'm not sure if it's just my code, but this seems like something that should be catched.

I'm getting the following error on 0.6.0 with certain child_window selections:
```
pywinauto\findbestmatch.py", line 274, in get_non_text_control_name
    best_name = text_ctrl.window_text() + ctrl_friendly_class_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I'm wondering if there should be a try/catch block around the statement at [line 274](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/findbestmatch.py#L274)?

**Comment by halfnibble** [comment]
Interestingly, if I wrap my problem selector with in an if statement:
```
if app.<selector>.exists():
    app.<selector>.click()
```
Then the TypeError goes away and the click action is performed.

**Comment by airelil** [comment]
Noninitialized friendly_class_name definitely looks as a bug. What type of backend do you use?

**Comment by airelil** [comment]
Oh. Probably it's not friendly_class_name, but text_ctrl.window_text()

**Comment by halfnibble** [comment]
I'm using 'win32'. For a legacy VB app that was probably made before I was born...

I think it's text_ctrl.window_text(). But I just started looking into the codebase a moment ago.

**Comment by airelil** [comment]
Maybe you'll find this oneliner be useful for you :
```app.selector.wait('exists').click()```

You can add an optional timeout parameter as well.

**Comment by halfnibble** [comment]
@airelil Actually, using `wait()` also causes the TypeError: NoneType + String bug.

It only works with `if app.<selector>.exists():`. I wish I could provide better debugging info. All I can think is that the control tree is so jacked up that searching for a best match is somehow coming across an unanticipated error state.

**Comment by halfnibble** [comment]
Would providing a .txt file with the list of controls help in any way?

**Comment by halfnibble** [comment]
I then ran across an issue whereby my "if exists()" fix wasn't working either. This may have something to do with the fact I'm running stuff in a **for** loop. I don't know. I hacked it into working by setting `time.sleep(1)` before my **for** loop starts.

**Comment by halfnibble** [comment]
So, I'm going to close this issue for most likely not affecting other users.

**Comment by vasily-v-ryabov** [comment]
Hi @halfnibble, the code in `findbestmatch` is not safe. I'll amend. Thanks for reporting this!
