### ISSUE TITLE
Is there a way to find the mouse cursor's coordinates? (pywinauto.mouse )

### ISSUE THREAD

**Issue by Moondra** [pywinauto/pywinauto#277]
Hi, I was just wondering if it's possible to know the mouse cursor's current coordinates.

I couldn't find any methods to do so under the pywinauto.mouse docs. 

Thanks.

**Comment by vasily-v-ryabov** [comment]
Hi @Moondra, it's easy to use `win32api` module from pyWin32 extensions that already installed with pywinauto.
```python
import win32api
x, y = win32api.GetCursorPos()
```

**Comment by Moondra** [comment]
Thank you~

**Comment by Moondra** [comment]
I was playing around with this code and I"m not quite sure why I'm getting an output that is different from my mouse cursor should be:

```import pywinauto
import win32api



pywinauto.mouse.move(coords=(500, 209))
x, y = win32api.GetCursorPos()
print(x,y)


Output is:
(333, 139)

I would presume that the output should be 
(500, 209)

**Comment by airelil** [comment]
@Moondra, it may be due to the [high-DPI awareness](https://msdn.microsoft.com/en-us/library/windows/desktop/dd371771(v=vs.85).aspx). Pywinauto makes the python process DPI-aware automatically on import pywinauto module (implicitly through include of win32functions). You can try to import pywinauto or even pywinauto.win32functions implicitly to make the python process in your script be DPI-aware.

**Comment by Moondra** [comment]
Hi Airelil. Yeah, after playing around with the DPI settings, you seem to be right. I don't quite understand how to use win32 functions through pywinauto. I"m trying the following code but I get the an error,




` import pywinauto`
`import win32api`

`pywinauto.mouse.move(coords=(800, 209))`
`x,y= pywinauto.win32functions.GetCursorPos()`


TypeError: 'int' object is not iterable


I then tried 
`y= pywinauto.win32functions.GetCursorPos()`

but when I print `y` I get an output of 1.


Thank you so much for you help.

**Comment by airelil** [comment]
You do not have to use win32functions. Just import it. After importing you can use win32 api as in your original example

**Comment by Moondra** [comment]
It doesn't seem to be working. I've tried different variations of this code, including the commented out area.


```
import pywinauto
##from pywinauto import win32functions
import win32api



pywinauto.mouse.move(coords=(500, 209))
x, y = win32api.GetCursorPos()
print(x,y)```


I'm getting a different CursorPos when the DPI is set to 150%.

**Comment by airelil** [comment]
We are a bit offline during the holidays. I'll try to play with it when I get access to my computer.

**Comment by airelil** [comment]
Hi @Moondra. I just tried to run your snippet on my laptop with the DPI set to 150% but it still works fine for me. I got printed 500, 209 back. I ran it on  64-bit Win8.1 with Python 3.5 and Python 2.7. What's your configuration ? Do you use two monitors ? Do you get ```1``` as a result to a following diagnostic call:
```pywinauto.win32functions.IsProcessDPIAware()``` ?

**Comment by Moondra** [comment]
Hi Valentin,


I'm currently using Windows 7 with Python 2.7.
I do have my laptop connected to a TV when I watch TV, but I disconnected
the hdmi and ran the code again, and I'm still getting different mouse
coordinates. I even right clicked and clicked on the "screen resolution"
option on  my windows desktop, to make sure only one monitor is being
recognized.

As for the line of code you wanted me to test out, I did get a 1 as an
output.





On Mon, Dec 26, 2016 at 2:31 PM, Valentin Kroupkin <notifications@github.com

**Comment by Moondra** [comment]
Hi Valentin,
I ran a couple of more tests.
120% DPI works, however 150% doesn't seem to work.

Can't figure out why.

**Comment by airelil** [comment]
@Moondra, you may try to play with setting up the DPI awareness. For Win7 it might require different settings. See the example below when I try to apply different settings:
```
In [6]: from pywinauto.win32functions import Process_DPI_Awareness

In [7]: from pywinauto.win32functions import SetProcessDpiAwareness

In [8]: SetProcessDpiAwareness(Process_DPI_Awareness["Process_Per_Monitor_DPI_Aware"])
Out[8]: -2147024891

In [9]: pywinauto.mouse.move(coords=(500, 209)); x, y = win32api.GetCursorPos(); print(x,y)
(500, 209)

In [10]: SetProcessDpiAwareness(Process_DPI_Awareness["Process_System_DPI_Aware"])
Out[10]: -2147024891

In [11]: pywinauto.mouse.move(coords=(500, 209)); x, y = win32api.GetCursorPos(); print(x,y)
(500, 209)

In [12]: from pywinauto.win32functions import SetProcessDPIAware

In [13]: SetProcessDPIAware()
Out[13]: 1

In [14]: pywinauto.mouse.move(coords=(500, 209)); x, y = win32api.GetCursorPos(); print(x,y)
(500, 209)

```

**Comment by Moondra** [comment]
Thanks. ATM, I just adjusted my DPI settings to 120% because I want to test out some other functions of Pywinauto.

**Comment by vasily-v-ryabov** [comment]
Hi @Moondra , can we close this thread?

**Comment by Moondra** [comment]
Yeah. Sorry for the late reply.

**Comment by santhuu24** [comment]
Hii can i get the coordinates dynamically without taking the xy coordinates and without taking inspect elements

**Comment by vasily-v-ryabov** [comment]
Hi @santhuu24 sorry I can't get your question. Please explain it in more details and submit separate issue.
