### ISSUE TITLE
Traceback on print_control_identifiers(): handle unicode

### ISSUE THREAD

**Issue by roger6blog** [pywinauto/pywinauto#280]
Traceback (most recent call last):
  File "C:\proj\InstallServer.py", line 1039, in <module>
    install(lstStepSetting)
  File "C:\proj\InstallServer.py", line 929, in installServer
    result = freshInstall(lstStepSetting[0])
  File "C:\proj\InstallServer.py", line 482, in freshInstall
    common.waitWindow("Software License", 180, className='#32770', title='Softwa
re License Agreement')
  File "C:\proj\common.py", line 96, in waitWindow
    if getText(app, text):
  File "C:\proj\common.py", line 58, in getText
    app.dlg.print_control_identifiers()
  File "build\bdist.win32\egg\pywinauto\application.py", line 632, in print_cont
rol_identifiers
    print_identifiers([this_ctrl, ])
  File "build\bdist.win32\egg\pywinauto\application.py", line 630, in print_iden
tifiers
    print_identifiers(ctrl.children(), current_depth + 1)
  File "build\bdist.win32\egg\pywinauto\application.py", line 628, in print_iden
tifiers
    print(output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 4
05: ordinal not in range(128)

I fixed it by changing **print(output)** to **print(output.encode('utf-8'))**

**Comment by vasily-v-ryabov** [comment]
Hi @roger6blog, thanks for reporting this! Is this app available for download? Just to reporduce it on our side. Are there specific language settings in OS or in the app?

**Comment by roger6blog** [comment]
Hi @vasily-v-ryabov , I found this error during manipulate window control of TrendMicro OfficeScan installer. You can download from here (size: 1.1G)
http://files.trendmicro.com/products/officescan/XG/osce_xg_win_en_gm_b1222.exe
The error was happened at print_control_identifiers()  of window "Software License"

**Comment by roger6blog** [comment]
BTW, I think no specific language settings in OS or in the app because I use English version of windows

**Comment by vasily-v-ryabov** [comment]
Thanks! Will take a look when have a chance (most probably after January, 9 but maybe earlier).

**Comment by vasily-v-ryabov** [comment]
Hmm... Could not proceed to "Software License" page. Error message: there is no enough space on disk C: (but I have 56GB free space!).

But I could write unit test catching this issue!
Don't know how to fix it right way (I think there is no right way at all), but I will workaround it with `.encode(locale.getpreferredencoding(), errors='backslashreplace')`.
