### ISSUE TITLE
AttributeError: WindowSpecification class has no 'CPUUsage' method

### ISSUE THREAD

**Issue by forhonourlx** [pywinauto/pywinauto#282]
Hi Master,
I tried the following code and an err raised, would you have a look?
Thanks & Regards,
Simon

app = application.Application(backend="uia")
app = app.start("C:\\Program Files (x86)\\___.exe")
app.wait_cpu_usage_lower(5,10,0.5)

Traceback (most recent call last):
  File "NT8Auto_v0.2.py", line 99, in <module>
    main()
  File "NT8Auto_v0.2.py", line 63, in main
    app.wait_cpu_usage_lower(5,10,0.5)
  File "C:\Program Files\Python35\lib\site-packages\pywinauto\application.py", line 1030, in wait_cpu_usage_lower
    while self.CPUUsage(usage_interval) > threshold:
  File "C:\Program Files\Python35\lib\site-packages\pywinauto\application.py", line 165, in __call__
    format(self.criteria[-1]['best_match']) )
AttributeError: WindowSpecification class has no 'CPUUsage' method

**Comment by airelil** [comment]
You didn't specify a window / dialog. The general form should be: app.WindowTitle.wait_cpu_usage_title(),  but you have to change it according to a title of a dialog in your app

**Comment by vasily-v-ryabov** [comment]
CPU usage is app specific only (window specification is not needed), so it looks like a bug produced by replacing deprecated `CPUUsage` method with `cpu_usage`. I think I know how to reproduce and fix this. Will do when get back from the trip (after January, 9).
