### ISSUE TITLE
[Suggestion] best_name in findbestmatch.py

### ISSUE THREAD

**Issue by roger6blog** [pywinauto/pywinauto#284]
I findbestmatch.py, line 266: 
**best_name = text_ctrl.window_text() + ctrl_friendly_class_name**
I suggest best_name should be consider "text_ctrl.window_text() is None" condition
ex:
**best_name = text_ctrl.window_text() + ctrl_friendly_class_name if text_ctrl.window_text() else ctrl_friendly_class_name**

same scenario in line 274

**Comment by roger6blog** [comment]
Found it's duplicated issue:
[#269](https://github.com/pywinauto/pywinauto/issues/269)

**Comment by vasily-v-ryabov** [comment]
Fixed in master branch.
