### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by steronydh** [pywinauto/pywinauto#286]
I've just tried to install pywinauto through pip on a clean install of Python 3.6, and there's an installer error - is it calling the right version of PyWin32?:

`C:\WINDOWS\system32>pip install pywinauto
Collecting pywinauto
  Downloading pywinauto-0.6.0.zip (495kB)
    100% |████████████████████████████████| 501kB 1.6MB/s
Collecting six (from pywinauto)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pypiwin32 (from pywinauto)
  Downloading pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 223kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Steronydh\AppData\Local\Temp\pip-build-pblukrc3\pypiwin32\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Steronydh\AppData\Local\Temp\pip-build-pblukrc3\pypiwin32\`

**Comment by steronydh** [comment]
Trying to install it manually, I've found PyWin32-220.win32-py3.6.exe cannot find the Python installation (although it's definitely there!).

Running the installer through easy_install also fails:

....
Installed c:\python36\lib\site-packages\pywin32-220-py3.6-win32.egg
Processing dependencies for pywin32==220
Finished processing dependencies for pywin32==220
Traceback (most recent call last):
  File "c:\python36\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Steronydh\\AppData\\Local\\Temp\\easy_install-q7d6wmn9\\pywin32-220-py3.6-win32.egg.tmp\\mfc140u.dll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\easy_install.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\setuptools\command\easy_install.py", line 2265, in main
    **kw
  File "c:\python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python36\lib\site-packages\setuptools\command\easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "c:\python36\lib\site-packages\setuptools\command\easy_install.py", line 669, in easy_install
    rmtree(tmpdir)
  File "c:\python36\lib\site-packages\setuptools\command\easy_install.py", line 2227, in rmtree
    return shutil.rmtree(path, ignore_errors, onerror)
  File "c:\python36\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\python36\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\python36\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\python36\lib\site-packages\setuptools\command\easy_install.py", line 1677, in auto_chmod
    six.reraise(et, (ev[0], ev[1] + (" %s %s" % (func, arg))))
TypeError: 'PermissionError' object is not subscriptable

**Comment by Harri1970** [comment]
Hi!
I have also tried to install pywin in couple of Windows 10 machines and get this error also
"File "C:\Users\Steronydh\AppData\Local\Temp\pip-build-pblukrc3\pypiwin32\setup.py", line 121
print "Building pywin32", pywin32_version
^
SyntaxError: Missing parentheses in call to 'print'

Now I can't try this great module. I would like to test GUI automation with this and learn Python also.

**Comment by airelil** [comment]
Hi guys. Seems that pywin32 package for python 3.6 is not released yet. There are some tickets about it. See, for example: https://sourceforge.net/p/pywin32/bugs/734/

**Comment by steronydh** [comment]
But there's a Python 3.6 installer available here! [https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/](https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/)

**Comment by airelil** [comment]
I can't install it nor with pip neither with ```conda install```. At least on my conda. As a workaround you may try to install it manually. Notice though that this version of pywin32 is a bit newer.

**Comment by vasily-v-ryabov** [comment]
Wow! It seems [pypiwin32 package](https://pypi.python.org/pypi/pypiwin32) was updated with build 220 wheels for Python 3.6 today!
So `pip install pywinauto` worked for me on clean Python 3.6 32-bit.

@steronydh sorry for late response. Just went back from the holidays trip. Hope it should work for you now.

**Comment by Harri1970** [comment]
Thank you vasily. I have to try again, and start to learn automation with Python.

**Comment by steronydh** [comment]
Thanks, @vasily-v-ryabov it installs perfectly! Now to try using it. :)

**Comment by steronydh** [comment]
Working well so far!

**Comment by Jdodo45** [comment]
I tried first to pip install it in cmd as admin, it did not work. Then I tried it in  a normal cmd, it did something but I had some error (many red lines), in the third pip install in a normal cmd it worked. (python 3.6)
