### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'right_click_input'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pywinauto/pywinauto#287]
I fail on running example from README.md
Windows 7 64bit, Python 3.5.2 32bit (and Python 3.5.2 64bit)

```cmd
[PYWINAUTO] λ python explore.py
2017-01-17 09:25:13,233 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\ME\\Envs\\PYWINAUTO\\lib\\site-packages\\comtypes\\gen\\__init__.py'>
2017-01-17 09:25:13,237 INFO: Using writeable comtypes cache directory: 'C:\Users\ME\Envs\PYWINAUTO\lib\site-packages\comtypes\gen'
Traceback (most recent call last):
  File "explore.py", line 10, in <module>
    common_files.right_click_input()
AttributeError: 'NoneType' object has no attribute 'right_click_input'
```

 ## explore.py
```python
from pywinauto import Desktop, Application

Application().start('explorer.exe "C:\\Program Files"')

# connect to another process spawned by explorer.exe
app = Application(backend="uia").connect(path="explorer.exe", title="Program Files")

app.ProgramFiles.set_focus()
common_files = app.ProgramFiles.ItemsView.get_item('Common Files')
common_files.right_click_input()
app.ContextMenu.Properties.invoke()

# this dialog is open in another process (Desktop object doesn't rely on any process id)
Properties = Desktop(backend='uia').Common_Files_Properties
Properties.print_control_identifiers()
Properties.Cancel.click()
Properties.wait_not('visible') # make sure the dialog is closed
```

**Comment by airelil** [comment]
@Tset-Noitamotua, you get the error because ```app.ProgramFiles.ItemsView.get_item('Common Files')``` didn't return any item. Try to tune your strings. Make sure that explorer app is started in ```c:\Program Files```.

**Comment by vasily-v-ryabov** [comment]
It might be a problem with lazy initialization of the list view. Can you update to the [recent master branch](https://github.com/pywinauto/pywinauto/archive/master.zip) and try `app.wait_cpu_usage_lower(threshold=2.5)` before `app.ProgramFiles.set_focus()`?

And probably `get_item` should raise an exception with relevant message instead of returning `None`.

**Comment by airelil** [comment]
@vasily-v-ryabov, in fact ListViewWrapper for UIA already raises exception if the item is not found. It looks that there is the only one place in [get_item method](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/controls/uia_controls.py#L653) to get None if the item was looked up by string.

**Comment by Tset-Noitamotua** [comment]
@vasily-v-ryabov  When I use `app.wait_cpu_usage_lower(threshold=2.5)` I get another error:

```shell
[PYWINAUTO] λ python explore.py
2017-01-19 08:03:12,398 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\ME\\Envs\\PYWINAUTO\\lib\\site-packages\\comtypes\\gen\\__init__.py'>
2017-01-19 08:03:12,401 INFO: Using writeable comtypes cache directory: 'C:\Users\ME\Envs\PYWINAUTO\lib\site-packages\comtypes\gen'
Traceback (most recent call last):
  File "explore.py", line 8, in <module>
    app.wait_cpu_usage_lower(threshold=2.5)
  File "C:\Users\ME\Envs\PYWINAUTO\lib\site-packages\pywinauto\application.py", line 1030, in wait_cpu_usage_lower
    while self.CPUUsage(usage_interval) > threshold:
  File "C:\Users\ME\Envs\PYWINAUTO\lib\site-packages\pywinauto\application.py", line 165, in __call__
    format(self.criteria[-1]['best_match']) )
AttributeError: WindowSpecification class has no 'CPUUsage' method
```

**Comment by Tset-Noitamotua** [comment]
@airelil  What exactly do you mean by
> Try to tune your strings. ?

Explorer app is started in `C:\Programme` which is `C:\Program Files` on German local:

![image](https://cloud.githubusercontent.com/assets/5635462/22097116/adcdfe40-de1f-11e6-91dc-866e3a78cc67.png)

**Comment by airelil** [comment]
@Tset-Noitamotua , I suspect that your explorer dialog is a bit different because of your computer localization. You may try to see if both the dialog and the list box are correctly detected by pywinauto:
```python
app.ProgramFiles.draw_outline('red')
app.ProgramFiles.ItemsView.draw_outline('blue')
```

**Comment by Tset-Noitamotua** [comment]
![image](https://cloud.githubusercontent.com/assets/5635462/22098900/2c9a6b88-de29-11e6-8543-b62378b2c43d.png)

**Comment by airelil** [comment]
So we can see that ```app.app.ProgramFiles.ItemsView``` doesn't refer to the right box. So let's see if ``` app.ProgramFiles.ListBox.draw_outline()``` works. A green outline should be presented around the list view with the folders.

**Comment by Tset-Noitamotua** [comment]
comming closer :)

But now rightclick seems to go to scrollbar and i get this MatchError:
```shell
 raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Properties' in 'dict_keys(['Bildlauf hierMenuItem', 'Seite nach obenMenuItem', 'MenuItem6', 'MenuItem2', 'Bildlauf untenMenuItem', 'Bildlauf hier', 'Seite nach oben', 'MenuItem4', 'Oberer RandMenuItem', 'Unterer Rand', 'MenuItem1', 'Bildlauf obenMenuItem', 'Bildlauf unten', 'MenuItem3', 'Unterer RandMenuItem', 'MenuItem', 'MenuItem7', 'MenuItem5', 'Seite nach untenMenuItem', 'Bildlauf oben', 'MenuItem0', 'Seite nach unten', 'Oberer Rand'])'
```
![image](https://cloud.githubusercontent.com/assets/5635462/22099708/bab5c086-de2c-11e6-99fc-e21d7f1c76cc.png)

**Comment by airelil** [comment]
This is what I mean - tune your strings. Give a go to this: ```app.ContextMenu[u'Properties'].invoke()
```, but instead of 'Properties' you should use a German translation of the item. Also make sure you got the click on the right item. Put another ```common_files.draw_outline()``` before ```common_files.right_click_input()```

**Comment by Tset-Noitamotua** [comment]
Is there a way to inspect UI element upfront to get an idea what the names are?

**Comment by airelil** [comment]
This is what we show in the example. You should use ```print_control_identifiers``` method to inspect any dialog/control. Also I forgot to mention, you can play with click coordinates: ```common_files.right_click_input((50, 5))```

**Comment by Tset-Noitamotua** [comment]
Are there some shortcuts istead of coordinates, like - center, left, right, left_corner, right_corner etc.?

**Comment by Tset-Noitamotua** [comment]
And do I understand it right that if name of a window contains spaces (e.g. `Eigenschaften von Common Files`) I have to replace them with underscores `_` (e.g. `Eigenschaften_von_Common_Files`)

`Properties = Desktop(backend='uia').Eigenschaften_von_Common_Files`

**Comment by airelil** [comment]
There are not shortcuts for coordinates, just try to use reasonable values. Regarding the names, I'd suggest you to read our docs:[Getting Started](https://pywinauto.readthedocs.io/en/latest/getting_started.html) and [How To's](https://pywinauto.readthedocs.io/en/latest/HowTo.html) I'm not sure if our 'best match' algorithm will work stable for the localized names, so you'd better stick with access through ```[u'local name string']``` as suggested in [this how-to section](https://pywinauto.readthedocs.io/en/latest/HowTo.html#how-to-use-pywinauto-with-application-languages-other-than-english).

**Comment by vasily-v-ryabov** [comment]
Of course, all readme examples are supposed to run on English interface of Windows. The Getting Started guide will help you to start using `Inspect.exe` if you need to modify some script for non-English localization.

**Comment by vasily-v-ryabov** [comment]
Exception with missing `CPUUsage` method is a known bug in 0.6.0, it's already fixed in master branch and will gone in 0.6.1. With the new info I see no problems so far.

**Comment by Tset-Noitamotua** [comment]
@vasily-v-ryabov  I installed from master branch some hours ago.

**Comment by vasily-v-ryabov** [comment]
@Tset-Noitamotua I can re-check tomorrow about `CPUUsage` crash. But it will not help you because the script must be modified for non-English localization with the name `Programme` instead of `ProgramFiles`. Can you modify the script and re-check without `wait_cpu_usage_lower` call?

**Comment by Tset-Noitamotua** [comment]
Below modification runs in German Windows 7 64bit. Thus I close this issue.

Thank you very much for your support!

```python
from pywinauto import Desktop, Application



Application().start('explorer.exe "C:\Program Files"')

# connect to another process spawned by explorer.exe
app = Application(backend="uia").connect(path="explorer.exe", title="Programme")

app.Programme.set_focus()
app.Programme.draw_outline('read')
app.Programme.ListBox.draw_outline('green')

common_files = app.Programme.ListBox.get_item('Common Files')
common_files.draw_outline('blue')
common_files.right_click_input((50,5))
app.ContextMenu['Eigenschaften'].invoke()


# this dialog is open in another process (Desktop object doesn't rely on any process id)
Properties = Desktop(backend='uia').Eigenschaften_von_Common_Files
Properties.print_control_identifiers()
Properties['Abbrechen'].click()
Properties.wait_not('visible') # make sure the dialog is closed
```

**Comment by vasily-v-ryabov** [comment]
Great! Welcome to ask everything that's unclear or looks like a bug.
