### ISSUE TITLE
Beginner questions about example code in README.md

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pywinauto/pywinauto#288]
There are some points about [example code](https://gist.github.com/Tset-Noitamotua/8c3086dc3e7ccd0444b4637a3c62ee7c#file-example_001-py) that are not fully clear to me.

Example code form README.md
=====================

```python
from pywinauto import Desktop, Application

Application().start('explorer.exe "C:\\Program Files"')

# connect to another process spawned by explorer.exe
app = Application(backend="uia").connect(path="explorer.exe", title="Program Files")

app.ProgramFiles.set_focus()
common_files = app.ProgramFiles.ItemsView.get_item('Common Files')
common_files.right_click_input()
app.ContextMenu.Properties.invoke()

# this dialog is open in another process (Desktop object doesn't rely on any process id)
Properties = Desktop(backend='uia').Common_Files_Properties
Properties.print_control_identifiers()
Properties.Cancel.click()
Properties.wait_not('visible') # make sure the dialog is closed
``` 

In line 1 you use double backslash `\\`. I gues first `\` serves as escape character here? But then why the code works exactly the same when I use only one backslash?
```python
Application().start('explorer.exe "C:\Program Files"')
```

In line 8 - what is `title good for? It seems to have no effect if I change it's value to e.g. `Nonesence`. The code runs the same.
```python
app = Application(backend="uia").connect(path="explorer.exe", title="FooNonesence")
```
In line 10 - where does the name `ProgramFiles` comes frome? How do I know which name to choose there? 
```python
app.ProgramFiles.set_focus()
```
When I run the example code explorer app opens and in task-manager I see that the task `Programme` (which is equivalent to `Program Files` on German Windows). Is this the name that I should use in line 10 instead of `ProgramFiles`? Or is it what I should use as `title` in line 8?
![image](https://cloud.githubusercontent.com/assets/5635462/22098571/4b4b3352-de27-11e6-99ac-a3f99e60d88b.png)

**Comment by vasily-v-ryabov** [comment]
Python 3.5 automatically detects (in most cases) that single backslash `\` isn't a part of escape sequence (like `\n`), but for better compatibility I'd recommend using double backslash `\\` that will work the same way in ALL cases for ALL Python versions. Another way to use single slash safely is using `r` (raw string) before the string: `r"C:\Programme\Common Files"`.

A question about acceptable names (and where to get them) is always about reading the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html). Please read it carefully. Desktop GUI automation is not so simple area as you may think of it after first look at pywinauto examples. :)

**Comment by Tset-Noitamotua** [comment]
Thanks. I am going through the Getting Started Guide ... indeed answers a lot of questions :)
