### ISSUE TITLE
pywinauto "[Error 1450} Insufficient system resources..." and increasing system handles. 

### ISSUE THREAD

**Issue by RalfHuefing** [pywinauto/pywinauto#290]
During long term GUI automation tests of my application I got often the following pywinauto error:

> pywinauto.remote_memory_block.AccessDenied: ('[Error 1450] Insufficient system resources exist to complete the requested service.process: %d', 9620)

### Test Environment:
- Windows 7 Professional, English
- pywinauto, Release 0.6.0
- python 2.7.11

### First investigation result:
- I am using often the pywinauto function **"exists()"** to check if a window control exists.
- If this **"exists()"** call is used, then the handles in the Windows system are increasing.
See attached screenshot of the Windows Task Manager:
![taskmanager_with_notepad_test - copy](https://cloud.githubusercontent.com/assets/25246209/22152324/94c466e2-df22-11e6-8ab8-2de546f6b799.png)

### Issue is reproducible with a simple Notepad test example
**Note:** This is reproducible e.g. with the Notepad "Print..." Dialog (not with all Notepad Dialog windows).
See source example below:
```python
# Simple Test application with pywinauto and Windows Notepad
from pywinauto import application

app = application.Application()
app.start(r"notepad.exe")

app['Notepad'].wait('ready')

# Test Endless loop to open and close the "Print"-Dialog in Windows Notepad.
while True :
    app['Notepad'].menu_select("File->Print")
    
    # NOTE: The "exists()" call below increases the number of used handles.
    if app['Print']['Cancel'].exists() : 
        app['Print']['Cancel'].close_click()
```

**Comment by airelil** [comment]
@RalfHuefing , a nice catch! I can confirm the same on Win8.1 python 2.7.12/python 3.5. There are a lot of process handles left open.  @vasily-v-ryabov , let me try to check it more.
![image](https://cloud.githubusercontent.com/assets/795040/22163662/965c6216-dfb8-11e6-99c4-b1cad9497764.png)

**Comment by vasily-v-ryabov** [comment]
Don't remember why I commented these lines out. But after the fix the handle count looks stable for me as well.

@RalfHuefing could you please re-check with recent master branch on your side?

**Comment by vasily-v-ryabov** [comment]
The issue seems fixed in master branch. Please re-open if it's still reproduced.

**Comment by vasily-v-ryabov** [comment]
Hi @Fuu-chan do you run the script as Administrator? Maybe the app is running as Administrator, while your script is not. This is the most probable reason of "access denied" error.
