### ISSUE TITLE
Make visible_only=False a default option for connect method

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#292]
For minimized Skype window the following line doesn't work:
```python
app = Application(backend='uia').connect(title_re='Skype')
```

But this code works for any state of the Skype main window:
```python
app = Application(backend='uia').connect(path='Skype.exe')
app.windows()[0].is_visible() # returns False
app.windows()[0].window_text() # returns u'Skype\u2122\u200e - <my Skype ID>'
```

**Comment by airelil** [comment]
When you say "minimized" you mean the Skype is presented only in the tray area ? I would expect this behavior for any "icon-in-tray" app because there is no any window at this state. Isn't it?

**Comment by vasily-v-ryabov** [comment]
Yes, I mean "icon-in-tray" state of Skype. But all the controls are present in Inspect.exe (all with `OffScreen=True` of course). I think we need to take offscreen elements into account while connecting.

**Comment by vasily-v-ryabov** [comment]
Probably we need to reconsider defaults in `find_elements(...)`. Currently we have `visible_only=True` by default. But in `application.py` we override it by `visible_only=False` for methods `.windows()` and `.exists()`.

What do you think about having `visible_only=False` by default in all cases? This is serious design decision because some legacy applications have several hidden top level windows. But it adds an ability to connect to minimized or "icon-in-tray" apps.

A local workaround (and some compromise) is to set `visible_only=False` specifically for `.connect(...)` method.

**Comment by vasily-v-ryabov** [comment]
`Application(backend='uia').connect(title_re='Skype', visible_only=False)` works for me on Win10.
`app.top_window()` doesn't work of course because it uses default `visible_only=True` as a part of criterion.

Probably `app.Skype_<your_Skype_ID>.exists()` would return `True`.

This is all about consistency. Current behavior is inconsistent because some cases use one value by default while others use different one. This may break some backward compatibility, but I'm not sure it's so serious because it should allow more scenarios while old scenarios should change a little (maybe more detailed top window name for some apps).

**Comment by vasily-v-ryabov** [comment]
Tried to change this for UIA only but had some problems with 1 win32 test anyway. So let's postpone this till 0.6.2 so far.
