### ISSUE TITLE
Could not find NotificationAreaToolbar

### ISSUE THREAD

**Issue by x1nas** [pywinauto/pywinauto#294]
There is no NotificationAreaToolbar in Russian version of Windows.
How can I access to it?
[Man](http://pywinauto.readthedocs.io/en/latest/HowTo.html#how-to-use-pywinauto-with-application-languages-other-than-english) doesn't help.

[error.txt](https://github.com/pywinauto/pywinauto/files/724047/error.txt)

**Comment by vasily-v-ryabov** [comment]
Hi @x1nas, sorry for late response. The fix was merged into master branch and it will be included into 0.6.2 soon.

**Comment by vasily-v-ryabov** [comment]
0.6.2 will be published on February, 28.
So closing all fixed issues. Please re-open if reproduced again.
