### ISSUE TITLE
dead link (video) in the doc

### ISSUE THREAD

**Issue by WiliTest** [pywinauto/pywinauto#295]
the video link is [here](http://pywinauto.github.io/docs/getting_started.html#sit-back-and-have-a-look-at-a-little-movie)
thanks!

**Comment by vasily-v-ryabov** [comment]
Thanks for reporting this.
But I can't find this link in [0.6.0 documentation](https://pywinauto.readthedocs.io/en/latest/getting_started.html). This is the same page but completely rewritten for 0.6.0.

Updating the docs for old 0.5.4 version doesn't make much sense for me. And the video is pretty the same as GIF animation demo on the [main page](http://pywinauto.github.io/). So closing the issue.
