### ISSUE TITLE
How to type text in a console!

### ISSUE THREAD

**Issue by mzbedat** [pywinauto/pywinauto#303]
Hi,
I'm trying to use pywinauto to control the kvm console window of iDrac Dell server managment interface:

![image](https://cloud.githubusercontent.com/assets/17043182/22731470/73cb919c-edf3-11e6-96fe-d036bfbe5182.png)

This is my code:

`import pywinauto
from pywinauto.application import Application

app = pywinauto.application.Application().connect(title_re='idrac-6311202,  , User: root')
win = app.Window_(title_re='idrac-6311202,  , User: root', class_name='SunAwtFrame')
win.SetFocus()

win.PrintControlIdentifiers()

win.TypeKeys("{PAUSE 2}")
win.TypeKeys("{TAB 2}{PAUSE 2}{ENTER}")`

I need the ability to type text on that console.
I tested the TypeKeys and its working for me, but TypeText is not.
As you can see from screenshot, there are no controls at all (at least with Win7 that am testing on).
Also from code, when I used: win.PrintControlIdentifiers(), no controls were retrieved.

**Comment by vasily-v-ryabov** [comment]
You can try `.send_chars()` method for the console window. But generally it looks like CLI automation, not GUI one. For that purpose you need to use standard module `subprocess` and class `Popen` with sending keys to `stdin` of the spawned process.

**Comment by mzbedat** [comment]
Thanks for the prompt response.
I couldn't find a method send_chars that is working on window object: win.send_chars('')!

However,
As a workaround for now I used something like this:
win.TypeKeys('+(r)+(o)+(o)+(t)')
But its printing it with special chars before the letter itself and only with Caps letters:
^[R^[O^[O^[T

Regarding subprocess, as I know its for CMD console! In my case a Java native window is opened.

**Comment by vasily-v-ryabov** [comment]
`send_chars()` is a method of `HwndWrapper` (since 0.6.0). Which version of pywinauto do you use? 0.5.4?

**Comment by mzbedat** [comment]
I have 0.5.4 indeed
Will consider upgrading, but this is not my only challenge :)
I'm facing other issues like how to get the text from the console in order to compare results.
(tried: WindowText() or Texts() but I got only the title of the screen and not the content of the console)
It's important for me to decide if to perform the next step (steps of server installation) or what to choose inside. Meanwhile I'm using time sleep and performing hardcoded steps.

If pywinauto will not give that flexibility I need to decide if to go ahead with it or not.

**Comment by vasily-v-ryabov** [comment]
If this Java app supports MS UI Automation technology, the texts should be visible in `Inspect.exe` in UIA mode. [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) explains some details where to find `Inspect.exe` etc.

Of course, some other ways like SSH connection (using paramiko) might be more appropriate for this task.

**Comment by mzbedat** [comment]
BTW, I'm trying the send_chars() with version 6.0 but it also isn't working!

![image](https://cloud.githubusercontent.com/assets/17043182/23104691/70758002-f6db-11e6-8ab9-11387df30d4f.png)

if I simply send a space it's written in that field:
self.win.TypeKeys("{SPACE}")
So I know that I can enter text there and its not a focus issue for example.

Is there a convention for digits? like in this link (which didnt work for me neither):
http://documentation.microfocus.com/help/index.jsp?topic=%2Fcom.borland.silktest.silk4net.doc%2Flangref%2Fcommon%2FTypeKeysMethodIKeyable_ref.html

**Comment by vasily-v-ryabov** [comment]
You may try 0.6.1. There were some fixes in `send_chars()` (see #299).
If it doesn't help, I have no more suggestions.

**Comment by mzbedat** [comment]
There is something really weird that I don't understand...
send_chars() with 6.1 didn't work as well, but when I used: self.win.TypeKeys('%1%9%2%.%1%6%8') it typed it without the last char (8 in this case)!

**Comment by vasily-v-ryabov** [comment]
It seems you found a workaround. Can we close the issue?

**Comment by mzbedat** [comment]
Closing it.
Thanks for the support.
