### ISSUE TITLE
a mistake or confusing  sentence in the doc (+ feedback)

### ISSUE THREAD

**Issue by WiliTest** [pywinauto/pywinauto#305]
Feedback from this page: https://pywinauto.readthedocs.io/en/latest/HowTo.html

> If the **control’s text** is empty (after removing non char characters) **text** is not used. Instead we look for the closest control above and to the right fo the cont_R_ol. 

Do you mean the control’s _title_ right? 

If so, that should be bellow:
"closest title text."

**Other feedback:**
I would also have added this parenthesis near control  _(dialog usually contains one or more controls (child windows) text field/options)._ 
Or the complete definition: 

> ( dialog box is a temporary window an application creates to retrieve user input. ... A dialog box usually contains one or more controls (child windows) with which the user enters text, chooses options, or directs the action.)

Your doc is very hard to understand for beginners (I personally did not know what was a "dialog" , a windows handle, a control. I'm not the only one (few friends right now struggle with those) Simple example [control (eg. text field, menu,...)] would make it much easier to understand. It's especially important in the beginning of the doc, because from the very beginning your docs might discourage (dumb) users like me.

Thanks for your work!

**Comment by vasily-v-ryabov** [comment]
Hi @WiliTest, thank you very much for the feedback about docs. This is a rarest kind of feedback unfortunately. That's why current documentation is mostly targeted to GUI developers. I will have more time to work on the docs soon (since 0.6.1 is out recently), but my first plans are about updating the [main page](http://pywinauto.github.io/). So pull requests for [docs sources](https://github.com/pywinauto/pywinauto/tree/master/docs) are very welcome! ;)

**Comment by WiliTest** [comment]
I will never cease to be amaze by the maturity of the pywinauto team, first the link pointing to your "competitors" (other projects), the wisdom of your answer on stack (I saw one of your reply to a guy choosing another module instead of pywinauto "yes that's a good solution too" you told him). And now this kind of feedback appreciation (I thought I'd be a bit crushed since I'm a beginner). Thanks for what you do and who you are Vasily...

**Comment by vasily-v-ryabov** [comment]
Hi @WiliTest hope it's still relevant. I've update the "How To" guide with some definitions (see PR #605). Is it possible to review and provide more feedback? I'm not a native speaker and some corrections would be helpful.

**Comment by vasily-v-ryabov** [comment]
Well, it seems not relevant any more. If you feel it's not finished, please re-open or submit another issue. Closing.
