### ISSUE TITLE
MSPaint example missing

### ISSUE THREAD

**Issue by robodude666** [pywinauto/pywinauto#310]
The Getting Started Guide hints there is an MSPaint example, but none exist in the repository.

Was hoping the MSPaint example would provide insight on how to interact with Ribbon Bars.

**Comment by vasily-v-ryabov** [comment]
There is nothing special for Ribbon bars in comparison with any other controls. Just use `Inspect.exe` and method `.print_control_identifiers()` (though it may print really huge listing). Anyway I spent 2 hours to create an example. In my mind there is only real pitfall with `dlg.Open.Open.click()` that calls another "Open" button inside "File name:" combo box.

**Comment by robodude666** [comment]
Thanks. It may not be as straight forward to new users as it may seem (otherwise #311 wouldn't exist).

I was following the Getting Started Guide but was unable to control Excel 2010. I was hoping the MSPaint example that the guide mentioned would be a good reference for Ribbon controls -- unless there's something else special about Excel?
