### ISSUE TITLE
Use logging properly

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#312]
The problem is described in the [StackOverflow question](http://stackoverflow.com/questions/41170360/importing-pywinauto-causes-debug-messages-to-appear-twice). We also observed this problem at work where we use pywinauto for handling confirmation dialogs.

**Comment by airelil** [comment]
I think the problem is in several active loggers. This is a list of active loggers I get on my machine after running the example for SO:
```
In [5]: logging.Logger.manager.loggerDict
Out[5]:
{'PIL': <logging.PlaceHolder at 0x2f95ef0>,
 'PIL.Image': <logging.Logger at 0x2f95e10>,
 'PYREADLINE': <logging.Logger at 0x2b6a030>,
 'TerminalIPythonApp': <logging.Logger at 0x2294530>,
 'comtypes': <logging.Logger at 0x2ec5230>,
 'comtypes._comobject': <logging.Logger at 0x2f145b0>,
 'comtypes.client': <logging.Logger at 0x2cce1f0>,
 'comtypes.client._code_cache': <logging.Logger at 0x28bce90>,
 'comtypes.client._events': <logging.Logger at 0x28d5cf0>,
 'comtypes.client._generate': <logging.Logger at 0x2fe19d0>,
 'pywinauto': <logging.Logger at 0x2d5b150>,
 'test': <logging.Logger at 0x2c5f390>}

In [6]:
```
So I'll try to modify ```actionlogger.disable()``` method to act only on pywinauto logger.
