### ISSUE TITLE
Tree view click only works when tree view items are visible on the screen

### ISSUE THREAD

**Issue by kono10** [pywinauto/pywinauto#314]
For example if there is a tree view that is very long so that it includes a scroll bar so you can select items that are off screen. When using pywinauto you can only click items in the tree view that are visible on the screen.  Here is my sample code. I'm trying to automate a 64 bit application with a 64 bit version of python 2.7
```python
from pywinauto.application import Application

app = Application().Start(cmd_line=u'"PATH TO APPLICATION" ')
windowsformswindowappeccrad = app[u'APPLICATION WINDOW NAME']
windowsformswindowappeccrad.Wait('ready')
systreeview = windowsformswindowappeccrad.TreeView
tree_item = systreeview.GetItem([u'Parent', u'Child'])
tree_item.Click()
```

**Comment by vasily-v-ryabov** [comment]
TreeView item has method `tree_item.EnsureVisible()` or `tree_item.ensure_visible()` in 0.6.0+.
Yeah, this method is not called automatically inside `click()` or `click_input()`. Do you think it should?

**Comment by kono10** [comment]
Thanks! Perfect. Yes I think it should be. It will only save one line of code, but might reduce likelihood for confusion when dealing with a longer tree view.
