### ISSUE TITLE
Maximized window is always resized (restored) when calling set_focus()

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#318]
[Reported on StackOverflow](http://stackoverflow.com/questions/42396129/why-my-windows-will-always-resize-to-normal-after-calling-win-clickinput-in-py)

**Comment by clockzhong** [comment]
vasily-v-ryabov,
Found the root cause or fixed it already?

Thanks!

Clock ZHONG

**Comment by vasily-v-ryabov** [comment]
Hi @clockzhong
It's already fixed in my fork, only left to write regression test and to merge into master branch. Planning to release 0.6.2 with recent fixes till March, 1.

**Comment by clockzhong** [comment]
Cool!!!!
