### ISSUE TITLE
menu_select not consistent, raising TimeoutError

### ISSUE THREAD

**Issue by EndermanAPM** [pywinauto/pywinauto#321]
I used to access the menu by simply using the menu_select function
`facWinMain.menu_select('Facturaciones->Gestión de facturaciones')`

But once in a while it raised timeoutError so I worked around it by using a try except loop (I know it's a bodge) 

```python
i=0
    while True:
        try:
            facWinMain.menu_select('Facturaciones->Carga de facturaciones')
            break
        except timings.TimeoutError:
            i += 1
            if i > 5:
                raise timings.TimeoutError
```
But then when I moved the project to a les powerful machine (which I access via RDP in oder to be able to keep doing things on my main machine while the program is running) it takes a long time to locate the menu (if it does manage to do it).

Clicking the window seems to make it find the menu faster, could it be a focus problem? SetFocus and focus are not working as facWinMain is a window specification.

facWinMain is using uia backend and I'm running pywinauto 0.6.1 under python 3.6 x64.

**Comment by vasily-v-ryabov** [comment]
Is `facWinMain` already opened at the moment you're trying `menu_select(...)`?

You said `facWinMain` is a window specification. It means pywinauto does the search for that window to create wrapper before calling `menu_select()`. In other words these 2 statements do the same:
```python
facWinMain.wrapper_object().menu_select('Facturaciones->Carga de facturaciones')
facWinMain.menu_select('Facturaciones->Carga de facturaciones')
```
If window opening takes longer than the default timeout, you need to wait explicitly:
```python
facWinMain_wrapper = facWinMain.wait('ready', timeout=10)
facWinMain_wrapper.menu_select('Facturaciones->Carga de facturaciones')
```
As I remember `TimeoutError` is not raised inside `menu_select(...)`. That's why I guess window opening takes too long.

**Comment by EndermanAPM** [comment]
Hi @vasily-v-ryabov yes, `facWinMain` is opened when i try to `menu_select()`
That's what It's bugging me. If the window wasn't visible yet I could understand it raising exceptions, but it is.

**Comment by vasily-v-ryabov** [comment]
Hmm... What is the declaration of `facWinMain`?
Did you try to call `.wrapper_object()` first and then to `menu_select(...)` for returned wrapper? I still can't believe it's inside `menu_select()`. Please re-check.

**Comment by EndermanAPM** [comment]
I haven't tryed to call ` .wrapper_object()` 
But I mean, there is not much to the declaration, maybe I'm doing something wrong?
```python
app = Application(backend="uia").start(r'C:\Factel5\Factel5.exe')
facWinMain = app["FacTel5"]
```

**Comment by vasily-v-ryabov** [comment]
If you use `backend='uia'` bitness doesn't matter (I believe pywinauto shouldn't warn you in this case - interesting!). Will try to play with your app a bit later.

**Comment by vasily-v-ryabov** [comment]
`TimeoutError` was not reproduced on my side yet though I've posted an answer for [your question on SO](http://stackoverflow.com/q/41675746/3648361).

Probably your scenario runs after filling many data fields in. So `main_window.wait('ready', timeout=10)` may help.

**Comment by EndermanAPM** [comment]
Unfortunately I'll not be working with the project that uses pywinauto for quite some time.

I'm going to close the Issue, if I encounter a similar problem down the road I'll just make a new one.

Regards.
