### ISSUE TITLE
question

### ISSUE THREAD

**Issue by drogit** [pywinauto/pywinauto#326]
##  i just an inexperienced newbie trying to install it but having all sorts of issues and not sure if this is my local system having an issue or not ???

  File "C:\Users/DEALER~1\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    code = compile(script, filename, 'exec')
  File "C:\Users\DEALER~1\AppData\Local\Temp\easy_install-ct3pe_kz\pypiwin32-219\setup.py", line 121
    print "Building pywin32", pywin32_version
                           ^
SyntaxError: Missing parentheses in call to 'print'

C:\py\pywinauto-0.6.0>

**Comment by vasily-v-ryabov** [comment]
It's a pyWin32 package installation problem (pywinauto depends on it). Usually if you run `pip install pywinauto` it should use .whl files from pypiwin32 (it's a PyPI version of pyWin32) without problems. But it seems you use easy_install. It's an out-of-date tool that can be useful for some old packages only.

As an alternative you can install pyWin32 by download exe installer [from here](https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/).

**Comment by vasily-v-ryabov** [comment]
Hi @drogit, did you resolve this problem? Can we close the issue?

**Comment by vasily-v-ryabov** [comment]
OK, no answer during 2 months. Closing the issue because it's obviously not of pywinauto.
