### ISSUE TITLE
pywinauto can not recognize the menustrip in winfrom application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/pywinauto#33]
```

1.in win7/x64bit ,Only get the object menustrip,but can not get the submenu of 
the menustrip.
 



```

Original issue reported on code.google.com by `pengdean...@gmail.com` on 7 Mar 2015 at 1:49

**Comment by vasily-v-ryabov** [comment]
Closing as duplicate of #3 . Menu strip can be well handled with UIA support.
