### ISSUE TITLE
how to use scroll with pywinauto

### ISSUE THREAD

**Issue by wangtubs** [pywinauto/pywinauto#337]
hi, when I open itunes on windows, some controls are not visible, so how to use scroll to scroll down and check the controls?

another question is I can't get control info of contents on the homepage of itunes, only menu controls.

**Comment by vasily-v-ryabov** [comment]
> how to use scroll to scroll down and check the controls?

Don't exactly remember whether negative values of `wheel_dist` will scroll down or up.
```python
app.iTunes.wheel_mouse_input(wheel_dist = 1)
```

______________________________
> I can't get control info of contents on the homepage of itunes, only menu controls

In which browser are you trying to automate this homepage? Or is it embedded page in the iTunes window?

**Comment by wangtubs** [comment]
thanks. the scroll works well. 
the second question. it seems a embedded page in the iTunes window

**Comment by vasily-v-ryabov** [comment]
It seems every embedded page controls are visible to me in Inspect.exe. Can you explain in more details which page do you mean? And how to reach it?

**Comment by wangtubs** [comment]
when you open itunes, you will see the default page. ok. this doesn't matter so much. I can use lackey instead. 
can you help to answer the additional question in https://github.com/pywinauto/pywinauto/issues/307?

**Comment by wangtubs** [comment]
hi, can I control the scrolll speed? the default speed is too fast, not like human.

**Comment by vasily-v-ryabov** [comment]
`time.sleep(0.5)` before every `wheel_mouse_input(wheel_dist = 1)` ?

**Comment by wangtubs** [comment]
no. I mean the scroll speed. I find the scroll speed is important for me. maybe you should add a parameter for this method.
thanks

**Comment by vasily-v-ryabov** [comment]
Don't know which scroll speed you mean. We use [mouse_event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646260(v=vs.85).aspx) Win32 API function and flag `MOUSEEVENTF_WHEEL`. There are no scroll speed or similar parameters for that.

**Comment by vasily-v-ryabov** [comment]
Scrolling speed is usually defined inside a GUI control / scroll bar. If it has `NativeWindowHandle` property in `Inspect.exe` it's technically possible to use `SetScrollInfo` Win32 API function. But I would set a low priority for such a feature. Too many efforts, too low effect. I'd like to concentrate on more important usability improvements and breakthrough features we're working on.

**Comment by zhy2020** [comment]
Hi @vasily-v-ryabov , can you provide some code examples for my reference?  thank you
