### ISSUE TITLE
lack of win32process broke import on linux ... wrong install? 

### ISSUE THREAD

**Issue by mjbe** [pywinauto/pywinauto#338]
Installed using pip3 install pywinauto

First import failed for want of Microsoft Windows modules.

```
>>> from pywinauto import application

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pywinauto/application.py", line 75, in <module>
    import win32process
ImportError: No module named 'win32process'
```
application.py wants a variety of win32 modules.

```
import win32process
import win32api
import win32gui
import win32con
import win32event

```

I appear not to have them, cannot see where I might get them, and don't really expect them to be available to my linux desktop. Have I taken a wrong turn during install?

**Comment by vasily-v-ryabov** [comment]
Hi @mjbe, `application` module is Windows only for now. There are only 2 modules supported on Linux: `mouse` and `keyboard`. To run the application it's easy to use standard Python module `subprocess`.

AT-SPI support is still in early development stage (hope to have some prototype this summer, no production due date yet). So clicking by text will not work on Linux.

**Comment by mjbe** [comment]
Thank you for clarifying this.
