### ISSUE TITLE
Method .wait(...) takes ~ default time (5 sec.) instead of customized timeout like 1 sec.

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#347]
The bug is reported on StackOverflow:
[pywinauto change default timeout values](http://stackoverflow.com/q/43558087/3648361)

I could reproduce it on simple example using Notepad and `backend='uia'`:
```python
app.window(title_re = 'About Notepad').wait('visible', timeout=1)
```
It took `5.0934726561 sec`.

**Comment by juysu2** [comment]
The default time is for resolve control:
app.window(title_re = 'About Notepad', timeout=1).wait('visible', timeout=1)

**Comment by vasily-v-ryabov** [comment]
The following call took `1.23639702764` sec.
```python
app.window(title_re = 'About Notepad').wait('exists', timeout=1)
```
So it's specific for "visible" state.

**Comment by vasily-v-ryabov** [comment]
I could find the root cause and fixed it! Now it takes around 1 sec:

```python
def t(action):
 	start = time.clock()
 	try:
 		app.window(title_re = 'About Notepad').wait(action, timeout=1)
 	except:
 		print time.clock() - start
>>> t('exists')
1.00364134489
>>> t('visible')
1.09575502439
>>> t('visible')
1.19378547428
>>> t('exists')
1.12031168922
>>> t('exists')
1.03774646544
>>> t('visible')
0.992245803911
>>> t('visible')
1.00437335693
```
Will write unit tests and merge it soon.
