### ISSUE TITLE
ListItem ElementNotFoundError

### ISSUE THREAD

**Issue by Ingustavo** [pywinauto/pywinauto#349]
Hi!

I'm facing same proplem which is mentioned in this stackowerflow Question - http://stackoverflow.com/questions/41112765/pywinauto-and-listitem-selection 

I'm getting error  when trying to select ListItem,

`app.top_window().child_window(title_re="High").select() `

, but items is being returned from print_control_identifiers() method, also I'm double checking the element with
`app.top_window().child_window(title_re="High").exists() ` which returns "True"

Error Msg:
```python
pywinauto.findwindows.ElementNotFoundError: {'top_level_only': False, 'title_re': 'High',
 'parent': <pywinauto.uia_element_info.UIAElementInfo object at 0x00A819D0>, 'backend': 'uia'} 
```

Is there known reason why this is happening? Is there another way how to select ListBox item?

Thanks

**Comment by vasily-v-ryabov** [comment]
Hi @Ingustavo, can you check return value of the following?
```python
app.top_window().child_window(title_re="High").is_visible()
```
If it's `False` probably you need to use `.child_window(title_re='High', visible_only=False)`.

P.S. Using `top_window()` is not recommended since it may produce unstable behavior when opening new window is in progress so it may bind to any of the 2 top windows (note sometimes context menu is a top window).

**Comment by Ingustavo** [comment]
Hi, Vasily!

Thanks for the quick response.

Passing extra parameter to method helped , I'm not getting the error anymore, also I take Your advice and I'm not using top_window(), but instead :
`app["window x"]["subwindow"].child_window(title_re="High", visible_only=False).is_visible()`

But I have another problem, the action -  `.select()` do nothing with element, is there some explanation or workaround?

**Comment by vasily-v-ryabov** [comment]
Probably you need to expand parent combo box first to make this list view visible. I saw similar situation with iTunes in #307 but didn't investigate it deep enough yet.

**Comment by vasily-v-ryabov** [comment]
Am I right? The parent is a combo box? It can be clicked by `.click_input()` because `.invoke()` may wait infinitely while drop-down list is collapsed again.

**Comment by vasily-v-ryabov** [comment]
Are there some news on your issues? If all is solved, can we close the issue?

**Comment by Ingustavo** [comment]
Sorry for the late response. Thank you, yes your suggestions worked for me. This issue can be close.
