### ISSUE TITLE
is it possible to get auto_id's from list?

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#366]
hi,

Is it possible to get auto_id's from list? Code below:

```
app = pywinauto.Application(backend='uia')
app_connect = app.connect(path='testApp.exe')
window = app_connect.window()
panel= window.child_window(auto_id="buttonPanel", control_type="Pane")
wrapper = panel.wrapper_object()
buttons = wrapper.descendants(control_type='Button')
```
Example so that i will use for loop to print all the auto_id's in that list

```
for i in buttons:
	print i.print_auto_id()
```

**Comment by vasily-v-ryabov** [comment]
Hi @nimuston it's possible this way:
```python
for btn in buttons:
	print btn.element_info.automation_id
```

**Comment by nimuston** [comment]
Thanks

**Comment by nimuston** [comment]
now that i have list of buttons and i know auto_id's of these buttons, how can i click on specific button? example `print btn.element_info.automation_id` gives me following results:
```
button1
button2
button3
button4
```
and i want to click button3

**Comment by nimuston** [comment]
i found a way, i need to create new list and then i'm using that.
