### ISSUE TITLE
Library import leads to Python 3.6.1 crash on Windows 10 RS2 (1703 version). Pywinauto==0.6.2

### ISSUE THREAD

**Issue by shmarlovsky** [pywinauto/pywinauto#367]
I can just import pywinauto, and not even use it, and at some point python crashes.
Screenshot and data from Event viewer are attached.

**From Event Viewer:**
   Faulting application name: python.exe, version: 3.6.1150.1013, time stamp: 0x58d169bd
   Faulting module name: uiautomationcore.dll_unloaded, version: 7.2.15063.332, time stamp: 
   0xcdde5ba9
   Exception code: 0xe0435555
   Fault offset: 0x00001704
   Faulting process id: 0x1390
   Faulting application start time: 0x01d2ddfff59aa305
   Faulting application path: C:\Program Files\Python36-32\python.exe
   Faulting module path: uiautomationcore.dll
   Report Id: b33750a9-e0e7-4637-9a12-7a998796441e
   Faulting package full name: 
   Faulting package-relative application ID

![image](https://cloud.githubusercontent.com/assets/9055497/26786301/004f54be-49bb-11e7-8b14-5ec38710874c.png)

**Comment by vasily-v-ryabov** [comment]
Hmm... It's something new and interesting. Are you able to run the following code without crash?
```python
import comtypes.client
UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
```

**Comment by shmarlovsky** [comment]
OK, I've tried, your code doesn't lead to crash. The main difficulty is that I can't identify the exact moment which leads to crash.
But in event viewer we can see "dll_unloaded". Does it mean that library unload leads to problem (not load)?

**Comment by vasily-v-ryabov** [comment]
No ideas yet.
Can you compare it with other Python versions? 3.5, 2.7...

**Comment by airelil** [comment]
A bit too late, but seems as it is similar to this problem: [Outlook 2010 fault in uiautomationcore.dll after upgrade to Win 10 1703](https://social.technet.microsoft.com/Forums/en-US/27f80dd4-c28c-4bd7-8b2c-73a28452b63a/outlook-2010-fault-in-uiautomationcoredll-after-upgrade-to-win-10-1703-1506313?forum=outlook). Probably, it's not Python to blame.

Just for the record, I wasn't able to reproduce it on Win10 ver.1607 trying the following combinations:
python 3.6.1 64-bit pywinauto 0.6.3
python 3.6.2 32-bit pywinauto 0.6.3
python 3.6.1 32-bit pywinauto 0.6.2

**Comment by shmarlovsky** [comment]
Thanks @airelil !
I cannot understand exact steps and conditions how to repro it..

**Comment by airelil** [comment]
I only tried to import pywinauto while running under different Python versions.

**Comment by vasily-v-ryabov** [comment]
It looks like not a Python related issue. Hope with latest Windows updates everything is OK. If you still see the issue, please re-open.
