### ISSUE TITLE
Treeview problem

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#369]
Hi,

I have a weird problem with treeview handling. I have a function that opens one item from treeview and it works just fine if the tested app is already opened before i use this treeview function, but it tested app is not open and i need to use another function to open it first then my treeview function does not work correctly. It finds all the treeview items even most of them are not visible at this point. Have you ever noticed this kind of behavior?

Below code i'm using to handle treeview

```
app = pywinauto.Application(backend='uia')
appconnect = app.connect(path='testapp.exe')
appwindow = appconnect.window()
treeview = appwindow.child_window(auto_id="TreeView", control_type="Tree", top_level_only=True, visible_only=True)
wrapper = treeview.wrapper_object()
treeview_item = wrapper.descendants(control_type='TreeItem')
treeview_item[4].click_input(double=True)
```

**Comment by vasily-v-ryabov** [comment]
Hi @nimuston which function doesn't work correctly? And what is the traceback? Please always attach a traceback for every problem if possible. Thanks!

**Comment by nimuston** [comment]
I have two functions. One is to check if test app is running and if not it will start it and the second function is for selecting one item from treeviw. The problem is with this my treeview function. If test app is running my function work fine but I need to use my first function to start my test app then my treeview function does not work correctly. If my test app is running then my treeview function finds all the visible treeview items and in my case this is correct, but if my second functions starts my test app then my treeview functions find all item in treeview even the ones that are not visible when test app is launched. Code I provided previously is my treevies function.

**Comment by vasily-v-ryabov** [comment]
The scenario looks clear to me. But without crash output it's not clear what was really happened inside.

**Comment by nimuston** [comment]
jeah thats the problem i don't have crash output, because it's not crashing. Only the behavior is different.

**Comment by vasily-v-ryabov** [comment]
OK, it's just not clear which line behaves differently. Are there different list returned by `treeview_item = wrapper.descendants(control_type='TreeItem')` ? Method `descendants` looks for all elements including non-visible ones. But you can cascade it using window specification method `.child_window()` that creates nested specification. This should behave consistently if I got it right:
```python
app = pywinauto.Application(backend='uia')
appconnect = app.connect(path='testapp.exe')
appwindow = appconnect.window()
treeview = appwindow.child_window(auto_id="TreeView", control_type="Tree", top_level_only=True, visible_only=True)
treeview_item = treeview.child_window(control_type='TreeItem', found_index=4, visible_only=True)
treeview_item.click_input(double=True)
```

**Comment by vasily-v-ryabov** [comment]
In this case actual search happens here: `treeview_item.click_input(double=True)` when accessing `click_input` attribute.

**Comment by nimuston** [comment]
@vasily-v-ryabov with this `child_window()` and `found_index=x` i'm able to get results i want, at least after i quickly tested this. Thanks
