### ISSUE TITLE
Firefox => Print as PDF: How to capture new Application/"Save As" Dialog Window ?

### ISSUE THREAD

**Issue by SergeGardien** [pywinauto/pywinauto#370]
I'm modifying the pywinauto script from [https://superuser.com/questions/933632/how-to-batch-print-swf-files-to-pdf/1007975#1007975](https://superuser.com/questions/933632/how-to-batch-print-swf-files-to-pdf/1007975#1007975) which tries to print as PDF various files  (SWFs from Adobe Flash) opened in Firefox (one each at a time).

In doing so I need to modify the code to "intercept" the dialog window where I specify where to store the PDF file and the file name.

Problem is, the "Save As" dialog window depends on the on the virtual printer used (e.g., CutePDF Writer, Adobe PDF, Nitro PDF Creator, etc.).

By checking the Windows task manager I've seen that both "Adobe PDF" and "Nitro PDF Creator" virtual printers start a new application named "Print driver host for applications" (path C:\Windows\splwow64.exe) but with different dialog window titles ("Save PDF File As" for Adobe PDF and "Save As" for Nitro).

The "CutePDF Writer" virtual printer instead opens a "Save As" window of "CutePDF Application".

My question: how can I intercept this new Application and its Save As window?
I can bypass such dialog window with "Adobe PDF" and the script works fine (it cycles through all the files) but I cannot rename the PDF on the fly hence they get overwritten.

I've tried
```
app1 = Application().connect(path = r"c:\windows\splwow64.exe")
app1.SaveAS.Save.Click()
```

But the Python script crashes soon as I start it. If instead I use the below script (little mod from the original one) I arrive till the "Save As" window but then it stops and crashes.

```
"""Convert all swf files in this directory to a pdf file using Firefox.

Note that some parameters in this script need to be adjusted according to
user's printer setup, screen resolution, etc.

Documentation of pywinauto:
 * https://pywinauto.github.io/docs/contents.html
An example script using pywinauto:
 * https://github.com/vsajip/pywinauto/blob/master/examples/SaveFromFirefox.py
"""
import re
import os
import warnings
import webbrowser
from time import sleep
from functools import partial

import pywinauto as pwa
from pywinauto.application import Application


def sendkey_escape(string):
    """Escape `+ ^ % ~ { } [ ] ( )` by putting them within curly braces.

    Refer to sendkeys' documentation for more info:
         * https://github.com/zvodd/sendkeys-py-si/blob/master/doc/SendKeys.txt
           (Could not open the original site: rutherfurd.net/python/sendkeys/ )
    """
    return re.sub(r'([+^%~{}\[\]()])', r'{\1}', string)


# Using 32-bit python on 64-bit machine? Will get the following warning a lot:
# "UserWarning: 64-bit application should be automated using 64-bit Python
# (you use 32-bit Python)"
# Limit this warnings to only show once.
# The following line does not work as expected. See
# github.com/pywinauto/pywinauto/issues/125
warnings.filterwarnings(
    'once', message=r'.*64-bit application should.*', category=UserWarning
)
# Assume Firefox is already open.
app = Application().connect(title_re=".*Firefox")
firefox = app.MozillaFireFox.GeckoFPSandboxChildWindow
filenames = os.listdir()
for filename in filenames:
    if not filename.endswith('.swf'):
        continue
    pdfname = filename[:-3] + 'pdf'
    if pdfname in filenames:
        # Already there!
        continue
    # Assume the default application to open swf files is Firefox.
    webbrowser.open(filename)
    firefox.SetFocus()
    firefox.Wait('exists ready', timeout=5)
    firefox.RightClickInput(coords=(200, 200))
    firefox.Wait('ready', timeout=10)
    # Click "print" from the rightclick menu.
    firefox.ClickInput(coords=(210, 320))
    pwa.timings.WaitUntilPasses(
        timeout=10,
        retry_interval=1,
        func=partial(app.Connect, title='Print'),
        exceptions=pwa.findwindows.WindowNotFoundError,
    )
    #app.Print.Wait('ready active', 5)
    # The printing process depends on the default printer being used.
    app.Print.OK.Click()
    app.Print.WaitNot('exists', timeout=5)
    # pwa.timings.WaitUntilPasses(
    #     timeout=20,
    #     retry_interval=1,
    #     func=partial(app.Connect, title='Save As'),
    #     exceptions=pwa.findwindows.WindowNotFoundError,
    # )
    # Be wary that some characters such as "%" don't work correctly in Save As
    # dialogs. This code does not handle such awkwardness of MS Windows.
    # app.SaveAS.ComboBox.SetFocus().TypeKeys(
    #     sendkey_escape(os.getcwd() + '\\' + pdfname), with_spaces=True
    # )
    #app1 = Application().connect(path = r"c:\windows\splwow64.exe")
    #app1.SaveAS.Save.Click()
    firefox.Wait('exists ready', timeout=5)
    # Focuse is lost to flash (bugzilla: 78414). Use mouse to close the tab.
    firefox.ClickInput(coords=(418, 16), absolute=True)
    firefox.WaitNot("exists", timeout=5)
```

**Comment by SergeGardien** [comment]
I've actually bypassed the problem by installing PDFCreator (free virtual printer to save PDF files). It has the option of bypassing the print dialog window so I don't need to provide a further command via pywinauto. Moreover I've added a time.sleep(1) in between file printing to avoid crashing the script.

I'm still very keen to know a possible solution for the previous mentioned issue hence any idea is welcome.

**Comment by vasily-v-ryabov** [comment]
Hi @SergeGardien thanks for interesting scenario. The author of original script used pywinauto 0.5.4 but newer version 0.6.2 adds much more capabilities with the new backend for MS UI Automation technology. It's briefly described in the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) written specially for 0.6.0+.

Right now I have no much time to re-write the whole script, but if you could post some screenshots and errors output I'd be able to provide some help.

**Comment by SergeGardien** [comment]
Hi @vasily-v-ryabov , many thanks for your reply. Actually I cannot provide any error output because the script simply crashes without any alert whatsoever.

In the end I've bypassed the issue and I've obtained my PDFs files. I've found a nice software that can batch process multiple SWF files into PDF. I'll get back to this issue in case of need.

**Comment by vasily-v-ryabov** [comment]
OK, since this is most probably app specific problem and there is no way to provide any output or screenshot I'd suggest to close this issue for now. You may re-open it any time you want to get back to this.

**Comment by sstipetic** [comment]
> Hi @vasily-v-ryabov , many thanks for your reply. Actually I cannot provide any error output because the script simply crashes without any alert whatsoever.
> 
> In the end I've bypassed the issue and I've obtained my PDFs files. I've found a nice software that can batch process multiple SWF files into PDF. I'll get back to this issue in case of need.

Hi, could you share which software do you use in the end to batch process multiple SWF files. I Used gfx2gfx but does not work well for all SWF files.

**Comment by SergeGardien** [comment]
> Hi, could you share which software do you use in the end to batch process multiple SWF files. I Used gfx2gfx but does not work well for all SWF files.

Yes, I've had issues with gfx2gfx like you.

The best solution (to obtain the best pdf quality) has been that of using reaConverter Pro (by ReaSoft Development) under Windows. In this case you cannot specify the "Page Size" hence you need to convert it to your desired one with cpdf.

Another working solution I tried was that of using swf2pdf (a Python script) with pywinauto, still under Windows.

**Comment by sstipetic** [comment]
> swf2pdf

Thanks. I am just downloading reaConverter to check and see what can I get. And as for swf2pdf, do you have a script that works - example with pywinauto to share?

**Comment by SergeGardien** [comment]
Here it is:

```
"""Convert all swf files in this directory to a pdf file using Firefox.

Note that some parameters in this script need to be adjusted according to
user's printer setup, screen resolution, etc.

Documentation of pywinauto:
 * https://pywinauto.github.io/docs/contents.html
An example script using pywinauto:
 * https://github.com/vsajip/pywinauto/blob/master/examples/SaveFromFirefox.py
"""


import re
import os
import warnings
import webbrowser
from time import sleep
from functools import partial
import time

import pywinauto as pwa
from pywinauto.application import Application


def sendkey_escape(string):
    """Escape `+ ^ % ~ { } [ ] ( )` by putting them within curly braces.

    Refer to sendkeys' documentation for more info:
         * https://github.com/zvodd/sendkeys-py-si/blob/master/doc/SendKeys.txt
           (Could not open the original site: rutherfurd.net/python/sendkeys/ )
    """
    return re.sub(r'([+^%~{}\[\]()])', r'{\1}', string)


# Using 32-bit python on 64-bit machine? Will get the following warning a lot:
# "UserWarning: 64-bit application should be automated using 64-bit Python
# (you use 32-bit Python)"
# Limit this warnings to only show once.
# The following line does not work as expected. See
# github.com/pywinauto/pywinauto/issues/125
warnings.filterwarnings(
    'once', message=r'.*64-bit application should.*', category=UserWarning
)
# Assume Firefox is already open.
app = Application().connect(title_re=".*Firefox")
firefox = app.MozillaFireFox.GeckoFPSandboxChildWindow
filenames = os.listdir()
for filename in filenames:
    if not filename.endswith('.swf'):
        continue
    # pdfname = filename[:-3] + 'pdf'
    # if pdfname in filenames:
    #     # Already there!
    #     continue
    # Assume the default application to open swf files is Firefox.
    webbrowser.open(filename)
    firefox.SetFocus()
    firefox.Wait('exists ready', timeout=5)
    time.sleep(1)
    firefox.RightClickInput(coords=(200, 200))
    firefox.Wait('ready', timeout=10)
    # Click "print" from the rightclick menu.
    firefox.ClickInput(coords=(210, 320))
    pwa.timings.WaitUntilPasses(
        timeout=10,
        retry_interval=1,
        func=partial(app.Connect, title='Print'),
        exceptions=pwa.findwindows.WindowNotFoundError,
    )
    #app.Print.Wait('ready active', 5)
    # The printing process depends on the default printer being used.
    app.Print.OK.Click()
   	#app.Print.WaitNot('exists', timeout=5)
    # pwa.timings.WaitUntilPasses(
    #     timeout=20,
    #     retry_interval=1,
    #     func=partial(app.Connect, title='Save As'),
    #     exceptions=pwa.findwindows.WindowNotFoundError,
    # )
 #    # Be wary that some characters such as "%" don't work correctly in Save As
 #    # dialogs. This code does not handle such awkwardness of MS Windows.
 #    app.SaveAS.ComboBox.SetFocus().TypeKeys(
 #        sendkey_escape(os.getcwd() + '\\' + pdfname), with_spaces=True
 #    )
	# #app1 = Application().connect(path = r"c:\windows\splwow64.exe")
 #    #app1.SaveAS.Save.Click()
 #    firefox.Wait('exists ready', timeout=5)
 #    # Focuse is lost to flash (bugzilla: 78414). Use mouse to close the tab.
 #    firefox.ClickInput(coords=(418, 16), absolute=True)
 #    firefox.WaitNot("exists", timeout=5)
```
