### ISSUE TITLE
Wait that process finished

### ISSUE THREAD

**Issue by efremovd** [pywinauto/pywinauto#376]
Hi,

What is best way to wait for process to finish with some timeout and if it timeouts then kill it.

I would think something like:
`
timings.wait_until(timeout=10, retry_interval=5, lamda: app.process_exist())
`

**Comment by vasily-v-ryabov** [comment]
Hi. Sorry for delayed reply. There is no such a method in `class Application`. But it's good idea to implement it. `win32process.GetExitCodeProcess` seems correct choice for doing that check though need to convert `int` process id to `PyHANDLE`.

I can implement it this Thursday or you may create your own pull request. I think good names for the new methods are `app.is_process_running()` and `app.wait_for_process_exit()` (using `wait_until` as you suggested).

**Comment by efremovd** [comment]
no worries will look for it later and create pr. I just wanted to confirm that I did not miss it somewhere :)
