### ISSUE TITLE
ProcessNotFoundError: Could not find any accessible process with a module of 'testapp.exe'

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#380]
Hi,

Another error that happens randomly. Process not found

```
Traceback (most recent call last):
  File "C:\temp\test.py", line 258, in check_process
    appconnect = app.connect(path='testapp.exe')
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 929, in connect
    self.process = process_from_module(kwargs['path'])
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 1342, in process_from_module
    raise ProcessNotFoundError(message)
```

**Comment by vasily-v-ryabov** [comment]
Hi @nimuston is this process started while you're trying to connect to it? `connect` method doesn't apply any timeout by default. But you can try the following:
```python
appconnect = app.connect(path='testapp.exe', timeout=5)
```
It will wait up to 5 sec. while process is started.

P.S. I think we can improve this by using some default implicit timeout every time you use `path` argument.

**Comment by nimuston** [comment]
Process is already running, i'm trying to press a button in the testapp.

**Comment by vasily-v-ryabov** [comment]
Anyway can you try the code with timeout? Using latest master branch (if any).

**Comment by nimuston** [comment]
yes i will try, i will take time to validate if it helps, because it's so random when this happens.

**Comment by nimuston** [comment]
I will close this issue, because not able to reproduce it anymore. Seems that `timeout` helps

**Comment by vasily-v-ryabov** [comment]
Great! It seems I can proceed with default timeout then.
