### ISSUE TITLE
Can 2 pyWinAuto versions co-exists on the same Python 2.7

### ISSUE THREAD

**Issue by jagadeesh1983** [pywinauto/pywinauto#390]
Hi,
I have installed Python 2.7 (x64) with pyWinAuto 0.4 (x64) and I would like to install new pyWinAuto version 0.6.3(x64) on the same Python 2.7 on the same Windows machine without uninstalling old pyWinAuto version. Could you please confirm can 2 pywinauto versions co-exists on the same Python 2.7 installation.

Thanks,
Jagadeesh

**Comment by vasily-v-ryabov** [comment]
Hi @jagadeesh1983 it's possible using `virtualenv`. Inside the virtual environment you can install any packets of any versions not touching Python installation itself. You just need to run special batch file to activate/de-activate virtual environment. It's all documented for `virtualenv` Python package. There is nothing specific to pywinauto.

**Comment by jagadeesh1983** [comment]
Thanks for the update.
Also I am checking option to uninstall old pyWinAuto version 0.4 (x64) and install new pyWinAuto version 0.6.3(x64) on the same Python 2.7 (without uninstalling Python 2.7.)
Could you please provide any document for uninstalling pyWinAuto. I didnt find any instruction for uninstalltion in README.txt file.

Thanks,
Jagadeesh

**Comment by jagadeesh1983** [comment]
Hi Vasily,

Any update on instructions for uninstallation of pyWinAuto version 0.4 (x64).

Thanks,
Jagadeesh

**Comment by vasily-v-ryabov** [comment]
You can uninstall any package using something like this in cmd.exe: `pip uninstall pywinauto`

**Comment by jagadeesh1983** [comment]
Thanks for the update.
I tried running uninstallation command which you have mentioned above. But i got following error.

Uninstalling pywinauto:
  c:\python\lib\site-packages\pywinauto-0.6.3-py2.7.egg
  Removing file or directory c:\python\lib\site-packages\pywinauto-0.6.3-py2.7.egg
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 126, in main
    self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\uninstall.py", line 40, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "C:\Python27\lib\site-packages\pip\req.py", line 856, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "C:\Python27\lib\site-packages\pip\req.py", line 482, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1398, in remove
    renames(path, new_path)
  File "C:\Python27\lib\site-packages\pip\util.py", line 255, in renames
    shutil.move(old, new)
  File "C:\Python27\Lib\shutil.py", line 296, in move
    rmtree(src)
  File "C:\Python27\Lib\shutil.py", line 253, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python27\Lib\shutil.py", line 251, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'c:\\python\\lib\\site-packages\\pywinauto-0.6.3-py2.7.egg'

Please let me know how to resolve this error.

**Comment by vasily-v-ryabov** [comment]
Hmm... You can delete this file manually: `c:\python\lib\site-packages\pywinauto-0.6.3-py2.7.egg`

**Comment by jagadeesh1983** [comment]
After deleting C:\python\lib\site-packages\pywinauto-0.6.3-py2.7.egg file manaully then running pip uninstall pywinauto command in command prompt went fine.

C:\Users\jkanthar>pip uninstall pywinauto
Uninstalling pywinauto:
  c:\python27\lib\site-packages\pywinauto-0.4.1-py2.7.egg-info
Proceed (y/n)? Y
  Successfully uninstalled pywinauto

But the pywinauto related files were not deleted from c:\python27\lib\site-packages folder.
Do I need to remove them manaully?
Please confirm.

**Comment by vasily-v-ryabov** [comment]
Yes, probably they could be removed manually as well. Pip won't work if 2 versions are already both in the box.

**Comment by jagadeesh1983** [comment]
Ok fine.. thanks for the confirmation.

**Comment by vasily-v-ryabov** [comment]
Finally I would recommend having 2 unpacked folders with different pywinauto versions (but don't install by pip) and do something like that (import directly from folder, maybe need to add an empty `__init__.py` near `setup.py`):
```python
from pywinauto042 import pywinauto as pywinauto_legacy
from pywinauto063 import pywinauto
```

But I'm also curios why you need 2 versions? Do you have some concerns about the most recent 0.6.3 ?

If it's for 2 separate projects (one is legacy, not changing now), why not having 2 Python installations? Like Python 2.7.10 and Python 2.7.13 in separate folders. Just use full path to `python.exe` then.

**Comment by jagadeesh1983** [comment]
Thanks Vasily for detailed explanation.
Actually, we have already installed Python 2.7 with pywinauto 0.4 in our QA test environments.
We dont want to uninstall old pywinauto in all the Test environments/VM boxes since it is just an additonal task. So i was just curious to know without uninstalling older pywinauto version will be possible to install new  pywinauto 0.6.3 in the same Python 2.7 install directory.

Anyways, thanks for your response.

**Comment by vasily-v-ryabov** [comment]
OK, then the answer is "it's not possible". Closing the issue. Thanks!
