### ISSUE TITLE
Window hangging issue in windows 2012 while using Pywinauto 0.4 through Jep

### ISSUE THREAD

**Issue by eloraparija** [pywinauto/pywinauto#391]
Hi,

I am using jep code to launch a application window in windows 2012 system.
Sometimes the window which launches gets hanged immediately after opening and doesn't throw any exception.
The issue is inconsistent. 
Is there any solution to this issue.

Thanks,
Elora

**Comment by vasily-v-ryabov** [comment]
Hi Elora, not sure I understood the issue clear. What is hanged? Python interactive window or application-under-test window?

And why are you using pywinauto 0.4.0? The latest version is 0.6.3. Do you have any problem specific to this latest version?

**Comment by eloraparija** [comment]
Hi Vasily,
For using pywinauto 0.6.3 we need to get approval from our company which we got now.
We will try with the new version and let you know if I still face the issue.

Thanks,
Elora
