### ISSUE TITLE
Horizontal scrolling problems (incorrect coordinates for scroll)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#392]
The problem is reported and workarounded on StackOverflow:
https://stackoverflow.com/questions/45163039/scrolling-issues-with-pywinauto

**Comment by airelil** [comment]
JFYI, I started working on ```UIAWrapper.scroll``` method - similar to ```HwndWrapper.scroll``` we already have for 'win32' backend.
