### ISSUE TITLE
`import pywinauto` not working on Windows Local User account

### ISSUE THREAD

**Issue by om-nishu-trantor** [pywinauto/pywinauto#393]
I installed `pywinauto` on windows using admin account(obviously, local account don't have installation permissions.)
When I try to run `import pywinauto` it never returns a control, neither it loads pywinauto ever on the cmd/powershell.
On debugging it seems to be an issue while running `from ..uia_defines import IUIA` in [`uia_controls.py`](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/controls/uia_controls.py#L42)

Where as when I use an Admin account to run `import pywinauto` in python shell, it works fine. But local user seems to be having issues.

**Comment by om-nishu-trantor** [comment]
@vasily-v-ryabov @airelil  @cetygamer 
Any ideas, as you are the contributors of the code file where I debugged the issue.

**Comment by airelil** [comment]
Probably it's related to COM. You can try to run it without ```comtypes``` package. In this case pywinauto will not load all UIA-related stuff

**Comment by vishalgarg231** [comment]
@airelil I am also facing the same issue. Simply writing `import pywinauto`. 
Not sure how to import without `comtypes` ?

**Comment by vasily-v-ryabov** [comment]
Hi @om-nishu-trantor, @vishalgarg231, I'm afraid you need an admin account for GUI access or you have to set some settings as an equivalent of `<uiAccess="true"/>` tag in .manifest file. I'm not aware of these settings and if they exist.

You may try using "win32" backend only uninstalling comtypes by `pip uninstall comtypes` in cmd.exe. But usually you may face the problem when method `.click()` sends `WM_CLICK` to the target app but it's not handled/received. One weird thing is that script will tell you nothing (action doesn't happen, exception isn't raised). Running script as Administrator resolves this problem. I'm thinking about some warning about insufficient privileges, but had no chance to research this yet.

**Comment by vasily-v-ryabov** [comment]
@vishalgarg231 @om-nishu-trantor The warning about insufficient privileges was added in `pywinauto==0.6.4`. Also I made few fixes in `comtypes` that should resolve the initial issue.

You can update all versions this way:
```
pip install -U pywinauto
pip install -U comtypes
```
I'm going to close this issue. If it's still relevant, please re-open it or submit another issue.
