### ISSUE TITLE
Not able to get a text (value)

### ISSUE THREAD

**Issue by alexgoryachev** [pywinauto/pywinauto#398]
backend="uia", win64
I'm trying to read a text (in reed frame) from a window.  I did homework and couldn't  find any appropriate method to get the text
The screenshot is attached.

![det value](https://user-images.githubusercontent.com/13759203/29093023-2b827a6c-7c3d-11e7-8d8e-17ce571b6b44.png)

**Comment by vasily-v-ryabov** [comment]
It could be retrieved by `.legacy_properties()['Value']`

**Comment by vasily-v-ryabov** [comment]
It looks resolved since no reply for a long time. Closing. Please re-open if any.

**Comment by jsonpanganiban** [comment]
I am having similar issue however though its not a legacy_properties value.

I'd like to get the email value (sample@test.com) but the following methods below are not returning the value:
window_text(), texts(), children_texts()

LocalizedControlType:	"edit"
Name:	""
AccessKey:	""
HasKeyboardFocus:	true
IsKeyboardFocusable:	true
IsEnabled:	true
AutomationId:	"CtxtEmail"
ClassName:	"WindowsForms10.EDIT.app.0.194e1a4_r17_ad1"
HelpText:	""
IsPassword:	false
NativeWindowHandle:	0x332B2
IsOffscreen:	false
FrameworkId:	"WinForm"
ProviderDescription:	"[pid:5640,hwnd:0x332B2 Main:Nested [pid:10132,hwnd:0x332B2 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Nonclient:Microsoft: Non-Client Proxy (unmanaged:uiautomationcore.dll); Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
Value.IsReadOnly:	false
**Value.Value:	"sample@test.com"**


Here is what I get when using print_control_identifers()

Control Identifiers:

Edit - ''    (L589, T154, R753, B175)
['Edit', u'']
child_window(auto_id="CtxtEmail", control_type="Edit")

**Comment by vasily-v-ryabov** [comment]
Hi @jsonpanganiban this can be obtained by `.iface_value.CurrentValue`

See [similar example on StackOverflow for Chrome URL](https://stackoverflow.com/questions/46145284/how-to-get-the-current-url-from-chrome-using-pywinauto-0-6).

**Comment by deven-s** [comment]
Try out `get_value()` for legacy values, it works out of the box, I tried on `pywinauto  0.6.8` version
