### ISSUE TITLE
RDP example

### ISSUE THREAD

**Issue by yatheesh-horizon** [pywinauto/pywinauto#405]
Could you please provide an example to open rdp session and do automation after login.

**Comment by vasily-v-ryabov** [comment]
Hmm... How do you imagine that? Information about UI controls are not provided by RDP. But you may run the script on remote machine using remote PowerShell `psexec` with cmd key `-i` (interactive). Of course, need to copy the script to the remote machine before starting it. See issue #401 for more details. Closing as duplication.

**Comment by vasily-v-ryabov** [comment]
One more useful guide: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html
