### ISSUE TITLE
I try to use is_pressed() function but failed

### ISSUE THREAD

**Issue by orabs** [pywinauto/pywinauto#406]
i have a normal button that i wanna check if it pressed or not  i tried to use with is_pressed function

but its raise an exception : AttributeError: WindowSpecification class has no 'is_pressed' method

my code is: app.Dialog.child_window(title='Save Patient', control_type='Button').is_pressed()

i found information about this function and i know its should work only with  ToolbarButton Class but how can i Casting my WindowSpecification Class to this 

 Thanks!!

**Comment by vasily-v-ryabov** [comment]
Hi @orabs, if you use "win32" backend (create `Application()` without params), it's necessary to find the whole Toolbar first. Win32 `ToolbarWrapper` is considered as monolithic UI element. So buttons are kinda virtual and can be obtained using `ToolbarWrapper` method `.button("button name")` (or by index). This virtual button object contains method `.is_pressed()`.

Conclusion:
```python
toolbar = app.Dialog.child_window(class_name="ToolbarWindow32", found_index=0).wrapper_object()
print toolbar.button("Save Patient", exact=False).is_pressed()
```

**Comment by orabs** [comment]
i use  with 'uia' backend not windows32  how should i do it?

**Comment by vasily-v-ryabov** [comment]
Then you can obtain `.wrapper_object()` for the button as self-sufficient UI element. Check which patterns are supported in `Inspect.exe` (can be downloaded here: https://github.com/blackrosezy/gui-inspect-tool) for this button. `IsTogglePatternAvaible == True` means everything is good.

**Comment by orabs** [comment]
unfortunately the required button IsTogglePatternAvaible ==False  there is any thing that i can do more?

**Comment by vasily-v-ryabov** [comment]
Which patterns are supported? What is the type of app? WPF? WinForms? Qt5?

**Comment by orabs** [comment]
WPF

**Comment by vasily-v-ryabov** [comment]
Currently we have only some unit tests for WPF toolbar buttons.
See [test_uiawrapper.py, line 1229](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/unittests/test_uiawrapper.py#L1229).
Need to take a look on my side. Probably some improvements are needed.

If you could provide a simple test app with such a toolbar with pressable buttons, it would speed up the investigation.

**Comment by vasily-v-ryabov** [comment]
OK, if the button pressed state is mutually exclusive with neighbor buttons, it should be RadioButton. In this case you should see `SelectionItemPatternAvailable == True` in Inspect.exe. If it's True, use methods `select()` and `is_selected()`.

If it's False, probably it's not a standard WPF toolbar. Not sure we can help.

**Comment by vasily-v-ryabov** [comment]
Make sure you're looking for patterns for button element. The button often has child text element which doesn't support any pattern that may add a confusion.

**Comment by vasily-v-ryabov** [comment]
Hi @orabs is that helped to resolve your issue?

**Comment by vasily-v-ryabov** [comment]
Closing since no more feedback. Please re-open if still actual.
