### ISSUE TITLE
Embedding pywinauto into a Windows application?

### ISSUE THREAD

**Issue by loopless** [pywinauto/pywinauto#411]
Is it possible to embed pywinauto inside a "python enabled" Windows application to allow for users to record, then run python "macros"

**Comment by vasily-v-ryabov** [comment]
Not sure I clearly understand you. If the application is written in Python, no problem to import and use pywinauto inside.

But how do you imagine recording? Do you want to allow user clicking/typing everything he wants and then have a pywinauto script as an output? Then it's a "record-replay" feature. We're currently working on the prototype. But I expect to make it really useful next year. The task to implement it is really hard. I bet there is no such a "record-replay" tool in the open source field. Of course I mean recording reliable scripts without hard-coded coordinates.

**Comment by loopless** [comment]
Sorry to not be clear - but as you suspect I was thinking of a record-replay feature almost exactly as you describe.  I'll watch out for your prototype on GitHub.

Thanks!
Andrew

**Comment by vasily-v-ryabov** [comment]
OK, I'm going to close it as a duplication of #332.
