### ISSUE TITLE
Application(backend='uia').Connect() doesn't work (trying with Chrome)

### ISSUE THREAD

**Issue by frogger72** [pywinauto/pywinauto#421]
manually running: chrome.exe --force-renderer-accessibility
then from Python: pywinauto.application.Application(backend='uia').Connect(handle=20185530)

results in: AppNotConnected: Please use start or connect before trying anything else

Works fine with backend='win32'

Running Windows 10. 32-bit Chrome and Python. Also tried running from a Python console with admin privileges

**Comment by vasily-v-ryabov** [comment]
Hi @frogger72 thanks for reporting this! It's a bug, though it's not intended to be core case for UIA backend (hence low priority) because some windows may not have a handle (like Windows Store apps). We will fix it a bit later. Thank you for understanding!

**Comment by frogger72** [comment]
Thanks.  Is there a workaround in the meantime?  Should PID or other options work for UIA and Connect?

**Comment by vasily-v-ryabov** [comment]
Sorry for late response. Yes, all other criteria should work for UIA as well. See [the first section of HOWTOs](https://pywinauto.readthedocs.io/en/latest/HowTo.html).

**Comment by frogger72** [comment]
I tried PID and it also didn't work.  This bug seems to be in general for using Connect with backend='uia'

**Comment by vasily-v-ryabov** [comment]
I've just checked both cases on my side and both worked fine for Notepad.exe (we have auto tests for these cases after all):
```python
>>> app = Application(backend='uia').connect(process=4060)
>>> app = Application(backend='uia').connect(handle=196928)
```
Need more details what you're trying step-by-step.

**Comment by vasily-v-ryabov** [comment]
It's also working for me with Chrome:
```python
>>> app = Application(backend='uia').connect(process=10208)
>>> app.windows()[0].window_text()
u"Application(backend='uia').Connect() doesn't work (trying with Chrome) \xb7 Issue #421 \xb7 pywinauto/pywinauto"
```
Which version do you use? Latest pywinauto==0.6.3 ?

**Comment by frogger72** [comment]
Was searching about a new issue and realized I completely missed this (my apologies - I somehow missed the reminder email on a reply). The only difference was that I was using "Connect" instead of "connect" - using the lowercase works great. The uppercase "Connect" does work with backend='win32', so a bit inconsistent. Thank you.

**Comment by vasily-v-ryabov** [comment]
Hi @frogger72 thanks for clarifying! This behavoir is intended because `Connect` exists for "win32" backend only!
```python
if self.backend.name == 'win32':
            # Non PEP-8 aliases for partial backward compatibility
            self.Start = self.start
            self.Connect = self.connect
```
Don't know why you got `AppNotConnectedError` instead of `AttributeError`.
Also I made some fixes in master branch (not released yet), some cases should work better for `connect(...)` with `timeout` param etc.

Can we close this now?

**Comment by frogger72** [comment]
Ah - makes sense! Yes, would make sense for this to show up as AttributeError. Closing
