### ISSUE TITLE
How to print current pywinauto version in output

### ISSUE THREAD

**Issue by jagadeesh1983** [pywinauto/pywinauto#422]
Hi,

How can I print version number for the current pywinauto installation in the output console?
I need to check the pywinauto version at the runtime when the script is running.

We have following code to check Python version
import platform
 print(platform.python_version())

Similar way I need to check pywinauto verison at the runtime.
Please help me on this.

Thanks,
Jagadeesh

**Comment by vasily-v-ryabov** [comment]
Use this one:
```python
import pywinauto
print(pywinauto.__version__)
```

**Comment by jagadeesh1983** [comment]
Thanks Vasily. It worked.
