### ISSUE TITLE
CaptureAsImage results a black image for second monitor (maybe re-use pyWin32?)

### ISSUE THREAD

**Issue by vitorsaldiva** [pywinauto/pywinauto#423]
In a simple test, using Notepad as an example, CaptureAsImage method results a image file fully black
as shown below:

![img](https://user-images.githubusercontent.com/12866789/31677303-16ba6336-b349-11e7-9745-8131a68f5d60.png)

The code that I'm using is:

from pywinauto.application import Application
app = Application().start('notepad.exe')
app.top_window_().set_focus().CaptureAsImage().save("d:\img.png")

Thank you

**Comment by airelil** [comment]
The simple test does work on my Win8 x64 machine (py27-x64 and py33-x86). So can you provide more details: python version, windows version, bitness. Do you have PIL installed ? Usually pywinauto gives a warning about it: 
"PIL does not seem to be installed. PIL is required for capture_as_image"

**Comment by vitorsaldiva** [comment]
Sure! There you go:

Win10 x64 1703 version
Python 3.5.1 :: Anaconda 2.5.0 (64-bit)

About PIL, i have PIL installed, because I use save method and png file is generated...

**Comment by airelil** [comment]
I tried also on Win10 x64 and Py3.6 x64. Still works for me. @vitorsaldiva, did you try to run PIL separately?
Something like this:
```
from PIL import ImageGrab
box = (0, 0, 200, 200)
ImageGrab.grab(box).save(r"D:\tmp.png")
```

**Comment by vitorsaldiva** [comment]
@airelil  Yes, this piece of code works fine.

![tmp](https://user-images.githubusercontent.com/12866789/31784288-e3374f22-b4df-11e7-8c8c-7aa02f1ee617.png)

But, Does CaptureAsImage() use ImageGrab or there is another issue?

**Comment by airelil** [comment]
Confirm, it doesn't work for me for a second monitor. And yes, we do use [ImageGrab](https://github.com/pywinauto/pywinauto/blob/f0dbeb8a3ae261b63e276818f9f27d96673a0647/pywinauto/base_wrapper.py#L478). So seems as an old [issue](https://github.com/python-pillow/Pillow/issues/1547) in PIL: ```ImageGrab.grab()``` doesn't handle negative coordinates. We may consider a proposal in this thread to re-use pywin32 instead of PIL.

**Comment by vitorsaldiva** [comment]
Great! Thank you for your help @airelil
