### ISSUE TITLE
How to start the program which named in Chinese? 

### ISSUE THREAD

**Issue by tianhaiyao** [pywinauto/pywinauto#424]
I have installed Pywinauto and tried to test the client. but I'm failed . I don't know how to use Pywinauto test a client in Chinese。

The details as follows:
Python 2.7.12 (v2.7.12  [MSC v.1500 32 bit (Intel)] on win32)
Pywinauto 0.6.1,

I run the following codes,but the program had no response.
```python
#!/usr/bin/env python
#coding=gbk
from pywinauto.application import Application
app = Application()
app.start("C:\文件\平台.exe".decode('gb2312'))
```
Can someone  help me?

**Comment by vasily-v-ryabov** [comment]
Hi @tianhaiyao this is a typical encoding problem for Python (not pywinauto specific). Try something like this (`#!/usr/bin/env python` is not needed on Windows):
```python
# encoding: gbk
from pywinauto.application import Application
app = Application()
app.start(u"C:\\文件\平台.exe")
```
If it's a Unicode string in correct encoding (mentioned in the first comment) there is no need to decode byte string to Unicode. The statement can be in Unicode using `u` literal.

**Comment by tianhaiyao** [comment]
Thank you very much for your details. I tried but it was failed .Then,I found that Our R & D products can't support this ,so I have to give up this tool and look for other tools for our products.
