### ISSUE TITLE
set_text(), button click() are not working when run in remote machine

### ISSUE THREAD

**Issue by jonyenosis** [pywinauto/pywinauto#426]
I have been trying to automate file upload through IE in my web application automation project. 
Using selenium, python, pywinauto. 
Automating 'Choose file to upload' dialog with pywinauto. Running test in remote machine connected with cisco vpn. 
It is working fine when remote machine screen is open. 
But, when the remote pc screen is minimized or the rdp is disconnected the click on Open button and set_text fails. 

I need the proper solution. 
Can anyone help me. I am blocked on plenty of test cases only because of this.

**Comment by airelil** [comment]
Did you see the similar issue #247?

**Comment by vasily-v-ryabov** [comment]
Similar issues can be solved using Ansible or `psexec` (maybe even simpler than with VNC): see #401 for details (scroll down to the latest posts).

**Comment by vasily-v-ryabov** [comment]
FYI: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html
