### ISSUE TITLE
set_focus() on qt5 app does not work the first time. Window disappears from task bar

### ISSUE THREAD

**Issue by raghur** [pywinauto/pywinauto#443]
So I'm running up against a very weird issue and not finding anything relevant around. I'm trying to automate bringing an app to focus. Specifically, the app is (https://github.com/neovim/neovim/releases)[Neovim]. I'm on windows 8.1 and the plugin I'm writing is here - branch (https://github.com/raghur/vim-ghost/tree/pywinauto)[pywinauto] @ 68d37f09e0297df029f4b99639d9546bb4b600df

Now for the problem:

1. On first click from the browser addon, the plugin code runs this `self.winapp.windows()[0].set_focus()`. The neovim window disappears from the task bar.
   1. If I try the recommended way - `self.winapp.Neovim.set_focus()` - I get a KeyError OR it just fails silently.
   1. Once the window has disappeared, the process is still running and I can run the same code `app.Neovim.set_focus()` above in from an IPython session and the window isn't found (No windows for this process)
   1. On the other hand, if I run `app.windows()[0].set_focus()`, the window is brought into focus and back in the taskbar.

For my plugin, this means that the first time interaction doesn't work - but after that everything works as intended (even without going through Ipython). So any idea why `set_focus()` doesn't work the first time but works after that without a hitch?

The setup is a little hard to replicate if you're not a Neovim user - so happy to do a screencast/im/video chat if needed.

**Comment by raghur** [comment]
So right after I posted this, some interesting updates:

1. If I call `self.winapp.windows()[1].set_focus()`, then the app window is brought to focus without the disappearing issue. However, keyboard focus isn't on it and I can't type till I click on it first.
  1. For reference, `app.windows()` returns this:
```
In [129]: x.windows()                                                 
Out[129]:                                                             
[<hwndwrapper.DialogWrapper - 'Neovim', Qt5QWindowIcon, 14550444>,    
 <hwndwrapper.DialogWrapper - 'M', MSCTFIME UI, 232785194>,           
 <hwndwrapper.DialogWrapper - 'Default IME', IME, 141952228>]         
```

1. I tried this to get the input focus back in my plugin code:
```
                self.winapp.windows()[1].set_focus()
                self.winapp.windows()[0].set_focus()
```
But now, I can visually see the window being brought into focus the and then immediately disappearing from the task bar (Again - first time only). Repeating the action, the window is brought into focus with keyboard focus without issues.

**Comment by raghur** [comment]
So I think I have finally found what works reliably:

```
            try:
                self.winapp.windows()[0].set_focus()
                self.winapp.windows()[0].ShowInTaskbar()
            except Exception as e:
                logger.warning("Error during _raise_window, %s", e)
```

I tried putting `IsInTaskbar()` but that returns True even when the window has disappeared from the task bar.

Would love not to have a hack - so keeping the issue open.

**Comment by airelil** [comment]
Sorry, we a bit busy right now. QT5 support is pretty limited in pywinauto. Any luck with UIA backend?

**Comment by vasily-v-ryabov** [comment]
Hi @raghur, good investigation. I've seen similar problem for Qt5 app (WireShark) but had no much time to debug it yet. Old implementation with `SetForegroundWindow(...)` we used in `set_focus()` before is also working for WireShark all the time. Maybe need to combine these approaches properly or find a better way.

**Comment by vasily-v-ryabov** [comment]
I'm getting back to this case. Running standalone `nvim-qt.exe` has shown several interesting things.

When using `Application(backend="uia")` (and `Inspect.exe`) there is no title text available:
```python
>>> app_uia = Application(backend="uia").connect(path='nvim-qt.exe')
>>> app_uia.windows()
[<uiawrapper.UIAWrapper - '', Dialog, -1584082235>]
```
Inspect.exe shows the same: title is absent in window properties. And `app_uia.Dialog.set_focus()` doesn't work silently: no crash or error, but the window is not brought to focus.

When using `backend="win32"` (the default one), the picture is much more optimistic. `.set_focus()` is working perfectly and I couldn't detect any issue. Even first time connecting to the app or starting it.
```python
app = Application(backend="win32").connect(path='nvim-qt.exe')
app.Neovim.set_focus()
```

Is this reproducible for browser plugin only? Or standalone app as well?

**Comment by raghur** [comment]
> Is this reproducible for browser plugin only? Or standalone app as well?

I'm not sure I understand what you mean - it's a nvim plugin - so runs inside nvim's python plugin process and tries to control the nvim-qt window and bring it to foreground.
