### ISSUE TITLE
how to select the item in  Listbox

### ISSUE THREAD

**Issue by xbclock** [pywinauto/pywinauto#444]
I tyring to use the pywinauto to test the software and the backend of the app is uia ,so how can i  to select the  item in a  Listbox?
wait for you help

**Comment by airelil** [comment]
You may get some ideas by having a glance at unit tests for ListView and ListViewItems https://github.com/pywinauto/pywinauto/blob/55f31621557a3884bbbda4eccbd015c6d1d58c33/pywinauto/unittests/test_uiawrapper.py#L796. 
As for example in:
https://github.com/pywinauto/pywinauto/blob/55f31621557a3884bbbda4eccbd015c6d1d58c33/pywinauto/unittests/test_uiawrapper.py#L1108
