### ISSUE TITLE
ElementInfo - other info (use legacy_properties and description as keywords)

### ISSUE THREAD

**Issue by alans09** [pywinauto/pywinauto#447]
it would be great to have access also to other MSAA element info:
 - Kbshortcut    (KeyboardShortcut)
 - Description   (AccessibleDescription)

Also it would be great, If I could search by this properties (eg.  elem.child_window(description="aaa"). The same for keyboardshortcut)

I have found that there is  .legacy_properties()  method if UIA is selected as backend. But I cant find this in standard backend (win32).

I have one application that is using AccessibleDescription of element and there are put unique identifiers of objects. How can I search for this items using this AccessibleDescription?

Thanks

**Comment by vasily-v-ryabov** [comment]
Hi @alans09, thanks for the suggestion! We're thinking about more unified way to define search properties. Search by these properties is not possible now. But for the next major release it could be improved with better `*ElementInfo` usage (search properties could be marked and have their own names for every backend to match `Inspect.exe` properties for consistency).
