### ISSUE TITLE
Trouble trying to get ListItem

### ISSUE THREAD

**Issue by jmbinette** [pywinauto/pywinauto#448]
Hi to all,

I am having trouble reaching a ListItem on a dialog box.

**Inspect.EXE result :** 
How found:	Mouse move (429,460)
	hwnd=0x002E056C 32bit class="ThunderRT6ListBox" style=0x54010081 ex=0x204
RuntimeId:	"[42.3016044.2.-2147483647.3016044.-4.1]"
BoundingRectangle:	{l:343 t:450 r:476 b:463}
ProcessId:	22788
ControlType:	UIA_ListItemControlTypeId (0xC357)
LocalizedControlType:	"list item"
Name:	"TEST_TOPIC"

**app.ThunderRT6FormDC.print_control_identifiers() result :** 
   | ListBox - ''    (L133, T240, R270, B296)
   | ['ListBox', '&ConnectListBox']
   | child_window(class_name="ThunderRT6ListBox")

**I tried :** 
app.ThunderRT6FormDC.ThunderRT6ListBox.Select("TEST_TOPIC")

and

app.ThunderRT6FormDC.child_window(title="Tag Upload Download Tool", control_type="ListItem").select("TEST_TOPIC")

[edit]
Could the problem be related to the fact the the ListBox gets populated after I automated the click of a button in the form ?

**Comment by vasily-v-ryabov** [comment]
Hi @jmbinette more detailed code is always better to understand previous steps. It's not clear which backend you're using (i.e. how `Application` object created).

ThunderRT6 list boxes are usually perfectly automated by default win32 backend. But if there is some lazy initialization for the list box, there are 2 general ways to handle it.

1. Use `app.wait_cpu_usage_lower(threshold=2, timeout=5)` means waiting while app specific part of CPU usage get down 2% (100% is a whole CPU with all cores, so make proper correction for one core if needed) up to 5 seconds before raising an error.

2. Function `wait_until_passes` provides flexible waiting for any condition. For example, `'TEST_TOPIC' in list_box.item_texts()`.
