### ISSUE TITLE
Citrix Transparent Window Client

### ISSUE THREAD

**Issue by rechlalef** [pywinauto/pywinauto#454]
I try to work on an application in a citrix server. I successfully connect application but when i print control identifiers i have this message : 
```
Control Identifiers:

Transparent Windows Client - 'MOSAIQ - Centre de radiotherapie XXX- \\Distant'    (L-32000, T-32000, R-31840, B-31973)
['MOSAIQ - Centre de radiotherapie XXX- \\\\Distant', 'MOSAIQ - Centre de radiotherapie XXX- \\\\DistantTransparent Windows Client', 'Transparent Windows Client']
child_window(title="MOSAIQ - Centre de radiotherapie XXX- \\Distant", class_name="Transparent Windows Client")
None
```
Can i work on it if the window is transparent ?

Thanks,
Achraf.T

**Comment by vasily-v-ryabov** [comment]
Hi @rechlalef I don't see any restrictions to work with transparent windows. Everything depends on an application you automate. Which backend do you use when doing `Application(backend="???").connect(...)` ? Choosing the most appropriate backend between `"win32"` and `"uia"` is important.

How did you call `print_control_identifiers()`? With default parameters? or with `depth=?`

Do you run your pywinauto script as Administrator? It's also important to retrieve all needed info.

**Comment by rechlalef** [comment]
Hi Vasily,

this is the code :

```
try:
        mosaiq_win = pywinauto.findwindows.find_windows(best_match=r"MOSAIQ - Centre de radiotherapie Peupliers- \\\\Distant")
        app = application.Application(backend="uia").connect(handle=mosaiq_win[0])
        print(mosaiq_win[0])
except application.ProcessNotFoundError:
        print("Demarrer Mosaiq avant de lancer le programme ")
        sys.exit()
 dlg = app['MOSAIQ - Centre de radiotherapie Peupliers- \\\\Distant']
 print(dlg.print_control_identifiers())
```
I can see the `print(mosaiq_win[0])` but not the ` print(dlg.print_control_identifiers())`

Thanks,

Achraf

**Comment by vasily-v-ryabov** [comment]
@rechlalef you don't have to call standard `print()` function. Method `print_control_identifiers()` should print all the info to the console by default. Also `filename` parameter is optional to write this content to file. Also please sure the script is running as Administrator (especially if the target app was elevated by UAC prompt previously).

**Comment by rechlalef** [comment]
I just run the code again and 'Transparent' have changed in 'Pane', i really don't know what i have done to change it. Nethertheless i can't get the control_identifiers. I have the following result :

`Control Identifiers:

Pane - 'MOSAIQ - Centre de radiotherapie XXX- \\Distant'    (L0, T0, R0, B0)
['Pane', 'MOSAIQ - Centre de radiotherapie Peupliers- \\\\Distant', 'MOSAIQ - Centre de radiotherapie XXX- \\\\DistantPane']
child_window(title="MOSAIQ - Centre de radiotherapie XXX- \\Distant", control_type="Pane")`. 
Could you provide an example, i tried with the documention without success.

thanks,

Achraf

**Comment by vasily-v-ryabov** [comment]
Hi @rechlalef it looks like there is only one control visible to pywinauto. Maybe your app doesn't provide any UI info to the operating system and doesn't implement MS UI Automation support. :(

**Comment by rechlalef** [comment]
arff too bad ... Thanks for your help.

Achraf
