### ISSUE TITLE
SetFocus() cause to crash script while connected to pc with RDP. 

### ISSUE THREAD

**Issue by Seljuke** [pywinauto/pywinauto#455]
Hi, i was using pywinauto at win10 computer that i was connected via RDP. When i minimize the RDP connection my pywinauto script trow an error. It is probably because of SetFocus() function trying to move my cursor to out of the screen. Is there a way to limit cursor movements or is there another alternative to SetFocus() function while my RDP connection minimized.

**Comment by vasily-v-ryabov** [comment]
Hi @Seljuke this is not a pywinauto specific problem, but for any GUI automation tool. RDP doesn't provide any GUI context while minimized. As a simple workaround you can switch RDP window from full screen mode to normal window, run the script inside it, then quickly switch focus to the local machine. The script should work while you're working on local machine.

If you need to run your automation on many machines, RDP can't help you. Much better solution is VNC server software (like TightVNC) which provides GUI context even if the VNC client is disconnected. But you have to restart remote machine every time after you use RDP (so just don't use RDP to avoid often reboots).

More details could be found in #247. Closing as duplication.
