### ISSUE TITLE
Can pywinauto now do UI automation test for application developed by GTK in Windows or is there any other way/tool?

### ISSUE THREAD

**Issue by zrbruce** [pywinauto/pywinauto#456]
Can pywinauto now do UI automation test for application developed by GTK in Windows or is there any other way/tool?
It would help a lot for this specific problem.

**Comment by vasily-v-ryabov** [comment]
I'm not sure if something is changed inside GTK project. It has no UI Automation support on Windows as far as I know. But I didn't check it for a long time.
