### ISSUE TITLE
how to parse or write the contents of print_control_identifier() in python

### ISSUE THREAD

**Issue by ma1nojk** [pywinauto/pywinauto#458]
Hello..

I would like to know if there's any method to parse or write the contents of print_control_identifier() in python , based on the output I want to take some dynamic actions through my code with the control and window position information , I tried using the parameter (filename="c:\\temp\test.txt") but it  gave the error "No windows for that process could be found" , can you give a code sample for this issue ?...thanks

**Comment by vasily-v-ryabov** [comment]
Hi @ma1nojk `print_control_identifiers(filename="C:\\temp\\test.txt")` should work. Can you provide the code with your attempt and full traceback?

There are more methods for choosing your actions dynamically: `children()` and `descendants()` which can enumerate all immediate children or the whole subtree of elements as actionable wrappers. Every obtained wrapper contains a lot of methods like `.rectangle()`, `.window_text()` etc.

Really no need to parse `print_control_identifiers()` output. It would be more complicated than just using `children()/descendants()`.

**Comment by salehtest** [comment]
Hi
Am trying to do a similar thing, but getting an encoding error. Can you please help here?

`handle.print_control_identifiers(filename="page_contents.txt")`

`Traceback (most recent call last): File "", line 1, in File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 696, in print_control_identifiers print_identifiers([this_ctrl, ], log_func=log_func) File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 685, in print_identifiers print_identifiers(ctrl.children(), current_depth + 1, log_func) File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 685, in print_identifiers print_identifiers(ctrl.children(), current_depth + 1, log_func) File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 685, in print_identifiers print_identifiers(ctrl.children(), current_depth + 1, log_func) [Previous line repeated 1 more time] File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 681, in print_identifiers log_func(output) File "C:\Users\test\PycharmProjects\LearnPythontest\venv\lib\site-packages\pywinauto\application.py", line 694, in log_func log_file.write(str(msg) + os.linesep) File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 721, in write return self.writer.write(data) File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 377, in write data, consumed = self.encode(object, self.errors) File "C:\Users\test\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 12, in encode return codecs.charmap_encode(input,errors,encoding_table) UnicodeEncodeError: 'charmap' codec can't encode character '\u25bc' in position 70: character maps to undefined`

I have few lines in the output like this,
`| | | | Static - 'Speed: 6.50 Mbps ▼' (L884, T711, R1109, B731) | | | | ['Speed: 6.50 Mbps ▼', 'Static22', 'Speed: 6.50 Mbps ▼Static'] | | | | child_window(title="Speed: 6.50 Mbps ▼", control_type="Text")`

I could see lines till the line above these lines are written to that file, but not anything after this 
Any help to resolve this and save the complete output to a file.
