### ISSUE TITLE
Not all controls are getting listed in print_control_identifier()

### ISSUE THREAD

**Issue by ma1nojk** [pywinauto/pywinauto#459]
Hello..

A window which uses SunAwtFrame has lots of menus and controls , but the print_control_identifier() prints only the below information , how to make it print all the available controls in the Dialog window ?..thanks
```
TitleBar - 'None'    (L27, T4, R991, B28)
   | ['', 'TitleBar']
   |    | 
   |    | Menu - 'System'    (L4, T4, R27, B27)
   |    | ['Menu', 'System', 'SystemMenu', 'System0', 'System1']
   |    | child_window(title="System", control_type="MenuBar")
   |    |    | 
   |    |    | MenuItem - 'System'    (L4, T4, R27, B27)
   |    |    | ['MenuItem', 'System2', 'SystemMenuItem']
   |    |    | child_window(title="System", control_type="MenuItem")
   |    | 
   |    | Button - 'Minimize'    (L921, T3, R946, B28)
   |    | ['MinimizeButton', 'Button', 'Minimize', 'Button0', 'Button1']
   |    | child_window(title="Minimize", control_type="Button")
   |    | 
   |    | Button - 'Maximize'    (L944, T3, R969, B28)
   |    | ['Maximize', 'Button2', 'MaximizeButton']
   |    | child_window(title="Maximize", control_type="Button")
   |    | 
   |    | Button - 'Close'    (L967, T3, R992, B28)
   |    | ['CloseButton', 'Button3', 'Close']
   |    | child_window(title="Close", control_type="Button")
```

**Comment by vasily-v-ryabov** [comment]
It depends on the backend used in creating `Application(backend="???")`. Did you read [the Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) about Spy++/Inspect.exe tools and corresponding backends in pywinauto?

Some apps may have controls not visible to Spy++ and default pywinauto's backend, but they might be visible to Inspect.exe and UIA pywinauto's backend.

**Comment by vasily-v-ryabov** [comment]
@ma1nojk any updates? Are you able to find necessary controls using `backend="uia"` ?
