### ISSUE TITLE
How to distinguish different Adobe AcrobatPro Windows from each other?

### ISSUE THREAD

**Issue by huaxz1986** [pywinauto/pywinauto#462]
I open many pdf files with AcrobatPro .How ever

```
for pdf_file in files:
   try:
     Application().start('%s %s' % (_adobe_path, pdf_file))  # open a file
       window=app.top_window()
       #do somethong
       window.TypeKeys('%FX')  # exit
    except:
      pass
```

However,when there is some excepthon, then there are more Acrobat Process. And `app.top_window()` then always throw excepthon. How to distinguish this Processes and return the top one.

**Comment by vasily-v-ryabov** [comment]
If AcrobatPro runs all documents using one process, then I wouldn't recommend using `top_window()`. Because all main windows are top in the hierarchy (`top_window()` returns the first one). To get the active (focused) window there is another method: `app.active()`.

But I'd recommend another way. You know a pdf file name and it's shown in the window title. So you may create window specification for this particular title:
```python
for pdf_file in files:
   try:
     Application().start('%s %s' % (_adobe_path, pdf_file))  # open a file
       window=app.window(title=u'Adobe AcrobatPro - {}'.format(pdf_file))
       #do somethong
       window.TypeKeys('%FX')  # exit
    except:
      pass
```
Of course it can be transformed to something like `os.path.basename(pdf_file)` if it's not a full path in the title.

**Comment by huaxz1986** [comment]
I try what you say,but there is something strange.

When I run:
```
from pywinauto.application import Application
app=Application().start('%s %s' % (_adobe_path,'a.pdf'))
sleep(10)
window=app.window(title='a.pdf - Adobe Acrobat Pro')
print(window.WindowText()
```
or 
```
from pywinauto.application import Application
app=Application().start('%s %s' % (_adobe_path,'b.pdf'))
sleep(10)
window=app.window(title='b.pdf - Adobe Acrobat Pro')
print(window.WindowText()
```
seperately, all is ok.

When I run:
```
from pywinauto.application import Application
app=Application().start('%s %s' % (_adobe_path,'a.pdf'))
sleep(10)
window=app.window(title='a.pdf - Adobe Acrobat Pro')
print(window.WindowText())
sleep(20)
app=Application().start('%s %s' % (_adobe_path,'b.pdf'))
sleep(10)
window=app.window(title='b.pdf - Adobe Acrobat Pro')
print(window.WindowText())
```
Adobe Acrobat pro will generate 2 processes, each process has one window. And only the first  `print(window.WindowText())` is ok, and the second `print(window.WindowText())` is failed,it says `ElementNotFoundError`.

**Comment by vasily-v-ryabov** [comment]
Hmm... maybe second file name contains some non-alphanumeric symbols. Try this one for the second document:
```python
window = app.windows()[0]
```
or
```python
window=app.window(best_match='b.pdf - Adobe Acrobat Pro')
```
Is `.window_text()` output different for these cases?

**Comment by vasily-v-ryabov** [comment]
OK, probably Acrobat is detecting previous process and sending the command to open new document in one process (you can see only one `Acrobat.exe` in Task Manager->Details page). So the second process just sends this command and closes the process.

To resolve it the first `app` object should be re-used:
```python
from pywinauto.application import Application
app=Application().start('%s %s' % (_adobe_path,'a.pdf'))
sleep(10)
window=app.window(title='a.pdf - Adobe Acrobat Pro')
print(window.window_text())
sleep(20)
second_app=Application().start('%s %s' % (_adobe_path,'b.pdf'))
sleep(10)
window=app.window(title='b.pdf - Adobe Acrobat Pro')
print(window.window_text())
```
