### ISSUE TITLE
trouble using select method

### ISSUE THREAD

**Issue by YF-Yifei** [pywinauto/pywinauto#467]
Hi everyone,

I am getting trouble on using method 'select()' on a listview object.

When I use:
`app.Dialog.ListView0.DataItem1.print_control_identifiers()`

I can get all information of the specified line normally as shown below:

> Control Identifiers:
> 
> DataItem - 'Simulator.cItemsToScan'    (L38, T190, R1239, B210)
> ['DataItem', 'Simulator.cItemsToScan', 'Simulator.cItemsToScanDataItem']
> child_window(title="Simulator.cItemsToScan", control_type="DataItem")
>    | 
>    | HeaderItem - ''    (L0, T0, R0, B0)
>    | ['', 'HeaderItem', '0', '1']
>    |    | 
>    |    | Thumb - ''    (L0, T0, R0, B0)
>    |    | ['2', 'Thumb', 'Thumb0', 'Thumb1']
>    |    | child_window(auto_id="PART_TopHeaderGripper", control_type="Thumb")
>    |    | 
>    |    | Thumb - ''    (L0, T0, R0, B0)
>    |    | ['3', 'Thumb2']
>    |    | child_window(auto_id="PART_BottomHeaderGripper", control_type="Thumb")
>    | 
>    | Custom - 'Item: Simulator.cItemsToScan, Column Display Index: 0'    (L38, T190, R72, B210)
>    | ['Item: Simulator.cItemsToScan, Column Display Index: 0', 'Custom', 'Item: Simulator.cItemsToScan, Column Display Index: 0Custom', 'Custom0', 'Custom1']
>    | child_window(title="Item: Simulator.cItemsToScan, Column Display Index: 0", control_type="Custom")
>    |    | 
>    |    | Button - ''    (L40, T192, R69, B207)
>    |    | ['4', 'Button']
>    | 
>    | Custom - 'Axial'    (L72, T190, R218, B210)
>    | ['Custom2', 'Axial', 'AxialCustom', 'Axial0', 'Axial1']
>    | child_window(title="Axial", control_type="Custom")
>    |    | 
>    |    | Static - 'Axial'    (L75, T191, R214, B208)
>    |    | ['Axial2', 'AxialStatic', 'Static', 'Static0', 'Static1']
>    |    | child_window(title="Axial", control_type="Text")
>    | 
>    | Custom - 's10511378904889'    (L218, T190, R656, B210)
>    | ['Custom3', 's10511378904889', 's10511378904889Custom', 's105113789048890', 's105113789048891']
>    | child_window(title="s10511378904889", control_type="Custom")
>    |    | 
>    |    | Static - 's10511378904889'    (L221, T191, R667, B208)
>    |    | ['s10511378904889Static', 's105113789048892', 'Static2']
>    |    | child_window(title="s10511378904889", control_type="Text")
>    | 
>    | Custom - 'Waiting'    (L656, T190, R947, B210)
>    | ['Waiting', 'Custom4', 'WaitingCustom', 'Waiting0', 'Waiting1']
>    | child_window(title="Waiting", control_type="Custom")
>    |    | 
>    |    | Static - 'Waiting'    (L659, T191, R943, B208)
>    |    | ['Waiting2', 'WaitingStatic', 'Static3']
>    |    | child_window(title="Waiting", control_type="Text")
>    | 
>    | Custom - 'test1'    (L947, T190, R1239, B210)
>    | ['Custom5', 'test1Custom', 'test1', 'test10', 'test11']
>    | child_window(title="test1", control_type="Custom")
>    |    | 
>    |    | Static - 'test1'    (L950, T191, R1235, B208)
>    |    | ['test12', 'test1Static', 'Static4']
>    |    | child_window(title="test1", control_type="Text")
>    | 
>    | Custom - ''    (L0, T0, R0, B0)
>    | ['5', 'Custom6']

But when I continue to use command:

`app.Dialog.ListView0.DataItem1.select()`

It comes to an error:

> Traceback (most recent call last):
> 
>   File "<ipython-input-41-185038824d8d>", line 1, in <module>
>     runfile('E:/00_Work/06_auto_run_recon/python_Recon/test_ListView.py', wdir='E:/00_Work/06_auto_run_recon/python_Recon')
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "E:/00_Work/06_auto_run_recon/python_Recon/test_ListView.py", line 36, in <module>
>     app.Dialog.ListView0.DataItem1.select()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywinauto\controls\uiawrapper.py", line 588, in select
>     self.iface_selection_item.Select()
> 
> COMError: (-2146233079, None, (None, None, None, 0, None))

Can anybody help to figure out the reason ?  Thanks very much !

platform info:
win7 professional + spyder3.2.7 (python3.6) + pywinauto0.6.4

**Comment by YF-Yifei** [comment]
To make background more clear, what I want to do is :
1) make a certain row as in a 'selected' status; (like this row is chosen by a mouse click. But should avoid of using mouse click here)
2) perform click() method on 'START' button.
3) choose another row and click() 'START' and start over...

**Comment by vasily-v-ryabov** [comment]
Hi @YF-Yifei this message usually looks like an error in `SelectionItemPattern` implementation for this kind of grid. So I'm afraid it's an app side issue.

> self.iface_selection_item.Select()
> COMError: (-2146233079, None, (None, None, None, 0, None))

Is it possible to workaround it using `backend="win32"`?

**Comment by YF-Yifei** [comment]
hi @vasily-v-ryabov, thanks for your reply! When I switched to `backend="win32"`, it says:

> MatchError: Could not find 'Dialog' in 'dict_keys(['Edit', ''])'

So I think only `backend="uia"` works here.

**Comment by vasily-v-ryabov** [comment]
OK, no luck. Only `.click_input()` will help.

**Comment by YF-Yifei** [comment]
Yes, seems `.click_input` works. It's not my first choice but still an alternative way, thanks @vasily-v-ryabov

**Comment by vasily-v-ryabov** [comment]
OK, seems we can close the issue since nothing to fix on pywinauto side. Feel free to submit another issue if you have more questions/problems.
