### ISSUE TITLE
We need application sample working in system tray

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#47]
Such application could be useful for testing `taskbar` module.

**Comment by airelil** [comment]
How about making it in Python like that: http://www.brunningonline.net/simon/blog/archives/SysTrayIcon.py.html ?

**Comment by vasily-v-ryabov** [comment]
Nice idea. Will make a comment about that in the first version of test_taskbar.py I'm working on.

**Comment by airelil** [comment]
A sample app added in 3faeb2c32ccc6a33a936ba1f5b792dce83705e5f, basic tests added in 9e51b0f5d1102d1875ef2e1702d8eff510c522be and 52ba38c6df63204e7da83a4d3b68769594d6bb5f
