### ISSUE TITLE
Qt error when integrate pyqt4 and pywinauto

### ISSUE THREAD

**Issue by chenhuaizhen** [pywinauto/pywinauto#472]
## Environment

- python 2.7
- pyQt 4.11.4
- pywinauto 0.6.4
- windows 10

## Detail 

Hello all, I have a problem when integrate pyqt4 and pywinauto, the code like below:
```python
from PyQt4 import QtGui
import sys
import pywinauto

def main():
    app = QtGui.QApplication(sys.argv)
    w = QtGui.QWidget()
    w.resize(250, 150)
    w.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```
And I get the error:

> Qt: Could not initialize OLE (error 80010106)

If I remove "import pywinauto" and it can run normally. 
thanks.

**Comment by vasily-v-ryabov** [comment]
Hi @chenhuaizhen can you try `pip install pywinauto==0.6.3` instead? We've made COM multithreading enabled for COM initialization and it could affect this.

**Comment by chenhuaizhen** [comment]
@vasily-v-ryabov Yes, it works, many thanks for your help!

**Comment by vasily-v-ryabov** [comment]
OK, it seems we should move COM initialization from import code to another place (when creating `Application(backend="uia")` probably with optional multithreading argument). Marking as a bug. @chenhuaizhen thanks for reporting this!

**Comment by vasily-v-ryabov** [comment]
By the way `sys.coinit_flags = 2` before `import pywinauto` should also help with pywinauto==0.6.4.
So you will not have to revert to 0.6.3.

We have one serious crash fixed in 0.6.4. So I would recommend the second solution.

**Comment by chenhuaizhen** [comment]
@vasily-v-ryabov I have tried your new method with pywinauto==0.6.4, but got another warning, my code is:
```python
from PyQt4 import QtGui
import sys
sys.coinit_flags = 2
import pywinauto

def main():
    app = QtGui.QApplication(sys.argv)
    w = QtGui.QWidget()
    w.resize(250, 150)
    w.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```
and the warning is:
> UserWarning: Apply externally defined coinit_flags: 2 
.format(module_sys.coinit_flags), UserWarning)

**Comment by vasily-v-ryabov** [comment]
This is just a warning and it looks reasonable. But just to make an experiment... Can you call `import pywinauto` with no `sys.coinit_flags` modification after this line:
```python
app = QtGui.QApplication(sys.argv)
```
Is there some warnings?

**Comment by chenhuaizhen** [comment]
@vasily-v-ryabov Sure, and my code is:
```python
import sys
from PyQt4 import QtGui

def main():
    app = QtGui.QApplication(sys.argv)
    import pywinauto
    w = QtGui.QWidget()
    w.resize(250, 150)
    w.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```
and I got a warning:

> UserWarning: Revert to STA COM threading mode
  warnings.warn("Revert to STA COM threading mode", UserWarning)

And I have a question about the "sys.coinit_flags", although the warning looks reasonable, can I hide that warning when I run my program?

**Comment by vasily-v-ryabov** [comment]
Try this code before `import pywinauto`:
```python
import warnings
warnings.simplefilter("ignore", UserWarning)
```

**Comment by chenhuaizhen** [comment]
@vasily-v-ryabov Many thanks, it works

**Comment by vasily-v-ryabov** [comment]
Well, I decided to re-qualify this thread as a question, because it's impossible to predict whether MTA or STA mode will be chosen by next import or statement. Let's leave MTA a default mode. Closing.

**Comment by sha-fuq** [comment]
Sorry, but what happened to this issue? Last year I used the hide warning fix you provided and left a comment in my code reminding me the extra lines were there temporarily till pywinauto 0.6.6. release.

It's been over a couple of months now and we've moved to the latest pywinauto version. But when I remove the temporary lines I still see the "pywinauto QWindowsContext: OleInitialize() failed:  COM error..." warning is there.

Will there be a permanent fix for this in the future?

**Comment by vasily-v-ryabov** [comment]
The latest comment in the thread should explain our decision. If we switch to STA as a default mode, it can break another library that wants to use MTA. And vice versa.

So permanent fix for all cases is impossible. Just import pywinauto later because it can adjust to COM threading mode already used by Qt4. While Qt4 can't do the same thing for pywinauto.

Removing the warning completely is also impossible, because this message is important at least first time. Just disable the warning if you don't want to see it. It's standard way Python provides. It can hide other `UserWarning`s, but it should be possible to write more tricky filter I believe.

Also the most important use cases involve interacting with another process, not with its own Python app. So we'd better concentrate on new features like UI recorder and Linux backend.

Thanks for understanding.
