### ISSUE TITLE
How to capture image when failing?

### ISSUE THREAD

**Issue by tibile** [pywinauto/pywinauto#474]
@vasily-v-ryabov can you tell me know: is  pywinauto supported to capture an image when testing fails?

**Comment by vasily-v-ryabov** [comment]
Hi @tibile if you have Pillow installed (`pip install -U Pillow`), just use something like
```python
app.MainWindow.capture_as_image().save(r"C:\temp\img.png")
```

pywinauto is an automation library, not a test runner. If you use pytest or built-in unittest it's easy to call capturing image in `teardown_method` if result is a failure.

**Comment by tibile** [comment]
It's awesome!
Thanks for helping!
