### ISSUE TITLE
SetCursorPos', 'No error message is available

### ISSUE THREAD

**Issue by limonides** [pywinauto/pywinauto#476]
```
from os import system
from pywinauto.application import Application

system("start C:\\tmp\\file.exe")


app = Application().Connect(title=u'Program Name', class_name='MsiDialogCloseClass')
dialog = app.MsiDialogCloseClass
button = dialog.Button
button.click_input()
```

When i tried run my script received error:

> File "...\pywinauto\base_wrapper.py", line 685, in click_input
>     key_down=key_down, key_up=key_up)
>   File "..\pywinauto\mouse.py", line 125, in _perform_click_input
>     win32api.SetCursorPos((coords[0], coords[1]))
> pywintypes.error: (0, 'SetCursorPos', 'No error message is available')

**Comment by vasily-v-ryabov** [comment]
Hi @limonides when you use `connect(...)`, please make sure the script is running as Administrator. We're working to add meaningful warnings.

By the way, why not just `Application().start("C:\\tmp\\file.exe")` ?

One more question: are you running this in Remote Desktop session? If yes, is RDP window minimized?

**Comment by vasily-v-ryabov** [comment]
Closing since no replies for 2 months. Please re-open if it's still actual.
