### ISSUE TITLE
How do I find the top-level window under my window and the mouse?

### ISSUE THREAD

**Issue by bloodbringer** [pywinauto/pywinauto#477]
I have a semi-transparent window. I want to drag it over some other target window ( which can be partially covered by other windows) and place the mouse cursor over the target window which I can see trough my window. At this point, I would activate some code in my application to identify the target. Once identified I want my application to raise the target fully under my window and discover the target's geometry. At this point I can easily set my window's geometry to match the target window's (I think I can, anyway). Does pywinauto provides the tools to do this?

Thanks for your help.

**Comment by vasily-v-ryabov** [comment]
Hi @bloodbringer the question is pretty wide. Looks like you can do all these things. There is method `set_focus()` that brings window to foreground. Method `drag_mouse_input()` implements some mouse movement that is usually detected as drag and drop by many apps (start moving smoothly then jump to target). Not sure this kind of movement is what you need. But you can emulate more complicated behavior by using methods `press_mouse_input()` and `move_mouse_input()`.

Many mouse related methods accept `coords` parameter (default is a center of control/window) and `absolute=False` by default (i.e. relative coords from specified window) that can be changed.

Hope it helps. Also don't forget to check out GUI object inspector mentioned in the Getting Started Guide. This is important to choose the most appropriate backend (pywinauto supports 2 different GUI accessibility technologies under the hood). Some apps may provide GUI elements info using only one of them.

**Comment by bloodbringer** [comment]
Привет, Васи́лий!  Thanks for the response. In the future I will try to ask skinny question. I should have stated that I am using Python 3.6.4 and PyQt5 5.10 on a Windows 10 system. I use method "moveMouse" to move the mouse programatically. To resolve my current issue, I'll just drag the rodent around manually until it's where I want it; it's not possible to program this bit. I do this by looking through my transparent window to see other application windows underneath. I'll drag the mouse pointer until it's over the one I want to "investigate." At this point I assume there are OS API calls to gather information about windows under the mouse pointer. Since I don't know ANYTHING about those other windows, I can't search for them using any IDs, window title, for example. The only criterion for the "target" is that it is the highest (in Z order) under the mouse pointer under my window. The target window may actually be under many other windows BUT a piece of it is NOT covered EXCEPT by my application window. This is why I can see it. I need to raise the target to be just under my window, determine its geometry, and then change my window's geometry to be the same.

By the way, I installed pywinauto using pip and did this as an experiment:
        winds = pywinauto.findwindows.find_windows(top_level_only = True, title = "emacs@TWO-M6800")
It worked.
print (winds) produced:
[263604] (which I guess is the OS's ID for the found window)

What I probably will get is a list of windows through which I need to wade to find the top one. Maybe the list will already be in Z-order, ergo, the first one IS the top one. Hooray for me!

Maybe PyQt5 has the API calls I need. I don't know; I'll look. I am a rank beginner so I don't know where to look or the right questions to ask.

When I run my program, I get this error:
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"

I don't know what it means but my pywinauto test worked anyway.

In a different application using tkinter, I used the lift method to raise a child window of mine.

Which Рябов are you? There are a bunch out there.

Спасибо!

Фома

**Comment by bloodbringer** [comment]
Hi, Vasily
I think I have mostly resolved this issue. Here's the code:
`        if (e.key() == Qt.Key_W):
            if (self.makeBaby):
                self.makeBaby = False
                self.setGeometry(self.previousGeometry)
                self.updateStuff()      #> Redraw everything after getting    <#
                                        #> off her. How do you know it's a    <#
                                        #> girl? Her mouth is open.           <#
            else:
                self.makeBaby = True
                Joe = self.geometry()
                self.previousGeometry = Joe
                self.windowHandle = win32gui.WindowFromPoint((QCursor.pos().x(), QCursor.pos().y()))
                                        #> Get my window's handle.            <#
                self.move(self.ws, self.hs)
                                        #> Get out of the way.                <#
                windowHandle = win32gui.WindowFromPoint((QCursor.pos().x(), QCursor.pos().y()))
                                        #> Get the target window's handle.    <#
                windowRect = win32gui.GetWindowRect(windowHandle)
                                        #> Get its geometry.                  <#

                x = windowRect[0]
                y = windowRect[1]
                w = windowRect[2] - x
                h = windowRect[3] - y
                self.move(Joe.x(), Joe.y())
                                        #> Return to the playing field.       <#
                win32gui.SetWindowPos (windowHandle, self.windowHandle, x, y, w, h, win32con.SWP_NOSIZE|win32con.SWP_NOMOVE)
                                        #> Position the target window under   <#
                                        #> my window.                         <#
                self.raise_()           #> This and the next line are         <#
                                        #> necessary. I don't understand why. <#
                self.activateWindow()
                self.setGeometry(x, y, w, h)
                                        #> Match my window's geometry to the  <#
                                        #> target's.                          <#
                self.updateStuff()      #> Give her a new coat of paint.      <#

It still has some rough spots. My application doesn't always get the entire target window. It apparently depends on the kind of window and where I grab it.

I didn't use pywinauto after all.

If you have any advice to streamline my code, lay it on me, please.

Thansk, again.

Tom

**Comment by vasily-v-ryabov** [comment]
@bloodbringer sorry for the late response. `WindowFromPoint` and `ChildWindowFromPoint` is the right way. It can be used to improve pywinauto by adding `from_point(...)` method to classes derived from `ElementInfo`. Maybe higher level method could be added to classes `Application` and `Desktop`.

Currently we have no much time to take a responsibility for implementing these things. Your contribution is very welcome!

**Comment by vasily-v-ryabov** [comment]
Of course, if your code is inside PyQt app only, there is no need to use pywinauto. The most frequent use cases include GUI automation from external Python process. That's why we can't consider it as high priority.

**Comment by bloodbringer** [comment]
"You can't comment at this time — your comment cannot be blank." Hmmmm... Why not? I'll try anyway.
Thanks for your responses, Vasily. I'll look into ChildWindowFromPoint and RealChildWindowFromPoint. As you correctly inferred, my goal is NOT to "control" some other application window, except to expose it completely under my slightly transparent window. As a Python novice, it's nearly impossible to find the tools I need to accomplish a task. There are too many toolboxes, pywinauto, tkinter, pyqt5, win32gu, win32api, wxpython, etc., and probably many more I have never heard of. Every one of these things is crammed with methods that do many wonderful things. The designers and long-time users take all this stuff for granted. The raison d'être for the existence of most of this stuff is sadly lacking as is a few very simple examples of how to use the methods. Since I'm pretty dumb and stupid, it takes me a VERY LONG time to tease out solutions to reach my programming goals. Just finding the "right" toolbox is very challenging. I hope I live long enough. I have some C programs from my UNIX days. What do you think of Cygwin? Will it resolve all the porting issues from UNIX to WIndows? Eventually, I will convert them to Python. Cheers.

**Comment by vasily-v-ryabov** [comment]
Ah, you're trying to port your current Qt program written in C to Python, right? Is it tend to be cross platform? or Windows only? AFAIK Cygwin can solve your problem for console programs only. GUI frameworks implementations (like Qt) has many OS specific things inside (hiding them from end users in an ideal world). So maybe you'll have to implement different branches of code for various OSes even in Python.

**Comment by bloodbringer** [comment]
Thanks, Vasily, for your reply.

 

First, let me straighten out the sequence of things.

 

1.     My original thread (#477) is in reference to a brand new Windows-based Python program of mine. Among many things, I want this program to be able to identify and “target” another application’s window under mine. I have NOT completely resolved this issue because my code (windowHandle = win32gui.WindowFromPoint((QCursor.pos().x(), QCursor.pos().y()))) does NOT consistently identify the target window. Sometimes, it identifies only a widget of the target window; this is NOT satisfactory. Please help me resolve this issue and then all my goals for this application will be met. I am writing this particular application in Python and PyQt5 to run on Windows, without regard for any other operating system (Unix, etc.) or toolbox (tkinter, etc.).

2.     My comment about wanting to port some Unix/X Window--based C programs to Windows 10, WITHOUT any modifications misled you. I apologize. Porting these C programs is a future project (soon, I hope) and has nothing whatsoever to do with item 1 in any way. If Cygwin can help me in this port, great! Converting from C to Python is definitely NOT the goal here. The goal is C (on Unix) to (the same) C (on Windows 10), without ANY modifications (or very, very, very few modifications). Refactoring from C to Python is also a future goal but, for now, it’s just C to C.

3.     I have made no mention of what you refer to as my “current” Qt program. I will mention it here and now. I am currently refactoring an earlier Python program of mine to use PyQt5 instead of tkinter, which I will never use again. And, that’s the name of that tune!

 

When I get around to item 2, I hope Cygwin will help a lot. I am not sure what you mean by “console programs.” Please elucidate. Some of the C programs involved do some GUI stuff and some don’t. After all, the GUI part of most applications is just the tip of the iceberg. The application itself is, in general, the part you don’t see, right?

 

As far as “different OSes” are concerned, why are there so many? I’ve been programming for over 50 years and I’m sick of this crap! The same thing goes for programming languages (https://en.wikipedia.org/wiki/List_of_programming_languages). More crap! The NIH (“not invented here”) principle is at work. Every time some smart guy thinks he has a “better” idea, he creates a new OS or language and, of course, he attracts a bunch of followers who worship him. This plethora of “stuff” suffocates creativity while very effectively creating chaos for all mankind. This chaos is expanding faster than the universe itself, I think.

 

I have a Windows 10 box at home. That’s it. All of my current programming efforts consider this environment alone and nothing else. I have no intention to be all things to all programmers in all programming environments.

 

Down below, I include the Python program that triggered item 1, about grabbing another application window. It works mostly, except for item 1, which still needs some work. Try it and tell me what you think.

 

Eventually, I want to post it at GitHub, if I can figure out how to do it. There’s a lot of stuff on GitHub. How in the heck can anybody ever discover anything on GitHub to make use of?

 

How can I get back to a thread, on github or stackoverflow, etc., when that tab in my browser goes away. If someone sends me an e-mail, there’s a reference and I can return to that topic. Otherwise, I don’t know how to get back.

 

Thanks.

 

Keep having fun.

 

Tom

**Comment by vasily-v-ryabov** [comment]
Oh, well. I like your sense of humor, but I need some time to parse this post first. Creating a repo would be ideal. But in this case maybe it's better to send me the code by e-mail (just do `.replace("-", ".")` for my GitHub nickname to get my gmail).

**Comment by bloodbringer** [comment]
As usual, I don’t get it. I had “it” once and dropped it. Naturally, it broke. Now, you, and all paraclete wanna-bes go through life with good intentions and smilely faces.

 

Here’s the deal, Neal: what am I supposed to do, EXACTLY, with “(just do .replace("-", ".") for my GitHub nickname”? What does this mean, EXACTLY?

 

Since you responded to my last e-mail, you obviously RECEIVED my last e-mail. Why do I have to send it twice? Is this another case of “refactoring for Jesus”?

 

For ultimate satisfaction and garbage collection, please dial 911. At the tone, execute this emergency code: for paraclete = -∞ to ∞ set theirStuff(paraclete) = theNullSetOfStuffAndToHellWithTheOtherStuff+π-allApostlesWhereverTheyMayBe+1. QED..

 

 

What’s for dinner?

 

 

Who took my drink?

 

 

A computer is like a toothbrush. I don’t use yours. Don’t use mine.

 

 

My e-mail address is thomas.oneal@verizon.net.

 

 

I want another drink.

You have a drink.

Oh, is that my hand?

Yes.

I still want another one.

Hand or drink?

Yes.

 

Are you done parsing? Do you hold a valid parsing license? Without one, you can get into a lot of trouble. The parsing police will show up without warning and make you debug yourself, in public, while female programmers watch. “female programmer” is an oxymoron. Usually, they’re highly overpaid to write makeup subroutines for outsourced customer service representatives in Mumbai, who speak all languages EXCEPT English. The best part is that they know absolutely nothing about computers.

 

 

I get dumber every day. Dumb da dumb dumb DUMB!

**Comment by vasily-v-ryabov** [comment]
Now I got parsing license (removed many empty lines) and enough time to figure out the problem.

Hmm... I've looked into `ChildWindowFromPoint` in more details. This code snippet helped to list all child handles under mouse cursor. I have 16 top level windows and obtained 6 pairs of child handle + parent handle. The idea is listing all the top level handles and test them all for `ChildWindowFromPoint` result.

```python
from pywinauto.findwindows import find_windows

top_windows = find_windows()
print("top_windows = {}".format(top_windows)) # length = 16 for me

import win32gui
for hwnd in top_windows:
    handle = win32gui.ChildWindowFromPoint(hwnd, (500, 500))
    if handle:
        print("handle = {}, top_handle = {}".format(handle, hwnd)) # printed 6 times
```
Just left to exclude the top handle that is yours. Got it?

To implement listing all top level handles without pywinauto you can take this code (clean version of `find_windows()`):

```python
import ctypes
EnumWindows = ctypes.windll.user32.EnumWindows
top_handles = []

# The callback function that will be called for each HWND
# all we do is append the wrapped handle
def enum_window_proc(hwnd, lparam):
    """Called for each window - adds handles to a list"""
    top_handles.append(hwnd)
    return True

# define the type of the child procedure
enum_win_proc_t = ctypes.WINFUNCTYPE(
    ctypes.c_int, ctypes.c_long, ctypes.c_long)

# 'construct' the callback with our function
proc = enum_win_proc_t(enum_window_proc)

# loop over all the top level windows (callback called for each)
EnumWindows(proc, 0)
```

Okay. Now I have too many other tasks and emotions outside your relations with QA girls and Mumbai programmers. It was funny to read the comments. I'll save them for long winter evenings after my retirement.

**Comment by vasily-v-ryabov** [comment]
And yeah... No ideas how to re-master Z order of these handles.

**Comment by vasily-v-ryabov** [comment]
Methods `from_point(x, y)` and `.top_from_point(x, y)` have been implemented for `class Desktop` and all wrappers.
