### ISSUE TITLE
AttributeError: WindowSpecification class has no 'CaptureAsImage' method

### ISSUE THREAD

**Issue by sarim-zafar** [pywinauto/pywinauto#488]
Hi when i try to capture an image it throws the following error
 When i open the application with win32 backend it works flawlessly but when I opened the application as uia backend it throws following error.
```python
File "C:\ProgramData\Anaconda3\lib\site-packages\pywinauto\application.py", line 173, in __call__
    format(self.criteria[-1]['best_match']))
AttributeError: WindowSpecification class has no 'CaptureAsImage' method
```

**Comment by vasily-v-ryabov** [comment]
Hi @sarim-zafar UIA method names are all aligned with PEP-8 coding convention. Use `.capture_as_image()` instead.

**Comment by sarim-zafar** [comment]
I didn't see anything like this in the documentation. Thank you for the reply!
