### ISSUE TITLE
How to click item in context menu

### ISSUE THREAD

**Issue by bulyhome** [pywinauto/pywinauto#490]
Hello,

I am new to pywinauto and I need to automate one application that has a ToolbarWindow32 control with several buttons that make one "Context" menu to appear. I am able to click on all those buttons, but not to navigate inside the menu. I guess I am missing something basic.

Here is what the Inspect.exe shows for that "Context" menu.

![context_menu](https://user-images.githubusercontent.com/24893177/39129512-54d6c2f0-4713-11e8-96e1-e27c505b25d4.PNG)

I've read other posts where it was written that the search should start from the "Desktop" part (not from the actual control: in this case the toolbar), but I could not find any example posted (the wireshark , notepad and explorer examples are slightly different situations)

Thanks in advance for your help.

**Comment by bulyhome** [comment]
I found the solution:

    popup_menu = Desktop(backend='uia').window(title="Context")
    popup_menu[submenu].click_input()

**Comment by dschiller** [comment]
Thanks Wasily. I alread tried that.

If I try

```
popup_menu = Desktop(backend='uia').window(title="Context")
pp.pprint(popup_menu.children())
```

The `Context` doesn't got found

```
pywinauto.findwindows.ElementNotFoundError: {'title': 'Context', 'top_level_only': True, 'backend': 'uia'}
```

**Comment by vasily-v-ryabov** [comment]
Hi @dschiller this method `Desktop(backend='uia').windows()` should return all top-level elements. Popup menu is usually among them. Call `.window_text()` for each to find correct title for `.window(title="...")` specification.

**Comment by dschiller** [comment]
Hi Vasily I iterated all Items from `Desktop(backend='uia').windows()` and cannot see the Popup. I only see the Application. So I believe the Popup is inside the Application and when I access the Application with `pywinauto` then the Popup disappears because `pywinauto` somehow trigger Dropdowns in the Application which forces the Popup to close.
