### ISSUE TITLE
Installation document for pywinauto

### ISSUE THREAD

**Issue by smitagodbole** [pywinauto/pywinauto#495]
Hi,
I have couple of questions regarding pywinauto...
1.  Is there any step by step document to install pywinauto on windows 10?    I wanted to install it on my colleague's machine who has installed python 3.6.5 and it looks like python is not getting recognized when we run python at command prompt.
2.  Can we do parameterization when automating the test using pywinauto?
Thanks for your help.
Smita

**Comment by smitagodbole** [comment]
Thanks Vasily !.  Actually we found the problem and after uninstalling/installing it worked.  You mentioned in reply that PYTest supports parameterization but isn't it for web application?  Sorry I am asking lot of questions as I am not a hard core developer.  I am QA engineer and trying to automate windows GUI.  I have lot of questions regarding this tool.  Is it okay if I ask all questions together if you don't mind.  That will help me a lot to learn this tool.Smita
    On Tuesday, May 8, 2018, 6:20:58 PM EDT, Vasily Ryabov <notifications@github.com> wrote:  
 
 
Hi @smitagodbole if python command is not recognized it means you didn't check option "Add Python to PATH" during Python installation (don't see pywinauto specific issues). I thought it's so obvious even for new Python users.

Parameterization is a feature of pytest (general purpose test framework to organize the tests), pywinauto is just an UI automation tool, not a complete test framework. At least for now.

**Comment by vasily-v-ryabov** [comment]
No problem, feel free to ask more questions. As I said pytest is a general purpose test framework to organize the tests. It's more powerful that built-in module `unittest` and it's compatible with `unittest` if you use pytest as a test runner. This is not for web only or unit tests only. pytest can be used for any kind of auto testing. For example, I use at the main job even for testing OS drivers.

I think pytest documentation will tell you more. I'm ready to answer questions about pywinauto and desktop GUI automation. The good starting point is [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html). Good luck and welcome!

**Comment by smitagodbole** [comment]
Thank you very much.  I will try to use PyTest to run all my scripts all together.

**Comment by vasily-v-ryabov** [comment]
Seems this is answered. Closing.
