### ISSUE TITLE
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_c_ulong instance instead of pointer to c_long

### ISSUE THREAD

**Issue by afrancoc2000** [pywinauto/pywinauto#497]
I created a Jenkins pipeline that executes a program in a remote server that manipulates an application for functional tests.

I started using pywin32 and later moved to pywinauto to start SAP Gui and then send an enter but although it works great while I have the remote desktop oppened, when I close the remote desktop and run it from Jenkins, the app gets lost.

This is my app with pywin32:

    os.startfile("C:\\Program Files (x86)\\SAP\\FrontEnd\\SAPgui\\saplogon.exe")

    time.sleep(5)
    handle = win32gui.FindWindow(0, "SAP Logon 740")  

    keyboard = Controller()
    keyboard.press(Key.enter)

So I tried to add focus to the app to force the focus without success:

    os.startfile("C:\\Program Files (x86)\\SAP\\FrontEnd\\SAPgui\\saplogon.exe")

    time.sleep(5)
    handle = win32gui.FindWindow(0, "SAP Logon 740")  

    win32gui.ShowWindow(handle, 5)           
    win32gui.SetForegroundWindow(handle)

    keyboard = Controller()
    keyboard.press(Key.enter)

I changed the key presses to this with the same result:

    shell = win32com.client.Dispatch("WScript.Shell")
    shell.SendKeys('{ENTER}')

I then moved to pywinauto trying to do a click on a button instead of sending the enter but I found more problems, as pywinauto is not recognizing my app titles:

    app = Application().start("C:\\Program Files (x86)\\SAP\\FrontEnd\\SAPgui\\saplogon.exe")

    app["SAP Logon 740"] # this doesn't work
    app.top_window_()    # this doesn't work either

    handle = win32gui.FindWindow(0, "SAP Logon 740")  
    sapApp = app.window_(handle = handle)            #Finally this works but...

    sapApp["Log &On"].click()                        # This doesn't work
    sapApp.log_on.Click()                            # This doesn't work

I get this exception:

    ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_c_ulong instance instead of pointer to c_long

I know that's the name because I tried:

    print(sapApp.descendants(control_type="MenuBar"))

And got this results:

    [<win32_controls.ButtonWrapper - 'Log &On', Button, 14221798>, ...]

So I know that's the name of the button but haven't been able to click on it.

I also tried setting focus to the app, with the same result:

    sapApp.SetFocus()

With the remote desktop oppened everything works fine but when it's closed my app doesn't get the enter

So has anyone had this problem before? I'm running out of ideas what else can I try?

I wrote this question in stackoverflow too: [stackoverflow](https://stackoverflow.com/questions/50299472/pywin32-pywinauto-not-working-properly-in-remote-desktop-when-it-is-minimized)

Also, tested this with notepad too, trying to do something as this issue: [issue](https://github.com/pywinauto/pywinauto/issues/270)

Thanks

**Comment by vasily-v-ryabov** [comment]
Hi @afrancoc2000 I left the answer on StackOverflow.
