### ISSUE TITLE
Application crashes when interacting with elements or print_control_identifers

### ISSUE THREAD

**Issue by madhavankumar** [pywinauto/pywinauto#501]
Here is my code:

```from pywinauto.application import Application
app = Application().start(r"C:\\Program Files\\myapp\\folder\\applicationname.exe -product=dev")
dlg = app['Login']
dlg.Wait('visible', timeout=30, retry_interval=0.5)

app['dlg']['User Name:Edit'].type_keys("userA")
time.sleep(1)
app['dlg']['Password:Edit'].type_keys("password")
time.sleep(1)
app['dlg']['OK'].Click()
main_page = app.window(title_re=".*My App Name*")
main_page.Wait('ready', timeout=20, retry_interval=1)
main_page.Maximize()
# works until the above line.

main_page_print_control_identifiers() 

syslistview = main_page.myListView
#also tried 
# syslistview = main_page['  myListview'] #
listview_item = syslistview.GetItem(u'MyItem')
listview_item.Click()
# try to access any element in the main_page crashed the application
#try to print_control_identifiers also crashed the application
#seeing multiple warning lines such as WARNING! Cannot retrieve text length for handle = 3345188 
```

I tried **inspect** and I see the main window with `role` = `window` and the child window with role=`client`. Both parent and the child have the same name. 

Spy++ shows only one window

How do I avoid the crash and identify the elements in the window. 

Inspect - (MSAA)

![image](https://user-images.githubusercontent.com/5941859/40700408-6ad032fc-63a7-11e8-9237-cd8375560461.png)

Spy++

![image](https://user-images.githubusercontent.com/5941859/40701514-29744e2e-63ac-11e8-90ed-05384caa2c66.png)

**Comment by madhavankumar** [comment]
I tried settings `top_level_only=False` as well. Still the same issue.

**Comment by vasily-v-ryabov** [comment]
Application may crash if it's 64-bit, but Python is 32-bit. Nothing is guaranteed. Install correct 32-bit or 64-bit Python to match app architecture.

Or use `Application(backend="uia")` to use MS UI Automation since you're using Inspect.exe.

**Comment by Vladibor** [comment]
I have a question, is the correspondence between bitness of Python interpreter and of bitness the tested application a requirement for using pywinauto?

**Comment by vasily-v-ryabov** [comment]
@Vladibor for `backend="win32"` the answer is yes. But UIA backend should work with any app.

**Comment by vasily-v-ryabov** [comment]
Particularly for ListView and TreeView 64-bit Python should work with both 32-bit and 64-bit app. It's handled correctly. 32-bit Python can be used for your own risk.

**Comment by madhavankumar** [comment]
The 64 bit Python did solve my problem. Thank you very much. 

I tried the backend as uia but I have am having trouble identifying windows. Is the syntax a little different when using backend as uia?

**Comment by vasily-v-ryabov** [comment]
Syntax is pretty the same for UIA backend, but the hierarchy of elements can be seriously different as well as properties of every element. For example, `control_type` is more useful than `class_name` for UIA. But UIA allows multi-level window specifications (>2 levels) and adds more properties like `auto_id`. It provides much more information especially for .NET apps. Sometimes UIA is the only choice because Win32 API is not able to see the whole hierarchy. But Win32 API is faster. There are many pros and cons for both.
