### ISSUE TITLE
Implement key down & key up actions in the keyboard module

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#503]
This is requested in StackOverflow question: https://stackoverflow.com/questions/50656751/pywinauto-send-key-down-to-application

`class KeyAction` already contains necessary params: `down = True, up = True`. So just need to use them at a higher level.

**Comment by badari412** [comment]
@vasily-v-ryabov Can you please review my PR and let me know if I need to change anything other than the coding standard issues pointed out by codacy?

**Comment by vasily-v-ryabov** [comment]
I think this can be closed after updating the docstring for `keyboard.py`.

**Comment by vasily-v-ryabov** [comment]
Hi @badari412 are you going to update the docs? Or I can do it on my side?

**Comment by badari412** [comment]
@vasily-v-ryabov I just created a pull request related to this. Please look into this.

**Comment by vasily-v-ryabov** [comment]
Fixed in #577 and #584 thanks to @badari412 !
