### ISSUE TITLE
How to retrieve the content of an item in Combobox in pywinauto ? 

### ISSUE THREAD

**Issue by hulei545** [pywinauto/pywinauto#504]

**Comment by vasily-v-ryabov** [comment]
For which backend? What have you tried?

**Comment by hulei545** [comment]
just the default backend. I can just select the item in the combobox, but I want to get the data stored in this item in the combobox

**Comment by vasily-v-ryabov** [comment]
OK, what kind of data do you mean? I can't read your minds. Can you be more detailed?
The type of application is also important. MFC? WinForms?

**Comment by vasily-v-ryabov** [comment]
Sorry for late reply. The question is still not clear. If some other controls data is associated with some combo box item, I think it can be retrieved by selecting this item and then getting the data from other controls which are auto filled. App side item selection handler may be structured up to developers. Who knows which data structures are used inside? It's impossible to read app authors mind.
