### ISSUE TITLE
What should we do when objects are not getting recognized by print_control_identifiers()

### ISSUE THREAD

**Issue by smitagodbole** [pywinauto/pywinauto#505]
Hi,
I am running into a situation where objects are not getting recognized.  I used print_control_identifier upto depth 5 but nothing is working.  It's so funny that it only recognizes the objects which are disable.  I tried mouse click method which works fine but I don't want to use that as if I move the window I have to update the x an y co-ordinates and that drives me crazy.   I tried to install AutoIT which gives me control_id for these objects but don't know how to use that.
Thanks
Smita

**Comment by vasily-v-ryabov** [comment]
Hey, using control_id is very unreliable because they can change from run to run. It can be used in `.child_window(...)` criteria as well (as int param `control_id`), but I wouldn't recommend it at all.

Can Inspect.exe see these objects?

**Comment by smitagodbole** [comment]
Hi,Inspect.exe is only recognizing "Pane" controller.  There are tons of tree view(+) buttons in pane controller which are not getting recognized at all.  Yesterday I just learned about these tree view buttons  that it is a C++ code.  So don't know pywinauto works with C++ object?  So it looks like I have to work with mouse.click method only.thanksSmita  

    On Thursday, June 7, 2018 3:09 PM, Vasily Ryabov <notifications@github.com> wrote:
 

 Hey, using control_id is very unreliable because they can change from run to run. It can be used in .child_window(...) criteria as well (as int param control_id), but I wouldn't recommend it at all.Can Inspect.exe see these objects?—

**Comment by smitagodbole** [comment]
Is there any tool other than Inspect.exe which will recognize the controllers?  Right now, I am facing this same problem with other window as well.

**Comment by madhavankumar** [comment]
I have a similar issue. The control is of type `ProfUIS-TabWindow` . I am not able to access the tabs.
![image](https://user-images.githubusercontent.com/5941859/41393855-b3ef3c2e-6f75-11e8-9a39-8f07b01845db.png)

I am not sure if this is possible. Is there any workaround? Is  there a way to click on a tab based on its text? e.g. If a tab has text `Status` , Can I find the text `Status` on the window and click it?

**Comment by vasily-v-ryabov** [comment]
@smitagodbole @madhavankumar If the control is recognized as "Pane", I'm afraid it's a custom control and it can't be automated by pywinauto for now.

One possible way to improve an application testability is implementing action handlers on app side. So developers should be QA friendly. After that it's possible to implement Python wrapper for this custom control that can send custom window messages to this control.

(1) In case of native C++ app it should be window message handlers like `OnClick` for `WM_CLICK` message. (2) But for .NET apps UI Automation API patterns should be supported in UI Automation provider for the control (maybe only app side handlers should be enough).

In the first case I can help to implement both app handlers and custom wrapper, but I have no experience with the second case unfortunately.

**Comment by smitagodbole** [comment]
Hi Vasily,I have another question for you.  Due to the nature of the application our workflows are very big and so as my scripts are getting very big.  Is it possible that if I break up these scrips into small scripts and call from each other?  And what about Windows specification object which have defined at the beginning of the script?  Can I call same object into other scripts?  Some where I read that I can not use/call same window's specification object into another script as it is a different process ID.  Can you please guide me how to work on this?
Thanks for all your help.Smita 

    On Saturday, June 9, 2018 9:33 AM, smita godbole <smita_godbole2002@yahoo.com> wrote:
 

 Hi,Inspect.exe is only recognizing "Pane" controller.  There are tons of tree view(+) buttons in pane controller which are not getting recognized at all.  Yesterday I just learned about these tree view buttons  that it is a C++ code.  So don't know pywinauto works with C++ object?  So it looks like I have to work with mouse.click method only.thanksSmita  

    On Thursday, June 7, 2018 3:09 PM, Vasily Ryabov <notifications@github.com> wrote:
 

 Hey, using control_id is very unreliable because they can change from run to run. It can be used in .child_window(...) criteria as well (as int param control_id), but I wouldn't recommend it at all.Can Inspect.exe see these objects?—

**Comment by vasily-v-ryabov** [comment]
Hi @smitagodbole what do you mean saying "another script"? If this is another Python module imported from main script, there should be no problem to re-use existing objects for the same application instance. If you declare window specifications for any `app` object, this code can also be re-used but you must pass another `app` object to the particular function/method as a parameter.

As a conclusion you have the full Python power and can do whatever you want. For example, it's possible to inherit your own class from `Application` and save window specification objects directly to your class instance as you do for `app` object.

**Comment by smitagodbole** [comment]
Thanks Vasily !!.  

 I have one more question, as I am trying to work with couple of desktop applications.  One is Config.py(cApp1) and other is Reg.py(App1)
My test case is like.... 1.  Login to Config App1(cApp1) and doing all necessary configuration and Log off(config.py )2.  Then open the other application i.e. (App1) and going through some steps and log off(reg.py)3.. Then going to 'Report Manager' and open the PDF report and read the data.This all I am trying to do in one Test script.  Is this possible?
I am trying to call reg.py in config.py script  but when I run config.py   it opens reg.py first instead of config.py.  I don't know what to do here.Is this possible.  I don't want to keep open both application.  But right now when I run the config.py it opens both applications.I hope I have explained better this time.
Thanks Smita



    On Thursday, June 21, 2018, 9:14:22 AM EDT, Vasily Ryabov <notifications@github.com> wrote:  
 
 
Hi @smitagodbole what do you mean saying "another script"? If this is another Python module imported from main script, there should be no problem to re-use existing objects for the same application instance. If you declare window specifications for any app object, this code can also be re-used but you must pass another app object to the particular function/method as a parameter.

As a conclusion you have the full Python power and can do whatever you want. For example, it's possible to inherit your own class from Application and save window specification objects directly to your class instance as you do for app object.

**Comment by vasily-v-ryabov** [comment]
Hi @smitagodbole it looks simple problems with cyclic imports or another kind of cyclic dependency of both scripts. Of course, running 2 different apps is possible (even simultaneously, though only one will be in focus). But for detailed answer I need to take a look at the code. Current explanation is too general. So the answer is "yes, it's possible".

**Comment by smitagodbole** [comment]
Thanks Vasily.  I think we realized this when my configuration object started recognizing. When I run the script always one app is in focus  and looks like all objects are getting loaded.  I am saying this because  we found that some of the C++ objects are started recognizing when running  this script..  So thank you very much .
I have again  couple of more questions.........
1.  I am also having little problem when I tried to iterate with menu Item.  Here is what control identifer is showing me.MenuItem - 'Reports'    (L446, T58, R558, B78)   |    |    |    |    |    | ['ReportsMenuItem', 'MenuItem40', 'Reports', 'ReportsMenuItem0', 'ReportsMenuItem1', 'Reports0', 'Reports1']   |    |    |    |    |    | child_window(title="Reports", control_type="MenuItem")   |    |    |    |    |    |    |   |    |    |    |    |    |    | MenuItem - 'Registration '    (L0, T0, R0, B0)   |    |    |    |    |    |    | ['RegistrationMenuItem', 'Registration', 'MenuItem41', ' MenuItem0', 'MenuItem1', 'Registration 0', 'Registration1']   |    |    |    |    |    |    | child_window(title="Registration", control_type="MenuItem")   |    |    |    |    |    |    |   |    |    |    |    |    |    | MenuItem - 'Payments'    (L0, T0, R0, B0)   |    |    |    |    |    |    | ['Payments', 'MenuItem42', 'PaymentsMenuItem', 'Payments0', ' Payments1', 'MenuItem0', 'MenuItem1']   |    |    |    |    |    |    | child_window(title="Payments", control_type="MenuItem")   |    |    |    |    |    |    |   |    |    |    |    |    |    | MenuItem - 'AutoReports'    (L0, T0, R0, B0)   |    |    |    |    |    |    | ['AutoReports', 'MenuItem43', 'AutoReportsMenuItem', 'Auto Reports0', 'AutoReports1', 'AutoReportsMenuItem0', 'Auto ReportsMenuItem1']   |    |    |    |    |    |    | child_window(title="AutoReports", control_type="MenuItem")   |    |    |    |    |    |    |    |   |    |    |    |    |    |    |    | MenuItem - ' List'    (L0, T0, R0, B0)   |    |    |    |    |    |    |    | [' List', ' ListMenuItem', 'MenuItem44', ' List0', 'List1', ' ListMenuItem0', ' ListMenuItem1']   |    |    |    |    |    |    |    | child_window(title=" List", control_type="MenuItem")   |    |    |    |    |    |    |    |   |    |    |    |    |    |    |    | MenuItem - 'RDS'    (L0, T0, R0, B0)   |    |    |    |    |    |    |    | ['RDS', 'RDSMenuItem', 'MenuItem45', 'RDS0', 'RDS1', 'RDSMenuItem0', 'RDSMenuItem1']   |    |    |    |    |    |    |    | child_window(title="RDS", control_type="MenuItem")
Here I am trying to click on Reports -->AutoReports-->RDS  But some how I am only enabled to click on Reports and later I can not select AutoReports and RDS.  Funny thing is Inspect.exe is not recognizing these two objects either.  So don't know what to do here...
2.  Another question is does pywinauto reads the text on PDF report?
3.  I have dialog that shows more than 10 list items and each list item shows another list items then how can I recognize the list item in second list?
Thanks a lot for your help.
Smita
    On Wednesday, July 11, 2018, 2:12:57 PM EDT, Vasily Ryabov <notifications@github.com> wrote:  
 
 
Hi @smitagodbole it looks simple problems with cyclic imports or another kind of cyclic dependency of both scripts. Of course, running 2 different apps is possible (even simultaneously, though only one will be in focus). But for detailed answer I need to take a look at the code. Current explanation is too general. So the answer is "yes, it's possible".

**Comment by vasily-v-ryabov** [comment]
Hi @smitagodbole it depends how you open .pdf file. If this is Adobe Reader, it seems it's possible. I see `Inspect.exe` can access the text in legacy properties. But if it's another app, you should rely on Inspect.exe. Eveything that Inspect.exe can recognize should be accessible to pywinauto.

Also for direct .pdf file parsing you may need something like this: https://github.com/pmaupin/pdfrw
It should be more reliable way.
