### ISSUE TITLE
No way to copy selected text ?

### ISSUE THREAD

**Issue by lux-lth** [pywinauto/pywinauto#506]
Hello,

Kudos for the great job !

I've got some issues though :

Using pywinauto I navigate to an input text.
Using type_keys (^a^c) I can select the text, and copy it to the clipboard (I can paste it using ctrl+v manually).
But there doesn't seem to be a way to retrieve it programmatically.
Or am I mistaken ?

In the doc there is a mention to pywinauto.clipboard, but it doesn't work at all for me :

```
>python -m pip install pywinauto --upgrade
Requirement already up-to-date: pywinauto in python\python36\lib\site-packages (0.6.4)
...

>python
Python 3.6.0a1 (v3.6.0a1:5896da372fb0, May 17 2016, 16:21:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywinauto
>>> pywinauto.clipboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pywinauto' has no attribute 'clipboard'
```

Any help would be much appreciated, thank you for your time.

**Comment by lux-lth** [comment]
Found a workaround copying the text in notepad.exe, saving it, and reading the file from python...

**Comment by badari412** [comment]
@vasily-v-ryabov  How about the approach mentioned [here](https://stackoverflow.com/a/101167/7433942) ?

**Comment by vasily-v-ryabov** [comment]
@badari412 nothing new. I had no time for higher priority issues than this. Also this approach is incomplete, because waiting some lock is required (this is not implemented now).

**Comment by Bipin-Kalakheti** [comment]
I would like to work on this issue.

**Comment by yuval728** [comment]
Hey! I'd love to work on this as a first-time contributor. Is this task still available?
