### ISSUE TITLE
ClickInput error

### ISSUE THREAD

**Issue by JohnS-BCS** [pywinauto/pywinauto#516]
I am using pywinauto with python 2.7 to automate software installs for testing. We use InstallShield for most of the install and pywinauto does great. Towards the end of the install process, InstallShield kicks off setup items that run in a separate msiexec process.  The problem is I need to click some buttons but cant access the buttons on these. 

here is a portion of the code 

```
app = Application().Connect(title=u'MARVLIS Installation', class_name='#32770')
window = app.Dialog
window.SetFocus()

b = window['OK']
b.SetFocus()
b.DrawOutline('red')
b.ClickInput()
```
When i run this code most of pywinauto works on the button (like setfocus and drawoutline) but click and clickinput do not. here is the error:

```
Traceback (most recent call last):
  File "C:/Test/projects/marvlistest/installhelper/trial.py", line 17, in <module>
    b.ClickInput()
  File "C:\Test\projects\marvlistest\venv\lib\site-packages\pywinauto\base_wrapper.py", line 685, in click_input
    key_down=key_down, key_up=key_up)
  File "C:\Test\projects\marvlistest\venv\lib\site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
    win32api.SetCursorPos((coords[0], coords[1]))
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')
```
Thanks ! 

PS. I am running this as Administrator login in an IDE and have also tried in a CMD started with Run As Administrator

**Comment by JohnS-BCS** [comment]
control identifiers

```
Dialog - 'MARVLIS Installation'    (L13, T13, R483, B175)
[u'MARVLIS Installation', u'Dialog', u'MARVLIS InstallationDialog']
child_window(title="MARVLIS Installation", class_name="#32770")
   | 
   | Button - 'OK'    (L275, T135, R363, B161)
   | [u'OK', u'OKButton', u'Button', u'Button1', u'Button0']
   | child_window(title="OK", class_name="Button")
   | 
   | Button - 'Cancel'    (L371, T135, R459, B161)
   | [u'Button2', u'Cancel', u'CancelButton']
   | child_window(title="Cancel", class_name="Button")
   | 
   | Static - ''    (L41, T65, R73, B97)
   | [u'Static1', u'Static0', u'Static', u'MARVLIS InstallationStatic']
   | child_window(class_name="Static")
   | 
   | Static - 'Please run all appropriate database scripts. Press Cancel to abort the installation.'    (L81, T65, R443, B97)
   | [u'Static2', u'Please run all appropriate database scripts. Press Cancel to abort the installation.', u'Please run all appropriate database scripts. Press Cancel to abort the installation.Static']
   | child_window(title="Please run all appropriate database scripts. Press Cancel to abort the installation.", class_name="Static")
```

**Comment by vasily-v-ryabov** [comment]
Hi @JohnS-BCS sorry for late response. Usually `SetCursorPos` fails in 2 cases:
 1. Windows Security Confirmation dialog is active (it can't be automated by OS design) or PC is locked.
 2. Target application process has higher privileges than Python process with pywinauto.

For the second case I've implemented privilege checks, but it's not released yet. Can you try install pywinauto from master branch and try your case one more time?

```
pip uninstall pywinauto -y
pip install https://github.com/pywinauto/pywinauto/archive/master.zip
```

**Comment by JohnS-BCS** [comment]
Thanks, @vasily-v-ryabov! I will give it a try in the next few days and let you know.

**Comment by JohnS-BCS** [comment]
I was able to look at it today and here are the results

```
C:\tmp\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevconsole.py" 50132 50133
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Test\\projects\\marvlistest', 'C:/Test/projects/marvlistest'])
PyDev console: starting.
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
from pywinauto import Application 
db = Application().Connect(title=u'MARVLIS Installation', class_name='#32770')
win = db.Dialog
win.SetFocus()
win.DrawOutline('red')
b = win['OK']
b.SetFocus()
b.DrawOutline('blue')
b.click_input()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\tmp\venv\lib\site-packages\pywinauto\base_wrapper.py", line 673, in click_input
    self._ensure_enough_privileges('win32api.SetCursorPos(x, y)')
  File "C:\tmp\venv\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 460, in _ensure_enough_privileges
    '(to resolve it run the script as Administrator)'.format(message_name))
RuntimeError: Not enough rights to use win32api.SetCursorPos(x, y) message/function for target process (to resolve it run the script as Administrator)
b.click()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\tmp\venv\lib\site-packages\pywinauto\controls\win32_controls.py", line 219, in click
    hwndwrapper.HwndWrapper.click(self, *args, **kwargs)
  File "C:\tmp\venv\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 748, in click
    self._ensure_enough_privileges('WM_*BUTTONDOWN/UP')
  File "C:\tmp\venv\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 460, in _ensure_enough_privileges
    '(to resolve it run the script as Administrator)'.format(message_name))
RuntimeError: Not enough rights to use WM_*BUTTONDOWN/UP message/function for target process (to resolve it run the script as Administrator)
win.DrawOutline('blue')
b.DrawOutline('blue')
```
As I stated earlier I am running as Administrator and have tried in both IDE and CMD. For me the challenge is the way our subinstall packages run as SYSTEM. 

![image](https://user-images.githubusercontent.com/16564985/42697492-3f694a9a-8689-11e8-8a15-64b8fcab03ba.png)

I have can see no way around this so I am working on a different workflow in my tests.

I will continue to use this build for a bit of time and see how it does with the rest of my tests. 

Thanks 
John

**Comment by vasily-v-ryabov** [comment]
This is interesting. Maybe some separate script could be run as SYSTEM as well.

What is the output of `import ctypes; print(ctypes.windll.shell32.IsUserAnAdmin())` ?

**Comment by JohnS-BCS** [comment]
one more note on the permission 

DrawOutline('red') give this warning 

`*C:\tmp\venv\lib\site-packages\pywinauto\application.py:975: UserWarning: Python process has no rights to make changes in the target GUI (run the script as Administrator)`

but that command does work and does outline the button

you may want to change the warning

**Comment by vasily-v-ryabov** [comment]
This warning comes from `Application().connect(...)` and it is more general than blocking errors for particular commands. `.draw_outline()` doesn't change anything, it just creates drawing context without any connection with the target process: it uses `.rectangle()` method only which provides read-only access again.

**Comment by JohnS-BCS** [comment]
I embellished the print start and the results:

`  print('Is user admin {}'.format(ctypes.windll.shell32.IsUserAnAdmin()))`

> Is user admin 1

**Comment by vasily-v-ryabov** [comment]
By the way, `pywinauto==0.6.5` is out with mentioned changes + some more fixes. Is this problem still actual?

**Comment by JohnS-BCS** [comment]
I am now using 0.6.5 and still seem same basic access issue. I changed the code to remove the outline and focus and here are the results

```
 File "C:/Test/projects/marvlistest/installhelper/serverinstaller.py", line 162, in __install
    b.click_input()
  File "C:\Test\projects\marvlistest\venv32\lib\site-packages\pywinauto\base_wrapper.py", line 685, in click_input
    self._ensure_enough_privileges('win32api.SetCursorPos(x, y)')
  File "C:\Test\projects\marvlistest\venv32\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 461, in _ensure_enough_privileges
    '(to resolve it run the script as Administrator)'.format(message_name))
RuntimeError: Not enough rights to use win32api.SetCursorPos(x, y) message/function for target process (to resolve it run the script as Administrator)
```
and 

> Is user admin 1

We have updated our installers so i can bypass this issue. The dialogs in question I run post install and this works for me.
