### ISSUE TITLE
How to click on Objects that are not listed in Control Identifier?

### ISSUE THREAD

**Issue by pvase666** [pywinauto/pywinauto#520]
Hi there, I am new with Pywinauto. I am trying to do some things with my Application called iCUE. 
I have listed all objects in this program by using print_control_identifier(). The result:
```
Control Identifiers:

Dialog - 'iCUE'    (L0, T0, R1280, B680)
['Dialog', 'iCUEDialog', 'iCUE', 'Dialog0', 'Dialog1']
child_window(title="iCUE", control_type="Window")
   | 
   | Dialog - ''    (L0, T0, R1280, B680)
   | ['Dialog2', '', '0', '1', '00', '01']
   |    | 
   |    | Edit - ''    (L26, T156, R276, B184)
   |    | ['2', 'Edit', 'Edit0', 'Edit1']
   |    |    | 
   |    |    | Static - 'Type profile name'    (L32, T158, R270, B182)
   |    |    | ['Type profile nameStatic', 'Static', 'Type profile name', 'Static0', 'Static1']
   |    |    | child_window(title="Type profile name", control_type="Text")
   |    | 
   |    | Button - ''    (L0, T0, R0, B0)
   |    | ['3', 'Button', 'Button0', 'Button1']
   |    | 
   |    | Button - ''    (L252, T162, R268, B177)
   |    | ['4', 'Button2']
   |    | 
   |    | ScrollBar - ''    (L0, T0, R0, B0)
   |    | ['5', 'ScrollBar', 'ScrollBar0', 'ScrollBar1']
   |    | 
   |    | ScrollBar - ''    (L0, T0, R0, B0)
   |    | ['5', 'ScrollBar', 'ScrollBar0', 'ScrollBar1']
   |    | 
   |    | Edit - ''    (L0, T0, R0, B0)
   |    | ['7', 'Edit2']
   |    | 
   |    | Edit - ''    (L0, T0, R0, B0)
   |    | ['7', 'Edit2']
   |    | 
   |    | Edit - ''    (L0, T0, R0, B0)
   |    | ['7', 'Edit2']
   |    | 
   |    | StatusBar - ''    (L0, T0, R0, B0)
   |    | ['StatusBar', '10', 'StatusBar0', 'StatusBar1']
   |    | 
   |    | Button - ''    (L244, T50, R260, B65)
   |    | ['11', 'Button3']
   .....
   ......
```

The problem is some objects such as SETTINGS, HOME, DASHBOARD, INSTANT LIGHTING and "Default" on my screenshot are not included in this Control Identifiers.

My question is that how to control (click on) these objects ? Thank you !

My screenshot: https://i.imgur.com/VQUxHBL.png

Inspect screenshot, mouse position is on SETTINGS text: https://i.imgur.com/BtUOxV8.png

**Comment by vasily-v-ryabov** [comment]
Hi @pvase666 probably you've already reached me on Facebook. The answer is: these texts are self-drawn and can't be identified by pywinauto. I can recommend to try image recognition tool like [lackey](https://github.com/glitchassassin/lackey) that some guys use along with pywinauto. It might be a bit CPU intensive but at least it's better than nothing.
