### ISSUE TITLE
New implementation of set_focus

### ISSUE THREAD

**Issue by mchels** [pywinauto/pywinauto#521]
The current implementation of set_focus https://github.com/pywinauto/pywinauto/blob/7f43aca24815dfa217f232b358f0ae59d953e54e/pywinauto/controls/hwndwrapper.py#L1293 is non-ideal because it is slow (due to time.sleep calls) and because it moves the mouse cursor.

A different implementation exists which appears to solve both issues:
https://github.com/groboclown/petronia/blob/master/src/petronia/arch/funcs_any_win.py#L529

Assuming that this other implementation is not buggy in some way can it replace pywinauto's current implementation? I can do the PR.

(I should note that I am not the author of this other implementation)

**Comment by mchels** [comment]
Never mind, the other implementation is not flawless either. It's decent but fails to consistently switch focus between, e.g., two cmd windows. I'll look into Autohotkey's implemention which I've found to work consistently: https://github.com/AutoHotkey/AutoHotkey/blob/4b8aa248906771a3e25744683dd161ef53c7555a/Source/window.cpp#L23

**Comment by vasily-v-ryabov** [comment]
Hi @mchels I have plans to improve `set_focus` implementation in August. But I would be happy to review your code if you take this task. It's tracked in #443 currently.
