### ISSUE TITLE
Selecting Color from a Color pallete

### ISSUE THREAD

**Issue by madhavankumar** [pywinauto/pywinauto#522]
I have a Color Selection window as below.
![image](https://user-images.githubusercontent.com/5941859/43043165-e3565cd8-8d5a-11e8-9dd0-f114b3484ec4.png)

I use win32 backend
The properties from Swapy are as below - 
![image](https://user-images.githubusercontent.com/5941859/43043178-20f3cd00-8d5b-11e8-8e89-c4d4fb2e1744.png)

If i want to select a color, is there a way to do that.
Workaround so far is to use sendkeys to send arrow keys e.g. {UP} or {RIGHT} etc. Is there a direct way to select the color?

**Comment by vasily-v-ryabov** [comment]
Nope, I had the same problem on my previous job. The list of colors is a static control. I made simple class using some mapping between text name of the color and proportional coordinates based on size of this static control. `Inspect.exe` also can't recognize every small square with a color.

**Comment by madhavankumar** [comment]
Thank you @vasily-v-ryabov . Should we just close this as Works as Designed?

**Comment by vasily-v-ryabov** [comment]
Sure. There is nothing to do inside pywinauto.
