### ISSUE TITLE
Want to know dynamic coordinates of my desktop screen or a webbrowser without inspecting the elements

### ISSUE THREAD

**Issue by santhuu24** [pywinauto/pywinauto#528]
iam trying to find the dynamic coordinates of my desktop screen by finding the text not by using image
 plse help me with a code

**Comment by vasily-v-ryabov** [comment]
Hi @santhuu24 please read the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) first. Understanding the core concept (e.g. window specification and wrappers) is important to become productive enough with pywinauto.

Do you have any screenshots or pieces of code? Usual answer should look like this:
```python
app.window(title="Your Main Window Title").rectangle()
```
But if you have any specific troubles, please provide your error output (as full as possible).

**Comment by vasily-v-ryabov** [comment]
To get the top window titles:
```python
print([w.window_text() for w in app.windows()])
```

**Comment by santhuu24** [comment]
My mouse need to go to a particular position on my desktop by finding the text using python

**Comment by vasily-v-ryabov** [comment]
It doesn't add any details on the question. Please be concrete. If the question is "is it possible?", the answer is "yes, it is possible".

> iam trying to find the dynamic coordinates of my desktop screen by finding the text

What exactly did you try? What is the error message?

**Comment by vasily-v-ryabov** [comment]
Closing as no replies during a month. Please re-open if it's still relevant.
