### ISSUE TITLE
pywinauto 0.6.5 control_type missing

### ISSUE THREAD

**Issue by meshuggahtas** [pywinauto/pywinauto#537]
While automation_id is at the end of props list (for example output of pywinauto.controls.hwndwrapper.get_dialog_props_from_handle, having an empty value maybe because the app dev needs to fill it, relevant code: https://github.com/pywinauto/pywinauto/blob/960682d0abd7db4efb8e129e4599fd47a4b5e5bd/pywinauto/controls/hwndwrapper.py#L218), it doesn't have control_type value.

Also calling control_type (for example APP.MainForm.control_type()) returns an empty string. Code says https://github.com/pywinauto/pywinauto/blob/960682d0abd7db4efb8e129e4599fd47a4b5e5bd/pywinauto/controls/hwndwrapper.py#L259
Tried with Delphi Dialog, Button and TreeView.

**Relevant changelog:**

>  * Add ``automation_id`` and ``control_type`` properties
>    for "win32" backend (the most useful for WinForms). Correct
>    child_window() keywords are ``auto_id`` and ``control_type``.

**Short example output of pywinauto.controls.hwndwrapper.get_dialog_props_from_handle:**

{'class_name': 'TRCSiteConnectionLoginDialog', 'friendly_class_name': 'TRCSiteConnectionLoginDialog', 'texts': ['Login'], 'control_id': 0, 'rectangle': <RECT L765, T414, R1155, B666>, 'is_visible': True, 'is_enabled': True, 'control_count': 7, 'style': -1765801984, 'exstyle': 65793, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Segoe UI' -12>], 'client_rects': [<RECT L0, T0, R384, B223>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}

**Example output of pywinauto.controls.hwndwrapper.get_dialog_props_from_handle:**
[{'class_name': 'TRCSiteConnectionLoginDialog', 'friendly_class_name': 'TRCSiteConnectionLoginDialog', 'texts': ['Login'], 'control_id': 0, 'rectangle': <RECT L0, T0, R390, B252>, 'is_visible': True, 'is_enabled': True, 'control_count': 7, 'style': -1765801984, 'exstyle': 65793, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Segoe UI' -12>], 'client_rects': [<RECT L0, T0, R384, B223>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}, {'class_name': 'TEdit', 'friendly_class_name': 'Edit', 'texts': ['••••••••', '••••••••'], 'control_id': 1575506, 'rectangle': <RECT L122, T162, R292, B183>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409351904, 'exstyle': 512, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R166, B17>], 'is_unicode': True, 'menu_items': [], 'automation_id': '', 'selection_indices': (0, 0)}, {'class_name': 'TEdit', 'friendly_class_name': 'Edit', 'texts': ['administrator', 'administrator'], 'control_id': 2231114, 'rectangle': <RECT L122, T130, R292, B151>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409351872, 'exstyle': 512, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R166, B17>], 'is_unicode': True, 'menu_items': [], 'automation_id': '', 'selection_indices': (0, 0)}, {'class_name': 'TButton', 'friendly_class_name': 'Button', 'texts': ['&...'], 'control_id': 1772376, 'rectangle': <RECT L306, T90, R356, B111>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409351680, 'exstyle': 0, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R50, B21>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}, {'class_name': 'TsComboBox', 'friendly_class_name': 'ComboBox', 'texts': ['WS28 régi formos',^', '192.168.200.1 55540 szerverteszt2', 'A39 WS29', 'Intellio Demo Server', 'ws28 +1 formos', 'WS28 NEM FORMOS', 'WS28 régi formos'], 'control_id': 2688758, 'rectangle': <RECT L122, T90, R292, B111>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409352531, 'exstyle': 0, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R170, B21>], 'is_unicode': True, 'menu_items': [], 'automation_id': '', 'selected_index': 8, 'dropped_rect': <RECT L0, T0, R170, B158>}, {'class_name': 'TRCColorFooter', 'friendly_class_name': 'TRCColorFooter', 'texts': [''], 'control_id': 3737330, 'rectangle': <RECT L3, T212, R387, B249>, 'is_visible': True, 'is_enabled': True, 'control_count': 2, 'style': 1442840576, 'exstyle': 65536, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'MS Shell Dlg' -11>], 'client_rects': [<RECT L0, T0, R384, B37>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}, {'class_name': 'TJvFooterBtn', 'friendly_class_name': 'TJvFooterBtn', 'texts': ['Cancel'], 'control_id': 2296068, 'rectangle': <RECT L279, T219, R379, B242>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409359883, 'exstyle': 0, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R100, B23>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}, {'class_name': 'TJvFooterBtn', 'friendly_class_name': 'TJvFooterBtn', 'texts': ['Co&nnect'], 'control_id': 3409868, 'rectangle': <RECT L175, T219, R275, B242>, 'is_visible': True, 'is_enabled': True, 'control_count': 0, 'style': 1409359883, 'exstyle': 0, 'user_data': 0, 'context_help_id': 0, 'fonts': [<LOGFONTW 'Tahoma' -11>], 'client_rects': [<RECT L0, T0, R100, B23>], 'is_unicode': True, 'menu_items': [], 'automation_id': ''}]

**Comment by vasily-v-ryabov** [comment]
Not all applications support `control_type` through Win32 API. This is correctly mentioned that it's guaranteed to work with WinForms only. For standard Win32 controls like MFC, WTL etc it's expected to have empty strings.

Is your Delphi project using .NET controls? In other words, is it managed code or native Delphi form?

**Comment by meshuggahtas** [comment]
They are native Delphi controls, not related to .NET controls. VCL components like JEDI VCL https://github.com/project-jedi/jvcl

So I assume this works correctly and issue can be closed.
