### ISSUE TITLE
pywinauto 0.6.5 with Python 3.7 showing deprecation warnings from common_controls.py

### ISSUE THREAD

**Issue by AFewMistakesAgo** [pywinauto/pywinauto#539]
I recently upgraded pywinauto to test with Python 3.7 (previous setup was pywinauto 0.6.4 with Python 2,7). In this new setup I am seeing a large number of DeprecationWarnings being output to the terminal from ..\pywinauto\controls\common_controls.py.

e.g., 
```
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:776: DeprecationWarning: Method .ItemCount() is deprecated, use .item_count() instead.
  return self.get_header_control().ItemCount()
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:776: DeprecationWarning: Method .ItemCount() is deprecated, use .item_count() instead.
  return self.get_header_control().ItemCount()
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:179: DeprecationWarning: ListView item properties "text", "state", "image" and "indent" are deprecated! Use methods text(), state(), image() and indent().
  'Use methods text(), state(), image() and indent().', DeprecationWarning)
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:776: DeprecationWarning: Method .ItemCount() is deprecated, use .item_count() instead.
  return self.get_header_control().ItemCount()
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:179: DeprecationWarning: ListView item properties "text", "state", "image" and "indent" are deprecated! Use methods text(), state(), image() and indent().
  'Use methods text(), state(), image() and indent().', DeprecationWarning)
..\testPyWinAutoPython37\venvTestPython37\lib\site-packages\pywinauto\controls\common_controls.py:776: DeprecationWarning: Method .ItemCount() is deprecated, use .item_count() instead.
```

I've googled how to suppress these warnings, but none of the suggestions I've seen so far have worked (e.g., suggestions here [How to ignore deprecation warnings in Python](https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python))

Any advice on how to stop these warnings from being output to the terminal during run of scripts that use pywinauto?

**Comment by AFewMistakesAgo** [comment]
For what it's worth, an edit of line 776 of common_controls.py from:

`            return self.get_header_control().ItemCount()`

To:
`            return self.get_header_control().item_count()`

...appears to have fixed the issue at my end.

**Comment by vasily-v-ryabov** [comment]
Good catch! I'll consider this as a high priority for next update release.

This workaround should disable warnings:
```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
```
If it doesn't help, you may need to clear all filters by `warnings.resetwarnings()` and then apply ignore filter.

**Comment by vasily-v-ryabov** [comment]
Already fixed by @CodyDeGhetto in #565 and #569.

**Comment by vasily-v-ryabov** [comment]
BTW, warning at `common_controls.py:179` is relevant. Can be fixed by changing `.text` by `.text()` etc.

**Comment by parlar** [comment]
Getting the same warnings under python 3.6

using latest pywinauto v.0.6.5 available from pip

**Comment by vasily-v-ryabov** [comment]
@parlar any more details? Code sample + traceback would be very helpful.

If you're using `CamelCase` methods in your code, the warnings are correct: just use `pep8_stype` methods. If not, please provide the traceback.

**Comment by airelil** [comment]
BTW, we recently made additional clean ups in commaon_controls.py (see rev: 3b66563b05be9f3061a8be33ef00f0019ed12567). @parlar , you could check it with the current sources from the trunk.
