### ISSUE TITLE
Tab can't switch when using Select of TabControlWrapper

### ISSUE THREAD

**Issue by sjhspp** [pywinauto/pywinauto#54]
Hi~
At first, thank you~
I am using Select of TabControlWrapper, and I want to use the index of tab to switch the tab. but I had this problem.
The default selected index of tab is 0, and I write this "Select(1)" to switch the tab of 1, but it doesn't work, the result is, 0 and 1 are both selected, no other changes. After this, if I write "Select(0)",  tab 1 will be up. All options of these, the content of page never changed.
I am wondering if I had missed something...
Thank you again!

**Comment by vasily-v-ryabov** [comment]
Hi, I need to clarify some things.

>  the result is, 0 and 1 are both selected

How is it possible? Sorry, this statement is not clear to me. After you called `Select(1)` only one tab should be selected (if it's 0 - method doesn't work, if 1 - it works).

Could you please provide code snippet?

**Comment by sjhspp** [comment]
Hi~
thanks a lot for your reply!
I have tried your sample CmnCtrl1.exe, it worked very well. My test sample is developed by C#, now I wonder if pywinauto doesn't support C# ？
My code and result:

```python
app = application.Application.start(os.path.join(sample_folder, u"WFCarControl.exe"))
dianame = u"模拟器上位机"
tabc = app[dianame].TabControl.WrapperObject()
tabc.Select(1)
```
![1](https://cloud.githubusercontent.com/assets/1592742/8747578/04565c8c-2cc7-11e5-8964-6b467567b88c.png)

**Comment by vasily-v-ryabov** [comment]
OK, one more question. Is your app compiled with "Multi byte character set" option in project properties? or "Unicode character set"?

**Comment by vasily-v-ryabov** [comment]
It seems the root cause is found. Method `TabControlWrapper.Select()` sends `TCM_SETCURFOCUS` message instead of [TCM_SETCURSEL](https://msdn.microsoft.com/en-us/library/bb760612(VS.85).aspx). We will test and probably push it as soon as possible (at the beginning of August). You may try to replace `TCM_SETCURFOCUS` with `TCM_SETCURSEL` in `common_controls.py`. Please let us know if it works. Thanks for the use case!

P.S. Pull request is another good option. ;)

**Comment by sjhspp** [comment]
Hi~Thanks a lot ~
Sorry, I am not very clearly with the compile of app, but I think it should be unicode...
I have tried this:
```
 replace TCM_SETCURFOCUS with TCM_SETCURSEL in common_controls.py.
```
The result is, after "Select(1)", tab 1 is selected, and tab 0 is up, this is right, but the content doesn't change. 
default:
![3](https://cloud.githubusercontent.com/assets/1592742/8760069/881c1fde-2d3a-11e5-9d39-8fc2e06779c6.png)

after Select(1):
![2](https://cloud.githubusercontent.com/assets/1592742/8760037/2fc0ba70-2d3a-11e5-8cc8-b4ffa155f576.png)

Thank you again ~

**Comment by vasily-v-ryabov** [comment]
OK, I will take a look deeper into this case when I come back.
pywinauto is not very well tested on WinForms applications so I can say about partial support only.

**Comment by sjhspp** [comment]
Thanks a lot again!
I will try other ways to solve my question, if you have any progress about this question, please tell me, I will always focus on it :)

**Comment by vasily-v-ryabov** [comment]
Hmm... I tried to automate the following WinForms demo with TabControl: http://www.codeproject.com/Articles/34164/WinForms-Tab-Control-with-properly-drawn-bottom-ta

pywinauto switches tabs correctly. Probably your case is more specific. If you were able to create simple app with similar behavior and attach it, it would be very helpful. Thanks!

**Comment by vasily-v-ryabov** [comment]
I could reproduce the problem with `Behavior.Appearance = Buttons` property on simple app.

**Comment by vasily-v-ryabov** [comment]
TCS_BUTTONS style produces very specific behavior. Documentation for TCM_SETCURFOCUS message has some remarks about that:

> If the tab control has the TCS_BUTTONS style (button mode), the tab with the focus may be different from the selected tab. For example, when a tab is selected, the user can press the arrow keys to set the focus to a different tab without changing the selected tab. In button mode, TCM_SETCURFOCUS sets the input focus to the button associated with the specified tab, but it does not change the selected tab.

But using TCM_SETCURSEL doesn't help. Tab content is not re-drawn properly. Currently I made workaround by sending WM_CLICK to corresponding tab rectangle. I hope other solution will be found later.

Please download the latest repo and check if it works for you.

**Comment by manojkukna** [comment]
TabControlWrapper
