### ISSUE TITLE
readthedocs empty pages

### ISSUE THREAD

**Issue by meshuggahtas** [pywinauto/pywinauto#541]
Some pages are empty in the documentation. Already experienced this when reading 0.6.4 but had to switch to stable or latest at that time. Now I need to select a previous version to read it.

**Same page but different revisions:**
https://pywinauto.readthedocs.io/en/0.6.5/code/pywinauto.findwindows.html
https://pywinauto.readthedocs.io/en/stable/code/pywinauto.findwindows.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.findwindows.html

**Same page in previous version with content:**
https://pywinauto.readthedocs.io/en/0.6.4/code/pywinauto.findwindows.html

**Comment by vasily-v-ryabov** [comment]
Good catch! Thanks! It looks like some requirements for docs have been updated. I'll try to pin them to previous version(s).

**Comment by meshuggahtas** [comment]
**Remaning empty pages without content in latest 0.6.5:**
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.xml_helpers.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.hooks.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.hwndwrapper.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.menuwrapper.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.common_controls.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.win32_controls.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.findwindows.html
https://pywinauto.readthedocs.io/en/latest/code/pywinauto.application.html

**Comment by vasily-v-ryabov** [comment]
Hi @meshuggahtas PR #578 should fix all the reported issues with empty pages and some more. Please review.

**Comment by meshuggahtas** [comment]
All the pages on https://pywinauto-fork.readthedocs.io/en/docs_fixes/ are working, thank you :)

Feel free to close the issue.

**Comment by vasily-v-ryabov** [comment]
Thanks! There was no need to close. It was closed automatically. Now in master branch.
