### ISSUE TITLE
Problem with datePicker

### ISSUE THREAD

**Issue by furby-eb** [pywinauto/pywinauto#548]
In the application I need to click through with pywinauto, I have the Date Picker, which looks in the interface just like drop down box, which is empty on default, when you click the drop-down arrow, then calendar is showing up and you can select the date.

The controls detected by pywinauto look like this:
  ```
 |    |    |    |    |    | Pane - 'gcDateAndTime'    (L230, T239, R615, B425)
 |    |    |    |    |    | ['gcDateAndTime', 'gcDateAndTimePane', 'Pane19']
 |    |    |    |    |    | child_window(title="gcDateAndTime", auto_id="gcDateAndTime", control_type="Pane")
 |    |    |    |    |    |    | 
 |    |    |    |    |    |    | Pane - ''    (L232, T260, R613, B423)
 |    |    |    |    |    |    | ['10', 'Pane20']
 |    |    |    |    |    |    | child_window(auto_id="searchDateAndTimeControl1", control_type="Pane")
 |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    | Pane - ''    (L417, T279, R502, B299)
 |    |    |    |    |    |    |    | ['11', 'Pane21']
 |    |    |    |    |    |    |    | child_window(auto_id="datePickerTo", control_type="Pane")
 |    |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    |    | Pane - ''    (L421, T282, R482, B296)
 |    |    |    |    |    |    |    |    | ['12', 'Pane22']
 |    |    |    |    |    |    |    |    | child_window(auto_id="4720152", control_type="Pane")
 |    |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    |    | Custom - ''    (L421, T282, R482, B296)
 |    |    |    |    |    |    |    |    | ['13', 'Custom29']
 |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    | Pane - ''    (L320, T279, R405, B299)
 |    |    |    |    |    |    |    | ['14', 'Pane23']
 |    |    |    |    |    |    |    | child_window(auto_id="datePickerFrom", control_type="Pane")
 |    |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    |    | Pane - ''    (L324, T282, R385, B296)
 |    |    |    |    |    |    |    |    | ['15', 'Pane24']
 |    |    |    |    |    |    |    |    | child_window(auto_id="5112538", control_type="Pane")
 |    |    |    |    |    |    |    |    | 
 |    |    |    |    |    |    |    |    | Custom - ''    (L324, T282, R385, B296)
 |    |    |    |    |    |    |    |    | ['16', 'Custom30']`
```
Also in inspect.exe it looks strange for me. All 3 of the components (for example datePickerFrom and his children), have LegacyAccesible.Name and LegacyAccessible.Value set on "Friday, August 17, 2018" (today), and all of them have role "drop down", and state "focused,focusable". Poping up the Calendar doesn't seem to be noticed by inspect.exe. When I set the date, the values and names are changed for the components.

Is it normal that it looks like this, or it seems like a problem with access to the component? I am newbie to pywinauto, but I feel like some components are missing here.
I tried to use methods click/click_input/invoke/set_text on these components (datePickerFrom/To and their children), but nothing works. Is it possible to select the date with pywinauto in this case?

I'm using backend="uia", pywinauto ver.0.6.5, python 3.7.0
Please advice me something.

Thank you!

**Comment by vasily-v-ryabov** [comment]
Looks like `DateTimePickerWrapper` is not implemented in UIA backend. And this particular control is detected as Pane anyway. But if this control has `NativeWindowHandle` property in `Inspect.exe`, it's possible to re-use wrapper from "win32" backend (at least try this). This should look so:
```python
from pywinauto.controls.common_controls import DateTimePickerWrapper

dateTimeFrom_win32 = DateTimePickerWrapper(dateTimeFrom_wrapper.handle)
dateTimeFrom_win32.set_time(year=2017, month=5, day=23) # if it's date only control (or see full params list)
```

**Comment by vasily-v-ryabov** [comment]
To choose proper element for creating "win32" wrapper it's useful to make sure `ClassName` property looks like `"DateTimePicker"` or `"SysDateTimePick32"`.

**Comment by furby-eb** [comment]
Thank you for your reply. Unfortunately it doesn't work for me (RuntimeError: "Failed to set time in Date Time Picker"). Also none of the classes is named like DateTimePicker, but I was trying to set it on 2 wrappers that should be DateTimePicker according to me.

I guess that there is no other workaround for this?

**Comment by furby-eb** [comment]
I found the workaround, type_keys method is working for me. Thank you for your support!

**Comment by vasily-v-ryabov** [comment]
OK, since it's custom control, I think we need to qualify this issue as question. Currently it's impossible to support custom controls without app side implementation or workaround like yours. Thanks for update.

**Comment by jrgdiaz** [comment]
> Looks like `DateTimePickerWrapper` is not implemented in UIA backend. And this particular control is detected as Pane anyway. But if this control has `NativeWindowHandle` property in `Inspect.exe`, it's possible to re-use wrapper from "win32" backend (at least try this). This should look so:
> 
> ```python
> from pywinauto.controls.common_controls import DateTimePickerWrapper
> 
> dateTimeFrom_win32 = DateTimePickerWrapper(dateTimeFrom_wrapper.handle)
> dateTimeFrom_win32.set_time(year=2017, month=5, day=23) # if it's date only control (or see full params list)
> ```

Hello, sorry to comment on this closed issue, i was struggling with this same problem and successfully tried this method. So just wanted to say that re-using win32 backend worked for me in the end.

**Comment by walkmiao** [comment]
> I found the workaround, type_keys method is working for me. Thank you for your support!我找到了解决方法，type_keys方法对我有用。感谢您的支持！

Can you provide the code, I'm having the same issue. At first I tried to use DateTimePickerWrapper to set the date, and it did, but the query did not succeed. I had to manually select the date to get it right, and then I tried type_keys and it got me to type, but the year, month, and day were always confused
