### ISSUE TITLE
Pywinauto to copy dates or text from the screen to clipboard > then csv file

### ISSUE THREAD

**Issue by volksmania** [pywinauto/pywinauto#551]
I have a question. I want to to be able to scrape from the command prompt window (add it to clipboard) to transfer to csv file. 

![image](https://user-images.githubusercontent.com/42187688/44480865-96347b00-a601-11e8-8be3-f64d539565f9.png)

could someone tell me what module (if any) I could use to accomplish this?

thanks
Volks

**Comment by volksmania** [comment]
additionally, my set up is as follow
pywinauto 0.6.5
Python 3.5.1
Pycharm IDE

**Comment by vasily-v-ryabov** [comment]
Hi @volksmania technically it's possible using Windows Console API, but it's not implemented in pywinauto. We consider it as low priority because it's not GUI. Points to appropriate functions can be found in issue #492. So closing this as duplicate.

**Comment by vasily-v-ryabov** [comment]
But anyway this functionality is not needed for many simple cases. If you need to run some command and get its output, just use built-in module `subprocess`. The most useful functions are `subprocess.call(...)`, `subprocess.check_call(...)` and `subprocess.check_output(...)`.

**Comment by volksmania** [comment]
thank you for offering some ideas, Vasily. Rgds, Volks
