### ISSUE TITLE
How to change the control identifier value?

### ISSUE THREAD

**Issue by bsateeja** [pywinauto/pywinauto#554]
I have 5 controls on the application with same properties as
child_window(title="Characteristic", control_type="Hyperlink")
They can be identified by using Pywinauto control identifiers which are CharacteristicHyperlink1, CharacteristicHyperlink2 and so on till CharacteristicHyperlink5

I want to write a generic method to click on the characteristic by modifying CharacteristicHyperlink with the characteristic number (char_number) 
When doing identifier_name = "CharacteristicHyperlink" + str(char_number)
identifier_name gets converted to type string. How can i convert it to handle and use it?

Please help.
Thank you.

**Comment by bsateeja** [comment]
I am using these statements:
print(identifier_name)

    dlg.identifier_name.draw_outline()

And get this error:
CharacteristicHyperlink1
Traceback (most recent call last):
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\timings.py", line 449, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/SA-21/StudioAutomationTesting/studio_auto/nlr/nlr_testcases/SA-21.py", line 79, in <module>
    nlr_configure_characteristic(SA_name, dlg, 1, "HelpURL", "String", "")
  File "C:\SA-21\StudioAutomationTesting\studio_auto\nlr\nlr_helper\nlr_helper.py", line 71, in nlr_configure_characteristic
    dlg.identifier_name.draw_outline()
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 351, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\timings.py", line 427, in wait_until_passes
    func_val = func(*args)
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\findwindows.py", line 300, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\bsateeja\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'identifier_name' in 'dict_keys(['', 'Pane', '0', '1', '2', 'Pane0', 'Pane1', 'Pane2', '3', 'Pane3', 'SA-21Pane', 'Pane4', 'SA-21', 'SA-21Pane0', 'SA-21Pane1', 'SA-21Pane2', 'Pane5', 'SA-210', 'SA-211', 'SA-212', '4', 'Pane6', '5', 'Pane7', '6', 'Pane8', 'Static', 'Compared ValuesStatic', 'Compared Values', 'false', 'falsePane', 'Pane9', 'false0', 'false1', 'false2', 'falsePane0', 'falsePane1', 'falsePane2', 'Pane10', 'false3', 'falsePane3', 'Pane11', '7', 'Pane12', '8', 'ComboBox', 'OpenButton', 'Open', 'Button', 'Static0', 'Static1', 'Static2', 'of the following rules:Static', 'of the following rules:', '9', 'of the following rules:Pane', 'Pane13', '10', 'Pane14', '11', 'Pane15', 'Expression', 'Pane16', 'ExpressionPane', 'Static3', 'Characteristic', 'CharacteristicStatic', 'CharacteristicHyperlink', 'Characteristic0', 'Characteristic1', 'Characteristic2', 'Hyperlink', 'Expression0', 'Expression1', 'Expression2', 'Static4', 'ExpressionStatic', 'Expression3', 'ExpressionHyperlink', 'Hyperlink0', 'Hyperlink1', 'Hyperlink2', '12', 'Pane17', '13', 'Pane18', 'Expression4', 'Pane19', 'ExpressionPane0', 'ExpressionPane1', 'ExpressionPane2', 'Static5', 'Characteristic3', 'CharacteristicStatic0', 'CharacteristicStatic1', 'CharacteristicStatic2', 'CharacteristicHyperlink0', '**CharacteristicHyperlink1'**, 'CharacteristicHyperlink2', 'Characteristic4', 'Hyperlink3', 'Expression5', 'Static6', 'ExpressionStatic0', 'ExpressionStatic1', 'ExpressionStatic2', 'Expression6', 'ExpressionHyperlink0', 'ExpressionHyperlink1', 'ExpressionHyperlink2', 'Hyperlink4', '14', 'Pane20', '15', 'Pane21', 'Expression7', 'Pane22', 'ExpressionPane3', 'Static7', 'Characteristic5', 'CharacteristicStatic3', 'CharacteristicHyperlink3', 'Characteristic6', 'Hyperlink5', 'Expression8', 'Static8', 'ExpressionStatic3', 'Expression9', 'ExpressionHyperlink3', 'Hyperlink6', '16', 'Pane23', '17', 'Pane24', 'Expression10', 'Pane25', 'ExpressionPane4', 'Static9', 'Characteristic7', 'CharacteristicStatic4', 'CharacteristicHyperlink4', 'Characteristic8', 'Hyperlink7', 'Expression11', 'Static10', 'ExpressionStatic4', 'Expression12', 'ExpressionHyperlink4', 'Hyperlink8', '18', 'Pane26', '19', 'Pane27', 'Expression13', 'Pane28', 'ExpressionPane5', 'Static11', 'Characteristic9', 'CharacteristicStatic5', 'CharacteristicHyperlink5', 'Characteristic10', 'Hyperlink9', 'Expression14', 'Static12', 'ExpressionStatic5', 'Expression15', 'ExpressionHyperlink5', 'Hyperlink10', 'Static13', 'If...Static', 'If...', 'Compared ValuesPane', 'Pane29', 'Compared Values0', 'Compared Values1', 'Compared Values2', 'Static14', 'Then...Static', 'Then...', 'Then...Pane', 'Pane30', 'Then...0', 'Then...1', 'Then...2', 'Static15', 'returnStatic', 'return', 'Static16', 'true', 'trueStatic', 'otherwise returnStatic', 'Static17', 'otherwise return', 'false4', 'Static18', 'falseStatic', 'Table', 'DataGridView', 'DataGridViewTable', '20', 'Pane31', '21', 'Pane32', '22', 'Pane33', 'RuleButton', 'Rule', 'Button0', 'Button1', 'Button2', 'DefsButton', 'Defs', 'Button3', 'InfoButton', 'Info', 'Button4', 'Test Cases', 'Test CasesButton', 'Button5', '23', 'Pane34', 'Static19', 'first_config: /Business Logic', 'first_config: /Business LogicStatic', 'first_config: /Business Logic0', 'first_config: /Business Logic1', 'first_config: /Business Logic2', 'first_config: /Business LogicHyperlink', 'Hyperlink11', '24', 'Pane35', '25', 'Pane36', '26', 'Pane37', 'Test Jobs', 'Test JobsPane', 'Pane38', 'Test Jobs0', 'Test Jobs1', 'Test Jobs2', 'Test JobsPane0', 'Test JobsPane1', 'Test JobsPane2', 'Pane39', 'Table0', 'Table1', 'Table2', 'DataGridView0', 'DataGridView1', 'DataGridView2', 'DataGridViewTable0', 'DataGridViewTable1', 'DataGridViewTable2', 'Top RowCustom', 'Custom', 'Top Row', '27', 'Header', 'Header0', 'Header1', 'Header2', 'JobHeader', 'Job', 'StatusHeader', 'Header3', 'Status', 'StartedHeader', 'Started', 'Header4', 'Elapsed', 'ElapsedHeader', 'Header5', 'DetailsHeader', 'Details', 'Header6', '28', 'Header7', 'Row 0Custom', 'Custom0', 'Custom1', 'Custom2', 'Row 0', ' Row 0DataItem', 'DataItem', ' Row 0', 'Job Row 0DataItem', 'DataItem0', 'DataItem1', 'DataItem2', 'Job Row 0', 'Status Row 0DataItem', 'DataItem3', 'Status Row 0', 'Started Row 0DataItem', 'DataItem4', 'Started Row 0', 'DataItem5', 'Elapsed Row 0', 'Elapsed Row 0DataItem', 'DataItem6', 'Details Row 0DataItem', 'Details Row 0', ' Row 0DataItem0', ' Row 0DataItem1', ' Row 0DataItem2', 'DataItem7', ' Row 00', ' Row 01', ' Row 02', '29', 'Pane40', 'Table3', 'DataGridView3', 'DataGridViewTable3', 'Top RowCustom0', 'Top RowCustom1', 'Top RowCustom2', 'Custom3', 'Top Row0', 'Top Row1', 'Top Row2', '30', 'Header8', 'Header9', 'JobHeader0', 'JobHeader1', 'JobHeader2', 'Job0', 'Job1', 'Job2', 'StatusHeader0', 'StatusHeader1', 'StatusHeader2', 'Header10', 'Status0', 'Status1', 'Status2', 'StartedHeader0', 'StartedHeader1', 'StartedHeader2', 'Started0', 'Started1', 'Started2', 'Header11', 'Elapsed0', 'Elapsed1', 'Elapsed2', 'ElapsedHeader0', 'ElapsedHeader1', 'ElapsedHeader2', 'Header12', 'DetailsHeader0', 'DetailsHeader1', 'DetailsHeader2', 'Details0', 'Details1', 'Details2', 'Header13', '31', 'Header14', 'Row 0Custom0', 'Row 0Custom1', 'Row 0Custom2', 'Custom4', 'Row 00', 'Row 01', 'Row 02', ' Row 0DataItem3', 'DataItem8', ' Row 03', 'Job Row 0DataItem0', 'Job Row 0DataItem1', 'Job Row 0DataItem2', 'DataItem9', 'Job Row 00', 'Job Row 01', 'Job Row 02', 'Status Row 0DataItem0', 'Status Row 0DataItem1', 'Status Row 0DataItem2', 'DataItem10', 'Status Row 00', 'Status Row 01', 'Status Row 02', 'Started Row 0DataItem0', 'Started Row 0DataItem1', 'Started Row 0DataItem2', 'DataItem11', 'Started Row 00', 'Started Row 01', 'Started Row 02', 'DataItem12', 'Elapsed Row 00', 'Elapsed Row 01', 'Elapsed Row 02', 'Elapsed Row 0DataItem0', 'Elapsed Row 0DataItem1', 'Elapsed Row 0DataItem2', 'DataItem13', 'Details Row 0DataItem0', 'Details Row 0DataItem1', 'Details Row 0DataItem2', 'Details Row 00', 'Details Row 01', 'Details Row 02', ' Row 0DataItem4', 'DataItem14', ' Row 04', '32', 'Pane41', '33', 'Pane42', 'Configuration Browser', 'Configuration BrowserPane', 'Pane43', 'Configuration Browser0', 'Configuration Browser1', 'Configuration Browser2', 'Configuration BrowserPane0', 'Configuration BrowserPane1', 'Configuration BrowserPane2', 'Pane44', '34', 'Pane45', '35', 'Pane46', '36', 'TreeView', 'Vertical', 'ScrollBar', 'VerticalScrollBar', 'Line up', 'Line upButton', 'Button6', 'Page up', 'Page upButton', 'Button7', 'Position', 'PositionThumb', 'Thumb', 'Page downButton', 'Page down', 'Button8', 'Line down', 'Button9', 'Line downButton', 'EventsTreeItem', 'TreeItem', 'Events', '2Dimensional Table', 'TreeItem0', 'TreeItem1', 'TreeItem2', '2Dimensional TableTreeItem', 'AdaptorTreeItem', 'TreeItem3', 'Adaptor', 'TreeItem4', 'Champion Challenger', 'Champion ChallengerTreeItem', 'Columnar Table', 'TreeItem5', 'Columnar TableTreeItem', 'Natural Language RuleTreeItem', 'TreeItem6', 'Natural Language Rule', 'NDimensional TableTreeItem', 'TreeItem7', 'NDimensional Table', 'TreeItem8', 'Node ListTreeItem', 'Node List', 'ProcessTreeItem', 'TreeItem9', 'Process', 'ProvenirTreeItem', 'TreeItem10', 'Provenir', 'TreeItem11', 'provenirAfterRunTreeItem', 'provenirAfterRun', 'provenirBeforeRunTreeItem', 'TreeItem12', 'provenirBeforeRun', 'TreeItem13', 'provenirInitializeTreeItem', 'provenirInitialize', 'provenirTerminateTreeItem', 'TreeItem14', 'provenirTerminate', 'provenirTransactionID', 'TreeItem15', 'provenirTransactionIDTreeItem', 'ScorecardTreeItem', 'TreeItem16', 'Scorecard', 'ScriptTreeItem', 'TreeItem17', 'Script', 'TreeItem18', 'Visual RuleTreeItem', 'Visual Rule', 'WorkflowTreeItem', 'TreeItem19', 'Workflow', 'Adaptor Profiles', 'TreeItem20', 'Adaptor ProfilesTreeItem', 'Business Logic', 'TreeItem21', 'Business LogicTreeItem', 'TreeItem22', 'Channels', 'ChannelsTreeItem', 'Scripts', 'TreeItem23', 'ScriptsTreeItem', 'TreeItem24', 'first_test_caseTreeItem', 'first_test_case', 'NaturalLanguageRule_bsTreeItem', 'TreeItem25', 'NaturalLanguageRule_bs', 'New', 'NewTreeItem', 'TreeItem26', 'TreeItem27', 'Process_retest', 'Process_retestTreeItem', 'TreeItem28', 'Process1', 'Process1TreeItem', 'TreeItem29', 'Process1aTreeItem', 'Process1a', 'Process1b', 'TreeItem30', 'Process1bTreeItem', 'TreeItem31', 'Process1kTreeItem', 'Process1k', 'Process2TreeItem', 'TreeItem32', 'Process2', 'Process3TreeItem', 'TreeItem33', 'Process3', 'Process4TreeItem', 'TreeItem34', 'Process4', 'TreeItem35', 'Process5TreeItem', 'Process5', 'TreeItem36', 'Process6TreeItem', 'Process6', 'PythonModel_factorialTreeItem', 'TreeItem37', 'PythonModel_factorial', 'PythonModel_sum', 'TreeItem38', 'PythonModel_sumTreeItem', 'SA_13WithPytestTreeItem', 'TreeItem39', 'SA_13WithPytest', 'SA-1', 'SA-1TreeItem', 'TreeItem40', 'TreeItem41', 'SA-1_pass', 'SA-1_passTreeItem', 'SA-21TreeItem', 'TreeItem42', 'SA-213', 'SASBatchModel1', 'TreeItem43', 'SASBatchModel1TreeItem', '37', 'Pane47', 'Search:Pane', 'Pane48', 'Search:', '38', 'Edit', '39', 'Pane49', '40', 'Pane50', '41', 'TitleBar', 'SystemMenu', 'Menu', 'System', 'MenuItem', 'System0', 'System1', 'System2', 'SystemMenuItem', 'Minimize', 'MinimizeButton', 'Button10', 'Restore', 'Button11', 'RestoreButton', 'Close', 'Button12', 'CloseButton'])'

It complains Could not find 'identifier_name' in 'dict_keys but value of 'identifier_name' which is 'CharacteristicHyperlink1' is present in the list.

**Comment by bsateeja** [comment]
Is there a way to convert string type to handle type?

Thank you.

**Comment by vasily-v-ryabov** [comment]
Hi @bsateeja the correct way for this attribute access should look so:
```python
getattr(dlg, identifier_name).draw_outline()

# or so:
dlg.child_window(best_match=identifier_name).draw_outline()
```
Your initial code is equivalent to `dlg.child_window(best_match="identifier_name").draw_outline()` which behaves different way.

**Comment by bsateeja** [comment]
Thank you for your input. This works well!!
