### ISSUE TITLE
open CMD 

### ISSUE THREAD

**Issue by rajarameshmamidi** [pywinauto/pywinauto#559]
Hi all,

is there a way to open CMD with the help of pywinauto?

i tried as below, code was successful but cmd not opened.  Any idea why cmd not opened?
```python
from pywinauto.application import Application
app = Application().start('c:\WINDOWS\System32\cmd.exe') 
```

Thanks,
Rajarameshmamidi

**Comment by vasily-v-ryabov** [comment]
`cmd.exe` is opened but exited very quickly. Correct way should be like this:
```python
app = Application().start(r'c:\WINDOWS\System32\cmd.exe /k', create_new_console=True, wait_for_idle=False)
```

If you want to ask about grabbing console output, this is not implemented and planned in the issue #492.

**Comment by rajarameshmamidi** [comment]
Thank you very much Vasily... now cmd is opening

**Comment by vishnuprasadP95** [comment]
Can we have any way to read and write to command prompt.

**Comment by vasily-v-ryabov** [comment]
Hi @vishnuprasadP95 this is tracked in #492 but it's of low priority.

**Comment by andrezamberlam** [comment]
# Make connection with Application
```
# Need to make with 'win32' and 'uia'
_title_re="c:\WINDOWS\System32\cmd.exe" #probably this
app_win32 = Application().connect(title_re=_title_re)
app_win32_window_handle = app_win32.top_window().handle

app_uia = Application(backend="uia").connect(title_re=_title_re) 
conn_uia = app_uia.top_window()
conn_uia_text_area = self.conn_uia.child_window(title="Text Area", control_type="Document").wrapper_object()
```


# Get text
`my_text = conn_uia_text_area.iface_text.DocumentRange.GetText(-1)
`

# Send commands to window

```
# only in foreground, but is recommended
conn_win32.type_keys(keys, **kwargs)
```
or
```
# cmd may be in the background
conn_win32.send_keystrokes(keystrokes, with_spaces=with_spaces, with_tabs=with_tabs, with_newlines=with_newlines) 
```
or 
```
conn_win32.send_chars(chars, *args, **kwargs)
```
