### ISSUE TITLE
Google Chrome title find fails

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#57]
The original issue raised on StackOverflow question (http://stackoverflow.com/questions/31931355/with-pywinauto-how-do-i-know-what-the-name-of-the-started-application-is/31954817#31954817)

After launching an instance of Google Chrome browser  you can't access the app by any title:

```python
from pywinauto import application
app = application.Application()
app.Start_("//PathToGChrome/Google Chrome.exe")

# Window not found error here:
app.Google_Chrome.ClickInput(coords=(0,0))
```

The search in *pywinauto\findwindows.py(183)find_windows()* function fails because there is not existing process ID. I think due a "trick" of Chrome's multi-process architecture we get only PID of a launcher but the actual process ID of the window is different .

**Comment by airelil** [comment]
I think it is similar or even the same problem as described in issue #4

**Comment by vasily-v-ryabov** [comment]
Chrome automation requires UIA support and maybe something more. Closing as duplication of #3.
