### ISSUE TITLE
How to wait for the end of processing

### ISSUE THREAD

**Issue by ruanwenfeng** [pywinauto/pywinauto#571]
How to wait for the end of processing。Like I clicked a button

**Comment by vasily-v-ryabov** [comment]
This is described in the docs: [Waiting for Long Operations](https://pywinauto.readthedocs.io/en/0.6.4/wait_long_operations.html)

**Comment by ruanwenfeng** [comment]
> This is described in the docs: [Waiting for Long Operations](https://pywinauto.readthedocs.io/en/0.6.4/wait_long_operations.html)

very useful. Thank you
