### ISSUE TITLE
pywinauto -how to handle alert window control

### ISSUE THREAD

**Issue by Gokul-15** [pywinauto/pywinauto#573]
https://stackoverflow.com/questions/52399273/pywinauto-how-to-handle-alert-window-control

**Comment by vasily-v-ryabov** [comment]
Hi @Gokul-15 I could understand your impatience if it was commercial tool or I worked on it full time. But it's a hobby project we make out of office hours. The number of questions is increasing, but the community grows slower. We also need this time to work on new features like "record-replay".

I'm monitoring StackOverflow questions and comments. Please avoid duplication.

**Comment by vasily-v-ryabov** [comment]
@Gokul-15  can we close this and mark SO answer as accepted?
