### ISSUE TITLE
ListViewWrapper from uia_controls does not work with WinForms DataGridView

### ISSUE THREAD

**Issue by van9konst** [pywinauto/pywinauto#579]
Hi.

So, i've checked documentation and found something that named "uia_controls". And as far as i see it's not working.
Functionality that i was looking for is to get items from table.

[link to repo](https://github.com/van9konst/temp_example_pywinauto.git) consist from [python_script](https://github.com/van9konst/temp_example_pywinauto/blob/master/winpyauto_test_script.py) and sources of C# program.
![image](https://user-images.githubusercontent.com/12187492/46608358-cded7880-cb04-11e8-9135-b3df2a7d4611.png)

Is "uia_controls" going to be supported, or am i making something wrong?

**Comment by vasily-v-ryabov** [comment]
Hi @van9konst it's wrong usage of wrappers. In the most cases direct usage of wrappers is not necessary, since they can be created by pywinauto for you automatically. This is described in the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html). See section "Window Specification". You have to read the whole core concept before surfing the rest of the docs. It will save your time.

What you're trying to do is creating wrappers directly and passing `WindowSpecification` objects into wrapper constructor. But the wrapper accepts another type of objects that you don't have to know of (it's internal class `UiaElementInfo`).

**Comment by vasily-v-ryabov** [comment]
* Code completion should work for wrappers, it doesn't work for window specification. It requires calling `.wrapper_object()` explicitly for now.
* Documentation is under fixing in PR #578. Sorry. Working page: https://pywinauto-fork.readthedocs.io/en/docs_fixes/code/pywinauto.controls.uia_controls.html

Maybe unit tests for DataGridView would be helpful as well: [test_uiawrapper.py#L830](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/unittests/test_uiawrapper.py#L830).

**Comment by van9konst** [comment]
I've updated my repo with example. https://github.com/van9konst/temp_example_pywinauto.git
As far as i see i have standard (for WPF) control and it's not captured by current version pywinauto.
![tempsnip](https://user-images.githubusercontent.com/12187492/46670518-b250a380-cbd2-11e8-8fcf-21ce895e20f0.png)

and one more thing. **_### .texts()_** used to return real value (values) or just a name of control that already selected? 
![image](https://user-images.githubusercontent.com/12187492/46671694-b03c1400-cbd5-11e8-85c6-beca463b0a4a.png)

**Comment by vasily-v-ryabov** [comment]
OK, what is printed by this code?
```python
print(vx.Form1.child_window(auto_id="dataGridView1").wrapper_object())
```
It's important to know which type of wrapper was created for this control.

**Comment by van9konst** [comment]
Here is output
`uiawrapper.UIAWrapper - 'DataGridView', Table
`

**Comment by vasily-v-ryabov** [comment]
It means this was not detected as a grid. This is strange because `control_type` is `Table`. Maybe there is some not implemented part of the code. Marking as a bug.

**Comment by vasily-v-ryabov** [comment]
Currently you may try this workaround (please let me know if it works):
```python
from pywinauto.controls.uia_controls import ListViewWrapper
table_info = vx.Form1.child_window(auto_id="dataGridView1").wrapper_object().element_info

grid = ListViewWrapper(table_info)
# then work with "grid" variable as a normal ListViewWrapper...
```

**Comment by van9konst** [comment]
As far as i see this workaround not works. I've tried your code and as you see on screenshot it wont return an actual column.
![image](https://user-images.githubusercontent.com/12187492/47292626-e337cc00-d607-11e8-9a3b-6828cc78bd4e.png)

**Comment by vasily-v-ryabov** [comment]
Merged to master in PR #588. Will be included into 0.6.6: https://github.com/pywinauto/pywinauto/milestone/14

**Comment by yongcong1415** [comment]
use item.legacy_properties() will return dist,the value in it

**Comment by RealLau** [comment]
I can not get DataGridView data, can somebody help me?
code：
```python
table.wait("exists enabled visible ready")
print(table.print_control_identifiers())
table_wrap = table.wrapper_object()
print("-"*100)
print(table_wrap)
```
output:
```shell
Control Identifiers:

WindowsForms10.Window.8.app.0.6ab532_r6_ad1 - ''    (L207, T315, R2559, B1004)
['WindowsForms10.Window.8.app.0.6ab532_r6_ad1']
child_window(auto_id="dg1", control_type="System.Windows.Forms.DataGridView")
   | 
   | WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad1 - ''    (L207, T987, R2542, B1004)
   | ['WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad1', 'WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad10', 'WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad11']
   | 
   | WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad1 - ''    (L2542, T315, R2559, B987)
   | ['WindowsForms10.SCROLLBAR.app.0.6ab532_r6_ad12']
None
----------------------------------------------------------------------------------------------------
hwndwrapper.HwndWrapper - '', WindowsForms10.Window.8.app.0.6ab532_r6_ad1
```

Inspect screenshot:
![image](https://user-images.githubusercontent.com/16678624/92958567-063e2400-f49d-11ea-84cf-c3d039c93b4a.png)

Any suggestion is appreciated

**Comment by vasily-v-ryabov** [comment]
Hi @RealLau which backend is used? I mean how do you create `Application()` object? There are "win32" and "uia" backends that both work for WinForms apps. But "uia" backend is a little bit better for such controls like DataGridView.
