### ISSUE TITLE
Question about getting win32 info

### ISSUE THREAD

**Issue by kodaman2** [pywinauto/pywinauto#587]
I know there is pyinspect, but that relies on QT which is around 200~MB.
Does anyone knows if Au3Info.exe can be used to grab data in the same fashion, that's 2MB and runs natively in windows.

**Comment by kodaman2** [comment]
Nvm is on the https://pywinauto.readthedocs.io/en/latest/getting_started.html
Forgot to RTFM.

**Comment by vasily-v-ryabov** [comment]
OK, thanks for the feedback. I think we can file an issue about minimal file size requirement in py_inspect repo (which size do you think is reasonable? 10-15~MB? it's hard to make smaller exe with Python). Hope it can be solved by proper cx_freeze/PyInstaller/py2exe script with further attaching target exe to every release. We haven't paid much attention to py_inspect yet, but will do in 2019.

Do you have any more thoughts on what can be improved in pywinauto?

**Comment by vasily-v-ryabov** [comment]
OK, thanks! Just leaving the reference here for faster navigation: pywinauto/py_inspect#1
