### ISSUE TITLE
not unicode MenuItem.Text()

### ISSUE THREAD

**Issue by moden-py** [pywinauto/pywinauto#59]
Commit 7035b405002c59aa893216f2d030c57806c007cb broke unicode texts for menu items.

Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win
32
```python
import pywinauto
pwa_app = pywinauto.application.Application()
w_handle = pywinauto.findwindows.find_windows(title_re=u'\u041a\u0430\u043b\
u044c\u043a\u0443\u043b\u044f\u0442\u043e\u0440', class_name='CalcFrame')[0]  # Калькулятор
window = pwa_app.window_(handle=w_handle)
m = window.Menu()
i1 = m.Items()[0]
```
rev e5842c74e5aeb3ff043d3e78e894be416329e666

```python
print i1.Text()
&Вид

print type(i1.Text())
<type 'unicode'>
```

rev 7035b405002c59aa893216f2d030c57806c007cb
```python
print i1.Text()
'&\xc2\xe8\xe4'  # &Вид

print type(i1.Text())
<type 'str'>
```

**Comment by vasily-v-ryabov** [comment]
Will fix it later. Need to handle every type of menu item with care.
Link for reference: https://msdn.microsoft.com/en-us/library/windows/desktop/ms647578(v=vs.85).aspx

**Comment by airelil** [comment]
Basically, *Text()* method should return something only if the menu type has *MFT_STRING* bit in other cases it should be *None*.

**Comment by moden-py** [comment]
Verified
