### ISSUE TITLE
UnicodeEncodeError calling .windows()

### ISSUE THREAD

**Issue by HakimEG** [pywinauto/pywinauto#594]
I am using Python 2.7 64bit, and going through the Danish version of VCDS.
Calling .windows() throws a UnicodeEncodeError error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 49: ordinal not in range(128)
```
Have been using it with the English version of VCDS, and it works flawlessly, couldn't be happier :) 

I can get through by calling 
```python
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```
But that poses some other issues for me.

Thanks

**Comment by vasily-v-ryabov** [comment]
Thanks! This is bug in `__repr__` method of wrapper. You can bypass it so:
```python
[print w.window_text(), w.control_type() for w in app.windows()]
```

**Comment by HakimEG** [comment]
Thanks for the quick response! even though mine has been somewhat late :)
