### ISSUE TITLE
Flag visible_only=True breaks search on deeper levels for visible elements if invisible subparent is present

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#596]
There is an example in issue #590 that shows flag `visible_only=False` is required to find visible element!

* This happens because some parent of visible element might be invisible and this subtree is not considered at all. Though the subtree contains some visible elements.

* We also have to write test application for this case.

* Method `dump_tree()` (a.k.a. `print_control_identifiers()`) should take this into account (maybe we have to always use `visible_only=False` or make deeper improvements in this method).

**Comment by gzll** [comment]
https://github.com/pywinauto/pywinauto/issues/607

**Comment by vasily-v-ryabov** [comment]
Couldn't find LDAP auth web service example quickly. Need to try this Flask example locally: https://github.com/alexferl/flask-simpleldap

**Comment by vasily-v-ryabov** [comment]
I could find the same "Sign in" dialog at this URL: https://mtt.open-mpi.org/submit/
But... now all elements are visible. Looks like Chrome team fixed this issue. So we don't have example for reproduce.
