### ISSUE TITLE
Element Not found error while installing

### ISSUE THREAD

**Issue by rajarameshmamidi** [pywinauto/pywinauto#603]
Hi Vasily,

How are you doing...

i am facing an issue while trying to install Git with pywinauto. Below is sample code and error message 
can you please let me know what is causing issue.
```python
from pywinauto.application import Application
import time
app = Application().start(r'C:\Users\Administrator\Desktop\Raja python\software\Git-2.9.3.2-64-bit.exe')
b = Application().connect(title = 'Git 2.9.3.2 Setup')
time.sleep(5)
b.Git_2_9_3_2_Setup.print_control_identifier()
```
Also i used as below but no luck,
```python
b.Git_2_9_3_2_SetupDailog.print_control_identifier()
```
Error message:-

```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/Raja python/python practice/click_install.py", line 10, in <module>
    b = Application().connect(title = 'Git 2.9.3.2 Setup')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto-0.6.5-py3.7.egg\pywinauto\application.py", line 965, in connect
    self.process = findwindows.find_element(**kwargs).process_id
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto-0.6.5-py3.7.egg\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title': 'Git 2.9.3.2 Setup', 'backend': 'win32'}
```

Thanks,
raja

**Comment by rajarameshmamidi** [comment]
Hi vasily,

i modified the code as below and got same error, can you help in this...

from pywinauto.application import Application
import time
app = Application().start(r'C:\Users\Administrator\Desktop\Raja python\software\Git-2.9.3.2-64-bit.exe')
b = app['Git 2.9.3.2 Setup']
time.sleep(5)
b.NextButton.click()

Thanks,
raja

**Comment by airelil** [comment]
@rajarameshmamidi, if your goal is to perform unattended installation, maybe you could use some of the flags of the setup program to run it silently?
![image](https://user-images.githubusercontent.com/795040/48647475-f09e7580-ea50-11e8-8eeb-a40f31a16156.png)

**Comment by vasily-v-ryabov** [comment]
Hi @rajarameshmamidi I agree with @airelil . If your goal is installation only (not GUI testing of Git installer), correct command line for silent install is the best and easiest choice.

**Comment by rajarameshmamidi** [comment]
Hi Airelil & vasily,

Thank you for sharing the details.

Further i tried in silent method.  i am new for this and followed the steps provide from google. for this we need .iss file to (-r) record first with the steps later we need to proceed with (-s) for silent install. 

But .iss file is not creating in the path. can you guide me when i went wrong...! Below are the steps i followed to create .iss file,
![no iss file](https://user-images.githubusercontent.com/42936846/48670934-f1193800-eb46-11e8-95e0-745d58b84182.PNG)
 

Regards,
Raja

**Comment by vasily-v-ryabov** [comment]
It works for me this way in `cmd.exe`:
```
start /WAIT Git-2.19.1-64-bit.exe /SILENT /NORESTART /NOCLOSEAPPLICATIONS /NORESTARTAPPLICATIONS
```
That's enough. Further command `echo %errorlevel%` should print `0`.

**Comment by rajarameshmamidi** [comment]
Hi Vasily,

thank you for sharing the details i tried above and it worked. Also i tested the error command too.

i have below doubts,

1. will this kind of installation creates log file?
2. is there a way to re-install the software itself by rectifying the errors, if the installation stops due to some errors? 

Regards,
raja

**Comment by vasily-v-ryabov** [comment]
How did you convert this path to the script? By using `.type_keys` method???
There is standard Python function to open file for write. No need to automate through Notepad or another text editor.
```python
with open("script.bat", "w") as f:
     f.write(path + "\n")
```
Maybe it's better to take Python course first? pywinauto is targeted mostly for GUI testing, not for sysadmin tasks.

**Comment by vasily-v-ryabov** [comment]
Regarding Git installation log, there is `/LOG="filename"` option in Git installer help. Please read help messages more carefully. I'd suggest to close this thread because it doesn't relate to pywinauto.

**Comment by rajarameshmamidi** [comment]
Thank you Vasily. i will go through Git Help for more details.
