### ISSUE TITLE
Runtimewarning: The window has not been focused due to COMError: (-2146233079, None, (None, None, None, 0, None)) When attempting to automate MS Word

### ISSUE THREAD

**Issue by codeNameMahi** [pywinauto/pywinauto#621]
#### I am attempting to automate Word, and I am getting the COMError in multiple places.

Basically when you launch the application, it brings up a window where you select the starting document. I am attempting to start with the option "Blank document"

##### code
    from pywinauto.application import Application
    app = Application(backend="uia")

    # start the Office 365 version of Word
    app.start("C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\WINWORD.EXE")

    # click the "Blank Document" option
    app.Word.HomePane.New2.Featured.ListItem0.invoke()

    # Opens a blank document (expected) but also generates error:
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Python\Python36\lib\site-packages\pywinauto\base_wrapper.py", line 168, in __repr__
      return '<{0}, {1}>'.format(self.__str__(), self.__hash__())
    File "C:\Python\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 203, in __hash__
      return hash(self.element_info.runtime_id)
    File "C:\Python\Python36\lib\site-packages\pywinauto\uia_element_info.py", line 231, in runtime_id
      return self._element.GetRuntimeId()
    _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

    # I have also tried invoking like this 
    app.Word.HomePane.New2.Featured.child_window(title="Blank document", control_type="ListItem").invoke()

    # Also opens a blank document and also generates an error
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python\Python36\lib\site-packages\pywinauto\base_wrapper.py", line 168, in __repr__
        return '<{0}, {1}>'.format(self.__str__(), self.__hash__())
      File "C:\Python\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 203, in __hash__
        return hash(self.element_info.runtime_id)
      File "C:\Python\Python36\lib\site-packages\pywinauto\uia_element_info.py", line 231, in runtime_id
        return self._element.GetRuntimeId()
    _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

    
    # I have been able to get it to work without an error like this:
    app.Word.HomePane.New2.Featured.ListItem0.double_click_input()

    # which will open a blank document without any errors, but when I attempt to write to the blank document I get a similar error:

    app.Dialog.Edit.type_keys("Hello World!")

    # generates this error, but writes the text as expected.
    C:\Python\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py:416: RuntimeWarning: The window has not been focused due to COMError: (-2146233079, None, (None, None, None, 0, None))
      'COMError: {}'.format(exc), RuntimeWarning)
    <uia_controls.EditWrapper - 'Page 1 content', Edit, 411693805108185671>

I am concerned about these error messages, even though the script appears to work as expected. When searching for the COMError in the pywinauto repository, there was supposed to be a fix in 0.6.4, and I am experiencing the error using version 0.6.5.

#### the print ctrl ids output for what I am trying to access
     app.Word.HomePane.New2.Featured.print_ctrl_ids()

    Control Identifiers:

    ListBox - 'Featured'    (L1218, T158, R2137, B351)
    ['ListBox', 'FeaturedListBox', 'Featured']
    child_window(title="Featured", control_type="List")
       |
       | ListItem - 'Blank document'    (L1219, T161, R1448, B350)
       | ['ListItem', 'Blank document', 'Blank documentListItem', 'ListItem0', 'ListItem1']
       | child_window(title="Blank document", auto_id="AIOStartDocument", control_type="ListItem")
       |
       | ListItem - 'Welcome to Word'    (L1449, T161, R1678, B350)
       | ['ListItem2', 'Welcome to WordListItem', 'Welcome to Word']
       | child_window(title="Welcome to Word", auto_id="AIOStartDocument", control_type="ListItem")
       |    |
       |    | Button - 'Unpin from list'    (L1644, T309, R1672, B329)
       |    | ['Button', 'Unpin from list', 'Unpin from listButton', 'Button0', 'Button1']
       |    | child_window(title="Unpin from list", auto_id="AIOStartDocumentPin", control_type="Button")
       |
       | ListItem - 'Single spaced (blank)'    (L1678, T161, R1907, B350)
       | ['Single spaced (blank)', 'ListItem3', 'Single spaced (blank)ListItem']
       | child_window(title="Single spaced (blank)", auto_id="AIOStartDocument", control_type="ListItem")
       |    |
       |    | Button - 'Pin to list'    (L1873, T309, R1901, B329)
       |    | ['Button2', 'Pin to list', 'Pin to listButton', 'Pin to list0', 'Pin to list1', 'Pin to listButton0', 'Pin to listButton1']
       |    | child_window(title="Pin to list", auto_id="AIOStartDocumentPin", control_type="Button")
       |
       | ListItem - 'Chronological Resume (Modern design)'    (L1907, T161, R2136, B350)
       | ['ListItem4', 'Chronological Resume (Modern design)', 'Chronological Resume (Modern design)ListItem']
       | child_window(title="Chronological Resume (Modern design)", auto_id="AIOStartDocument", control_type="ListItem")
       |    |
       |    | Button - 'Pin to list'    (L2102, T309, R2130, B329)
       |    | ['Button3', 'Pin to list2', 'Pin to listButton2']
       |    | child_window(title="Pin to list", auto_id="AIOStartDocumentPin", control_type="Button")

**Comment by vasily-v-ryabov** [comment]
Hi @codeNameMahi `COMError` inside `runtime_id` property is a new issue never reported before. Thanks! One more reason for its visibility is that many methods of wrappers allow chaining. So `.invoke()` call is succeed and returns wrapper object to make things like `.invoke().window_text()` possible (BTW, it can be a workaround for your case). Returned wrapper object is considered by interactive Python console to be printed, therefore method `__repr__` for this wrapper is called and failed. Assume the same code should work when running the whole script, but it will fail running line by line in interactive interpreter.

The nature of RuntimeWarning in `type_keys` might be different, it looks like incorrect `set_focus()` handler implementation on app side (yes, Microsoft can introduce bugs as well), but it works because the edit box is already in focus. Fortunately we raise only warning there. :)

**Comment by shsharma-apttus** [comment]
Even I am facing this Issue, while automation word, I am trying to click on Insert, but its giving me same error "RuntimeWarning: The window has not been focused due to COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
    'COMError: {}'.format(exc), RuntimeWarning)", anyone knows how to resolve this issue?

**Comment by vasily-v-ryabov** [comment]
@shsharma-apttus is it blocking exception? or just warning? The click action is performed or not after all?

**Comment by shsharma-apttus** [comment]
@vasily-v-ryabov it worked now for me, click_input() is working, but its just that my application was static and freezed in some scenario, where i was trying to automate, which is handled by changing my approac their.

**Comment by vasily-v-ryabov** [comment]
@shsharma-apttus the problem here is that we can't fix 3rd-party application code. So sometimes different ways help to workaround such problems. But don't hesitate to report them as it is not always clear which side has a bug.

**Comment by lazyautomation** [comment]
@vasily-v-ryabov  I am also facing the same issue at runtime when my outlook test script is in progress and in between a new mail gets arrived and notification pop up.

 RuntimeWarning: The window has not been focused due to COMError: (-2146233079, None, (None, None, None, 0, None))
  'COMError: {}'.format(exc), RuntimeWarning)

**Comment by vasily-v-ryabov** [comment]
@lazyautomation is it just warning or blocking error?

**Comment by lazyautomation** [comment]
@vasily-v-ryabov Its not blocking error/test run and just a warning, what i observed that this happened only if any notification arrived in between the test run.

**Comment by vasily-v-ryabov** [comment]
This is most probably application issue. We call standard handler for bringing it to focus. If this handler is implemented with errors, this is app side error. Of course, Microsoft Office is also not guaranteed to be bug-free. :)

**Comment by vasily-v-ryabov** [comment]
Or it can be window re-create issue if you call some action for the element that was destroyed while you're calling the action. You can handle it several ways by waiting: https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html
