### ISSUE TITLE
Issue with cx_Freeze and pywinauto Application

### ISSUE THREAD

**Issue by irajeshr** [pywinauto/pywinauto#623]
Hi all,

i have an Python application that i am trying to convert into an exe/msi using cx_freeze. in my python script i am using pywinwuto to perform automated key stroke send. build is happening fine and when i try to run the application after installation, i get below error. when i check the code its errors out at the line where i am trying to bring focus to the application. when i try to run the code normally, it works fine. please help.

**code where its' failing**: app.top_window().set_focus()

**code that i tried in local which works fine :**
```python
import subprocess
from pywinauto import Application

proc = subprocess.Popen("notepad.exe")
app = Application().connect(process=proc.pid)
print(proc.pid)
app.top_window().set_focus()
```

in my setup script i am importing the necessary packages aswell ..

**Error Message:**
```
Traceback (most recent call last):
  File "C:\Python36_86\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36_86\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "C:\code.py", line 463, in <module>
  File "C:\Python36_86\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 1323, in set_focus
  File "C:\Python36_86\lib\site-packages\pywinauto\win32functions.py", line 296, in WaitGuiThreadIdle
RuntimeError: Window (hwnd=hwndwrapper.DialogWrapper - 'None', Afx:00A70000:8:00010003:00000000:01B204AD) is not responding!
```

**Comment by vasily-v-ryabov** [comment]
It seems I need to take a look more precisely. Will try to reproduce and debug later. Which cx_Freeze version do you use? 5.1.1 or latest 6.x beta?

**Comment by vasily-v-ryabov** [comment]
Is it reproduced with minimal Notepad example provided? Or it happens inside bigger Python app only?

**Comment by irajeshr** [comment]
Python version: 3.6 (32 bit)
cx_freeze version: 5.1.1

this issue is happening for bigger application. as a workaround, i have added wait time in between and it seems to be working fine. however, need to know if this is how it should behave or is it something that i am missing anything

```
taskId = subprocess.Popen("")
time.sleep(30)
app = Application().connect(process=taskId.pid)
```

**Comment by airelil** [comment]
@irajeshr, I wonder if you tried to use pywinauto built-in ```start``` method to launch the application instead of ```subprocess.Popen()``` ? Did you know that ```Application().start``` method has ```wait_for_idle``` flag already enabled by default. This flag is to be used to wait till the application start up is finished. You can also tune the wait time with another ```timeout``` argument if the default wait period doesnt' suit you well.  The internal wait should be better as it tries to check the process state every 1 sec and continue immediately when the app is ready.

**Comment by irajeshr** [comment]
@airelil Thanks for the suggestion. I did try the Applicaiton().Start. However, i was not getting back the process_id of the started application. Hence had to use subprocess. if you could suggest an alternative means, that would be really helpful

**Comment by vasily-v-ryabov** [comment]
@irajeshr `app.process` is the process_id of started application. It doesn't matter `.start()` or `.connect()` was used before.

**Comment by vasily-v-ryabov** [comment]
Well, the `window is not responding` message is correct there. Generally it's responsibility of application developers to make their GUI responsible and to implement a proper progress bar.

There is another useful function in pywinauto to workaround this: `app.wait_cpu_usage_lower()` which can be called before `.set_focus()`. The full set of wait functions is described in chapter [Waiting for Long Operations](https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html).

It seems there is nothing to do on pywinauto side. If all these things resolve your problem, I would consider closing the issue.

**Comment by irajeshr** [comment]
@vasily-v-ryabov  Thanks for your inputs. let me try and get back!

**Comment by irajeshr** [comment]
Opened a new issue #638

**Comment by irajeshr** [comment]
@vasily-v-ryabov tried as suggested by using the wait_cpu_usage_lower() and still it seems to not work as intended

**Comment by airelil** [comment]
I just noticed in ```HwndWrapper.set_focus``` 
https://github.com/pywinauto/pywinauto/blob/bb4fc6527954ae221321977a9baeb1de71d6a8eb/pywinauto/controls/hwndwrapper.py#L1328
It probably should not pass the object instance itself as a parameter, but the actual handle
```python
WaitGuiThreadIdle(self.handle)
```

**Comment by airelil** [comment]
@irajeshr, I just made a quick fix for ```WaitGuiThreadIdle``` calls in my branch: https://github.com/airelil/pywinauto/tree/issue_623 . It still has to pass our CI tests, but you can try the code from this branch and see if it helps to solve your problem.

**Comment by irajeshr** [comment]
@airelil for now i believe i cant test it because we are not permitted t download anything directly. is there any approx wait time by when i can do an installation using pip?

**Comment by airelil** [comment]
I'm affraid it will take time to make the next official release. We still have more issues to close for the [milestone 0.6.6](https://github.com/pywinauto/pywinauto/milestone/14)

**Comment by irajeshr** [comment]
@airelil thanks for the updates. i guess then i need to wait till the official release happens and until then manage with my work around

**Comment by vasily-v-ryabov** [comment]
@irajeshr `pip` allows installation from branch as well. This command should work if traditional `pip install pywinauto` works:
```
pip install https://github.com/airelil/pywinauto/archive/issue_623.zip
```
Maybe you will need `pip uninstall pywinauto` first.

**Comment by irajeshr** [comment]
@vasily-v-ryabov thanks for the updates. unfortunately i didnt get approval to do such :( i have been asked to wait till its available as part of the next update.

**Comment by vasily-v-ryabov** [comment]
Hi @irajeshr I've just posted release 0.6.6. Please re-check everything if you're still waiting till that moment. Sorry for long waiting.
