### ISSUE TITLE
controltypes - obsolete class variable in common_controls module?

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#635]
All classes in common_controls have the following construction or similar:
```
    if sysinfo.UIA_support:
        #controltypes is empty to make wrapper search result unique
        #possible control types: IUIA().UIA_dll.UIA_ListControlTypeId
        controltypes = []
```
But from search it doesn't look like it is used anywhere. Should we remove it ?

**Comment by vasily-v-ryabov** [comment]
I think we should. The initial idea was re-using some "win32" wrappers for UIA backend. But it seems it was wrong way. Now we have some workarounds in UIA wrappers that create Win32 wrappers explicitly inside some methods. But that's it. No other plans in this direction.
