### ISSUE TITLE
Issue when executing RDP session is in Console mode

### ISSUE THREAD

**Issue by irajeshr** [pywinauto/pywinauto#638]
Hi All,

i have an application built using pywinauto/cx_freeze that does keystroke send to application. this works perfectly fine when i take the remote desktop session and manually trigger the utility. when i try to schedule the utility and keep the RDP session disconnected (but active using the tscon ... /dest:console command), my utility is getting launched (which i can confirm by the logs generated) but fails with below error and nothing happens 

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 1310, in set_focus
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\pywinauto\mouse.py", line 232, in move
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')

**Update:**
the line thats failing is 
`app.top_window().set_focus()`

**Comment by airelil** [comment]
@irajeshr, since you mentioned tscon.exe you may have seen it already, but if not please have a look at our [Remote Execution Guide](https://pywinauto.readthedocs.io/en/latest/remote_execution.htm). Also, as mentioned by @vasily-v-ryabov , other possible reason could be "UAC" dialog: https://stackoverflow.com/questions/46505942/python-win32api-setcursorpos-error

**Comment by irajeshr** [comment]
@airelil  thanks for the feedback. 
Remote Execution guide link seems to be not working.

Regarding the UAC -- it doesnt prompt any UAC box as we have disabled it completely.

**Comment by irajeshr** [comment]
@airelil Thanks for your inputs. Unfortunately i dont have any control over the type of remote client to use. we are permitted to use the windows default mstsc only :( having said that, is there anything else that can be done using some module to keep the remote session active and not getting itself locked up due to inactivity?

**Comment by vasily-v-ryabov** [comment]
`.type_keys(...)` works the same way as `keyboard.send_keys()` except it calls `.set_focus()` for the target control before typing.

By the way, [Remote Execution Guide suggests some "Tricks to run automation on a locked machine"](https://pywinauto.readthedocs.io/en/latest/remote_execution.html#tricks-to-run-automation-on-a-locked-machine) which includes 2 other methods for a wrapper object. These methods are available for `backend="win32"` only.

Did you try 2 links to TestComplete docs in the Remote Execution Guide for your RDP? Is it applicable?

**Comment by vasily-v-ryabov** [comment]
And mentioned docs for `type_keys` has link to `keyboard` module with some code snippets: https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html

**Comment by irajeshr** [comment]
> `.type_keys(...)` works the same way as `keyboard.send_keys()` except it calls `.set_focus()` for the target control before typing.
> 
> By the way, [Remote Execution Guide suggests some "Tricks to run automation on a locked machine"](https://pywinauto.readthedocs.io/en/latest/remote_execution.html#tricks-to-run-automation-on-a-locked-machine) which includes 2 other methods for a wrapper object. These methods are available for `backend="win32"` only.
> 
> Did you try 2 links to TestComplete docs in the Remote Execution Guide for your RDP? Is it applicable?

Yep I already have tested the 2 steps. it works. the problem that i am facing is that when i sort of schedule the utility to execute, it fails even though i have disconnected using the option 2 suggested in that documentation. my assumption is that after some inactivity, the policy is such that it locks the remote machine and hence the issue.

**Comment by vasily-v-ryabov** [comment]
If it's impossible to change auto lock policy, it makes sense to schedule every few minutes some fake task that performs one click somewhere if main task is not running (for example, by checking some signal file or another Python process).

**Comment by vasily-v-ryabov** [comment]
By the way, method `.set_edit_text()` can be a good candidate for locked machine. It uses `.set_value()` for UIA backend and `WM_SETTEXT` message for Win32 backend.

**Comment by irajeshr** [comment]
@vasily-v-ryabov : Thanks for the updates, can you please some more info and documentation on how to use the above said function?

**Comment by vasily-v-ryabov** [comment]
It's dead simple: `app.DialogSpec.SomeControlSpecification.set_edit_text("something with spaces")` That's it. There are optional arguments to replace some part of edited text: `startpos` and `endpos`.
