### ISSUE TITLE
win32functions.IsWindowVisible issue: OverflowError: int too long to convert

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#641]
The issue has been recently reported on StackOverflow: https://stackoverflow.com/q/53942453/3648361

**Comment by airelil** [comment]
Oh, forgot to mention, and we can set IsWindowVisible.argtypes as well

**Comment by vasily-v-ryabov** [comment]
Yes, this is for `argtypes` change, of course.
