### ISSUE TITLE
Unable to select menu item from popup menu in Sublime Text

### ISSUE THREAD

**Issue by sarora** [pywinauto/pywinauto#647]
I can automate right click on an empty file opened on sublime. But once I get the menu from the right click I cannot seem to select any of the options like `Paste` or `Open containing folder` shown on the menu n Sublime.Any way I can do that? 

Need access/focus/control of that popup menu before I choose the option I want to click. Struggling to achieve that.  Any help be appreciated. Thanks.

**Comment by airelil** [comment]
@sarora, please provide a short piece of code with your problem.
As an example, you can refer to a unit test for right click menu for 'win32' backend:
https://github.com/pywinauto/pywinauto/blob/0b7102e9f0a99bbc39365c78469e765cd7838558/pywinauto/unittests/test_hwndwrapper.py#L691

**Comment by sarora** [comment]
Thanks for the reply @airelil .
Here is what I am doing
```
sublime = Application(backend="uia").start(app_path)

p_sublime = sublime.window(title_re=".*Sublime")

p_sublime.menu_select('File->Open file')

p_open = sublime.window(title_re=".*Open")

P_open.FilenameEdit.set_edit_text(file_to_open)

p_open.Open.set_focus()

p_open.Open.click()

p_sublime.type_keys("Hello")

p_sublime.type_keys('^{S}')

p_sublime.click_input(button='right')

### I cant get to select anything from the context menu
p_sublime.ContextMenu.MenuSelect('Paste')

```
The last line of the code; I want to select one of the options from the context menu after the right click.

**Comment by airelil** [comment]
@sarora, as per example in my previous comment:
```python
sublime.PopupMenu.wait('ready').menu().get_menu_path('Paste')[0].click_input()
```

A similar code, even though it talks about system tray, can be found in our docs: https://pywinauto.readthedocs.io/en/latest/HowTo.html?highlight=menu#how-to-access-the-system-tray-aka-systray-aka-notification-area

**Comment by airelil** [comment]
What SW versions your run (windows, python, pywinauto) ? Do you have multiple screens ? What error do you get ? Did you try to analyze it with Inspect.exe tool as explained in https://pywinauto.readthedocs.io/en/latest/getting_started.html#getting-started-guide ?

The code below works for me on Win8.1 64 bit and Python 3.6.2 64 bit. It also works on my Python 2.7 64 bit. I use a portable version of Sublime3.
```python
from pywinauto import Application

app_path = r"C:\Users\DELL\Downloads\Sublime Text Build 3176 x64\sublime_text.exe"
file_to_open = r"C:\Users\DELL\Downloads\Sublime Text Build 3176 x64\test.txt"

sublime = Application().start(app_path)

p_sublime = sublime.window(title_re=".*Sublime")

p_sublime.click_input(button='right')

sublime.PopupMenu.wait('ready').menu().get_menu_path('Paste')[0].click_input()
```
Notice that it's based on your comment and it's pretty straightforward. The real code needs at least make sure that the application is fully started and is in the focus.

**Comment by sarora** [comment]
Windows 10 Home, Python 3.7, Sublime Text 2. All 64 bit. Application is fully started obviously. Only one screen and it's in focus.

Sadly no error which is a pain. It just does not click on any of the items on the pop up menu.
`p_sublime.click_input(button='right')`  shows the popup menu, but then its gone as if someone clicked on outside the popup area.

**Comment by sarora** [comment]
I tested this on notepad. It works there. Do not understand why there is a problem with Sublime Text2

**Comment by airelil** [comment]
You may try to enable action logging in pywinauto and verify the click coordinates with Inspect.exe
To start the logging place the below lines at the top of your script.
```python
import pywinauto
pywinauto.actionlogger.enable()
```

**Comment by vasily-v-ryabov** [comment]
I've started looking into this case and found side issue with `__repr__` method on Python 2.7. But this code works fine with Python 3.5:
```python
from pywinauto.application import Application 

app = Application(backend="win32").start(r"sublime_text.exe")
p_sublime = app.window(title_re=".*Sublime Text 2.*")
#p_sublime.dump_tree()
p_sublime.click_input(button='right')

print(app.PopupMenu.wait('ready').menu().items()) # crashed on Py2.7
app.PopupMenu.wait('ready').menu().get_menu_path('Paste\tCtrl+V')[0].click_input()
```

The issue for Python 2.7 looks so:
```python
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 326, in RunScript
    exec codeObject in __main__.__dict__
  File "...\test_sublime.py", line 15, in <module>
    print(app.PopupMenu.wait('ready').menu().items())
  File "...\pywinauto\controls\menuwrapper.py", line 370, in __repr__
    return "<MenuItem " + self.text().encode(locale.getpreferredencoding()) + ">"
UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 20: ordinal not in range(128)
```
