### ISSUE TITLE
WinForms: menu_select() raises TimeoutError if application menu have no sub menu item

### ISSUE THREAD

**Issue by shibingstar** [pywinauto/pywinauto#652]
i am running auto UI test on an win10 64bit PC, the application is Visual Stusio C# winform application, and it has one menu strip:
```
WindowsForms10.Window.8.app.0.33c0d9d - ''    (L6, T272, R2038, B320)
   | ['2', 'WindowsForms10.Window.8.app.0.33c0d9d115']
   | child_window(auto_id="uxMenuBar", control_type="System.Windows.Forms.MenuStrip")
```

The menu structure like this:
File->Exit, Settings(when you click it will pop up a window ),Error Report

I am trying to use `menu_select()` to select the menu, it works fine for `"File->Exit"`, but when try to click on "Error Report" menu which doesn't have sub menu, it report following error:
```python
Traceback (most recent call last):
  File "C:/PycharmProjects/MSNewVersionValidation/Test2.py", line 23, in <module>
    app.window(title_re='.*Service.*').menu_select('Error Report')
  File "C:\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 723, in menu_select
    menu.item_by_path(path, exact).select()
  File "C:\Python37-32\lib\site-packages\pywinauto\controls\uia_controls.py", line 848, in item_by_path
    part0, parts = path.split("->", 1)
ValueError: not enough values to unpack (expected 2, got 1)_
```

My code is:
```python
_app = application.Application(backend="uia").start(appPath,10,None,False,True,os.path.dirname(appPath))
sleep(10)
app.window(title_re='.*Service.*').menu_select('Error Report')_
```

so I change my code to this:
```python
_app = application.Application(backend="uia").start(appPath,10,None,False,True,os.path.dirname(appPath))
sleep(10)
app.window(title_re='.*Service.*').menu_select('**Error Report->**')_
```
but it report time out error:
```python
Traceback (most recent call last):
  File "C:/PycharmProjects/MSNewVersionValidation/Test2.py", line 23, in <module>
    app.window(title_re='.*Service.*').menu_select('Error Report->')
  File "C:\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 723, in menu_select
    menu.item_by_path(path, exact).select()
  File "C:\Python37-32\lib\site-packages\pywinauto\controls\uia_controls.py", line 869, in item_by_path
    lambda: len(self.top_level_parent().descendants(control_type="Menu")) > 0)
  File "C:\Python37-32\lib\site-packages\pywinauto\timings.py", line 370, in wait_until
    raise err
pywinauto.timings.TimeoutError: timed out
```

so look like the `menu_select()` only works for the menu which has sub menu?
how do i select the menu which doesn't have a sub menu?

thanks

**Comment by shibingstar** [comment]
i use following work around to fix this issue, i modify the source code of function "item_by_path(self, path, exact=False)" in uia_controls.py as this:

 _def item_by_path(self, path, exact=False):
        """Find a menu item specified by the path

        The full path syntax is specified in:
        :py:meth:`.controls.menuwrapper.Menu.get_menu_path`

        Note: $ - specifier is not supported
        """
        # Get the path parts
        part0, parts = path.split("->", 1)
        part0 = part0.strip()
        if len(part0) == 0:
            raise IndexError()

        # Find a top level menu item and select it. After selecting this item
        # a new Menu control is created and placed on the dialog. It can be
        # a direct child or a descendant.
        # Sometimes we need to re-discover Menu again
        try:
            menu = None
            if part0.startswith("#"):
                menu = self._sub_item_by_idx(self, int(part0[1:]))
            else:
                menu = self._sub_item_by_text(self, part0, exact)

            **if len(parts)==0:
                return menu**_

and it begin to work.

**Comment by vasily-v-ryabov** [comment]
Hi @shibingstar thanks for sharing the workaround! Method `menu_select()` requires more serious improvements including Qt5 apps and MFC menu bar handling. But I would suggest to stick this issue for WinForms specifics and file separate issues for other GUI frameworks (will submit later).

It would be fair to say that we don't have time to fix and unit test it during January and maybe early February. So you are free to send a pull request. Though I'd expect some new auto tests for WinForms app with a menu strip. We don't have such app in the `apps` folder of the main repo yet. We usually add the binaries there. Source code of sample apps is in the neighbor repo: https://github.com/pywinauto/PywinautoTestapps (in case if you're willing to add such sample app to the project).

**Comment by vasily-v-ryabov** [comment]
Hi @shibingstar the issue has been fixed in master branch. Please check it and confirm it's gone.
```
pip uninstall -y pywinauto
pip install https://github.com/pywinauto/pywinauto/archive/master.zip
```
