### ISSUE TITLE
click on listitem ?

### ISSUE THREAD

**Issue by parlar** [pywinauto/pywinauto#653]
Thanks for making pywinauto! 

I'm trying to automate import of data into a program called 'Genome Studio' that used for analyzing microarray data.

For some reason I'm having issues controlling the file menu. However, to open the import wizard I can also click on a listitem. Now, the problem is that I can select the listitem using pywinauto but I cannot click on it. Is there a way to click on listitems?

So this works (but does not open the wizard):

```
from pywinauto.application import Application

app = Application(backend="uia").start(cmd_line=u'"C:\\Program Files\\Illumina\\GenomeStudio 2.0\\GenomeStudio.exe" ')
mw = app.window(title='GenomeStudio 2.0', class_name='WindowsForms10.Window.8.app.0.378734a')
mw.wait('ready', timeout=20)
mw.NewProject\
    .child_window(auto_id="listViewModule", control_type="List")\
    .ListItem2\
    .select()
```

But this does not:

```
mw.NewProject\
    .child_window(auto_id="listViewModule", control_type="List")\
    .ListItem2\
    .click()
```

Exits with an error:

```
Traceback (most recent call last):
  File "C:/Users/PELA09/PycharmProjects/ArrayImporter/gs_run.py", line 7, in <module>
    .child_window(auto_id="listViewModule", control_type="List")\
  File "C:\Apps\Python\Python36\lib\site-packages\pywinauto\application.py", line 174, in __call__
    format(self.criteria[-1]['best_match']))
AttributeError: Neither GUI element (wrapper) nor wrapper method 'click' were found (typo?)
```

There is a workaround for accessing the file menu and open the the wizard using SendKeys, but I'd rather avoid it if possible.

**Comment by vasily-v-ryabov** [comment]
Hi @parlar there is method `.invoke()` which has alias `.click()` for Button control type only. But I see it doesn't call the wizard as well.

What can always help is method `.click_input()` that performs the most realistic click with moving mouse cursor. But this list box item reacts on text area click only, and middle point of the item rect is out of text area. That's why simple `.click_input()` at the center of item won't call the wizard again.

Finally I could make it working this way:
```python
from pywinauto.application import Application

app = Application(backend="uia").start(cmd_line=u'"C:\\Program Files\\Illumina\\GenomeStudio 2.0\\GenomeStudio.exe" ')
mw = app.window(title='GenomeStudio 2.0', class_name='WindowsForms10.Window.8.app.0.378734a')
mw.wait('ready', timeout=20)
list_view = mw.NewProject.child_window(auto_id="listViewModule", control_type="List")
item = list_view.ListItem2
item.click_input(coords=(0, 0))
```
Method `.click_input()` with all its power has one disadvantage: it requires active desktop. So when running on remote machine with minimized or diconnected RDP it will not work by default. Fortunately there are few tricks to overcome this in [Remote Execution Guide](https://pywinauto.readthedocs.io/en/latest/remote_execution.html).

**Comment by parlar** [comment]
Many thanks, Vasily!  I realized that the question, perhaps, would have been better suited for stackoverflow. But you answered it, spent a lot of time on it, downloading the software and everything, and even solved it! I'm grateful!

**Comment by vasily-v-ryabov** [comment]
You're welcome! There is no much difference. :)
https://stackoverflow.com/tags/pywinauto/topusers

**Comment by karges612** [comment]
i have a similar issue. i tried the same click_input() method. it does click but some where else.  even after giving 0,0 
below is my screen 
[https://imgur.com/a/qYl7zRg](Screen shot of the application)

**Comment by vasily-v-ryabov** [comment]
@karges612 it could be some DPI issue. Please check your OS settings on font scaling or something like that.

**Comment by karges612** [comment]
@vasily-v-ryabov  not sure what you say exactly.  But I tried using the draw method to draw the rectangle..as I said, I am dealing with a table here In a JavaFX windows application. 
Table is at one place and the program drawing all the borders of all the cells some where else !! 
To be precise some where top and left from the original location.

**Comment by vasily-v-ryabov** [comment]
What is your "Display->Scale layout" value in "System" settings when you right click at Start button on Taskbar?
