### ISSUE TITLE
can you please add following enum_child_windows() function for findwindows.py

### ISSUE THREAD

**Issue by shibingstar** [pywinauto/pywinauto#658]
i need a function to enumerate all child window for a specified window, so I create this new test base on your original enum_windows() test, can you please add this new function to pywinauto? thanks
#=========================================================================
def enum_child_windows(parent_hwnd):
    """Return a list of handles of all the top level windows"""
    windows = []

    # The callback function that will be called for each HWND
    # all we do is append the wrapped handle
    def enum_window_proc(hwnd, lparam):
        """Called for each window - adds handles to a list"""
        windows.append(hwnd)
        return True

    # define the type of the child procedure
    enum_win_proc_t = ctypes.WINFUNCTYPE(
        ctypes.c_int, ctypes.c_long, ctypes.c_long)

    # 'construct' the callback with our function
    proc = enum_win_proc_t(enum_window_proc)

    # loop over all the children (callback called for each)
    win32functions.EnumChildWindows(parent_hwnd,proc,0)

    # return the collected wrapped windows
    return windows

**Comment by airelil** [comment]
Could you please explain the rationale behind this ? What's use case here ? Did you consider using ```BaseWrapper.children``` method ? https://github.com/pywinauto/pywinauto/blob/bb9b6c75105bfa6689a7d09d963a297584ff0cdb/pywinauto/base_wrapper.py#L452

**Comment by shibingstar** [comment]
That seems the same function as i created, thanks for remind.
