### ISSUE TITLE
IsVisible, IsActive, IsEnabled call find_windows implicitly

### ISSUE THREAD

**Issue by moden-py** [pywinauto/pywinauto#66]
`IsVisible, IsActive, IsEnabled` used in `Wait/WaitNot` functions whatever call `find_windows`.
Call `control.IsVisible()` invokes:
1. `WindowSpecification.__getattr__`
2. `_resolve_control`
3.`_get_ctrl`
4. `find_windows`

This case affects the following:
1. You should handle `WindowNotFound` and other exceptions.
2. Since `_resolve_control` internally already have Wait function, the top `Wait/WaitNot` can be executed longer than you expected (+0...+`Timings.window_find_timeout`).
3. Every `IsVisible, IsActive, IsEnabled` call creates a `controls.WrapHandle` instance of the same window/control. This increases consumed resources.

This issue requires a discussion. We can make for example, a cached `controls.WrapHandle`instance, store it in `WrapperObject` and refresh it if needed.
But we should be careful with internal usage and backwards compatibilities. Something like this:

``` python
def WrapperObject(self, cached=False):
    if cached:
        return self._cashed_wrapper_object
    else:
        #refresh & cahce
```

Then one can be used `control.WrapperObject(cached=True).IsVisible()`.

**Comment by airelil** [comment]
Agree, a some degree of optimization for *_resolve_control* should be done. @moden-py, with your new implementations of *Wait* and *WaitNot* (PR #61) *_resolve_control* is going to be used more extensively than before. Managing the cached object can be tricky though. Maybe a hook on a window destroy could come in handy here.

**Comment by moden-py** [comment]
Yes @airelil you are right, but `WaitNot` in last realization as now used a wrapper object methods. It is because criteria `active_only=False` does not match `not active`. So the problem persists even if we decide to roll back. We have to solve it.
A good idea about a hook, how about hook on certain control?

**Comment by vasily-v-ryabov** [comment]
Looks like issue #347 is exactly the same problem that is already fixed. The problem might be wider, but I suggest to open another issue (with more details) if something is still incorrect. Closing.
