### ISSUE TITLE
TreeView .Next() deprecation when calling select(), get_item()

### ISSUE THREAD

**Issue by kooki4** [pywinauto/pywinauto#663]
@vasily-v-ryabov Greetings from Bulgaria ! 
My team has chosen to use pywinauto for automation and I have hit some weird and not very clear things for me:

System:
```python
sys.version
'3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]'
print(pywinauto.__version__)
0.6.5

a = pywinauto.application.Application(backend="win32").connect(process=XXXX)
b = a.window(title_re="XXXX")
c = b.TreeView

type(c)
<class 'pywinauto.application.WindowSpecification'>

c.select("\\Layout Manager")
[Path]\pywinauto\controls\common_controls.py:1522: DeprecationWarning: Method .Next() is deprecated, use .next_item() instead.
cur_elem = cur_elem.Next()
```
---- it select the item, even if i give a child one but it keep throwing the warning

```python
d = c.get_item("\\Layout Manager")
[Path]pywinauto\controls\common_controls.py:1522: DeprecationWarning: Method .Next() is deprecated, use .next_item() instead.
cur_elem = cur_elem.Next()

type(d)
<class 'pywinauto.controls.common_controls._treeview_element'>
```

Q1: Is a correct deprecate warning, do I need to disable it ? I tried to disable the warning with no luck..
Q2: Since I am inexperience do you have an examples somewhere how to work with TreeView except the docs

Warning disable, both did not stop the warning:
```python
>>> import warnings
>>> warnings.filterwarnings("ignore", category=DeprecationWarning)
....
>>> warnings.resetwarnings()
```
.... after the reset calling the same functions return the warning

**Comment by vasily-v-ryabov** [comment]
Hi @kooki4 thanks for reporting! This was mostly fixed in master branch and can be tried so:
```
pip uninstall pywinauto
pip install https://github.com/pywinauto/pywinauto/archive/master.zip
```
The only place where `.Next()` alias is called is method `roots()`. Will fix it before publishing 0.6.6. There are very few issues left: [milestone "pywinauto 0.6.6"](https://github.com/pywinauto/pywinauto/milestone/14).

**Comment by airelil** [comment]
> Q2: Since I am inexperience do you have an examples somewhere how to work with TreeView except the docs

I always encourage devs to look into unittests this is usually most updated and always working code.
win32 backend:
https://github.com/pywinauto/pywinauto/blob/82344ab2e61679854315f375f8b51fe53939a2a6/pywinauto/unittests/test_common_controls.py#L561
https://github.com/pywinauto/pywinauto/blob/82344ab2e61679854315f375f8b51fe53939a2a6/pywinauto/unittests/test_common_controls.py#L697

uia backend:
https://github.com/pywinauto/pywinauto/blob/82344ab2e61679854315f375f8b51fe53939a2a6/pywinauto/unittests/test_uiawrapper.py#L1575

**Comment by vasily-v-ryabov** [comment]
Sorry, this was fully fixed in fact. So marking as duplication of #539.
