### ISSUE TITLE
Is there any chance not auto load the uia mode.

### ISSUE THREAD

**Issue by a358003542** [pywinauto/pywinauto#665]
I am test on the xp machine on some reason, and if the windows xp is complete there is not problem, but if I in the some kind ghost xp system, maybe the system is not complete, then load pywinauto 3.6.5 module on python 3.4 cause a error. 

based on the error info , that is becasue of pywinauto auto load the UIA mode , but lately i am not use the UIA mode at all . so , is there any chance the pywinauto module not auto load the UIA mode .

Here if i change the UIA_support = False and everything goes fine.

```
try:
    # Disable 'INFO' logs from comtypes
    log = logging.getLogger('comtypes')
    log.setLevel('WARNING')
    import comtypes  # noqa: E402

    UIA_support = False
except ImportError:
    UIA_support = False
```

Or maybe give a option give user a handler to turn it on . I am not familar with the pywinauto moduel inside.

**Comment by vasily-v-ryabov** [comment]
```
pip uninstall comtypes
```

**Comment by a358003542** [comment]
So the pywinauto module is rely on the comtypes only if when i need the UIA mode , if not , I can uninstall it ?

**Comment by lld2001** [comment]
@a358003542 My os is XP. Could you please help me. Which version of pywinauto do you use in Windows XP? And which version of pywin32?
