### ISSUE TITLE
Backend UIA locks main thread [HOW TO]

### ISSUE THREAD

**Issue by SaadeMotion** [pywinauto/pywinauto#666]
Hello, I have successfully automated an internal software here using WIN32 backend.
But, using win32 i cant get toggle state of checkboxes (always return 0/False), so i'm using UIA as backend for now.

# The problem 
Using UIA, when a "Select File" window appears, it freezes the main thread,  so i cant do a thing while the "Select file" window is opened, **not even a print()**!!

How do i handle this window whithout locking the thread (i need to do stuff with this window, like set_edit_text() to choose a file for me )

![how_to_handle_this_windoww](https://user-images.githubusercontent.com/14329460/51993509-253d9d00-2496-11e9-98dd-cff0dbc56a7e.gif)

**Comment by SaadeMotion** [comment]
For now, i'm executing the .click() in a new thread and not waiting for it (cause it locks itself), then my code can run.

**Comment by vasily-v-ryabov** [comment]
Sometimes `InvokePattern` (`.click()` is an alias of `.invoke()`) is implemented as blocking on app side. I would say it's an app side issue decreasing testability. Glad you could workaround it.

**Comment by SaadeMotion** [comment]
Yeah, this app is poorly coded in Delphi (Bordland), so i stick with:

```
button = self.app.window(auto_id=auto_id)
Thread( target=lambda: button.click() ).start()

## Now the main thread is free to continue the code
## Some code that checks every 1 seg if window is opened (while)
## ....
```
