### ISSUE TITLE
 Wheel support 

### ISSUE THREAD

**Issue by SecT0uch** [pywinauto/pywinauto#670]
I'm distributing my software using pynsist.
It allows to import packages on a chosen version only if a .whl is available on pypi.
It would be much more easy to distribute.
Would it be possible to do it and publish future releases with a wheel file ?

**Comment by vasily-v-ryabov** [comment]
Posted release 0.6.6 with `.whl` file. Please check it on your side. Especially with Python 2.7.

**Comment by SecT0uch** [comment]
Just tested with python 3.7.1 and it works perfectly.
Unofortunately I have not the possibility to try it with python 2.7.
