### ISSUE TITLE
disable user keyboard, mouse input ?

### ISSUE THREAD

**Issue by parlar** [pywinauto/pywinauto#673]
Hi, 

Some methods/functions such as ```click_input()``` can be disturbed by user input. Is there a recommended way to prevent this risk? Temporarily disable user mouse/keyboard input?

**Comment by vasily-v-ryabov** [comment]
Hi @parlar good question. There is Win32 API function [BlockInput](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-blockinput). It can be used so (at your own risk):
```python
import ctypes
from ctypes import wintypes

BlockInput = ctypes.windll.user32.BlockInput
BlockInput.argtypes = [wintypes.BOOL]
BlockInput.restype = wintypes.BOOL

blocked = BlockInput(True)
if blocked:
    try:
        pass # do something
    finally:
        unblocked = BlockInput(False) # unblock in any case
else:
    raise RuntimeError('Input is already blocked by another thread!')
```

**Comment by vasily-v-ryabov** [comment]
Never used this function before. Could you play with various scenarios and provide a feedback on this experience?

**Comment by parlar** [comment]
Of course! I tried a method using pyhook that didn't work.  Will try ctypes.

**Comment by parlar** [comment]
hm .. works when privileges are elevated (as administrator) but not as a regular user. Then ```BlockInput(True)``` returns 0. 

Trying to figure out a way around this ..

**Comment by parlar** [comment]
Argh!! 

.. One way might be to spawn a separate process with elevated privileges using CreateProcessAsUser, but it seems awfully complicated. Another way might be to temporarily block/disable the usb ports where mouse and keyboard are connected. This might work as a regular user but neither method seem ideal.

**Comment by rajeshkhadka123** [comment]
does it work ??

**Comment by BluelyTASer** [comment]
> Hi @parlar good question. There is Win32 API function [BlockInput](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-blockinput). It can be used so (at your own risk):
> 
> ```python
> import ctypes
> from ctypes import wintypes
> 
> BlockInput = ctypes.windll.user32.BlockInput
> BlockInput.argtypes = [wintypes.BOOL]
> BlockInput.restype = wintypes.BOOL
> 
> blocked = BlockInput(True)
> if blocked:
>     try:
>         pass # do something
>     finally:
>         unblocked = BlockInput(False) # unblock in any case
> else:
>     raise RuntimeError('Input is already blocked by another thread!')
> ```

If you start a script without BlockInput(False), then you unfortunately need to reinstall windows 10 inorder to fix this, or am I wrong? 🤔

**Comment by vasily-v-ryabov** [comment]
Hi @BluelyTASer I've never tried this code in reality. :)

**Comment by D4v1dW3bb** [comment]
> 
> 
> > Hi @parlar good question. There is Win32 API function [BlockInput](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-blockinput). It can be used so (at your own risk):
> > ```python
> > import ctypes
> > from ctypes import wintypes
> > 
> > BlockInput = ctypes.windll.user32.BlockInput
> > BlockInput.argtypes = [wintypes.BOOL]
> > BlockInput.restype = wintypes.BOOL
> > 
> > blocked = BlockInput(True)
> > if blocked:
> >     try:
> >         pass # do something
> >     finally:
> >         unblocked = BlockInput(False) # unblock in any case
> > else:
> >     raise RuntimeError('Input is already blocked by another thread!')
> > ```
> 
> If you start a script without BlockInput(False), then you unfortunately need to reinstall windows 10 inorder to fix this, or am I wrong? 🤔

The system will unblock input in the following cases:

   -  The thread that blocked input unexpectedly exits without calling BlockInput with fBlock set to FALSE. In this case, the system cleans up properly and re-enables input.
  -  The user presses CTRL+ALT+DEL or the system invokes the Hard System Error modal message box (for example, when a program faults or a device fails).
 
see: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-blockinput

**Comment by AhmedAhmedEG** [comment]
@vasily-v-ryabov Will you integrate this feature in PyWinAuto?

**Comment by KendoClaw1** [comment]
> ```python
> ctypes.windll.user32.BlockInput
> ```

can u selectively block only mouse?

**Comment by AhmedAhmedEG** [comment]
> @AhmedAhmedEG there are no such plans. Do you think it is really necessary?

Well, sometime it's crucial to prevent the user from moving the mouse by mistake or he will cause a fatal error in the automation workflow, just the mouse input is the problem here, the keyboard input is not that big of a deal.
