### ISSUE TITLE
automating application developed in Qt using pywinauto,print_control_identifiers() cannot print the controls 

### ISSUE THREAD

**Issue by qdwangjianjun** [pywinauto/pywinauto#678]
When automating application developed in Qt using pywinauto,the inspect++ shows there are many controls ,  as in the picture.
But the app_window.print_control_identifiers() cannot print the controls.only print the QWidget object for the entire application or window.

code："app_window = app["HiServer"]
app_window.print_control_identifiers()"
result：“Qt5QWindowIcon - 'HiServer'    (L0, T0, R1920, B1040)
['HiServer', 'Qt5QWindowIcon', 'HiServerQt5QWindowIcon']
child_window(title="HiServer", [class_name="Qt5QWindowIcon")"

![image](https://user-images.githubusercontent.com/40756962/53232240-a23ee980-36c5-11e9-92c1-bc18f7697093.png)

**Comment by airelil** [comment]
Probably related to #596 . Try to follow @vasily-v-ryabov 's suggestion: https://github.com/pywinauto/pywinauto/issues/590#issuecomment-435698581. Get the main window and try to access its child by specifying the criteria based on info from Inspect++. The trick is to add "visible_only=False'

**Comment by qdwangjianjun** [comment]
Thanks for your help. It has resovled my issue.

**Comment by playing4living** [comment]
I am a totally newbie, but I solved this two way by using this two crutches:
1. For the first I just opened inspector.exe for a few seconds and killed it from a thread, all worked but I didn't like the solution. Then I tried to apply suggestion in #590 and it's led me to this:
2.
app = Application(backend="uia").start(r"my_app.exe", wait_for_idle=False)
sleep(4)
app = Application(backend="uia").connect(title=u'my_title', class_name='QWidget', visible_only=False)
app_win = app.window(title=u'my_title', class_name='QWidget', visible_only=False)
app_win.print_control_identifiers(filename="NUL")
app_win.print_control_identifiers(filename="NUL")
app_win.print_control_identifiers(filename="NUL")

app = Application().connect(title=u'my_title', class_name='QWidget', visible_only=False)
qwidget = app.QWidget
qwidget.print_control_identifiers(filename="out.txt")

**Comment by vasily-v-ryabov** [comment]
Hi @playing4living thanks for reporting it. We pay attention to workaround many Qt5 bugs regularly. For example, we introduced alternative way to walk the hierarchy in `atspi` branch:
```python
pywinauto.windows.uia_element_info.UIAElementInfo.use_raw_view_walker = True
```
By default it is `False` for performance reasons.

How to install `atspi` branch (with some other re-factoring so please be ready to adapt your code and read error messages carefully):
```
pip uninstall -y pywinauto
pip install https://github.com/pywinauto/pywinauto/archive/refs/heads/atspi.zip
```
