### ISSUE TITLE
how to get the reference of already launched application

### ISSUE THREAD

**Issue by prathibha-ashok** [pywinauto/pywinauto#683]
Hi Vasily,

I have created an object map file which includes all the objects present in my application based on the app value as below.

for ex:
app = Application(backend='uia').start(appPath)
objButton = app.window(title='xyz').window(control_type='Button', found_index=0)

Value of 'app' will get change if i reopen the application and hence objButton will be invalid.
Is there any method to get the reference of already opened application by providing any parameter?

Note: I am using pyatom/atomac to test the same application in MAC machine. I am using getAppRefByBundleID(bundleId) method to get the reference of application. So whenever i reopen the application, i just call this method and update all the objects in object map.

Thanks in advance.

**Comment by airelil** [comment]
@prathibha-ashok , sounds like you have to use [connect](https://pywinauto.readthedocs.io/en/latest/HowTo.html?highlight=connect#how-to-specify-a-usable-application-instance) method.  After the reconnection, the second line from your example should just work:
```python
app = Application(backend='uia').connect(appPath)
objButton = app.window(title='xyz').window(control_type='Button', found_index=0)
```

**Comment by prathibha-ashok** [comment]
connect method is working fine in my case.
Thank you so much for the on time help.
