### ISSUE TITLE
How to Monitor clickable button which changes from start to stop state using pywinauto module in python

### ISSUE THREAD

**Issue by Nagesh1504** [pywinauto/pywinauto#693]
i am trying to automate an windows application which has a button called start/stop. This button will automatically changes (start to stop) when user click on start button.
Here my question is that How i can monitor this button using pywinauto module

**Comment by vasily-v-ryabov** [comment]
Hi @Nagesh1504 if your script is running continuously, it's better to remember wrapper object for this button and check its `.window_text()` in a loop. Saving `.wrapper_object()` to a variable can guarantee you deal with the same control without repeating search procedure which is called automatically if you call some method for `WindowSpecification`.

It's also possible to subscribe on PropertyChanged events using MS UI Automation API, but it's more complicated way for now.

**Comment by Nagesh1504** [comment]
Thanks for the help :)
