### ISSUE TITLE
Fix text setting methods with unicode input arguments (backward compatibility with 0.4.2)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#70]
For example, `TypeKeys` fails so:
```
File "C:\Python27\lib\site-packages\pywinauto\controls\HwndWrapper.py", line 1136, in TypeKeys
    self.actions.log('Typed text to the ' + self.FriendlyClassName() + ': ' + str(keys))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-10: ordinal not in range(128)
```

Adding unit tests for that is also important.

**Comment by vasily-v-ryabov** [comment]
All `str()` type conversions should probably be replaced with `six.text_type`.

**Comment by vasily-v-ryabov** [comment]
Current implementation of `TypeKeys` uses `win32api.keybd_event` that doesn't support Unicode.
Previously `SendInput` function was used. It does support Unicode, but it's less reliable.

This is a useful guide about [Keyboard Input](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645530.aspx). Switching keyboard layout (locale) may help fixing some issues for 2 languages case. But what's about generic Unicode?

**Comment by vasily-v-ryabov** [comment]
`SendInput()` works well for 32-bit apps. But for 64-bit ones it returns 0 and the characters are typed into the Python process. I found the problem in `AttachThreadInput` calls inside the `TypeKeys` method and fixed it (incorrect target process thread it was taken). I've also fixed similar problem in `_perform_click` function (not committed yet).

But `SendInput()` still fails for 64-bit case.

**Comment by vasily-v-ryabov** [comment]
It seems we need to initialize `dwExtraInfo` pointer in `KEYBDINPUT` structure with `GetMessageExtraInfo()` call.

[This StackOverflow question](http://stackoverflow.com/questions/8962850/sendinput-fails-on-64bit) was helpful.

**Comment by vasily-v-ryabov** [comment]
In fact it's a problem with structures alignment. I found it [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/627b1c8c-0b75-4f73-9e29-3e17e93d539a/sendinput?forum=windowscompatibility) right after "accepted" answer.

It's a perfect win, guys! :)

**Comment by airelil** [comment]
@vasily-v-ryabov, good point! I think the alignment should be checked everytime we have a problem of this kind. (Works on x86, but not x64)
