### ISSUE TITLE
Error returned by CreateProcess: (740, 'CreateProcess', 'The requested operation requires elevation')

### ISSUE THREAD

**Issue by lijin132** [pywinauto/pywinauto#700]
当我使用Application().start()某一软件时会提示这个错误，当执行notepad，calc就没有问题

**Comment by lijin132** [comment]
When I use Application (). start () a software, I will prompt for this error.  But when I execute notepad, Calc has no problem.

**Comment by lijin132** [comment]
Error returned by CreateProcess: (740, 'CreateProcess', 'Error returned by CreateProcess: (740, 'CreateProcess', '请求的操作需要提升。'。'

**Comment by lijin132** [comment]
Error returned by CreateProcess: (740, 'CreateProcess', '  Request operations need to be upgraded'

**Comment by nwillemse** [comment]
I had the same issue.  There are two possible solutions:

1) Use Popen with shell=True to open the application

2) Change you group policy security as follows:

- run gpedit.msc
- Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options and disable the following two options
A) 	User Account Control: Admin Approval Mode for built in Administrator account
B)	User Account Control: Run all administrators in Admin Approval Mode
- Reboot

**Comment by vasily-v-ryabov** [comment]
Obviously the child process requests higher privileges than Python process has. So you have to run Python script as Administrator anyway. It's not possible to automate many actions for an app with higher privileges. That's why we're not willing to change `CreateProcess` to `ShellExecute` or whatever. It simply doesn't make sense.

**Comment by lijin132** [comment]
> Obviously the child process requests higher privileges than Python process has. So you have to run Python script as Administrator anyway. It's not possible to automate many actions for an app with higher privileges. That's why we're not willing to change `CreateProcess` to `ShellExecute` or whatever. It simply doesn't make sense.

thank you very much,the problem has been solved.
