### ISSUE TITLE
dialogs fail to implement __getitem__ 

### ISSUE THREAD

**Issue by bernd-wechner** [pywinauto/pywinauto#707]
This is a tad puzzling and for now just an empirical observation (I haven't drilled into the code to find out why).

But basically I I have a an app, and I can open a dialog box in that app and on that dialog box is a Help button. I want to fetch me that button and observe:

`app.top_window()["Help"]`

works fine.

but that's rather uncool in a sense as the Help button is on the dialog on on the top window so trying to do it better:

`dialog = app.top_window()["DialogTitle"]`

is totally fine and returns me the dialog. Then:

`dialog["Help"]`

bombs with:

`AttributeError: The control does not have a __getitem__ method for item access (i.e. ctrl[key]) so maybe you have requested this in error?`

but:

`dialog.Help`

returns the button!

Inconsistent behaviour and traps me a bit. I can't use attributes as in my code I do't know it's called Help at that point, it's in a variable, and I can find the button from the top_window using the dictionary access method but that's not kosher (if there are any ambiguities, other windows open with help buttons, I'm in trouble) but form the dialog I cna't use the dictionary access method.

For now, my work around is to use the top_window().

**Comment by vasily-v-ryabov** [comment]
This is already tracked in #570 targeted for next major release.
