### ISSUE TITLE
print_control_identifiers() for apps in Microsoft store

### ISSUE THREAD

**Issue by New2Python** [pywinauto/pywinauto#711]
Hi,

I see the below error when i try to print_control_identifiers() for Netflix app from Microsoft Store but the same error is not seen when i tried Movies & TV app or Skype app.
```python
>>> from pywinauto import Desktop
>>> dlg_desktop = Desktop(backend="uia")["Netflix"]
>>> dlg_desktop.print_control_identifiers()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\application.py", line 598, in print_control_identifiers
    all_ctrls = [this_ctrl, ] + this_ctrl.descendants()
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\base_wrapper.py", line 494, in descendants
    return [self.backend.generic_wrapper_class(element_info) for element_info in desc_elements]
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\base_wrapper.py", line 494, in <listcomp>
    return [self.backend.generic_wrapper_class(element_info) for element_info in desc_elements]
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 186, in __new__
    return super(UIAWrapper, cls)._create_wrapper(cls, element_info, UIAWrapper)
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\base_wrapper.py", line 127, in _create_wrapper
    new_class = cls_spec.find_wrapper(element_info)
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 159, in find_wrapper
    if element.control_type in UiaMeta.control_type_to_cls:
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\uia_element_info.py", line 250, in control_type
    return self._get_control_type()
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\uia_element_info.py", line 112, in _get_current_control_type
    return IUIA().known_control_type_ids[self._element.CurrentControlType]
KeyError: 0
```
Please let me know if i'm doing something wrong.

Thanks in advance.

**Comment by vasily-v-ryabov** [comment]
Hi @New2Python I could reproduce the issue on my side and found an element with invalid control type as shown in `Inspect.exe`:
```
ControlType:	Warning: Invalid Control Type Value (0x0)
```
We should definitely handle this situation more flexibly. This is the first such report. Thanks!

**Comment by New2Python** [comment]
@vasily-v-ryabov Not sure if this is related information, but when I changed the backend to win32, looks like print_control_identifiers() worked.

>>> from pywinauto import Desktop
>>> dlg = Desktop(backend="win32")["Netflix"]
>>> dlg.print_control_identifiers()
Control Identifiers:

ApplicationFrameWindow - 'Netflix'    (L236, T0, R1458, B959)
['Netflix', 'ApplicationFrameWindow', 'NetflixApplicationFrameWindow', 'Netflix0', 'Netflix1']
child_window(title="Netflix", class_name="ApplicationFrameWindow")
   |
   | ApplicationFrameTitleBarWindow - ''    (L247, T0, R1447, B48)
   | ['ApplicationFrameTitleBarWindow', 'NetflixApplicationFrameTitleBarWindow', 'ApplicationFrameTitleBarWindow0', 'ApplicationFrameTitleBarWindow1']
   | child_window(class_name="ApplicationFrameTitleBarWindow")
   |
   | Windows.UI.Core.CoreWindow - 'Netflix'    (L247, T48, R1447, B948)
   | ['NetflixWindows.UI.Core.CoreWindow', 'Netflix2', 'Windows.UI.Core.CoreWindow']
   | child_window(title="Netflix", class_name="Windows.UI.Core.CoreWindow")
   |    |
   |    | Windows.UI.Core.CoreComponentInputSource - 'CoreInput'    (L258, T96, R258, B96)
   |    | ['CoreInput', 'CoreInputWindows.UI.Core.CoreComponentInputSource', 'Windows.UI.Core.CoreComponentInputSource']
   |    | child_window(title="CoreInput", class_name="Windows.UI.Core.CoreComponentInputSource")
   |    |
   |    | Internet Explorer_Server - ''    (L247, T48, R247, B48)
   |    | ['NetflixInternet Explorer_Server', 'Internet Explorer_Server']
   |    | child_window(class_name="Internet Explorer_Server")
   |
   | Windows.UI.Core.CoreComponentInputSource - 'CoreInput'    (L258, T96, R258, B96)
   | ['CoreInput', 'CoreInputWindows.UI.Core.CoreComponentInputSource', 'Windows.UI.Core.CoreComponentInputSource']
   | child_window(title="CoreInput", class_name="Windows.UI.Core.CoreComponentInputSource")
   |
   | Internet Explorer_Server - ''    (L247, T48, R247, B48)
   | ['NetflixInternet Explorer_Server', 'Internet Explorer_Server']
   | child_window(class_name="Internet Explorer_Server")
   |
   | ApplicationFrameTitleBarWindow - ''    (L247, T0, R247, B0)
   | ['', 'ApplicationFrameTitleBarWindow2']
   | child_window(class_name="ApplicationFrameTitleBarWindow")
   |
   | ApplicationFrameInputSinkWindow - ''    (L247, T48, R1447, B948)
   | ['NetflixApplicationFrameInputSinkWindow', 'ApplicationFrameInputSinkWindow']
   | child_window(class_name="ApplicationFrameInputSinkWindow")


Thank you.

**Comment by New2Python** [comment]
Thank you @vasily-v-ryabov and @airelil . 
I used the change in Merge request #718 on my current pywinauto version and do not see the issue anymore.
