### ISSUE TITLE
Build docs on AppVeyor and push them into pywinauto.github.io automatically

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#72]
1. Docs can be built using sphinx (need to install it for separate "docs builder" env).

2. "_static" and "_source" folders should be renamed to "static" and "source" respectively (to be able to show them in public URL). All links in HTML files should also be corrected by a docs builder script.

3. Then we need to commit built docs to https://github.com/pywinauto/pywinauto.github.io. How to do it from AppVeyor: http://www.appveyor.com/docs/how-to/git-push

**Comment by airelil** [comment]
Running it as a separate 'docs builder' can be problematic because it won't be aware of the whole matrix status. As a result, the documents will always get built and pushed to pywinauto.github.io

**Comment by vasily-v-ryabov** [comment]
@airelil , good point. Probably `on_success` step is the right place for building docs.
Also building PyPI-compatible .zip archive (by `setup.py build` and `setup.py sdist --format=zip`) would be useful for faster release process.

**Comment by airelil** [comment]
Regarding *_static/_source* folders. It looks that a special file, *.nojekyll*, has to be added to the root dir in order to allow processing of names that begin with underscores. Source: http://stackoverflow.com/questions/6397780/names-starting-with-underscore-shows-errors-page-doesnot-exists-for-gh-pages-bra/6398875#6398875

**Comment by vasily-v-ryabov** [comment]
@airelil , great finding! That allows us to get rid of one annoying step in the chain.

**Comment by airelil** [comment]
I moved *static / source* folder to *_static / _source*. Changes are pushed into pywinauto.github.io@f5f31b2a4e228df6497f1f81767e82505d23bd1e

I discovered that there are link errors in the generated docs:
```
Error: URLError:  The system cannot find the file specified: 
u'..\\pywinauto.github.io\\docs\\code\\class-pywinauto.controls.HwndWrapper.HwndWrapper.html'
u'..\\pywinauto.github.io\\docs\\code\\pywinauto.controlscommon_controls.html'
```
class-pywinauto.controls.HwndWrapper.HwndWrapper.html  -> pywinauto.controls.HwndWrapper.html
pywinauto.controlscommon_controls.html -> pywinauto.controls.common_controls.html

**Comment by vasily-v-ryabov** [comment]
Great! It looks like some source *.txt files in the `doc_src\code` subfolder are generated with corrupted links. Some top level doc sources like `controls_overview.txt` can be fixed manually.

@airelil confirmed he is figuring out how `doc_src\*.py` files should be used by sphinx commands to re-generate `doc_src\code` folder. These *.py files may require some fixes as well.

**Comment by airelil** [comment]
I try to mock up win32* modules to enable the documentation generation with RTD. It looks as early imports of ```findwindows``` and others modules from ```__init__``` prevent the proper mocking up. The question is, do we need all these imports in ```__init__```? 

I tried to comment most of the imports and run a couple of unit tests. It's still working for me. Didn't try it on the latest branch though.
```python
from __future__ import absolute_import

__version__ = "0.5.3"

#from . import findwindows
#WindowAmbiguousError = findwindows.WindowAmbiguousError
#WindowNotFoundError = findwindows.WindowNotFoundError
#
#from . import findbestmatch
#MatchError = findbestmatch.MatchError
#
#from .application import Application, WindowSpecification
```

**Comment by vasily-v-ryabov** [comment]
`Application` class import might be useful and probably used by many people. `findwindows` and `findbestmatch` imports are not so obviously necessary. So in case RTD experiments show successful mocking up I vote for re-considering necessity of all these imports.

**Comment by airelil** [comment]
You are right, let's see if I get to something on RTD. It still doesn't work for me so far.

**Comment by vasily-v-ryabov** [comment]
I think we can close it since we're relying on ReadTheDocs that works fine for us now.
