### ISSUE TITLE
Does pywinauto use the Windows Automation API?

### ISSUE THREAD

**Issue by shreyasparbat** [pywinauto/pywinauto#721]
I was reading the docs but could not figure out whether pywinauto uses the [Windows Automation API](https://docs.microsoft.com/en-us/windows/desktop/winauto/windows-automation-api-portal) or not. If so, can it do everything the Automation API can or do I need to use .net to harness the full capabilities of the API?

I'd love to use and help further develop this tool, but I'm a bit concerned about how robust it is.

Thank you so much in advance!

**Comment by vasily-v-ryabov** [comment]
Replied on StackOverflow: https://stackoverflow.com/q/55873524/3648361

**Comment by vasily-v-ryabov** [comment]
> I'd love to use and help further develop this tool, but I'm a bit concerned about how robust it is.

We appreciate any help. If you're interested to contribute, this is cool. Unfortunately we have no good public picture of the library architecture which might be helpful to you. Just a small draft of the [Contribution Guide](https://github.com/pywinauto/pywinauto/wiki/Contribution-Guide-(draft)).

The highest priority efforts are on UI recorder implementation using UI Automation API features (see PR#701) for now. It will make difference in the next major [release 0.7.0](https://github.com/pywinauto/pywinauto/milestone/10) with some other re-design breaking backward compatibility.
