### ISSUE TITLE
I can't read the inner text of the object HwndWrapper

### ISSUE THREAD

**Issue by FerneyDiaz** [pywinauto/pywinauto#725]
I wanna get text of the object HwndWrapper but when I try get the data with the next code doesn't return none:
```python
from pywinauto.application import Application
app = Application().start(cmd_line u'"C:\\app.exe"')
role = app[u'Datos Generales']
table = role[u'1']
dataTable = table.texts()
```

The previus code doesn't return none.

I appreciate your collaboration with a solution
Thanks

**Comment by airelil** [comment]
Hi @FerneyDiaz, you didn't provide much information about your application, so it's hard to give any sensible tip here. For beginners, usually, we recommend to get familiar with the Pywinauto principals through reading https://pywinauto.readthedocs.io/en/latest/getting_started.html and getting a grip on GUI inspection tools, such as: Inspect.exe or Spy++. For example, the Inspect.exe utility could show you the controls heirarchy of the application that you try to automate and would provide you with additional details about the GUI elements. At its most basic, if you can't see the text you are looking for in the Inspect.exe you, probably, will have hard times with accessing it through a pywinauto.

**Comment by vasily-v-ryabov** [comment]
Hi @FerneyDiaz maybe it's worth trying `Application(backend="uia")` which should have more chances to deal with data grid (is it WinForms DataGrid?). Many things are application specific or GUI framework specific. So it's important to know what kind of app you're trying to automate. It should be included into full technical description.

**Comment by FerneyDiaz** [comment]
ok @vasily-v-ryabov my app is the next:

![inspect](https://user-images.githubusercontent.com/38636320/57334951-d6cc1a00-70e6-11e9-81f3-87bf0e16ed8d.png)
![swapy](https://user-images.githubusercontent.com/38636320/57334956-d92e7400-70e6-11e9-9922-f97b7e98ea64.png)

The problem is that no app "inspect or SWAPY can get the text inner the panel but I need that information.

Maybe you have some idea how I get the data inside the table inside the panel.

Thanks

**Comment by FerneyDiaz** [comment]
Hello.

I test with `.type_keys("^a^c") and `pywinauto.clipboard` but it not is possible because pywinauto doesn't get text inside this panel and I don't have the source code because this module was development for other person.

You have some idea what's the problem, why y can't get text inside this tables and why the inpect or other app like inspect can't recognizes those tables or grids in desktop apps 

Thanks.

**Comment by vasily-v-ryabov** [comment]
As I said MFC doesn't support standard GUI automation interfaces for Grid while more modern WPF and WinForms does.

Some custom Grid implementations for MFC may implement window messages handlers that can be used for automation in `backend="win32"` on pywinauto side. But these window messages must be known and described somewhere (usually only GUI component source code may contain this info).

So if you're unlucky with Ctrl+A and Ctrl+C approach, I'm not optimistic about technical possibility to resolve your problem.

**Comment by githubcyc** [comment]
You may try followings,
```
for c in role.children():
     print(c)
     print(c._element_info.name)
```
