### ISSUE TITLE
How do you hold right click in a background window?

### ISSUE THREAD

**Issue by Florrdv** [pywinauto/pywinauto#731]
I am currently trying to make a script that holds right click in a background window but I can't get it to work. The `pywinauto.mouse.press` function looks like it's perfect for this but I'm not sure how I send the keypress to a certain background window.`

**Comment by vasily-v-ryabov** [comment]
Module `pywinauto.mouse` requires window to be in focus. Wrapper objects have method `.set_focus()` before calling `.click_input()` method. If you don't want to bring the window into foreground, it might be not possible to send corresponding event. But you may have chances if more details are provided. Which backend is used? How the app looks like? I mean on which GUI framework it is based on: MFC, WinForms, WPF, Qt5? Screenshots from `Inspect.exe` in UI Automation mode would be useful as well.

**Comment by JGSgamer** [comment]
The only thing I know off the top of my head is that the application is written in java.
