### ISSUE TITLE
How to get the index number of an object by its name

### ISSUE THREAD

**Issue by prathibha-ashok** [pywinauto/pywinauto#743]
Hi,

Is there any method/way to get the index number of an object by providing its name/control_type or both.
Please let me know if any.
Thanks in advance.

**Comment by vasily-v-ryabov** [comment]
```python
all_sub_tree_list = app.MainWindowTitle.descendants()
all_names = [w.window_text() for w in all_sub_tree_list]
all_names.index("Target name")

all_control_types = [w.control_type() for w in all_sub_tree_list]
all_control_types.index("Button") # index of the first inclusion
```

**Comment by vasily-v-ryabov** [comment]
It's Python related question. Nothing special to pywinauto. You can do whatever you want with the list returned by `.descendants()`.

**Comment by prathibha-ashok** [comment]
Thanks for the answer.
I am currently getting the index number using python login but I just wanted to know, whether any direct method exists in order to get the index number.
