### ISSUE TITLE
is_visible returns True for some not existing elements

### ISSUE THREAD

**Issue by Arching-Noradan** [pywinauto/pywinauto#772]
## Short Example of Code to Demonstrate the Problem
```
from pywinauto.application import Application

app = Application(backend="uia").start('notepad.exe')


foo = [
	'Menu',
	'Menufgaf',
	'Menufgaf1543']

for item in foo:
	print(item)
	bar = app.window()[item].is_visible()
	print(bar)
```
## Result:
```
Menu
True
Menufgaf
True
Menufgaf1543
pywinauto.findbestmatch.MatchError: Could not find 'Menufgaf1543' in ....
```

## Question!
Notepad.exe has no element 'Menufgaf'. Why is_visible() function returns True?
## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7.3
  - Platform and OS: Win10

**Comment by airelil** [comment]
I think, it's an effect of applying "best match" algorithm while trying to resolve the UI element name. Have a read at one of our article in the docs: https://pywinauto.readthedocs.io/en/latest/HowTo.html#how-to-specify-a-control-on-a-dialog

**Comment by vasily-v-ryabov** [comment]
Yes, "best_match" algorithm can match items with resistance to typos. If you need exact matching, just use `bar = app.window().child_window(title=item).is_visible()`.
