### ISSUE TITLE
ImportError: cannot import name 'Desktop' from 'pywinauto'

### ISSUE THREAD

**Issue by doverradio** [pywinauto/pywinauto#774]
## Expected Behavior
On a new pc, I installed pywinauto and then try to run:
from pywinauto import Desktop, Application

It's not supposed to throw error but...

## Actual Behavior
Here's the immediate error I get when running that:

ImportError: cannot import name 'Desktop' from 'pywinauto' (`C:\ProgramData\Anaconda3\lib\site-packages\pywinauto\__init__.py`)

## Steps to Reproduce the Problem

  1. `pip install pywinauto==0.5.4`
  2. `from pywinauto import Desktop, Application`
  3. get error: `ImportError: cannot import name 'Desktop' from 'pywinauto'` (`C:\ProgramData\Anaconda3\lib\site-packages\pywinauto\__init__.py`)

## Short Example of Code to Demonstrate the Problem
`from pywinauto import Desktop`

## Specifications

  - Pywinauto version:
  - Python version and bitness:
  - Platform and OS:

**Comment by vasily-v-ryabov** [comment]
pywinauto==0.5.4 is too old. The latest version is 0.6.7 which contains class Desktop. It was introduced in one of 0.6.x releases.
