### ISSUE TITLE
Provide access to title/cuebanner for Edit control

### ISSUE THREAD

**Issue by agusdb** [pywinauto/pywinauto#779]
Edit controls are considered title-less by pywinauto, even though programs like inspect.exe show a title equal to the cue banner. If I want to find a specific edit control based on the cue banner, I have to use `control_type=Edit, predicate_func=lambda e: e.element.CurrentName == name`, because as far as I can tell this property is not surfaced directly by pywinauto at all.

I think either Edit controls should have titles, or they should explicitly expose the cue banner in some obvious way.

**Comment by vasily-v-ryabov** [comment]
Hi @agusdb sorry for delay. Can you try this branch with potential fix?
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/edit_by_title.zip
```
