### ISSUE TITLE
0.6.7 SetForegroundWindow is missing from pywinauto.win32functions

### ISSUE THREAD

**Issue by Fed64** [pywinauto/pywinauto#785]
## Expected Behavior
SetForegroundWindow is present in pywinauto.win32functions

## Actual Behavior
In pywinauto version 0.6.7, SetForegroundWindow is missing from pywinauto.win32functions

## Steps to Reproduce the Problem

  1. Install pywinauto 0.6.6
  2. from pywinauto.win32functions import SetForegroundWindow
  3. notice that no error is shown
  4. upgrade to pywinauto 0.6.7
  5. import the same thing (from pywinauto.win32functions import SetForegroundWindow)
  6. notice the error: SetForegroundWindow is not found in win32functions.py

## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7.3 64bit
  - Platform and OS: PC Windows 10
  - I am using latest version of Pycharm to install pywinauto packages

**Comment by airelil** [comment]
That's correct, the function was removed in https://github.com/pywinauto/pywinauto/commit/326e9b4f707288be9a15678321ac0db6d0f6e9e9 because it's not used by any code in Pywinauto. There are also several other functions removed as well. Do you mind explaining your use case?

**Comment by Fed64** [comment]
I am using SetForegroundWindow in a couple of methods. Here's one:

    def check_if_control_with_text_is_enabled(self, app, control_text):
        result = False
        SetForegroundWindow(app.top_window().wrapper_object())
        all_controls = app.top_window().descendants()
        for ctrl in all_controls:
            if ctrl.texts() == control_text:
                if ctrl.is_enabled() and ctrl.is_visible():
                    result = True
                    break
        return result

The other is quite similar except that it also sends a click_input() to the ctrl. These two methods are used a lot throughout the rest of the code.

**Comment by airelil** [comment]
Pywinauto [uses](https://github.com/pywinauto/pywinauto/blob/85eb12132d475c4ca86625b0afbdfffae59ab753/pywinauto/controls/hwndwrapper.py#L1319) `win32gui.SetForegroundWindow()` from `pywin32` package. You can also switch to this function. Notice that you don't need even need to change the function parameter and still pass down `wrapper_object()`.

**Comment by vasily-v-ryabov** [comment]
Agree with @airelil. Method `.set_focus()` and using wrappers is more preferable. Also `top_window()` is not recommended to use since it takes the window at the moment of call (it can confuse if top window has been switched). We're planning to remove or re-design this method in future releases.

**Comment by vasily-v-ryabov** [comment]
We may return `SetForegroundWindow` to `win32functions` only in one case: if we decide to get rid of `pywin32` dependency for Jython support (and Cucumber BDD framework), for example. But currently there are no enough signals from community to do that.

**Comment by Fed64** [comment]
Thank you for the help. I have decided to use .set_focus() since it works without any other changes.

**Comment by meshko** [comment]
problem is that set_focus() doesn't work if there is no used logged in to the system...

**Comment by LeiYangGH** [comment]
i can use 
`win32gui.SetForegroundWindow(win.wrapper_object().handle)`
