### ISSUE TITLE
ctypes.ArgumentError: argument 1: : expected LP_POINT instance instead of pointer to POINT

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#788]
Reported on StackOverflow:
https://stackoverflow.com/q/57304399/3648361

## Actual Behavior
```python
ctypes.windll.user32.GetCursorPos(ctypes.byref(cursor))
ctypes.ArgumentError: argument 1: : expected LP_POINT instance instead of pointer to POINT
```

## Steps to Reproduce the Problem

  1. Install pywinauto
  2. Install `pyautogui==0.9.47`
  3. Run the mentioned code

## Short Example of Code to Demonstrate the Problem
```python
slider = content_of_page.find_element_by_id("SystemSettings_Display_Brightness_Slider")
slider.click()
pyautogui.dragRel(args.value, 0, duration=1.0, button='left')
pyautogui.click()
```

## Specifications

  - Pywinauto version: unknown
  - Python version and bitness:  unknown
  - Platform and OS: Windows

We should think on how to eliminate such errors even if another library behaves incorrectly. Maybe do explicit type conversion for every Win32 API function call.

**Comment by DoTheBestMayB** [comment]
I use pyautogui==0.9.47, but don't work

```
import pyautogui as pag
pag.position()
```

**Comment by jyoti-python** [comment]
I too getting the same issue when my code steps moves from pywinauto to pyautogui. Commenting pywinauto code and running only pyautogui gives me same error.But if I run the same pyautogui code in separate newly created python file, it works. 
@vasily-v-ryabov , is the issue due to file corruption??? I am clueless why it behaves like that

**Comment by mayurpande** [comment]
Yes I have this issue too, but I am not even running the `pyautogui` code anymore as well. This used to work before

**Comment by vasily-v-ryabov** [comment]
Well, I could reproduce the issue on my side. Technically it's mutual issue of both libraries. Changing order of imports fixes the problem. But I will try to overcome it completely.

**Comment by vasily-v-ryabov** [comment]
You can try early fix by
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/ctypes_conversion_fix.zip
```

**Comment by airelil** [comment]
@vasily-v-ryabov, might be worth exploring an old suggestion from  https://bugs.python.org/issue22552
"""
> If you want cached libs without polluting ctypes.cdll or ctypes.windll, just create your own instance such as windll = ctypes.LibraryLoader(ctypes.WinDLL).
"""

**Comment by vasily-v-ryabov** [comment]
@airelil thanks! This change is much more compact and it seems working perfectly as well.

@DoTheBestMayB @jyoti-python @mayurpande let's check it from this branch:
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/ctypes_windll_loader.zip
```

**Comment by vasily-v-ryabov** [comment]
Well, it is fixed in master branch. Closing it before next release 0.6.8 (hope the last 0.6.x one).
