### ISSUE TITLE
Error importing pywinauto

### ISSUE THREAD

**Issue by xqzts** [pywinauto/pywinauto#804]
If i importing like these:
`from pywinauto import application`
i've got following error:
```
PS Z:\> python.exe D:\temp\policies\pywinauto.py
Traceback (most recent call last):
  File "D:\temp\policies\pywinauto.py", line 1, in <module>
    from pywinauto import application
  File "D:\temp\policies\pywinauto.py", line 1, in <module>
    from pywinauto import application
ImportError: cannot import name 'application' from 'pywinauto' (D:\temp\policies\pywinauto.py)
```

if so:
`from pywinauto.application import Application`
then this:
```
PS Z:\> python.exe D:\temp\policies\pywinauto.py
Traceback (most recent call last):
  File "D:\temp\policies\pywinauto.py", line 2, in <module>
    from pywinauto.application import Application
  File "D:\temp\policies\pywinauto.py", line 2, in <module>
    from pywinauto.application import Application
ModuleNotFoundError: No module named 'pywinauto.application'; 'pywinauto' is not a package
```
and if importing so:
`import pywinauto`
then i got this:
```
PS Z:\> python.exe D:\temp\policies\pywinauto.py
Traceback (most recent call last):
  File "D:\temp\policies\pywinauto.py", line 4, in <module>
    import pywinauto
  File "D:\temp\policies\pywinauto.py", line 10, in <module>
    pywinauto.application.Application().start(f"mmc.exe {mmc_loc}")
AttributeError: module 'pywinauto' has no attribute 'application'
```
my code:

```
import time
import pywinauto

mmc_loc = "mmc_file_location"
managed_group_path = "managed group\path"
groups = ["test"]

pywinauto.application.Application().start(f"mmc.exe {mmc_loc}")
time.sleep(10)
app = pywinauto.application.Application().connect(path="mmc.exe")
tree = app.mmc_main_frame.tree_view
for group in groups:
    folder = tree.get_item(f"{managed_group_path}{group}")
    folder.click()
    items = app.mmc_main_frame.list_view.items()
    for i in range(0, len(items), 2):
        print(items[i].text())
```

Contents of site-packages folder:

PS Z:\> ls C:\python3_32\Lib\site-packages\

    Каталог: C:\python3_32\Lib\site-packages

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       03.09.2019     10:23                adodbapi
d-----       03.09.2019     10:23                comtypes
d-----       03.09.2019     10:23                comtypes-1.1.7-py3.7.egg-info
d-----       03.09.2019     10:23                isapi
d-----       03.09.2019     10:22                pip
d-----       03.09.2019     10:22                pip-19.2.3.dist-info
d-----       03.09.2019     10:18                pkg_resources
d-----       03.09.2019     10:23                pythonwin
d-----       03.09.2019     10:23                pywin32-224.dist-info
d-----       03.09.2019     10:23                pywin32_system32
d-----       03.09.2019     10:23                pywinauto
d-----       03.09.2019     10:23                pywinauto-0.6.7.dist-info
d-----       03.09.2019     10:18                setuptools
d-----       03.09.2019     10:18                setuptools-40.8.0.dist-info
d-----       03.09.2019     10:23                win32
d-----       03.09.2019     10:23                win32com
d-----       03.09.2019     10:23                win32comext
d-----       03.09.2019     10:23                __pycache__
-a----       03.09.2019     10:18            126 easy_install.py
-a----       03.09.2019     10:22            138 pythoncom.py
-a----       03.09.2019     10:22        2650084 PyWin32.chm
-a----       03.09.2019     10:22            395 pywin32.pth
-a----       03.09.2019     10:22              5 pywin32.version.txt
-a----       08.07.2019     19:24            121 README.txt

Windows 10 x64
Python version 3.7.4 x86

**Comment by vasily-v-ryabov** [comment]
Naming script as `pywinauto.py` is completely wrong way. This Python script is obviously interpreted as a module which redefines `pywinauto` package. This is basic question about Python fundamentals.
