### ISSUE TITLE
Add caching of intermediate WindowSpecification widgets.

### ISSUE THREAD

**Issue by pakal** [pywinauto/pywinauto#808]
I often want to browse the GUI in a hierarchical manner, using intermediate parents (found by auto_id, index...) to reach the proper children.

The WindowSpecification stores these steps in the "criteria" lists, and performs a whole lookup of each control when wrapper_object access is triggered, which can be quite slow (I use automation_id much more than faster lookups like class_name).

Since one often wants to perform all kinds of operations on descendants of a control, how about adding some kind of `WindowSpecification .cache()` methods which looks up the currently targeted widget, and uses it directly as "parent" in find_elements() the next time the WindowSpecification is chained to new (sub)criteria?

( This might be slightly related to https://github.com/pywinauto/pywinauto/issues/570 )

**Comment by vasily-v-ryabov** [comment]
I think it's exactly what issue #570 tells about. Anyway let's write additional ideas around it to the original ticket.

I'd recommend to take a look at all these issues first to avoid such duplications:
https://github.com/pywinauto/pywinauto/issues?q=is%3Aissue+is%3Aopen+label%3Arecorder_0_7_0_critical

P.S. Issue #511 suggests another good idea similar to object repository in QTP/UFT commercial tool.
