### ISSUE TITLE
Potential typo bug in pywinauto top-level file.

### ISSUE THREAD

**Issue by pakal** [pywinauto/pywinauto#810]
Line 91 in `pywinauto/__init__.py` we have this code which looks like a typo ("ElementNotFoundError = findwindows.ElementNotFoundError" is duplicated as is), wasn't it supposed to be WindowNotFoundError instead ?

```
    WindowAmbiguousError = findwindows.WindowAmbiguousError
    ElementNotFoundError = findwindows.ElementNotFoundError

    if UIA_support:
        ElementNotFoundError = findwindows.ElementNotFoundError
        ElementAmbiguousError = findwindows.ElementAmbiguousError
```

**Comment by vasily-v-ryabov** [comment]
It seems you're right for `ElementNotFoundError` which was `WindowNotFoundError` a long time ago (when there was no backend concept and Win32 API was the only way).

`WindowAmbiguousError` is not a duplication, but an old alias for backward compatibility. Anyway all this could be cleaned up in current re-factoring. Easy to fix as your first issue. ;)

**Comment by pakal** [comment]
Allright, I'm having a quick look at it -> https://github.com/pywinauto/pywinauto/pull/811
