### ISSUE TITLE
How to close Select Setup Language

### ISSUE THREAD

**Issue by Aechee** [pywinauto/pywinauto#818]
When i run this application, it prompts for Select Setup Language. I tried to Press Okay  on that window, but this does not work. 

```
    app = Application(backend="uia").start("setups/wampserver3.1.7_x64.exe")

    Wizard = app['Select Setup Language']

    Wizard.OK.click_input()
```

How can i click okay on the select setup language window.

**Comment by airelil** [comment]
Looks like the window is forked under another process. We can use Desktop class to find the windows of other processes. I guess, the setup elevates the installation rights to Admin, since the a separate process. So in order to make it work, you also have to run your pywinauto script as Admin.
 
```python
from pywinauto import Application
from pywinauto import Desktop

app = Application(backend="uia").start("setups/wampserver3.1.7_x64.exe")
Wizard = Desktop(backend='uia').Select_Setup_Language
Wizard.OK.click_input()
```

**Comment by Aechee** [comment]
> FYI. The question is also duplicated here: https://stackoverflow.com/q/57895411/3648361

That's my posted question. I did not get any reply.

**Comment by Aechee** [comment]
I have another question.

It works fine for language select. I have window where i have to pro check the I accept the agreement check box and click on Next. 


Title of window is "Setup - Wampserver64 3.1.7"

how can i do thta?

**Comment by airelil** [comment]
The same approach ?
```python
Wizard = Desktop(backend='uia').Setup_Wampserver64
Wizard.i_accept_the_agreement.click_input()
```

**Comment by Aechee** [comment]
I actuallly don't really get these names e.g. how to use Setup_Wampserver64 or i_accept_the_agreement. 

can you explain me, how those names are generated ?

**Comment by Aechee** [comment]
Also i want to wait for the Wizard to complete installlation. How can i handle that ?

**Comment by airelil** [comment]
Pywinauto used 'best match' approach, trying to locate control with similar names.

The documentation maybe not perfect, but still can give you ideas.
https://pywinauto.readthedocs.io/en/latest/getting_started.html#attribute-resolution-magic
https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html

**Comment by Aechee** [comment]
Okay, thank you very much for your help I am closing this issue.
