### ISSUE TITLE
How to access buttons in ToolBarWindow32 control?

### ISSUE THREAD

**Issue by eastam** [pywinauto/pywinauto#822]
I happened to have a software that the Icon Buttons in toolbar are with class "ToolBarWindow32", but I don't found corresponding controls in pywinauto for this class. Only toolbar is the closet one. How can I use toolbar to access buttons for ToolBarWindow32 control? The toolbar in the software is with some big icon and when mouse hove on it, it will become a raised button and could be pressed. 

I also tried different spy tools. 
ViewWizard could only access the whole toolbar (with highlight box out of it).
UIASpy could list the toolbar and its sub Buttons. For each button, there is corresponding property like text, button count etc. 

How can I access the single button in this "ToolBarWindow32" control?

**Comment by eastam** [comment]
What's the relation between ToolBarWindow32 control and ToolBar control? Are they the same? But how to access the ToolBarWindow32 control? It is not in the pywinauto controls.

**Comment by airelil** [comment]
`ToolbarWindow32` control is supported by win32 backend. Have a look here: https://github.com/pywinauto/pywinauto/blob/28a8f5dde2d6d447e5a484639a1872690ff40470/pywinauto/controls/common_controls.py#L2433
However, if you want stick to UIA, you could try to sub-class the toolbar wrapper and then you should be able to get the instance of the class through the regular pywinauto control resolution. For example, for UIA backend, you would do something like this (I didn't run it, just an idea):
```python
import pywinauto.controls.uia_controls as uia_ctls

class ToolbarWindow32Wrapper(uia_ctls.ToolbarWrapper):

    """Subclass UIA ToolBar control"""

    _control_types = ['ToolBarWindow32']

    # -----------------------------------------------------------
    def __init__(self, elem):
        """Initialize the control"""
        super(ToolbarWindow32Wrapper, self).__init__(elem)

# Access it with pywinauto
tb_wrapper = app.top_window().child_window(class_name="ToolBarWindow32").wrapper_object()

```

PS: we might need to add `'ToolBarWindow32` to UIA toolbar wrapper control types

**Comment by eastam** [comment]
> `ToolbarWindow32` control is supported by win32 backend. Have a look here:
> 
> https://github.com/pywinauto/pywinauto/blob/28a8f5dde2d6d447e5a484639a1872690ff40470/pywinauto/controls/common_controls.py#L2433
> 
> 
> However, if you want stick to UIA, you could try to sub-class the toolbar wrapper and then you should be able to get the instance of the class through the regular pywinauto control resolution. For example, for UIA backend, you would do something like this (I didn't run it, just an idea):
> ```python
> import pywinauto.controls.uia_controls as uia_ctls
> 
> class ToolbarWindow32Wrapper(uia_ctls.ToolbarWrapper):
> 
>     """Subclass UIA ToolBar control"""
> 
>     _control_types = ['ToolBarWindow32']
> 
>     # -----------------------------------------------------------
>     def __init__(self, elem):
>         """Initialize the control"""
>         super(ToolbarWindow32Wrapper, self).__init__(elem)
> 
> # Access it with pywinauto
> tb_wrapper = app.top_window().child_window(class_name="ToolBarWindow32").wrapper_object()
> ```
> 
> PS: we might need to add `'ToolBarWindow32` to UIA toolbar wrapper control types

OK. Thanks. I will try it. My understanding is to rebuild a new class for the ToolBarWindow32 to get the control handle. Then for the access of the corresponding Buttons, there still needs some furhter steps like to define more methods for the class like ToolBar one. Currently I think if I have the access to the control itself, I can access the button through coordinate anyway.

**Comment by airelil** [comment]
If you inherit from the UIA ToolbarWrapper you'll get all its methods: `buttons()`, `button()`, `button_count()`, `check_button()`:
https://github.com/pywinauto/pywinauto/blob/03da856d145c9f7056d88738bde1b6b068fd6f94/pywinauto/controls/uia_controls.py#L1085

**Comment by eastam** [comment]
> If you inherit from the UIA ToolbarWrapper you'll get all its methods: `buttons()`, `button()`, `button_count()`, `check_button()`:
> https://github.com/pywinauto/pywinauto/blob/03da856d145c9f7056d88738bde1b6b068fd6f94/pywinauto/controls/uia_controls.py#L1085

OK. Got it and thanks very much. 
I am running in uia backend. I tride following code and find the ToolbarWindow32 could be accessed even without define a new wrapper. 

toolbar = main_wnd.window(control_id=59392, class_name='ToolbarWindow32')  #main_wnd is the handle of the main window, and the control id for ToolbarWin32 is 59392 in my application.
# and then following code works.
button=toolbar.button(r" Refresh ")
button.click()

I can also obtain the button_count, obtain all buttons with toolbar.buttons() and access the corresponding button through index like 
button = toolbar.button(7)
button.click()

 Therefore I think the ToolbarWindow32 is there in the package and could be accessed with uia backend. Maybe one thing is to update the documentation for the controls and then users could know the entry exists.  I stopped to try it just because I don't find an entry in the documentation for the control "ToolbarWindow32".

Thank you very much for your help and thank you all for the great contribution!
