### ISSUE TITLE
How to connect to wifi(SSID) with username and password

### ISSUE THREAD

**Issue by akhilesherwa** [pywinauto/pywinauto#826]
![4207784ac72a7894067c4e45dd627381](https://user-images.githubusercontent.com/55728260/65480393-ec33bc00-deae-11e9-8606-937ca9fcea0c.jpg)

**Comment by airelil** [comment]
You should consider scripting with netsh: https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-contexts
I think, it's more compatible for the task

**Comment by vasily-v-ryabov** [comment]
I'm also not willing to code typical sysadmin task with GUI automation. I'm sure it's technically possible, but makes no sense as too complicated for such easy job. Closing the issue.
