### ISSUE TITLE
if absolute bug?

### ISSUE THREAD

**Issue by Akababa** [pywinauto/pywinauto#835]
Is this a bug?
https://github.com/pywinauto/pywinauto/blob/69eedc759d9327c64305f95ba1b3f1593b0ebd14/pywinauto/controls/hwndwrapper.py#L1676-L1677
Should it be `if not absolute`?

**Comment by airelil** [comment]
I don't see a bug here. If the "absolute" flag is true we translate the coordinates to absolute coordinates on the screen. Usually, coordinates are relative to the window where the control belongs.

**Comment by Akababa** [comment]
In one other place we do the opposite:
https://github.com/pywinauto/pywinauto/blob/69eedc759d9327c64305f95ba1b3f1593b0ebd14/pywinauto/controls/hwndwrapper.py#L849-L850
Should the absolute flag mean that the coordinates passed in are absolute, so if not absolute then we need to translate them?

**Comment by vasily-v-ryabov** [comment]
This is a duplication of issue #540. We need some time to debug it and this is not the highest priority for now. If want to provide any help or discuss something, let's move to #540.
