### ISSUE TITLE
pywinauto to trace, app Identifiers are not found, 

### ISSUE THREAD

**Issue by jjbright** [pywinauto/pywinauto#836]
## Problem Description
Unified Service Desk is a CRM software, which is a desktop application.  Though its a desktop application, it used the browser in the background to handle all the request/response.  
It's like an application, which us SKIN over the browser.
When it was USD 3.3 version, we used inspect.exe to spy the objects and use it in the pywinauto code to execute, the script was working well.  
Now the USD was upgraded to version 4.1, we find the script not working and many identifiers are missing... 

Hence seeking help, please advise how to proceed.... 

## Expected Behavior
Identify the AutomationId while using inspect.exe

## Actual Behavior
AutomationId is not coming

## Steps to Reproduce the Problem
Software used - **Unified Service Desk 4.1** 
Previous version **Unified Service Desk 3.3**
  1. Spy USD 3.3 using inspect.exe, we used to get the AutomationId
  2. Spy USD 4.1 using inspect.exe, we do not get the many identifiers
  3. USD 3.3 was using Internet Explorer in the background, USD 4.1 is using Chrome in the background

## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7 64 bit
  - Platform and OS: Windows 10 64 bit

@vasily-v-ryabov @funkyHat

**Comment by vasily-v-ryabov** [comment]
Hi @jjbright it's a question for app developers if they didn't enable accessibility feature for the used browser engine. For example, pure Chrome browser have to be started with command line option `--force-renderer-accessibility` to provide more info for pywinauto / inspect.exe. So it should be some parameter in browser engine initialization to enable the same thing.

**Comment by jjbright** [comment]
inspect.exe is used to find the elements, so close #836
