### ISSUE TITLE
Question: Is it possble to pass arguments when starting the process?

### ISSUE THREAD

**Issue by fredrikbondesson** [pywinauto/pywinauto#843]
I am trying out pywinauto (coming from another ui automation framework https://github.com/Roemer/FlaUI).

I am trying to automate a windows program that accepts some arguments (from the command line).
Does pywinauto support passing arguments when starting the process?
If answer is no, is there a reason or it?

Regards Fredrik

**Comment by jessicakwilson** [comment]
You can specify command line arguments in the cmd_line parameter of Application.start() like so:

`app = pywinauto.application.Application()`
`app.start(cmd_line=r"c:\myprogram.exe -args")`

**Comment by fredrikbondesson** [comment]
Thanks!
