### ISSUE TITLE
Unable to get the text from a dialog box

### ISSUE THREAD

**Issue by manojsinghal134** [pywinauto/pywinauto#845]
## Steps to Reproduce the Problem
I have a dialogbox with 1 ok button, 1 information icon and 1 label. i am trying to get the label but unable to do so.
![Capture](https://user-images.githubusercontent.com/40144998/68471196-b3c02580-0243-11ea-8921-15f462ea25f0.PNG)

I am able to click on the OK button with
app.Desk.OKButton.set_focus().click()

## Short Example of Code to Demonstrate the Problem

pops=p1.app.window(title='my title', found_index=0)
for x in pops.descendants():
    print (x.window_text())
    print (x.class_name())
    print(x.texts())
    print("*"*5)
## Specifications

  - Pywinauto version:
  - Python version and bitness:
  - Platform and OS:3.7.4/Win 10 64 bit

**Comment by airelil** [comment]
We usually suggest to start with `print_control_identifiers` method. Seems that for your dialog it could be something like: `App.Desk.print_control_identifiers()` . Did you try it? Also, can you see the control in "Inspect.exe" utitlity? (Important to set the inspect.exe into the same mode as your backend: https://pywinauto.readthedocs.io/en/latest/getting_started.html#gui-objects-inspection-spy-tools)

**Comment by manojsinghal134** [comment]
Airelil, First of all thanks for resonding :)

Sad part is print_control_identifiers() doesn't show it. it's show couple of picture boxes and buttons.

inspect/spy++ doesn't capture it. Those are able to highlight button, title, i and nothing else

When i tried to spy it in HP-UFT it is showing it as a vbLabel. I confirmed with the developer of the application, it is a label infact.

WE are planning to move away from UFT to pywinAuto. This pop-up is kind of road blocker for now as the confirmation number is important to perform further actions.

**Comment by airelil** [comment]
Just to make sure, did you try the both backends?

**Comment by manojsinghal134** [comment]
Yes i have tried both, Win32 is showing more objects and none of the backends is showing my object.

**Comment by manojsinghal134** [comment]
Is there any other info i can share which can lead us to resolution?

**Comment by airelil** [comment]
@manojsinghal134 , sorry we are not committed the full time for this project, so some responses can come late... Generally, if inspect.exe doesn't detect the control, it won't be easy to get it in pywinauto. Do you know what frameworks is used for the app. Are you in position to discuss with developers changes to make the application more "accesibility"-friendly?

**Comment by manojsinghal134** [comment]
Np! @airelil . it's built in vb.6 and as it's built on kind of legacy technology, developers will not change it.

**Comment by vasily-v-ryabov** [comment]
In this case I can suggest only some OCR method. You can capture only the rectangle of the smallest element containing this text and then OCR it. The method is called `capture_as_image()`. Example: `.capture_as_image().save("target_rect.png")`

**Comment by manojsinghal134** [comment]
Thank you for the suggestion.
would it be possible to retrieve text from the image then?

**Comment by vasily-v-ryabov** [comment]
No, we don't provide any OCR functions. It's better to use some other Python package like [Lackey](https://github.com/glitchassassin/lackey).
