### ISSUE TITLE
.click() element of control_type=Pane 

### ISSUE THREAD

**Issue by benton-anderson** [pywinauto/pywinauto#860]
I have an element: 
`{'class_name': 'WindowsForms10.Window.8.app.0.3b93019_r36_ad1',
 'friendly_class_name': 'Pane',
 'texts': [' On '],
 'control_id': 328786,
 'rectangle': <RECT L121, T476, R141, B496>,
 'is_visible': True,
 'is_enabled': True,
 'control_count': 0,
 'is_keyboard_focusable': True,
 'has_keyboard_focus': False,
 'automation_id': 'm_7b4cbcbae7174e47929ddd7339f80b0d'}`

`Control Identifiers:
Pane - ' On '    (L751, T747, R771, B767)
[' On ', 'Pane', ' On Pane']
child_window(title=" On ", auto_id="m_7b4cbcbae7174e47929ddd7339f80b0d", control_type="Pane")`

Output from Inspect.exe:

- hwnd=0x00050452 32bit class="WindowsForms10.Window.8.app.0.3b93019_r36_ad1" 
- ControlType:	UIA_PaneControlTypeId (0xC371)
- LocalizedControlType:	"pane"
- Name:	" On "
- ClassName:	"WindowsForms10.Window.8.app.0.3b93019_r36_ad1"
- NativeWindowHandle:	0x50452
- IsOffscreen:	false
- FrameworkId:	"WinForm"
- ProviderDescription:	"[pid:6960,hwnd:0x50452 Main:Nested [pid:1908,hwnd:0x50452 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"

The element looks like a CheckBox, but raises `AttributeError: Neither GUI element (wrapper) nor wrapper method 'click' were found (typo?)` upon .click(), and raises `NoPatternInterfaceError` upon .invoke() and .select().  I believe this error is because it's a Pane control_type. 

.click_input() works fine, but I would prefer to not have the window and button visible. 

I should also note that all of the above is identical with both 'uia' or 'win32' backends.

My question: is it possible to get .click() to work on this element? 

Thanks in advance.

**Comment by airelil** [comment]
The simplest way might be just get the control coordinates and use the mouse module to perform the click.
```python
import pywinauto.mouse as mouse

coords = app.child_window(title=" On ", auto_id="m_7b4cbcbae7174e47929ddd7339f80b0d", control_type="Pane").rectangle().mid_point()
mouse.click(coords=(coords.x, coords.y))  # left button is the default

```

**Comment by vasily-v-ryabov** [comment]
It's worth trying methods `.toggle()` and `.select()`. Method `.click()` is an alias for `.invoke()` for pure buttons only. Otherwise use `.click_input()` method as a usual click by mouse.

**Comment by benton-anderson** [comment]
Hi airelil and Vasily. Thanks for your responses.

Getting mid_point() coords and mouse clicking performs the same as .click_input(). It works when the item is visible in the window, but doesn't work when scrolled out of view. 

But never mind that, I got .click() to work. Using `backend='win32'` makes it respond to .click(). I thought I tested this, but I obviously did not.

Now my next issue is getting the button to click while the window is minimized. 

If I set `Application(visible_only=False)` or  `.window(visible_only=False)` then I should expect that `dlg.button.click()` will work when the window is minimized, is that right?

**Comment by airelil** [comment]
First, make sure you are able to get the access to the control. If it's resolved you can get the "wrapper_object" for the control with `dlg.button.wrapper_object()`. After this, you may want to call set_focus() before calling the click(), so the window will be restored back.

If you don't want to change the active window, I think, there is not much you can do about it because, win32 backend's HwndWrapper.click() method is already sending WM_*BUTTON* messages to the control and that's up to the application and the control itself to process the messages.

**Comment by benton-anderson** [comment]
That's good to know. I'll mark as closed because I have a good solution. I plan to use .set_focus() and then .move_window() to ensure robust button clicking. Thanks for all the help.

**Comment by Ashish-308** [comment]
Hi 
If I use wo = getattr(app, app_name_for_pb).child_window(title=ev['element_name'], control_type=ev['control_type'], found_index=0).wrapper_object()
 where element_name and control_type are derived from the elements properties. 
Will it be possible to use this wrapper_object to click on an element whose control_type is pane. 
ev is the events which is stored in a json format after a bunch of action has been performed on an application
