### ISSUE TITLE
TreeItemWrapper object is not subscriptable

### ISSUE THREAD

**Issue by jkwhite91** [pywinauto/pywinauto#866]
I have recently had to redo automation for one of our apps as the app changed significantly after a recent software update. We don't develop or maintain the app, we just utilize it. 

I have had to try to get all of the descendants of a window looking specifically at the tree items. Doing this returns a list of TreeItemWrapper elements. Looking at the documentation, I can find two conflicting (and possibly unchecked) definitions of what a TreeItemWrapper actually is.

## Expected Behavior
According to documentation [here](https://readthedocs.org/projects/pywinauto-fork/downloads/pdf/uia/), it is supposed to inherit click_input().

>**class pywinauto.controls.uia_controls.TreeItemWrapper(elem)**
Bases: pywinauto.controls.uiawrapper.UIAWrapper
Wrap an UIA-compatible TreeItem control
In addition to the provided methods of the wrapper additional inherited methods can be especially
helpful: select(), extend(), collapse(), is_extended(), is_collapsed(), click_input(), rectangle() and
many others

## Actual Behavior
When dealing with the element, I am simply writing `element[index].click_input()` and the code breaks here. The exception thrown is:

> 'TreeItemWrapper' object is not subscriptable

The inclusion of click_input() is also not mentioned in the newer [documentation.](https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.uia_controls.html#pywinauto.controls.uia_controls.TreeItemWrapper) is this a bug? or was this something that was removed on purpose? Is there a way to make this work so I can click on that tree item?

## Steps to Reproduce the Problem

  1. Get a list of **tree item elements** via ` elements = app.descendants(control_type="TreeItem")`
  2. Pick a known index `elements[0].click_input()`
  3. Error is thrown.

## Short Example of Code to Demonstrate the Problem
```
def openFile(file_name):
     elements = dlg.window(title=App,class_name=appClass).descendants(control_type="TreeItem")
     items = None
     for element in elements:
         #checking if the filename exists within the descendants list
          if re.search(r".*"+re.escape(file_name)+r".*", str(element), re.IGNORECASE):
               items = element
          items[0].click_input() # Error is thrown here
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.8  x64 bit
  - Platform and OS: Windows 10 PC

**Comment by eavictor** [comment]
I got into this problem too.
But for my situation, use `.select()` on TreeItem solved the problem I was facing.

**Comment by jkwhite91** [comment]
@eavictor so I tried to use `.select()` on the TreeItem and it still provides me with the same error:

> 'TreeItemWrapper' object is not subscriptable

**Comment by jkwhite91** [comment]
So there is an issue. The method that I am using is only returning one element. Trying to access the item as `items[0].click_input()` causes the error to be thrown. However returning just the item and not the item in a list works. I want to handle multiple file names but why does `item.click_input()' work when `items[0].click_input()` does not. Both are looking at one specific TreeItemWrapper element.

**Comment by vasily-v-ryabov** [comment]
Hi @jkwhite91 could you provide the full traceback?

Method `.click_input()` is available globally for all elements. It uses the most natural click with real cursor move. Other methods like `.select()` or `.invoke()` use MS UI Automation API methods which seen as "patterns" in `Inspect.exe` (if you switch `Inspect.exe` from "MSAA" to "UI Automation" mode).

**Comment by jkwhite91** [comment]
@vasily-v-ryabov I have been using `Inspect.exe` with "UI Automation" selected. It looks like part of my problem is the application itself. Within `Inspect.exe` I can clearly see the correct item **only once** but using `print_control_identifiers()` all elements are returned times ten. However, in other parts of the application, it's only returned as a single element. Is there any reason why what pywinauto detects is different than what is seen by `Inspect.exe`?

The `.click_input()` method works when the proper tree element is returned. I've had to change how the elements are retrieved based on the particular aspect of the application. The issue I was having before was that I was not selecting the correct `TreeItemWrapper`.

**Comment by vasily-v-ryabov** [comment]
Probably `Inspect.exe` uses `RawTreeWalker` object in MS UI Automation API while pywinauto uses function `FindAll(...)` which sometimes provides different results especially for some "bugful" versions of Qt 5.x. We're planning to add `RawTreeWalker` usage as a default behavior. But other significant re-factoring is moving pretty slow.

**Comment by jkwhite91** [comment]
I'll keep my eyes open for future updates but use what I have for now. Thanks for the good work you guys are doing.
