### ISSUE TITLE
Selecting Application with Trade Mark in name

### ISSUE THREAD

**Issue by Kenney-Chan** [pywinauto/pywinauto#869]
## Expected Behavior
Open Intel XTU, window name has a Trade Mark symbol.  Try to select window but fails.

## Actual Behavior
Exception pywinauto.findbestmatch.MatchError: <exception str() failed> thown

## Steps to Reproduce the Problem

  1. Install Intel XTU https://downloadcenter.intel.com/download/24075/Intel-Extreme-Tuning-Utility-Intel-XTU

  2.Run pywinauto script as admin. See sample code below.

  3. Exception is thrown probably due to TM symbol.   

```python
C:\Python27\lib\site-packages\pywinauto\application.py:1087: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
Traceback (most recent call last):
  File "C:\Python27\test.py", line 20, in <module>
    dlg_spec.click_input(coords=(600, 420))
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 396, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
pywinauto.findbestmatch.MatchError: <exception str() failed>
```

## Short Example of Code to Demonstrate the Problem
```python
import pywinauto
from pywinauto import Desktop
from pywinauto.application import Application
import time

app = Application(backend="win32").start('C:\Program Files (x86)\Intel\Intel(R) Extreme Tuning Utility\Client\PerfTune.exe')

top_windows = Desktop(backend="win32").windows()
for w in top_windows:
    s = w.window_text()
    if s.find("Intel") <> -1:
        win = s

dlg_spec = app[win]

# wait till the window is really open
time.sleep(3)

dlg_spec.click_input(coords=(600, 420))
```

## Specifications

  - Pywinauto version: 0.6.8 
  - Python version and bitness: 2.7.17
  - Platform and OS: Windows 10

**Comment by vasily-v-ryabov** [comment]
The error message is correct. The similar window title is not found in the process of `app`. The reason of that is less obvious. `PerfTune.exe` behaves as a launcher that spawns a child process if an instance of this app is not yet started. If it's already started, it just exits. In any case the launcher process exits with or without spawning a child.

You have to reconnect to the process with actual window. How it works for me:
```python
app = Application(backend="win32").start('C:\Program Files (x86)\Intel\Intel(R) Extreme Tuning Utility\Client\PerfTune.exe')

app = Application(backend="win32").connect(title_re='Intel.*Extreme Tuning Utility')
app['Intel Extreme Tuning Utility'].set_focus().click_input(coords=(600, 420))
```

Also I'd recommend using `backend="uia"` because WPF app is seen as a single window for `backend="win32"` while `backend="uia"` can see many elements.

**Comment by vasily-v-ryabov** [comment]
The initial error message is different for me on Python 2.7.8 (looks more clear than yours):
```python
  File ".\pywinauto\application.py", line 396, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File ".\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
MatchError: Could not find 'Intel\xae Extreme Tuning Utility' in '[]'
```

That makes me thinking about some "new bugfixes" in Python 2.7.17 which break something for `str()` function. But when I tried Python 2.7.17, I got this stupid error that looks like outdated `pywin32` that must be compiled for newer Python:
```python
  File ".\pywinauto\__init__.py", line 59, in <module>
    import win32api  # noqa: E402
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by Kenney-Chan** [comment]
@vasily-v-ryabov thanks for the explanation of why the code did not work and the sample code on how to fix it.
