### ISSUE TITLE
'RECT' object has no attribute 'width'

### ISSUE THREAD

**Issue by junqi95** [pywinauto/pywinauto#871]
I tried to screenshot a window without border and I followed this code: https://stackoverflow.com/questions/54767813/pywinauto-capture-as-image-adds-unwanted-borders
## Expected Behavior
The screenshot was supposed to have no border, like the image shown in the link.

## Actual Behavior
But I got an error from python saying that AttributeError: 'RECT' object has no attribute 'width'. It seems like the error is from inside the base_wrapper.py in capture_as_image(self, rect) where the attribute 'width()' was used

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.6
  - Platform and OS: Windows 10 

I don't have to stick to this method, so any way of taking a borderless screenshot of a window is welcomed. I just think it might be worthy to mention this issue here.

**Comment by vasily-v-ryabov** [comment]
I've reproduced the issue. Though it's 3rd-party code and we can't guarantee anything, I would consider it as feature request. The mentioned code can't work now, because it uses `ctypes.wintypes.RECT` while method `.capture_as_image()` expects `pywinauto.win32structures.RECT` instead (inherited from `ctypes.wintypes.RECT`). We should add proper error and proper handle this situation in method `.rectangle()`.

As a workaround I can suggest using `pywinauto.win32structures.RECT` for `rect` object passed in `capture_as_image()`.

**Comment by vasily-v-ryabov** [comment]
Method `rectangle()` should have new parameter `border=True` that can be set to `False` optionally. In this case you don't have to pass a rectangle additionally.

**Comment by junqi95** [comment]
@vasily-v-ryabov Thanks for the suggestion. I replaced the line with `pywinauto.win32structures.RECT `and I got a `TypeError: byref() argument must be a ctypes instance, not '_ctypes.PyCStructType' `on line `ctypes.byref(rect)`

**Comment by vasily-v-ryabov** [comment]
Since it works on my machine, I need more info. Which exact version of Python 3.6? I use Python 3.6.5 32-bit.

Also I need full traceback (with all stack frames and line numbers, not only final error message).

**Comment by vasily-v-ryabov** [comment]
Also please mention if you're using `py2exe` or `cx_freeze` or similar tool to pack Python code to executable.

**Comment by junqi95** [comment]
My Python is 3.6.5 64-bit. I currently run my code in JupyterLab. 
Whole traceback:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8b6c34d11bea> in <module>()
     15     ctypes.wintypes.HWND(win32gui.FindWindow(None, window_title)),
     16     ctypes.wintypes.DWORD(DWMWA_EXTENDED_FRAME_BOUNDS),
---> 17     ctypes.byref(rect),
     18     ctypes.sizeof(rect)
     19 )

TypeError: byref() argument must be a ctypes instance, not '_ctypes.PyCStructType'
```

**Comment by vasily-v-ryabov** [comment]
Can you try to run the script in `cmd.exe` using `python.exe`? And provide the full error output. IPython doesn't print full traceback.

**Comment by junqi95** [comment]
I just saw that my python version is actually 3.6.4. Below is what I got from the cmd.exe
```
C:\Windows\System32>C:\Users\MyName\Desktop\test.py
Traceback (most recent call last):
  File "C:\Users\louie\Desktop\test.py", line 17, in <module>
    ctypes.byref(rect),
TypeError: byref() argument must be a ctypes instance, not '_ctypes.PyCStructType'
```

**Comment by vasily-v-ryabov** [comment]
Hmm... It works perfectly on my Python 3.6.0 and Python 3.6.5 both 64-bit. Will try exactly Python 3.6.4 64-bit...

**Comment by vasily-v-ryabov** [comment]
Just a small remark... Running Python script without `python.exe` may not work in some cases. For example, if you have another association with `.py` file extension.

**Comment by junqi95** [comment]
That reminds me. I rerun the script but it looks like the same. 
```
C:\WINDOWS\system32>C:\Users\MyName\AppData\Local\Programs\Python\Python36\python.exe C:\Users\MyName\Desktop\test.py
Traceback (most recent call last):
  File "C:\Users\louie\Desktop\test.py", line 17, in <module>
    ctypes.byref(rect),
TypeError: byref() argument must be a ctypes instance, not '_ctypes.PyCStructType'
```

**Comment by vasily-v-ryabov** [comment]
No luck. The same Python 3.6.4 64-bit installed from scratch at the very similar path in `C:\Users` works perfectly with this script (just in case):

```python
import ctypes
from pywinauto import Application
from pywinauto.win32structures import RECT
import win32gui

app = Application().connect(title_re=".*- Notepad$") # OS language: English
hwin = app.top_window()
hwin.set_focus()

window_title = hwin.window_text()
rect = RECT()
DWMWA_EXTENDED_FRAME_BOUNDS = 9
ctypes.windll.dwmapi.DwmGetWindowAttribute(
    ctypes.wintypes.HWND(win32gui.FindWindow(None, window_title)),
    ctypes.wintypes.DWORD(DWMWA_EXTENDED_FRAME_BOUNDS),
    ctypes.byref(rect),
    ctypes.sizeof(rect)
)

img = hwin.capture_as_image(rect)
img.save('notepad_screenshot_ok.png')
```

**Comment by vasily-v-ryabov** [comment]
Hey, you forgot to create instance of the `RECT` class! You're passing the class, not the object.

Took so much of my time. If you were posted the whole your code, it would save me 1 hour! Please pay attention to the technical issue description culture. It saves the time of everybody. Please!!!

**Comment by vasily-v-ryabov** [comment]
You wrote `rect = RECT` and didn't say about that.

**Comment by junqi95** [comment]
Yeah I just found out why. Sorry for taking your time. Thank you so much!

**Comment by vasily-v-ryabov** [comment]
I will keep the issue open anyway. Sorry for emotions.
