### ISSUE TITLE
Click button with pywinauto implies crash of a simple widget QT 5.2 application 

### ISSUE THREAD

**Issue by diblud13** [pywinauto/pywinauto#892]
## Expected Behavior
Click on PushButton works

## Actual Behavior
The QT 5.2 application crashes

## Steps to Reproduce the Problem

  1. With QT 5.2.1 create a simple widget application with a button
  2. Run this application
  3. Click on the button with pywinauto (last version) (same behaviour => crash if use of invoke on the button on inspect.exe)

Important : I have tried at home with Windows 8 and it works but at the work on Windows 7/10 (There is not Windows 8)  I have a crash . Moreover at home to set a simple string to a TextBox with QT 5.2.1 I had to update the source code of QT https://bugreports.qt.io/browse/QTBUG-55546
 and after it works.

So I would have two ideas/questions please :

1) maybe it could be a problem of pywinauto requirements I mean on https://pywinauto.readthedocs.io/en/latest/getting_started.html it is said the framework works with QT5 but with my first tests QT 5.9 seems more stable for pywinauto (indeed QTBUG-55546 spoken before is solved in QT 5.9) Is there a recommended release of QT5 for pywinauto ? Some help to make work pywinauto with QT 5.2? (for my target, a more complex QT 5.2 application on Win10, the print_control_identifiers method doesnt even return the different controls but the control appear in the inspect.exe)

2) There is apparently an OS problem but could it be the different releases of Automation dlls (https://docs.microsoft.com/fr-fr/dotnet/framework/ui-automation/ui-automation-overview) between Windows 8 (it works at home) and Windows 10 (it doesnt work at the work) I doubt about it but why not or something in my Windows 10, a setting for example that could block ?

## Short Example of Code to Demonstrate the Problem

        app = Application(backend="uia").start('./debug/sans_titre1.exe')

        app.MainWindow.print_control_identifiers()

        app.MainWindow.Custom.PushButton.click()

## Specifications

  - Pywinauto version: last version
  - Python version and bitness: 2.7.17 (I have tried with Python 3.X too)
  - Platform and OS: Windows 10

**Comment by diblud13** [comment]
The Microsoft Windows 10 event viewer seems to indicate it is a problem of a Qtgui dll or something like that. Pywinauto seems a very nice framework then I hope there are not too much updates to do on QT 5.2.1 and Pywinauto source codes to make it work nicely with QT 5.2. Basically it could be nice to list progressively all the possible needed source codes updates to make work pywinauto properly with a special release of QT. We could imagine a compatibility matrix with Qt version (x_axis) and pywinauto (y-axis) => green all the pywinauto tests are OK yellow need some source codes updates to make it OK with the links of these updates and red not compatible. Or maybe (even if currently my target is QT 5.2.1) the simpliest is to give a minimum release of QT in  which all pywinauto tests are OK

As for me for now I just start and I have noticed:

Pywinauto
- Make SetValue on Slider Work
https://github.com/pywinauto/pywinauto/issues/726

QT
- Make SetText on TextEdit work QT 5.2.1 and apparently up to QT 5.9 
https://bugreports.qt.io/browse/QTBUG-55546

I would have to investigate more for my problem but all relevant ideas are welcome :o)

**Comment by vasily-v-ryabov** [comment]
It's very interesting question. Different Qt versions have various problems including even some that make pywinauto behave not as good as `Inspect.exe`. We're planning to use `RawTreeWalker` instead of `FindAll` from `UIAutomationCore.dll`. Then it should behave similarly. It's already tracked issue in milestone "pywianuto-0.7.0". Don't recall exact number.

If you or someone else have enough time and passion to prepare Qt vs pywinauto compatibility table, that would be great. I think a draft can be made at the repository Wiki.

Example of the page with a table:
https://github.com/pywinauto/pywinauto/wiki/UI-Automation-tools-classification

**Comment by diblud13** [comment]
Ok thanks for the informations. In the place where I work now, I am an IT service provider (I work as an IT Automation engineer) and If I continue in the project team I could initiate this compatibility table with pleasure with QT 5.2.1 and QT 5.9.6. Now to solve the problem of pushing the button, I should investigate more this Qtgui dll problem to see if it is needed to update the QT source code or if the problem is elsewhere
