### ISSUE TITLE
Application(backend="uia").connect(path="explorer.exe") cannot find dialog

### ISSUE THREAD

**Issue by czhhua28** [pywinauto/pywinauto#893]
I have one file explorer. 'Downloads' file explorer is launched by administrator.

app = Application(backend="uia").connect(path="explorer.exe")
app.Downloads

If I run the above script using normal user, it raised exception 'Cannot find "Downloads'
If I run the above script using administrator, it works.

How can I make it work using normal user?

  - Pywinauto version: 0.68
  - Python version : 3.8.0
  - Platform and OS: win2012 r2

**Comment by airelil** [comment]
AFAIK, you can't violate the system permissions. It's by design, that the less privileged user is prevented from accessing a process launched by power users.

**Comment by vasily-v-ryabov** [comment]
Yes, this is impossible by OS design, of course. As well as UAC confirmation dialog can't be automated. :) Or just start "Downloads" file explorer as normal user.
