### ISSUE TITLE
Pywinauto - get text from CLI application

### ISSUE THREAD

**Issue by cola6969** [pywinauto/pywinauto#897]
Hi, currently im trying to get client numer  from CLI windows app but unfortunately with no success

![CLI_app_number](https://user-images.githubusercontent.com/57720440/75334073-85fcfc00-5887-11ea-8d8d-c495e267224b.png)

I need to get highlighted number but pywinauto  can only see application window. 

Control Identifiers:

ConsoleWindowClass - 'Select Ottolainaustilin hoito'    (L853, T222, R1509, B661)
['Select Ottolainaustilin hoito', 'Select Ottolainaustilin hoitoConsoleWindowClass', 'ConsoleWindowClass']
child_window(title="Select Ottolainaustilin hoito", class_name="ConsoleWindowClass")

Do you have any idea how i can extract this number??

**Comment by airelil** [comment]
You can't capture the content of your console with Pywinauto. But you should consider just writing a Python script (or batch) to capture and filter the output

**Comment by vasily-v-ryabov** [comment]
An interesting project to work with console using WinPTY API: https://pypi.org/project/pywinpty/
