### ISSUE TITLE
Handle destroyed parent case while notifying it

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#900]
Reported on StackOverflow:
https://stackoverflow.com/q/60609600/3648361

**Comment by michaelsatish** [comment]
**Control Identifiers** from the application.

    ['Create Batch', 'Dialog', 'Create BatchDialog']
    child_window(title="Create Batch", control_type="Window")
       | 
       | Static - 'Batch class:'    (L516, T288, R658, B304)
       | ['Static', 'Batch class:', 'Batch class:Static', 'Batch class:0', 'Batch class:1', 'Static0', 'Static1', 'Batch class:Static0', 'Batch class:Static1']
         child_window(title="Batch class:", control_type="Text")
       | 
       | ComboBox - 'Batch class:'    (L666, T286, R1232, B310)
       | ['ComboBox', 'Batch class:2', 'Batch class:ComboBox', 'ComboBox0', 'ComboBox1']
       | child_window(title="Batch class:", auto_id="27651", control_type="ComboBox")
       |    | 
       |    | Static - 'Batch class:'    (L3, T3, R542, B21)
       |    | ['Static2', 'Batch class:3', 'Batch class:Static2']
       |    | child_window(title="Batch class:", control_type="Text")
       |    | 
       |    | Button - 'Open'    (L1212, T287, R1231, B309)
       |    | ['Button', 'OpenButton', 'Open', 'Button0', 'Button1', 'OpenButton0', 'OpenButton1', 'Open0', 'Open1']
       |    | child_window(title="Open", auto_id="DropDown", control_type="Button")oreButton', 'More0', 'More1', 'MoreButton0', 'MoreButton1']
       |    | child_window(title="More", auto_id="MoreButton", control_type="Button")
       |    | 
       |    | Button - 'Less'    (L1382, T298, R1404, B310)
       |    | ['Button3', 'Less', 'LessButton', 'Less0', 'Less1', 'LessButton0', 'LessButton1']
       |    | child_window(title="Less", auto_id="LessButton", control_type="Button")
