### ISSUE TITLE
Why don't support the newest python?

### ISSUE THREAD

**Issue by AndyLawFighting** [pywinauto/pywinauto#905]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Pywinauto version:
  - Python version and bitness:
  - Platform and OS:

**Comment by vasily-v-ryabov** [comment]
What do you mean? The newest Python 3.8.2 is supported.
Python 3.8.1 and 3.7.6 have known issue (see #868 for the full history).

**Comment by AndyLawFighting** [comment]
Python 3.8.1 is not supported, but Python 3.8.2 is supported, right?

**Comment by vasily-v-ryabov** [comment]
Yes, this was a bug in Python 3.8.1 (not a pywinauto issue) which was fixed in Python 3.8.2.

**Comment by AndyLawFighting** [comment]
Thank you.
