### ISSUE TITLE
Unable to Access Currently running Background process "Credential Manager UI Host" for VPN connection app.

### ISSUE THREAD

**Issue by surendrasai** [pywinauto/pywinauto#907]
## Expected Behavior
Need to Switch to Back-ground app and click on "**Allow**".

## Actual Behavior
My Script is able to trigger VPN app and pass credentials then connect to VPN.
But New Security key POP-UP started coming, and I am not unable to switch to that **pop up** to select **Allow Button**.
Please help me if it can be possible with Pywinauto or I need to use any other library in python.

## Steps to Reproduce the Problem

  1. Below
  2.
  3.

## Short Example of Code to Demonstrate the Problem

Below is my Script.

```
from pywinauto.application import Application
from subprocess import Popen,PIPE
from tkinter import ttk
import time
import tkinter as tk
 
def VPNConnect():
    app = Application().start(r'C:\windows\system32\rasphone.exe -d "<VPN_app>"')
    time.sleep(2)
    app.VPN_app1.Connect.click()
    dlg = app.top_window()
    print(dlg)
    dlg.Button.Allow.click()
    time.sleep(5)
    app.Warning.OK.click()
    time.sleep(10)
     app.VPN_app1.type_keys('user_id')
     app.VPN_app1.type_keys("{TAB}")
     app.VPN_app1.type_keys("{TAB}")
     app.VPN_app1.type_keys("{TAB}")
     app.VPN_app1.type_keys("{TAB}")
     app.VPN_app1.type_keys("password")
     time.sleep(2)
     app.VPN_app1.type_keys("{ENTER}")
     
 def VPNcheck():
     cmd = ['%comspec% /c route print 10.10.10.0'] #Command for getting VPN connection status
     result = subprocess.Popen('%comspec% /c route print 10.10.10.0', stdout=subprocess.PIPE, shell =True)
     for line in result.stdout.readlines():
         if b'<VPN_app1>' in line or b'<VPN_app2>' in line:
             return True
     return VPNcheck
 
 def popupmsg(msg):
     popup = tk.Tk()
     popup.wm_title("!")
     label = ttk.Label(popup, text=msg)
     label.pack(side="top", fill="x", pady=20)
     B1 = ttk.Button(popup, text="Okay", command = popup.destroy)
     B1.pack()
     popup.mainloop()
 
 VPNcheck()
 
 #Condition to check if the VPN is already connected and then call VPNConnect().
 if VPNcheck() == True:
     popupmsg('VPN is already connected')
 else:
     VPNConnect()
 
```

Below Is the error.

```
 ElementNotFoundError                      Traceback (most recent call last)
 <ipython-input-14-3dc39ad4f5a7> in <module>
      53     popupmsg('VPN is already connected')
      54 else:
 ---> 55     VPNConnect()
 
 <ipython-input-14-3dc39ad4f5a7> in VPNConnect()
      17     dlg = app.top_window()
      18     print(dlg)
 ---> 19     dlg.Button.Allow.click()
      20     time.sleep(5)
      21     app.Warning.OK.click()
 
 ~\AppData\Roaming\Python\Python37\site-packages\pywinauto\findwindows.py in find_element(**kwargs)
      85 
      86     if not elements:
 ---> 87         raise ElementNotFoundError(kwargs)
      88 
      89     if len(elements) > 1:
 
 ElementNotFoundError: {'best_match': 'Allow', 'top_level_only': False, 'parent': win32_element_info.HwndElementInfo - '&Cancel', Button, 1706668>, 'backend': 'win32'}
 
```

## Specifications

  - Pywinauto version: NA
  - Python version and bitness: Version 3.7.4
  - Platform and OS: Windows 10

**Comment by michel117** [comment]
You have to inspect which attributes the control actually exposes. Use the `print_control_identifiers()` method of pywinauto.
And/or for more inspection use inspect.exe or the new MS accessibility insight tool.

**Comment by airelil** [comment]
Quite possible that the popup window belong to another process, forked after connecting to VPN. Also, remember to check the permissions.

**Comment by surendrasai** [comment]
> You have to inspect which attributes the control actually exposes. Use the `print_control_identifiers()` method of pywinauto.
> And/or for more inspection use inspect.exe or the new MS accessibility insight tool.

**Comment by surendrasai** [comment]
> Quite possible that the popup window belong to another process, forked after connecting to VPN. Also, remember to check the permissions.

Yes Its an another process when I checked under Task Manager this is appearing in **Background process**  under **Credential Manager UI Host**, but I am unsure on how to switch to that process.
Any suggestions would be highly appreciated 👍

**Comment by airelil** [comment]
Typically, you use another Application instance with the [connect](https://pywinauto.readthedocs.io/en/0.6.8/code/pywinauto.application.html#pywinauto.application.Application.connect) method. If you know the path to the executable, it would be enough. Another option, is try to get the window through [Desktop class](https://github.com/pywinauto/pywinauto/blob/aea0429b14f9e471974889246b3c4455b93508f3/pywinauto/__init__.py#L104). https://pywinauto.readthedocs.io/en/0.6.8/getting_started.html#entry-points-for-automation

**Comment by surendrasai** [comment]
> Typically, you use another Application instance with the [connect](https://pywinauto.readthedocs.io/en/0.6.8/code/pywinauto.application.html#pywinauto.application.Application.connect) method. If you know the path to the executable, it would be enough. Another option, is try to get the window through [Desktop class](https://github.com/pywinauto/pywinauto/blob/aea0429b14f9e471974889246b3c4455b93508f3/pywinauto/__init__.py#L104). https://pywinauto.readthedocs.io/en/0.6.8/getting_started.html#entry-points-for-automation

Thank you for your quick response Airelil!!!

I tried all the ways you suggested and modified my code as bellow, but still unable to switch to the app- **Windows Security**  under **Credential UI Blocker**, 
`from pywinauto.application import Application
from subprocess import Popen,PIPE
from tkinter import ttk
from pywinauto import Desktop
import subprocess
import time
import tkinter as tk

def VPNConnect():
    app1 = Application().start(r'C:\windows\system32\rasphone.exe -d "UTC-Asia"')
    dlg1 = Desktop(backend = 'uia').UTC_Asia
    dlg1.wait('visible')
    
    app1.UTC_Asia.Connect.click()
    
    #time.sleep(5)
    #dlg2 = Application().connect(path = r'C:\Windows\System32\CredentialUIBroker.exe')
    
    windows = Desktop(backend="uia").windows()
    #print(windows)
    "Windows Security" in [w.window_text() for w in windows]
    
    if True:
        app2 = Application().connect(path = r'C:\Windows\System32\CredentialUIBroker.exe')
        
        dlg2 = Desktop(backend = 'uia').Windows_Security
        dlg2.wait('visible')
        
        app2.Windows_Security.Allow.click()
        print(dlg2)`

Below is the error.

`MatchError: Could not find 'Windows_Security' in 'dict_keys([])'`

Any Suggestions???

**Comment by airelil** [comment]
Did you verify procesd id of your pop up? You can do it with Inspect.exe utility, as suggested by @michel117  . As a debug step, you could hard code the pid and try to connect to it. Also, did you try to run your script as admin, to eliminate permissions problems?

**Comment by surendrasai** [comment]
@airelil , @michel117 Thankyou so much for your help. now my script is working perfectly after using **print_control_identifiers()** method I was able to identify which element to click on. 

```
def VPNConnect():
    app1 = Application().start(r'C:\windows\system32\rasphone.exe -d "VPN-app1"')
    dlg1 = Desktop(backend = 'uia').VPN-app1
    dlg1.wait('visible')  
    app1.UTC_Asia.Connect.click()
    
    #Validation to Check For Windows Security popup Message
    windows = Desktop(backend="uia").windows()
    "Windows Security" in [w.window_text() for w in windows]
    if True:
        app2 = Application().connect(path = r'C:\Windows\System32\CredentialUIBroker.exe')
        dlg2 = Desktop(backend = 'uia').Windows_Security
        dlg2.wait('visible')
        dlg2.Allow.click()
       
    dlg1.wait('visible')
    app1.Warning.OK.click()
    dlg1.wait('visible')
    app1.UTC_Asia.type_keys('UN')
    app1.UTC_Asia.type_keys("{TAB}")
    app1.UTC_Asia.type_keys("{TAB}")
    app1.UTC_Asia.type_keys("{TAB}")
    app1.UTC_Asia.type_keys("{TAB}")
    app1.UTC_Asia.type_keys("PW")
    dlg1.wait('visible')
    app1.UTC_Asia.type_keys("{ENTER}")
```
