### ISSUE TITLE
Unittests pause for tray application, right-clicking / OK'ing and it repeats.

### ISSUE THREAD

**Issue by enjoysmath** [pywinauto/pywinauto#909]
## Expected Behavior

For the tests to run through automatically, on their own.  Or for the on-screen instructions to make sense.  The message box shown in the image below seems to indicate that right-clicking on the tray icon will progress you further into the tests. 

## Actual Behavior
It pauses at:
![image](https://user-images.githubusercontent.com/1606391/78454995-9fe0ea00-7650-11ea-850b-75356f7de66d.png)

If you follow the dialogs instructions, and hit OK, it repeats itself, going to control panel then opening the exact same dialog.

## Steps to Reproduce the Problem
1. Same with either 64-bit or 32-bit Python.  But install Python 3.6.5 and make sure it's the first python that shows up with `where python`.
2. Install the required dependencies with `pip install -U -r dev-requirements.txt`
3. Run `nosetests --with-coverage --cover-html --cover-html-dir=Coverage_report pywinauto\unittests`

## Specifications

  - Pywinauto version:
    Default branch of pywinauto/pywinauto github repository.
  - Python version and bitness:
    32-bit -or- 64-bit Python 3.6.5
  - Platform and OS:
    Windows 10, 64-bit

**Comment by airelil** [comment]
Notice that all the tests do not require any manual input. However, GUI testing can be intricate and affected by many factors: operating system difference, different resolutions, themes, number of monitors... If the test is stuck, it means it has a bug. I assume that you still didn't update to the latest code, so it's possible that this fix: [977f0a0](https://github.com/pywinauto/pywinauto/commit/977f0a0e516b2b3901fc88c22eb405878515d2e9#diff-916efc21230a6ed4f6d2358c5895f86b) can help

**Comment by enjoysmath** [comment]
@airelil  what is the easiest method of "applyig a fix" such as the one you gave?

**Comment by airelil** [comment]
`git cherry-pick 977f0a0` will probably do.

It looks to me, you might need to catch up with Git basics. IMO, there is not shortcut to it, sorry.

If you are not able to align with the latest code, the best course of action would be @vasily-v-ryabov aligning the "recorder" branch with "atspi" and than you could re-apply your changes. Not sure when he'll have time for it, though. There is already ongoing work on merging a pool request with "macOS" platform support: https://github.com/pywinauto/pywinauto/pull/841
