### ISSUE TITLE
Running an individual unittest in a debugging IDE doesn't work for me.  🐛

### ISSUE THREAD

**Issue by enjoysmath** [pywinauto/pywinauto#910]
## Expected Behavior
For the inidividual unittest not to crash immediately at first import line.

## Actual Behavior
![image](https://user-images.githubusercontent.com/1606391/78462000-d2a3d600-7682-11ea-8cbd-b34c9fd69997.png)

## Steps to Reproduce the Problem

  1. Git clone:  `https://github.com/enjoysmath/pywinauto.git` to `pywinautorec`
  2. `pip install -U -r dev-requirements.txt`
  3. Set `pywinautorec/pywinauto/unittests/test_taskbar.py` as main entry point in your debugging IDE.
  4. Hit run.

## Short Example of Code to Demonstrate the Problem
`min_example.py`: 
     `from pywinauto import taskbar`

## Specifications
  - Pywinauto version:
    "0.6.4"
  - Python version and bitness:
    Python 3.6.5, 64-bit
  - Platform and OS:
    Windows 10, 64-bit

**Comment by airelil** [comment]
Isn't it just a matter of settings in your IDE? Can you add the upper pywinauto folder to your PYTHON_PATH?

**Comment by enjoysmath** [comment]
> Isn't it just a matter of settings in your IDE? Can you add the upper pywinauto folder to your PYTHON_PATH?

Yes, that worked ! :)
