### ISSUE TITLE
Unable to click/interact with QT App

### ISSUE THREAD

**Issue by RakuTheSenpai** [pywinauto/pywinauto#918]
## Expected Behavior
Click action performed by pywinauto.
## Actual Behavior
No click action happens, nor any interaction for that matter.
## Steps to Reproduce the Problem

  1. Substitute anki_Path with the path to [Anki](https://apps.ankiweb.net/) application
  2. Run code

## Short Example of Code to Demonstrate the Problem
The following are two different implementantions of the code, I've included them both since both of them return different objects when printing **anki**.
```
anki_App = Application(backend="uia").start(anki_Path)
anki = anki_App.window(title_re=r".* - Anki", class_name="AnkiQt").wait('Active', timeout=20, retry_interval=0.5)
anki['Import File'].click_input()
```
First one returns: <pywinauto.application.WindowSpecification object at 0x02E63820>

```
anki_App = Application(backend="uia").start(anki_Path)
anki_App.top_window().wait("Visible") #Wait for Anki's sync to server
anki = anki_App.window(title_re=r".* - Anki", class_name="AnkiQt")
anki['Import File'].click_input()
```
Second one returns: uiawrapper.UIAWrapper - 'User 1 - Anki', Dialog
## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.8.2 64-bit
  - Platform and OS: Windows 10
[Control identifiers for reference](https://github.com/pywinauto/pywinauto/files/4513486/control_identifiers.txt)
Thank you for your time.

**Comment by airelil** [comment]
Didn't have much time to dig, but I might see the problem. The coordinates are probably wrong:
![image](https://user-images.githubusercontent.com/795040/79962313-fddc5100-84db-11ea-923a-3ffa4a10d456.png)

**Comment by RakuTheSenpai** [comment]
Thank You!! I was able to fix it using:
```
anki_App = Application(backend="uia").start(anki_Path)
anki_App.top_window().wait("Visible") #Wait for Anki's sync to server
anki = anki_App.window(title_re=r".* - Anki", class_name="AnkiQt")
anki['Browse'].draw_outline()
anki['Browse'].click_input(coords=(anki['Browse'].rectangle().left -1, anki['Browse'].rectangle().top -1), absolute = True)
```
I'm not sure how optimal of a solution it actually is... But I'm glad I'm making progress! Thank you so much!
