### ISSUE TITLE
Lookup button click in a Edit Control not working

### ISSUE THREAD

**Issue by jjbright** [pywinauto/pywinauto#921]
Unable to click on the lookup button in the Edit control @vasily-v-ryabov Need your quick help

## Expected Behavior
Click on the YELLOW highlighted lookup button
![image](https://user-images.githubusercontent.com/55202374/80126143-49602f00-85b0-11ea-8062-87b4f2b076cf.png)

## Actual Behavior
Unable to click that lookup button, able to do set_text in the edit control

## Short Example of Code to Demonstrate the Problem
`contentPanel = mainPanel.child_window(auto_id="contentIFrame0", control_type="Pane")
caseClass = contentPanel.child_window(auto_id="gcct_caseclassification", control_type="Window")
caseClassText = caseClass.child_window(auto_id="gcct_caseclassification_ledit", control_type="Edit")
caseClassText.set_text("Has Been To Dealer")
caseClassLookup = caseClass.child_window(auto_id="gcct_caseclassification_lookupSearch", control_type="DataItem")
caseClassLookup.click_input()
`
## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7.4 64 bit
  - Platform and OS: Windows 10

## Control Identifiers
Control Identifiers:

`Dialog - 'Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. Select the Enter key to edit the lookup field'    (L868, T597, R1067, B627)
['Dialog', 'Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. Select the Enter key to edit the lookup field', 'Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. Select the Enter key to edit the lookup fieldDialog']
child_window(title="Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. Select the Enter key to edit the lookup field", auto_id="gcct_caseclassification", control_type="Window")
   | 
   | Table - 'Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. '    (L874, T597, R1068, B627)
   | ['Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. ', 'Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. Table', 'Table']
   | child_window(title="Case Classification Select Case Classification OR build the Case Classification by using Level 1 through 4 selections. ", auto_id="gcct_caseclassification_lookupTable", control_type="Table")
   |    | 
   |    | Custom - ''    (L874, T597, R1068, B627)
   |    | ['Custom', '', '0', '1']
   |    |    | 
   |    |    | DataItem - 'Enter a search term, then select the Enter key to search Enter a search term, then select the Enter key to search'    (L874, T597, R1033, B627)
   |    |    | ['DataItem', 'Enter a search term, then select the Enter key to search Enter a search term, then select the Enter key to search', 'Enter a search term, then select the Enter key to search Enter a search term, then select the Enter key to searchDataItem', 'DataItem0', 'DataItem1']
   |    |    | child_window(title="Enter a search term, then select the Enter key to search Enter a search term, then select the Enter key to search", control_type="DataItem")
   |    |    |    | 
   |    |    |    | Static - 'Enter a search term, then select the Enter key to search'    (L0, T0, R0, B0)
   |    |    |    | ['Enter a search term, then select the Enter key to searchStatic', 'Enter a search term, then select the Enter key to search', 'Static']
   |    |    |    | child_window(title="Enter a search term, then select the Enter key to search", control_type="Text")
   |    |    |    | 
   |    |    |    | Edit - 'Enter a search term, then select the Enter key to search'    (L874, T597, R1040, B627)
   |    |    |    | ['2', 'Edit']
   |    |    |    | child_window(title="Enter a search term, then select the Enter key to search", auto_id="gcct_caseclassification_ledit", control_type="Edit")
   |    |    | 
   |    |    | DataItem - ''    (L1032, T597, R1040, B627)
   |    |    | ['3', 'DataItem2']
   |    |    | 
   |    |    | DataItem - 'Select a value. Select a value.'    (L1039, T597, R1068, B627)
   |    |    | ['DataItem3', 'Select a value. Select a value.DataItem', 'Select a value. Select a value.']
   |    |    | child_window(title="Select a value. Select a value.", auto_id="gcct_caseclassification_lookupSearch", control_type="DataItem")
   |    |    |    | 
   |    |    |    | Image - 'Select a value.'    (L1039, T602, R1067, B625)
   |    |    |    | ['Select a value.', 'Select a value.Image', 'Image', 'Select a value.0', 'Select a value.1']
   |    |    |    | child_window(title="Select a value.", auto_id="gcct_caseclassification_i", control_type="Image")
   |    |    |    | 
   |    |    |    | Hyperlink - 'Select a value.'    (L0, T0, R0, B0)
   |    |    |    | ['Select a value.2', 'Select a value.Hyperlink', 'Hyperlink']
   |    |    |    | child_window(title="Select a value.", auto_id="gcct_caseclassification_a", control_type="Hyperlink")
`

**Comment by airelil** [comment]
If you're able to put a text in the "Edit", you may work it around by sening "Enter" key. Otherwise, try to identify the control in question with Inspect.exe utility and verify it with `draw_outline()` method.
I also noticed you use pywinatuo 0.6.7 so you could try a newer version 0.6.8

**Comment by jjbright** [comment]
I had to select the meuitem by getting the list from the dropdown -

`lkpList.child_window(auto_id="item0", control_type="MenuItem").click_input()`

**Comment by Navyapalvai** [comment]
Hi @jjbright,
I tried to automate USD 4 using UFT and problem started here at case classification fields and could not move any further. Please let me know if you find any solution and how you are automating this USD 4. Thanks in advance!
