### ISSUE TITLE
encrypted_keys

### ISSUE THREAD

**Issue by rambabu3381** [pywinauto/pywinauto#923]
app = application.Application()
app.connect(path=r"C:\Program Files \notepad.exe")
encrpt = app.top_window()
encrpt = app.top_window().type_keys("this_test")
# here,is it  possible to  use (this_test) as encrypted so that no one can see   this if it was my #password

**Comment by airelil** [comment]
Hey @rambabu3381, I don't think the question is directly related to pywinauto. Generally, you shouldn't keep any passwords/auth. tokens in your scripts. It's considered a security hole. The simplest alternative would be to prompt the user to enter the password when you start your script. Another, option is to read it from a file, but it poses exactly the same risk, unless you start creating a special user with very limited permissions and only the one be able to access the password file .

You can see a lot of discussions about passwords in the scripts all over the Internet. One of argument is if you really don't care about keeping your "secret" in the script, why should you care on trying to hide it or even have it at all?

**Comment by rambabu3381** [comment]
Hi  airelil, 

I am trying to automate a  routine procedure that includes typing password and username everything when we log on and i do it very often.So,is there any way to encrypt the password.
if i prompt the user, it no longer the automated stuff.
Any how , What i want is that i will create a  function which return  char 
i will use that function here .Is that possible?

**Comment by airelil** [comment]
Not pywinauto related. Not sure can help you with that.
