### ISSUE TITLE
drag_mouse_input code is likely to be partial/wrong

### ISSUE THREAD

**Issue by r-jean-pierre** [pywinauto/pywinauto#928]
## Expected Behavior
A correct drag&drop from a point A to a point B, with intermediate steps on the line [AB]

## Actual Behavior
It "flies" correctly from A to B, but the intermediate steps are inconsistent and do not simulate a human drag

## Steps to Reproduce the Problem

  1. Do a simple : `app.drag_mouse_input(dst=(100, 100), src=(300, 300), absolute=False)`
  2. Set timings to slow() mode to have time to see the cursor moving, and see how strange the intermediate steps are located
  3. to understand, look at code around line 898 in base_wrapper, inside the for loop, there is no sense to this line of code:
`self.move_mouse_input((press_coords[0] + i, press_coords[1]), pressed=pressed, absolute=absolute)`

It can be expected an interpolation from src to dst to generate the famous 5 intermediate mouse positions, and as of today, the code just add one pixel towards the right direction

In the best case scenario it handles badly a horizontal drag from left to right, in any other case, the behaviour is not correct

## Short Example of Code to Demonstrate the Problem
`app.drag_mouse_input(dst=(100, 100), src=(300, 300), absolute=False)`

## Specifications

  - Pywinauto version: 0.6.8 
  - Python version and bitness: 3.7 64bits
  - Platform and OS: Windows

**Comment by airelil** [comment]
Thanks for interedting input. I guess, we didn't put much thought in it. Would be interesting to see some code example. Ideally a pull request with a test

**Comment by vasily-v-ryabov** [comment]
This is already tracked in #878. Please provide all suggestions to the original issue.
