### ISSUE TITLE
Read text from WPF pane window

### ISSUE THREAD

**Issue by sachinpatole** [pywinauto/pywinauto#945]
I am trying to read text from WPF pane window. Previously this windows was a normal win32 windows. So my automated script was working fine. Now since the developer has changed it to WPF swappy is unable to detect it. So I tried the UIA approach and used Inspect.exe.

The challenge which I am facing is how to use Inspect.exe and pywinauto together to read the text data

Here I am coping the pane window details which I got from Inspect.exe

Is there any way we can read text from WPF pane window?

How found:	Selected from tree...
Name:	""
ControlType:	UIA_PaneControlTypeId (0xC371)
LocalizedControlType:	"pane"
BoundingRectangle:	{l:639 t:541 r:1337 b:657}
IsEnabled:	true
IsOffscreen:	false
IsKeyboardFocusable:	true
HasKeyboardFocus:	false
AcceleratorKey:	""
AccessKey:	""
ProcessId:	17928
RuntimeId:	[7.4608.364D350]
AutomationId:	""
FrameworkId:	"WPF"
ClassName:	"ScrollViewer"
IsControlElement:	true
IsContentElement:	true
ProviderDescription:	"[pid:17928,providerId:0x0 Main(parent link):Unidentified Provider (managed:MS.Internal.Automation.ElementProxy, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)]"
IsPassword:	false
ItemStatus:	""
ItemType:	""
IsRequiredForForm:	false
HelpText:	""
ClickablePoint:	{x:988 y:599}
Orientation:	0
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	""
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	""
LegacyIAccessible.Role:	pane (0x10)
LegacyIAccessible.State:	focusable (0x100000)
LegacyIAccessible.Value:	""
Scroll.HorizontallyScrollable:	false
Scroll.HorizontalScrollPercent:	-1.000000
Scroll.HorizontalViewSize:	100.000000
Scroll.VerticallyScrollable:	false
Scroll.VerticalScrollPercent:	-1.000000
Scroll.VerticalViewSize:	100.000000
IsAnnotationPatternAvailable:	false
IsDragPatternAvailable:	false
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	false
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	false
IsScrollPatternAvailable:	true
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	false
IsSpreadsheetPatternAvailable:	false
IsStylesPatternAvailable:	false
IsSynchronizedInputPatternAvailable:	true
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	false
IsTextEditPatternAvailable:	false
IsTextPatternAvailable:	false
IsTextPattern2Available:	false
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	false
IsValuePatternAvailable:	false
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
IsCustomNavigationPatternAvailable:	false
IsSelectionPattern2Available:	false
FirstChild:	"" text
LastChild:	"" scroll bar
Next:	[null]
Previous:	[null]
Other Props:	Object has no additional properties
Children:	"" text
	"0x5107:031 Cycle length" text
	"Value:" text
	"14405 Unit" text
	"Factory setting:" text
	"360 Unit" text
	"Range:" text
	"0.000000001 ... 2147483647 Unit" text
	"Raw value:" text
	"14405 (0x000000008022CC40)" text
	"Data type:" text
	"LREAL - IEEE 754 Long Real (8 bytes)" text
	"Note:" text
	"Controller must be inhibited before write operation!" text
	"" text
	"" scroll bar
	"" scroll bar
Ancestors:	"" custom
	"" custom
	"elementHost" pane
	"elementHost" pane
	"" pane
	"Filter active!" pane
	"" pane
	"" pane
	"" pane
	"" pane
	"" pane
	"" pane
	"Parameter list" pane
	"" tab
	"" pane
	"" pane
	"Device" pane
	"" pane
	"UpdateMotionAxes_OldVersion.project" window
	"Desktop 1" pane
	[ No Parent ]

**Comment by sachinpatole** [comment]
# I was able to read the text.

from pywinauto.application import Application
from pywinauto import application

plcPid = application.process_from_module(module = 'MyApp.exe')
wpfApp = Application(backend='uia').connect(process=plcPid)

handle = wpfApp.window_(title='MyDoc.project - MyApp 3.21.0')
child = handle.child_window(auto_id='elementHostInfoBox')

child0 = child.wrapper_object()

child1 = child0.children()
child2 = child1[0].children()
child3 = child2[0].children()
print(child3[0].children_texts())

**Comment by vasily-v-ryabov** [comment]
`.connect(path="MyApp.exe")` is more compact. Also `window` is better than deprecated `window_`. SWAPY uses "win32" backend (mopre precisely it doesn't use backend, but it has separate code base).

Useful method `main_window.dump_tree()` (`main_window` is better name than `handle`) can help to find proper names for specifications.

Read the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) for core concept. And some guides around it in the Contents. You will find many interesting things that will save you a lot of time.

**Comment by sachinpatole** [comment]
@vasily-v-ryabov Thanks, you are doing a great job!
I did changes suggested by you. But dump_tree() is not working for me. Is there any code dependency before we give a call to dump_tree()? I am getting this error attribute error for 'dump_tree'. Let me know I would love to use 'dump_tree()' method

**Comment by vasily-v-ryabov** [comment]
`dump_tree` method is available for top level window specification like `app.MainWindowTitle.dump_tree()`, not for Application object. With full traceback it's better to understand which object raised AttributeError. So bug reporting culture always matters. ;)
