### ISSUE TITLE
COMError with WPF application 

### ISSUE THREAD

**Issue by JohnS-BCS** [pywinauto/pywinauto#949]
I am using pywinauto to test a WPF application that contains both WPF controls and a few win32 controls.  Since I have both types of controls I am trying to use print_control_identifiers().

here is my code 
```
app_win32 = Application(backend='win32').connect(path=exe)
app_uia = Application(backend='uia').connect(path=exe)

app_win32.top_window().print_control_identifiers()
app_uia.top_window().print_control_identifiers()
```
this produces an error 

> Traceback (most recent call last):
>   File "C:/Users/Administrator/.PyCharmCE2019.3/config/scratches/scratch_7.py", line 13, in <module>
>     app_uia.top_window().print_control_identifiers()
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\application.py", line 689, in print_control_identifiers
>     print_identifiers([this_ctrl, ])
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\application.py", line 685, in print_identifiers
>     print_identifiers(ctrl.children(), current_depth + 1, log_func)
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\application.py", line 685, in print_identifiers
>     print_identifiers(ctrl.children(), current_depth + 1, log_func)
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\application.py", line 641, in print_identifiers
>     ctrl_id = all_ctrls.index(ctrl)
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\base_wrapper.py", line 662, in __eq__
>     return self.element_info == other.element_info
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\uia_element_info.py", line 360, in __eq__
>     return bool(IUIA().iuia.CompareElements(self.element, other.element))
> _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
> 
> Process finished with exit code 1

The error is not always the same. Sometimes it will produce a COMError in a different part of the pywinauto. Here is the error with the same code from a different run:

> Traceback (most recent call last):
>   File "C:/Users/Administrator/.PyCharmCE2019.3/config/scratches/scratch_7.py", line 13, in <module>
>     app_uia.top_window().print_control_identifiers()
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\application.py", line 624, in print_control_identifiers
>     ctrl_names = findbestmatch.get_control_names(ctrl, all_ctrls, txt_ctrls)
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\findbestmatch.py", line 320, in get_control_names
>     non_text_names = get_non_text_control_name(control, allcontrols, textcontrols)
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\findbestmatch.py", line 206, in get_non_text_control_name
>     is_above_or_to_left(ctrl, prev_ctrl):
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\findbestmatch.py", line 164, in is_above_or_to_left
>     ctrl_r = ref_control.rectangle()
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\base_wrapper.py", line 367, in rectangle
>     return self.element_info.rectangle
>   File "C:\marvlisvenv\lib\site-packages\pywinauto\uia_element_info.py", line 326, in rectangle
>     bound_rect = self._element.CurrentBoundingRectangle
> _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
> 

Thanks 

John 

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 2.7
  - Platform and OS: Windows Server 2016

**Comment by iamvkundra** [comment]
Are you running a application packed with installshield?

**Comment by vasily-v-ryabov** [comment]
The first part of issue is also reported here: https://stackoverflow.com/q/75363721/3648361

**Comment by JohnS-BCS** [comment]
I have had to scale back testing with pywinauto and no longer pursuing this.
