### ISSUE TITLE
[Question]: dose pywinauto support DevExpress?

### ISSUE THREAD

**Issue by eramyang** [pywinauto/pywinauto#950]
I am a software tester and a newbie in pywinauto.
I want to use pywinauto on winform GUI automation.
It goes will on main windows, but, it failed to get Back button on the pop-up windows.
As the pop-up windows uses DevExpress. So, I want to whether pywinauto supports DevExpress.

**Below is some code in my applicaion:**
 WindowsForms10.Window.8.app.0.1114f81_r6_ad1 - 'windowsTitle'    (L384, T136, R1282, B797)
   | ['windowsTitleWindowsForms10.Window.8.app.0.1114f81_r6_ad12', 'WindowsForms10.Window.8.app.0.1114f81_r6_ad12', 'windowsTitle2']
   | child_window(title="windowsTitle", auto_id="wizardControl1", control_type="DevExpress.XtraWizard.WizardControl")
   |    | 
   |    | WindowsForms10.Window.b.app.0.1114f81_r6_ad1 - '< &Back'    (L1031, T763, R1106, B787)
   |    | ['< &Back', 'WindowsForms10.Window.b.app.0.1114f81_r6_ad1', '< &BackWindowsForms10.Window.b.app.0.1114f81_r6_ad1', 'WindowsForms10.Window.b.app.0.1114f81_r6_ad10', 'WindowsForms10.Window.b.app.0.1114f81_r6_ad11']
   |    | child_window(title="< &Back", control_type="DevExpress.XtraWizard.WizardButton")

Thanks in advance.

**Comment by airelil** [comment]
@eramyang , if you search through the past pywinauto issues you'll see that people already tried to automate DevExpress controls with different degree of success. Your best friend should be Inspect.exe in UIA mode. Usually, any controls that is accessible/visible in Inspect.exe can be accessed from pywinauto too. Notice that Inspect.exe shows what "UI automation patterns" each control supports. These are patterns that pywinauto (running with uia backend) tries to use.

**Comment by vasily-v-ryabov** [comment]
Hi @eramyang you can try `Application(backend="uia")` which is recommended for WinForms. See the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html) about backends and other core concepts. But regarding DevExpress controls there are some custom controls not supported by pywinauto (and underlying MS UI Automation API).

For better DevExpress support we need some DLL injection approach. This research is not started yet due to activities for Linux and macOS and some general re-factoring to improve pywinauto API.

**Comment by eramyang** [comment]
Many thanks for your help @airelil , @vasily-v-ryabov 
Many problem is resolved with your help.

And, this is the first time I submit question on GitHub.
I feel so happy as I got the answers.

Thanks again.

**Comment by vasily-v-ryabov** [comment]
Hi @Ja2ger you can try pywinauto's branch "atspi" with this flag set:
```python
pywinauto.windows.uia_element_info.UIAElementInfo.use_raw_view_walker=True
```
This branch contains some other re-factoring. So be ready for informative errors that should be easy to fix.

**Comment by vasily-v-ryabov** [comment]
Some explanation is here: PR #1012.
