### ISSUE TITLE
COMError: An event was unable to invoke any of the subscribers

### ISSUE THREAD

**Issue by Econ808** [pywinauto/pywinauto#952]
## Expected Behavior
Invoke hyperlink and then continue to next step in code

## Actual Behavior
Invokes hyperlink **but** then hangs until COM Error is raised:

`_ctypes.COMError: (-2147220992, None, (None, None, None, 0, None))`
which also translates to when catching Exception as e:
`(-2147220991, 'An event was unable to invoke any of the subscribers.', (None, None, None, 0, None))`

As of now I catch the exception and move on, however, as it hangs for approx. 20 secs this slows everything down dramatically. Therefore, a satisfying fix would simply be to raise the error faster?

## Steps to Reproduce the Problem
1. Use backend='uia'

```
(self.subwin[0]
                .children()[index]
                .children()[0]
                .children()[7]
                .children(title='BlaBla', control_type="Text")[0]
                .children(title="BlaBla", control_type="Hyperlink")[0]
                .invoke())
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.7.3
  - Platform and OS: Windows 10

**Comment by airelil** [comment]
Are these 20 secs totalling for the whole five-level search or only on the last `children` call? Also, you might be able to speed up some of the `children` calls with trying to apply additional filter: `content_only=True`.

**Comment by airelil** [comment]
One more tip. Looking into your code example, if you actually accessing only the first child as in below, it might worth switching to [iter_children](https://pywinauto.readthedocs.io/en/latest/code/pywinauto.base_wrapper.html?highlight=iter_children#pywinauto.base_wrapper.BaseWrapper.iter_children)
```python
children(title='BlaBla', control_type="Text")[0]
```

**Comment by Econ808** [comment]
It's the invoke that takes up time - when using `click_input()` it is almost instantaneous, however, the hyperlink is not always visible so I don't think `click_input()` will work as it merely moves the mouse and then clicks? Also I kind of like the fact that it might be able to run headless

**Comment by airelil** [comment]
You're right about `click_input`, it's a realistic mouse simulation that needs the control to be visible. WRT `invoke`, did you see this comment from our past issue: https://github.com/pywinauto/pywinauto/issues/563#issuecomment-419554134? I mean, it's hard to say what's going on inside the invoke on the app side.

**Comment by Econ808** [comment]
Yeah, I actually saw that post, however, what concerns me is simply the waiting time of said error. I tested it further and when using `invoke` through `inspect.exe` on the same control, there is also an error - instantaneously. I just want to know if there is a way to throw the error sooner, such that the code can continue? On the spawned window I actually just use `pyautogui` (performance reasons), so I guess I could use threading but I'd rather not 😶

**Comment by Econ808** [comment]
I think this could be solved using a "throwaway thread" and as such I close the issue.

**Comment by 643364103** [comment]
> 
How to fixed it ? I need it very much,thank you.

**Comment by vasily-v-ryabov** [comment]
@643364103 it's an app side issue, but it is handled in `atspi` branch which will become next major release. But there is no exact due date though.
