### ISSUE TITLE
Backend win32 wrappers confuses the "descendants" and "children" methods.

### ISSUE THREAD

**Issue by julienplee** [pywinauto/pywinauto#959]
## Expected Behavior
Using win32, when requesting children of a wrapper, we expend to retrieve the direct descendants of the element. 
The UIA backend does this right.
_Note:_ I need Win32 backend because it's 1000x faster, and I think I'm trying to control an application that saturates UIA (the delay is 17seconds+ when a batch of this app is working)

## Actual Behavior
Every descendant related to the original wrapper is returned. 

The following two bugs may be related :
* I tried to filter out those results with `main_window.windows(parent=main_window)` and the "parent" filter is not considered.
* The "parent" filter does not work in UIA backend.

## Steps to Reproduce the Problem

  1. Have a window with complex descendants tree
  2. Fetch the dialog using win32 backend
  3. Try to fetch the Nth child

## Short Example of Code to Demonstrate the Problem
**Sample code**
```python3
from pywinauto import Application
# Switch on/of the following lines to compare "UIA" and "Win32" behavior
# app = Application(backend="uia").connect( process=pid )
app = Application(backend="win32").connect( process=pid )

# Another behavior difference between UIA and Win32 with app.top_window() returning my TMainForm (UIA) window or TApplication (Win32) forces me to use this workaround to get the main window. I don't know if TMainForm is supposed to change across different GUI frameworks.
main_win = app.window(class_name="TMainForm", active_only = True).wrapper_object()

def desc( *args ):
        print( *args, sep="\n\t", end="\n\n" )
desc( "main_win.descendants()", *main_win.descendants() )
desc( "main_win.children()", *[(x, x.parent()) for x in main_win.children()] )
desc( "main_win.children(parent=main_win)", *[(x, x.parent()) for x in main_win.children(parent=main_win)] )
```

**Results with backend UIA**
> ```
> main_win.descendants()
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - 'Help', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - 'Like us on Facebook', Pane
>         uiawrapper.UIAWrapper - 'Feedback', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - 'About', Pane
>         uiawrapper.UIAWrapper - 'Options', Pane
>         uiawrapper.UIAWrapper - 'Batch Repair', Pane
>         uiawrapper.UIAWrapper - 'Repair', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - 'Start Repair', Pane
>         uiawrapper.UIAWrapper - '...', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - '...', Pane
>         uiawrapper.UIAWrapper - '', Pane
>         uiawrapper.UIAWrapper - 'Repair process log:', Pane
>         uiawrapper.UIAWrapper - 'Save Log', Pane
>         uia_controls.EditWrapper - '', Edit
>         uia_controls.EditWrapper - '', Edit
>         uia_controls.EditWrapper - '', Edit
> 
> main_win.children()
>         uiawrapper.UIAWrapper - '', Pane   ##   uiawrapper.UIAWrapper - '', Dialog
>         uiawrapper.UIAWrapper - '', Pane   ##   uiawrapper.UIAWrapper - '', Dialog
>         uiawrapper.UIAWrapper - '', Pane   ##   uiawrapper.UIAWrapper - '', Dialog
> 
> ### Oops, the "parent" filter does not work on UIA backend ###
> Traceback (most recent call last):
>   File "automate\dwordrecovery.py", line 129, in <module>
>     exit(main())
>   File "automate\dwordrecovery.py", line 42, in main
>     try_winauto(pid)
>   File "automate\dwordrecovery.py", line 70, in try_winauto
>     desc( "main_win.children()", *[str(x)+"   ##   "+str(x.parent()) for x in main_win.children(parent=main_win)] )
>   File "C:\Users\Julien\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\base_wrapper.py", line 470, in children
>     child_elements = self.element_info.children(**kwargs)
>   File "C:\Users\Julien\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\uia_element_info.py", line 282, in children
>     cond = IUIA().build_condition(**kwargs)
> TypeError: build_condition() got an unexpected keyword argument 'parent'
> ```

**Results with backend Win32**
> ```
> main_win.descendants()
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '&Help', Button
>         win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '&Like us on Facebook', Button
>         win32_controls.ButtonWrapper - '&Feedback', Button
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '', Button
>         win32_controls.ButtonWrapper - '', Button
>         win32_controls.ButtonWrapper - '&About', Button
>         win32_controls.ButtonWrapper - '&Options', Button
>         win32_controls.ButtonWrapper - '&Batch Repair', Button
>         win32_controls.ButtonWrapper - '&Repair', Button
>         hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '&About', TTabSheet
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox
>         win32_controls.ButtonWrapper - '&Enter License Key', Button
>         win32_controls.ButtonWrapper - 'B&uy Business License for Commercial Use', Button
>         hwndwrapper.HwndWrapper - 'Advanced Options', TTabSheet
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.EditWrapper - '512', Edit
>         win32_controls.ButtonWrapper - '...', Button
>         hwndwrapper.HwndWrapper - '&Batch Repair', TTabSheet
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Save &Log', Button
>         win32_controls.ButtonWrapper - 'Remo&ve All', Button
>         win32_controls.ButtonWrapper - 'Re&move Files', Button
>         win32_controls.ButtonWrapper - 'S&earch Files', Button
>         win32_controls.ButtonWrapper - 'A&dd Files', Button
>         win32_controls.ButtonWrapper - '&Start Repair', Button
>         hwndwrapper.HwndWrapper - '&Repair', TTabSheet
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'A&dvanced Options', Button
>         win32_controls.ButtonWrapper - 'O&ptions', Button
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TbsSkinGauge
>         win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '&Start Repair', Button
>         win32_controls.ButtonWrapper - '...', Button
>         win32_controls.ButtonWrapper - '', Button
>         win32_controls.ButtonWrapper - '...', Button
>         hwndwrapper.HwndWrapper - '', TbsSkinScrollBar
>         hwndwrapper.HwndWrapper - 'Repair process log:', TbsSkinLabel
>         win32_controls.ButtonWrapper - 'Save &Log', Button
>         win32_controls.EditWrapper - '', Edit
>         win32_controls.EditWrapper - '', Edit
>         hwndwrapper.HwndWrapper - '', TbsSkinMemo
> 
> main_win.children()
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Help', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Like us on Facebook', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Feedback', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&About', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Options', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Batch Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TPageControl   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '&About', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '&About', TTabSheet
>         hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Enter License Key', Button   ##   hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox
>         win32_controls.ButtonWrapper - 'B&uy Business License for Commercial Use', Button   ##   hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox
>         hwndwrapper.HwndWrapper - 'Advanced Options', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - 'Advanced Options', TTabSheet
>         win32_controls.EditWrapper - '512', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '...', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '&Batch Repair', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '&Batch Repair', TTabSheet
>         win32_controls.ButtonWrapper - 'Save &Log', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Remo&ve All', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Re&move Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'S&earch Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'A&dd Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Start Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '&Repair', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'A&dvanced Options', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'O&ptions', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TbsSkinGauge   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Start Repair', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '...', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '...', Button   ##   win32_controls.StaticWrapper - '', Static
>         hwndwrapper.HwndWrapper - '', TbsSkinScrollBar   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - 'Repair process log:', TbsSkinLabel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Save &Log', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.EditWrapper - '', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.EditWrapper - '', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TbsSkinMemo   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
> 
> main_win.children(parent=main_win)
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Help', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Like us on Facebook', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Feedback', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&About', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Options', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Batch Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TPageControl   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '&About', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '&About', TTabSheet
>         hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Enter License Key', Button   ##   hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox
>         win32_controls.ButtonWrapper - 'B&uy Business License for Commercial Use', Button   ##   hwndwrapper.HwndWrapper - 'License Information:', TbsSkinGroupBox
>         hwndwrapper.HwndWrapper - 'Advanced Options', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - 'Advanced Options', TTabSheet
>         win32_controls.EditWrapper - '512', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '...', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '&Batch Repair', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '&Batch Repair', TTabSheet
>         win32_controls.ButtonWrapper - 'Save &Log', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Remo&ve All', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Re&move Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'S&earch Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'A&dd Files', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Start Repair', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '&Repair', TTabSheet   ##   hwndwrapper.HwndWrapper - '', TPageControl
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'A&dvanced Options', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'O&ptions', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.DialogWrapper - '', TMainForm
>         hwndwrapper.HwndWrapper - '', TGSFRPanel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TbsSkinGauge   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.StaticWrapper - '', Static   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - '&Start Repair', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '...', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '', Button   ##   win32_controls.StaticWrapper - '', Static
>         win32_controls.ButtonWrapper - '...', Button   ##   win32_controls.StaticWrapper - '', Static
>         hwndwrapper.HwndWrapper - '', TbsSkinScrollBar   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - 'Repair process log:', TbsSkinLabel   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.ButtonWrapper - 'Save &Log', Button   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.EditWrapper - '', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         win32_controls.EditWrapper - '', Edit   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
>         hwndwrapper.HwndWrapper - '', TbsSkinMemo   ##   hwndwrapper.HwndWrapper - '', TGSFRPanel
> ```

## Specifications

  - Pywinauto version:  **0.6.8**
  - Python version and bitness:  **3.8 64bits**
  - Platform and OS:  **CMD.exe inside WSL2 inside Windows 10 64bits inside a VM**

**Comment by julienplee** [comment]
I fixed the source code. In the following extract of the file _win32_element_info.py, l121_

In fact, as one can see in the original function comments, "depth" feature were not implemented. I updated the comment accordingly.
Now, as far as I understand this piece of code, I can't understand the sibling `descendants()` function. As it looks like returning the same results. `descendants()`just seams to includes additional filtering. 
A discriminating description would be really much appreciated since the `children()` and `descendants()` definition is pretty much the same except that "children" has been transposed as "descendants", letting the user to guess what is named a "child" compared to what is named a "descendant". I could not clarify that in the Win32 backend, even if the UIA backend is more obvious.

Because of this, and because the function is used elsewhere, I did not update the code considering my own definition of a child. We have to indicate "depth" or "parent" argument to retrieve the actual direct children in my update.


```
    def children(self, **kwargs):
        """Return a list of immediate children of the window"""
        class_name = kwargs.get('class_name', None)
        title = kwargs.get('title', None)
        control_type = kwargs.get('control_type', None)
        parent = kwargs.get('parent', None)
        depth = kwargs.get('depth', None)
        # TODO: 'cache_enable' is ignored so far

        # this will be filled in the callback function
        child_elements = []

        # The callback function that will be called for each HWND
        # all we do is append the wrapped handle
        def enum_window_proc(hwnd, lparam):
            """Called for each window - adds wrapped elements to a list"""
            element = HwndElementInfo(hwnd)
            if parent is not None and parent != element.parent:
                return True
            if depth is not None:
                def get_depth(child, referent):
                    parent=child.parent
                    if parent is None:
                        return None
                    if( referent == parent ):
                        return 1
                    parent_depth=get_depth( parent, referent )
                    if parent_depth is None:
                        return None
                    return parent_depth + 1

                child_depth = get_depth( element, self )
                if child_depth != depth:
                    return True
            if class_name is not None and class_name != element.class_name:
                return True
            if title is not None and title != element.rich_text:
                return True
            if control_type is not None and control_type != element.control_type:
                return True
            child_elements.append(element)
            return True

        # define the type of the child procedure
        enum_win_proc_t = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

        # 'construct' the callback with our function
        proc = enum_win_proc_t(enum_window_proc)

        if self == HwndElementInfo():  # self == root
            # loop over all the top level windows (callback called for each)
            win32functions.EnumWindows(proc, 0)
        else:
            # loop over all the children (callback called for each)
            win32functions.EnumChildWindows(self.handle, proc, 0)

        return child_elements
```

Usage example base on my report :
```
desc( "main_win.children(parent=main_win)", *[(x, x.parent()) for x in main_win.children(parent=main_win)] )
desc( "main_win.children(depth=1)", *[(x, x.parent()) for x in main_win.children(depth=1)] )
```
provides the following results :

> ```
> main_win.children(parent=main_win)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 4195602>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 3606456>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TPageControl, 5114294>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 4983220>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 3672238>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
> 
> main_win.children(depth=1)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 4195602>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 3606456>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TPageControl, 5114294>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 4983220>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
>         (<hwndwrapper.HwndWrapper - '', TGSFRPanel, 3672238>, <hwndwrapper.DialogWrapper - '', TMainForm, 4262330>)
> 
> ```

Those still are not the same results as when using the UIA backend : 3 Panels in UIA, 4 Panels + 1 PageControl in Win32. An explanation would be much appreciated.

Thanks to the developers for their hard work and I hope this patch will help.

**Comment by julienplee** [comment]
I found out that if I discard invisible windows, I leave with the same results as with the UIA backend.

```
[x for x in main_win.children(depth=1, visible_only=True) if x.is_visible()]
```

Though, I don't know how I can filter visibility inside the `children()` method since I can't understand the complex object model used in this project.

**Comment by airelil** [comment]
@julienplee , thanks for the detailed analysis! I think, the main idea is to have "children" method that brings immediate descendants of a control while "descendants" method should bring all sub-controls including the children. Anyway, it seems that we missed a remark in Win32 API about `EnumChildWindows` function that says: 
> If a child window has created child windows of its own, EnumChildWindows enumerates those windows as well.

So we ended up having the full list even for the "children" method. Turns out we even don't have a unit tests for `HwndElementInfo.descendants()`

Do you mind making a pull request to our 'atspi' branch, as it's our current dev branch that we plan to release as 0.7? Otherwise if we make the proposed change, your contribution to the project will be a bit missed.

**Comment by julienplee** [comment]
Hello Valentin,
I lack Git knowledge and I'm afraid I would spend too much time discovering it and most importantly, make mistakes.
I only know how to execute the anonymous clone method and have a SVN usage knowledge. If you can help me the right steps, I could provide a pull request with the patch.

Overwise, I don't care about contribution credits or anything as long as the module keeps getting better.

In the case I deal with the pull request, it would be interesting to solve those constraints from an authoritative point of view, first.
- Should the `children()` method provide `depth=1` or `parent=caller` by default ?
- Should the returned items be filter on visibility by default ? (and can it be done in the callback function with the used wrappers ?)

Thank you

**Comment by julienplee** [comment]
Oh, and I should notice that this part might be wrong :
```
                    if parent is None:
                        return None
```
I went on a guess basis as a safeguard. Their should always be a parent before eventually matching the actual parent and I didn't meet this case.

**Comment by airelil** [comment]
We prefer pull request, as it usually triggers a CI job with all unittests. It helps to spot any regression earlier. IMHO, `depth` should be equal 1 as we're retrieving only the immediate children. Regarding `visible` it can be set to visible only if not specified explicitly. Something like this:
`parent = kwargs.get('visible', True)`. 
Not sure if it's `visible` or `visible_only`, though.

I'd also prefer to wait a bit in case there are additional comments from @vasily-v-ryabov,
