### ISSUE TITLE
Getting the title from a children

### ISSUE THREAD

**Issue by jjbright** [pywinauto/pywinauto#964]
How to get the title **CAS-31230026-RRYYM6** from the below

The print_control_identifiers()  on the `FormTitle` returns this -
```
Control Identifiers:

Custom - ''    (L609, T259, R912, B323)
['CAS-31230026-RRYYM6Custom', 'Custom']
child_window(auto_id="FormTitle", control_type="Custom")
   | 
   | Static - 'CAS-31230026-RRYYM6'    (L613, T259, R908, B323)
   | ['CAS-31230026-RRYYM6Static', 'Static', 'CAS-31230026-RRYYM6']
   | child_window(title="CAS-31230026-RRYYM6", control_type="Text")
```

**Comment by airelil** [comment]
If you already have the child wrapper object you can try to use `texts()`, `window_text()` methods. If you have only a parent you can use `children_text()`, but this might be quite slow as it'll go through all the children.
Also you might consider an iterator method `iter_children()` as you can guess it will allow to iterate over children elements and query each with `texts` or `window_text`.

**Comment by jjbright** [comment]
`children_texts()` worked. Thanks @airelil
