### ISSUE TITLE
Support use child_window in pywinauto for desktop application

### ISSUE THREAD

**Issue by yenbka** [pywinauto/pywinauto#977]
## Expected Behavior
I want to control one alert of desktop application by pywinauto

## Steps to Reproduce the Problem

 print_control_identifiers()
Dialog - 'MainWindow'    (L-32000, T-32000, R-31840, B-31972)
['MainWindowDialog', 'MainWindow', 'Dialog']
child_window(title="MainWindow", control_type="Window")
   |
   | Custom - ''    (L-32000, T-32000, R-30634, B-31232)
   | ['Custom', 'Phần mềm quản lý nhà hàng, quán cafeCustom', 'Custom0', 'Custom1', 'Phần mềm quản lý nhà hàng, quán cafeCustom0', 'Phần mềm quản lý nhà hàng, quán cafeCustom1']
   |    |
   |    | Custom - ''    (L-32000, T-32000, R-30634, B-31800)
   |    | ['Custom2', 'Phần mềm quản lý nhà hàng, quán cafeCustom2']
   |    |    |
   |    |    | Image - ''    (L-30739, T-31980, R-30714, B-31955)
   |    |    | ['Image', 'Image0', 'Image1']
   |    |    |
   |    |    | Image - ''    (L-30689, T-31980, R-30664, B-31955)
   |    |    | ['Image2']
   |    |    | child_window(auto_id="imgClose", control_type="Image")
   |    |    |
   |    |    | Static - ''    (L-30871, T-31930, R-30664, B-31894)
   |    |    | ['Static', 'Về trang chủStatic', 'Static0', 'Static1', 'Về trang chủStatic0', 'Về trang chủStatic1']
   |    |    | child_window(auto_id="lblBackHome", control_type="Text")
   |    |    |    |
   |    |    |    | Image - ''    (L-30871, T-31923, R-30843, B-31895)
   |    |    |    | ['Image3']
   |    |    |    |
   |    |    |    | Static - 'Về trang chủ'    (L-30833, T-31930, R-30664, B-31894)
   |    |    |    | ['Static2', 'Về trang chủ', 'Về trang chủStatic2']
   |    |    |    | child_window(title="Về trang chủ", control_type="Text")
   |    |    |
   |    |    | Image - ''    (L-31417, T-31923, R-31217, B-31868)
   |    |    | ['Image4']
   |    |    |
   |    |    | Static - 'Phần mềm quản lý nhà hàng, quán cafe'    (L-32000, T-31848, R-30634, B-31800)
   |    |    | ['Static3', 'Phần mềm quản lý nhà hàng, quán cafeStatic', 'Phần mềm quản lý nhà hàng, quán cafe']
   |    |    | child_window(title="Phần mềm quản lý nhà hàng, quán cafe", control_type="Text")
   |    |
   |    | Custom - ''    (L-32000, T-31800, R-30634, B-31332)
   |    | ['Custom3', 'Phần mềm quản lý nhà hàng, quán cafeCustom3']
   |    | child_window(auto_id="uc", control_type="Custom")
   |    |    |
   |    |    | Static - 'Đăng nhập tài khoản chủ nhà hàng'    (L-31565, T-31780, R-31069, B-31742)
   |    |    | ['Static4', 'Đăng nhập tài khoản chủ nhà hàng', 'Đăng nhập tài khoản chủ nhà hàngStatic']
   |    |    | child_window(title="Đăng nhập tài khoản chủ nhà hàng", control_type="Text")
   |    |    |
   |    |    | Image - ''    (L-31629, T-31695, R-31579, B-31658)
   |    |    | ['Image5', 'Phần mềm quản lý nhà hàng, quán cafeImage']
   |    |    |
   |    |    | Static - '(+84)'    (L-31579, T-31705, R-31465, B-31648)
   |    |    | ['Static5', '(+84)Static', '(+84)', '(+84)Static0', '(+84)Static1']
   |    |    | child_window(title="(+84)", control_type="Text")
   |    |    |
   |    |    | Edit - ''    (L-31459, T-31712, R-30995, B-31642)
   |    |    | ['Edit', '(+84)Edit']
   |    |    | child_window(auto_id="txtPhone", control_type="Edit")
   |    |    |    |
   |    |    |    | Static - 'Nhập số điện thoại'    (L-31452, T-31690, R-31000, B-31663)
   |    |    |    | ['Static6', 'Nhập số điện thoại', 'Nhập số điện thoạiStatic']
   |    |    |    | child_window(title="Nhập số điện thoại", control_type="Text")
   |    |    |
   |    |    | Static - 'Phương thức đăng nhập khác'    (L-31669, T-31612, R-31369, B-31584)
   |    |    | ['Static7', 'Phương thức đăng nhập khác', 'Phương thức đăng nhập khácStatic']
   |    |    | child_window(title="Phương thức đăng nhập khác", control_type="Text")
   |    |    |
   |    |    | Static - 'Kích hoạt bằng mã thiết bị'    (L-31234, T-31612, R-30965, B-31584)
   |    |    | ['Static8', 'Kích hoạt bằng mã thiết bị', 'Kích hoạt bằng mã thiết bịStatic']
   |    |    | child_window(title="Kích hoạt bằng mã thiết bị", control_type="Text")
   |    |    |
   |    |    | Button - 'GỬI SMS'    (L-31417, T-31484, R-31217, B-31399)
   |    |    | ['GỬI SMSButton', 'Button', 'GỬI SMS', 'GỬI SMS0', 'GỬI SMS1']
   |    |    | child_window(title="GỬI SMS", control_type="Button")
   |    |    |    |
   |    |    |    | Static - 'GỬI SMS'    (L-31348, T-31450, R-31286, B-31432)
   |    |    |    | ['Static9', 'GỬI SMSStatic', 'GỬI SMS2']
   |    |    |    | child_window(title="GỬI SMS", control_type="Text")
   |    |
   |    | Custom - ''    (L-32000, T-31332, R-30634, B-31232)
   |    | ['GỬI SMSCustom', 'Custom4', 'Phần mềm quản lý nhà hàng, quán cafeCustom4']
   |    |    |
   |    |    | Static - ''    (L-31602, T-31298, R-31329, B-31265)
   |    |    | ['Static10', 'WebsiteStatic', 'WebsiteStatic0', 'WebsiteStatic1']
   |    |    |    |
   |    |    |    | Image - ''    (L-31602, T-31298, R-31574, B-31270)
   |    |    |    | ['Image6', 'OKImage']
   |    |    |    |
   |    |    |    | Static - 'Website'    (L-31564, T-31298, R-31479, B-31265)
   |    |    |    | ['Static11', 'WebsiteStatic2', 'Website']
   |    |    |    | child_window(title="Website", control_type="Text")
   |    |    |    |
   |    |    |    | Static - ': '    (L-31479, T-31298, R-31467, B-31265)
   |    |    |    | ['Static12', ': ', ': Static']
   |    |    |    | child_window(title=": ", control_type="Text")
   |    |    |    |
   |    |    |    | Static - 'www.sapo.vn'    (L-31467, T-31298, R-31329, B-31265)
   |    |    |    | ['Static13', 'www.sapo.vnStatic', 'www.sapo.vn', 'www.sapo.vn0', 'www.sapo.vn1']
   |    |    |    | child_window(title="www.sapo.vn", control_type="Text")
   |    |    |    |    |
   |    |    |    |    | Hyperlink - 'www.sapo.vn'    (L-31467, T-31298, R-31329, B-31270)
   |    |    |    |    | ['Hyperlink', 'www.sapo.vn2', 'www.sapo.vnHyperlink']
   |    |    |    |    | child_window(title="www.sapo.vn", control_type="Hyperlink")
   |    |    |
   |    |    | Static - '    '    (L-31329, T-31298, R-31316, B-31265)
   |    |    | ['Static14', '    Static', '    ', '    Static0', '    Static1']
   |    |    | child_window(title="    ", control_type="Text")
   |    |    |
   |    |    | Static - ''    (L-31269, T-31298, R-31032, B-31265)
   |    |    | ['Static15', '    Static2']
   |    |    |    |
   |    |    |    | Image - ''    (L-31269, T-31298, R-31241, B-31270)
   |    |    |    | ['    Image', 'Image7']
   |    |    |    |
   |    |    |    | Static - 'Hotline'    (L-31231, T-31298, R-31154, B-31270)
   |    |    |    | ['Static16', 'HotlineStatic', 'Hotline']
   |    |    |    | child_window(title="Hotline", control_type="Text")
   |    |    |    |
   |    |    |    | Static - ': 1800 6750'    (L-31154, T-31298, R-31032, B-31270)
   |    |    |    | ['Static17', ': 1800 6750', ': 1800 6750Static']
   |    |    |    | child_window(title=": 1800 6750", control_type="Text")
   |
   | Custom - ''    (L-31636, T-31741, R-30997, B-31491)
   | ['Đăng nhập tài khoản chủ nhà hàngCustom', 'Custom5']
   |    |
   |    | Static - ''    (L-31421, T-31731, R-31213, B-31685)
   |    | ['Static18', '(+84)Static2']
   |    |    |
   |    |    | Image - ''    (L-31416, T-31726, R-31380, B-31690)
   |    |    | ['Image8', '(+84)Image']
   |    |    |
   |    |    | Static - 'Thông báo'    (L-31370, T-31726, R-31218, B-31690)
   |    |    | ['Static19', 'Thông báo', 'Thông báoStatic']
   |    |    | child_window(title="Thông báo", control_type="Text")
   |    |
   |    | Static - 'OK'    (L-31636, T-31571, R-30997, B-31491)
   |    | ['Static20', 'OKStatic', 'OK', 'OKStatic0', 'OKStatic1', 'OK0', 'OK1']
   |    | child_window(title="OK", control_type="Text")
   |    |    |
   |    |    | Static - 'OK'    (L-31334, T-31546, R-31300, B-31516)
   |    |    | ['Static21', 'OKStatic2', 'OK2']
   |    |    | child_window(title="OK", control_type="Text")
   |    |
   |    | Static - 'Số điện thoại không đúng định dạng'    (L-31520, T-31643, R-31114, B-31613)
   |    | ['Static22', 'Số điện thoại không đúng định dạngStatic', 'Số điện thoại không đúng định dạng']
   |    | child_window(title="Số điện thoại không đúng định dạng", control_type="Text")

==> I want to control 
 Static - 'OK'    (L-31636, T-31571, R-30997, B-31491)
   |    | ['Static20', 'OKStatic', 'OK', 'OKStatic0', 'OKStatic1', 'OK0', 'OK1']
   |    | child_window(title="OK", control_type="Text")
   |    |    |
   |    |    | Static - 'OK'    (L-31334, T-31546, R-31300, B-31516)
   |    |    | ['Static21', 'OKStatic2', 'OK2']
   |    |    | child_window(title="OK", control_type="Text")
   |    |
   |    | Static - 'Số điện thoại không đúng định dạng'    (L-31520, T-31643, R-31114, B-31613)
   |    | ['Static22', 'Số điện thoại không đúng định dạngStatic', 'Số điện thoại không đúng định dạng']
   |    | child_window(title="Số điện thoại không đúng định dạng", control_type="Text")

Please help me!
Thanks so much!!

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.7
  - Platform and OS: win10

**Comment by vasily-v-ryabov** [comment]
The root `Application` or `Desktop` object should use `window(...)` method to specify top level window first. Example:
```python
app = Application(backend="uia").start("your_app.exe")
main_window = app.window(title="MainWindow", control_type="Window")
main_window.wait('ready', timeout=20)  # flexibly wait up to 20 sec or till window is open
ok_button = main_window.child_window(title="OK", control_type="Text")
# use dir(ok_button.wrapper_object()) for returned wrapper to list all available methods
ok_button.click_input()
```

**Comment by yenbka** [comment]
Help me, result after:
Traceback (most recent call last):
  File "c:/Users/YEN NGUYEN/Desktop/test1.py", line 12, in <module>
    ok_button.click_input()
  File "C:\Users\YEN NGUYEN\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\YEN NGUYEN\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 258, in __resolve_control
    criteria)
  File "C:\Users\YEN NGUYEN\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\YEN NGUYEN\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\application.py", line 222, in __get_ctrl

**Comment by vasily-v-ryabov** [comment]
@yenbka the traceback looks not full. Error message with `ElementNotFoundError` is usually clear enough to understand which level of search is failed. It could be "main window is not found" or "button on the window is not found".

**Comment by yenbka** [comment]
Thanks so much. My issue has been solved
