### ISSUE TITLE
How to access Popup Menu from Application

### ISSUE THREAD

**Issue by dschiller** [pywinauto/pywinauto#981]
## Expected Behavior

Be able to inspect / access the opened Popup Menu

## Actual Behavior

Popup Menu closes as far as I access the Application

## Steps to Reproduce the Problem

  1. Connect to Application
  2. Open Popup Menu
  3. Try to access Popup Menu
  4. Menu closes befor it can be accessed

## Short Example of Code to Demonstrate the Problem

```
import pywinauto

# Open App
clientProcess = pywinauto.Application('uia').start('C:\\tmp\\myapp.exe')

# Open Popup Menu
clientProcess.MyApp.Custom.children()[4].click_input()

# Click `Disconnect` Item in Popup Menu
clientProcess.MyApp.Disconnect.click_input()  # Fails because accessing 'clientProcess.MyApp'
                                              # triggers the Popup Menu to close
# Close App
clientProcess.kill()
```

## Specifications

  - Pywinauto version: 0.6.6
  - Python version and bitness: 3.7.2 64 Bit
  - Platform and OS: Windwos 10

**Comment by airelil** [comment]
You might want to try to access the menu through the desktop (`from pywinauto import Desktop`)
Something like here: https://github.com/pywinauto/pywinauto/issues/490#issuecomment-383875129

**Comment by dschiller** [comment]
I found out one essential thing one should know. If you access the Application via the Names like

```
clientProcess.MyDialog.Custom.children()[4].click_input()
                                      ^
```

then the Application behave different and is much slower as you use the `children` Method

```
clientProcess.Workcenter.children()[6].children()[4].click_input()
                                         ^
```

It is the same Object but the Application behaves much faster and the Popup doesn't close and is readable.

**Comment by vasily-v-ryabov** [comment]
This is interesting case because we take care of consistency and speed where it is possible. If you could provide some app (maybe available for download?) and short script to reproduce the problem, I'd like to investigate the root cause of such flapping behavior.

**Comment by dschiller** [comment]
Vasily that is not possible but maybe it helps, it is a WPF C# Application.
