### ISSUE TITLE
No Conda Installation

### ISSUE THREAD

**Issue by CibelesR** [pywinauto/pywinauto#983]
## Expected Behavior
I am trying to install pywinauto thought conda. Here is the documentation:
https://anaconda.org/conda-forge/pywinauto

## Actual Behavior
PackagesNotFoundError: The following packages are not available from current channels:

  - pywinauto

## Steps to Reproduce the Problem

  1. Open any Conda Environment
  2. Write:
     2.1. conda install -c conda-forge pywinauto or
     2.2. conda install -c conda-forge/label/cf201901 pywinauto or
     2.3. conda install -c conda-forge/label/cf202003 pywinauto 

## Specifications

  - Pywinauto version:
  - Python version and bitness: Python 3.7
  - Platform and OS: MacOS Sierra v10.12.6

**Comment by vasily-v-ryabov** [comment]
Version 0.6.8 doesn't support macOS (conda package is also for Linux and Windows only). But I'm planning to prepare macOS prototype for early testing in October.

Pull request #841 contains some code, but latest code for macOS is a little bit distributed on different branches. I need to merge everything into one branch before pushing to early adopters.

**Comment by vasily-v-ryabov** [comment]
I'd prefer to track macOS progress in #335. So marking this thread as a duplication.

**Comment by CibelesR** [comment]
Wow! Thank you for the quick answer. I am sorry because It is my fault for not reading correctly. I am going to delete it if you do not mind
