### ISSUE TITLE
Disabling Keyboard Input

### ISSUE THREAD

**Issue by ScullCandy72** [pywinauto/pywinauto#991]
Hi, I'm trying to figure out how I could disable keyboard input and then re-enable it when I need it later in my code, please help.

  - Python version and bitness: Python3
  - Platform and OS: [Repl.it](repl.it)
Edition: Windows 10 home
Processor: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz 1.70 GHz
System type: 64-bit operating system, x64-based processor
Pen and touch: Toch support with 10 touchpoints
Version: 2004
Installed on: 9/23/2020
Experience: Windows Feature Experience Pack 120.2212.31.0

**Comment by vasily-v-ryabov** [comment]
The discussion about it was going in #673. Might be useful for your needs.

**Comment by ScullCandy72** [comment]
@vasily-v-ryabov I'm using the website [Repl.it](repl.it), and I want to make it so I can call on a command to disable keyboard input, then re-enable it with another command.

**Comment by vasily-v-ryabov** [comment]
Not sure `BlockInput` would work from this website. Maybe it's worth thinking about `sys.stdin` overriding if you want to block stdin. Of course original `sys.stdin` object should be cached to a temp variable.

**Comment by ScullCandy72** [comment]
@vasily-v-ryabov Ok, I will try that, but just so you can know, I'm using Python to create a text adventure game, where at the start, before it shows the title, I have a fake loading screen, so I want to disable the keyboard input, until the fake loading is over, just so you can type on the keyboard, but nothing will display into the console, until after the fake loading is over.

**Comment by CosmeT17** [comment]
@ScullCandy72 Hey, I have the same exact problem. I'm using Repl.it too. I'm trying to do Threading/ Multiprocessing with readchar.readkey() so that everything that is typed is eaten up and not printed on the console, but this isn't working properly. I keep having issues with infinite loops. Any updates on a possible solution on your part?

**Comment by ysfadmsm2002** [comment]
@ScullCandy72 hey there i am also working on a similar project (text adventure game) and have a fake loading screen as well. in my game I print text char by char to give the pokemon game feel, but when running the game I also wish to block keyboard input when its printing the char by char text. just wondering if you found a solution?
